rust-lang/rustfmt

src/mod.rs
This makes rustfmt compile with latest nightly rust.
=> Update from Path to PathBuf

src/types.rs, tests/idem/fn.rs
I believe it resolves #54. Thanks for the low-hanging fruit. I'm hoping to have some fun working on this tool  some more.
=> Spaces around  in type bounds

src/imports.rs, src/visitor.rs, tests/idem/imports.rs
This should fix https://github.com/nrc/rustfmt/issues/41.
=> Correctly indent use items and functions

src/imports.rs, src/lists.rs, src/visitor.rs, tests/idem/imports.rs
This closes https://github.com/nrc/rustfmt/issues/24.
=> Keep import lists on a single line when possible

tests/idem/fn.rs
=> Added regression test for #53.

tests/target/structs.rs
=> Regression test for pub struct fields

tests/source/doc.rs, tests/source/multiple.rs, tests/source/other.rs, tests/target/doc.rs, tests/target/multiple.rs, tests/target/other.rs
It does too much, it should be split up
=> Add a terrible, but useful, test which I used locally

src/expr.rs, src/items.rs, src/lib.rs, src/types.rs, src/visitor.rs
=> Don't apologise if its not our fault in warnings

src/items.rs, tests/target/trait.rs
This closes https://github.com/nrc/rustfmt/issues/145.
=> Format unnamed function arguments

tests/source/expr.rs, tests/target/expr.rs
=> Add regression tests for binOps

src/imports.rs, tests/source/imports.rs, tests/target/imports.rs
This conflicts with https://github.com/nrc/rustfmt/pull/142. Created this PR so I don't forget about it later. I'll rebase this after the former PR is merged.
Closes https://github.com/nrc/rustfmt/issues/121.
=> Format simple imports

README.md, src/bin/rustfmt.rs, src/filemap.rs, src/lib.rs, tests/system.rs
Closes https://github.com/nrc/rustfmt/issues/171.
=> Add an option to forgo backups

src/comment.rs, src/expr.rs, src/filemap.rs, src/imports.rs, src/issues.rs, src/items.rs, src/lib.rs, src/lists.rs, src/modules.rs, src/rewrite.rs, src/types.rs, src/utils.rs, src/visitor.rs, tests/source/expr.rs, tests/source/loop.rs, tests/target/expr.rs, tests/target/loop.rs, tests/target/match.rs
Also does empty blocks and continue (badly).
I was at first happy with how easy this was, then disappointed by how much code it took to get things right. I think we can do better with the abstractions we're using, but not sure how yet...
=> match expressions

src/config.rs, src/default.toml, src/expr.rs, src/imports.rs, src/items.rs, src/lists.rs, src/types.rs, src/visitor.rs, tests/config/small_tabs.toml, tests/source/closure.rs, tests/target/closure.rs, tests/target/comments-fn.rs
This closes https://github.com/nrc/rustfmt/issues/179.
=> Format closures

src/types.rs, tests/source/structs.rs, tests/target/structs.rs
Fixes https://github.com/nrc/rustfmt/issues/197.
=> Fix bug in path formatting

src/config.rs, src/default.toml, src/expr.rs, tests/config/small_tabs.toml, tests/source/expr.rs, tests/source/single-line-if-else.rs, tests/target/expr.rs, tests/target/single-line-if-else.rs
Closes https://github.com/nrc/rustfmt/issues/92, https://github.com/nrc/rustfmt/issues/32.
=> Implement single line if-else formatting

src/visitor.rs
https://github.com/rust-lang/rust/pull/27857
Need this for the other PR.
@marcusklaas
=> Fix build on nightly

src/expr.rs, src/items.rs, src/rewrite.rs, src/visitor.rs, tests/source/attrib.rs
=> Implement Rewrite for [ast::Attribute]

Contributing.md, Design.md, README.md
I also added some little bits in the readme that tripped me up
=> I rejiggered the readme file 

tests/source/expr.rs, tests/target/expr.rs
Closes https://github.com/nrc/rustfmt/issues/223, https://github.com/nrc/rustfmt/issues/181.
=> Add regression test for bad break span

src/config.rs
With this change one can use a config file
that only specifies a subset of config keys
to overwrite. E.g. a config file that looks like this
```
struct_trailing_comma = "Never"
struct_lit_trailing_comma = "Never"
```
Fixes #255
=> Allow partial rustfmt.toml

Cargo.lock, Cargo.toml, src/expr.rs, src/lib.rs, src/string.rs, src/utils.rs, tests/source/string-lit.rs, tests/target/string-lit.rs
Fix https://github.com/nrc/rustfmt/issues/120
=> Unicode string lit

src/types.rs, tests/source/paths.rs, tests/target/paths.rs
Fixify https://github.com/nrc/rustfmt/issues/275.
=> Fix qself rewrites without explicit casts

src/expr.rs, src/items.rs, tests/source/closure.rs, tests/target/closure.rs
Fixes https://github.com/nrc/rustfmt/issues/277.
=> Format closures' return types

tests/source/expr.rs, tests/target/expr.rs
Closes https://github.com/nrc/rustfmt/issues/184.
=> Add regression test for bad continue span

src/expr.rs, src/items.rs, tests/source/fn-simple.rs, tests/target/fn-simple.rs
Fixes https://github.com/nrc/rustfmt/issues/271.
=> Rewrite types in function arguments

src/expr.rs, tests/source/expr.rs, tests/target/expr.rs
Fixes https://github.com/nrc/rustfmt/issues/302.
=> Format array literals

README.md
Removed reference to default.toml
=> https://github.com/nrc/rustfmt/issues/304

src/expr.rs, tests/target/fn.rs
=> Preserve unsafe blocks in closures

src/comment.rs, src/expr.rs, src/issues.rs, src/items.rs, src/lib.rs, src/lists.rs, src/macros.rs, src/types.rs, src/visitor.rs, tests/source/macros.rs, tests/target/macros.rs, tests/target/match.rs
Addresses https://github.com/nrc/rustfmt/issues/35.
Unformatted code is running out of places to hide!
=> Format macro invocations

tests/source/fn-simple.rs, tests/target/fn-simple.rs
Build should pass after the next nightly release.
=> Add regression test for non-returning functions

src/expr.rs, tests/source/expr.rs, tests/source/struct_lits.rs, tests/target/expr.rs, tests/target/struct_lits.rs
Closes https://github.com/nrc/rustfmt/issues/231.
=> Fix struct overflows

src/items.rs, src/visitor.rs, tests/source/extern.rs, tests/target/extern.rs
Fixes https://github.com/nrc/rustfmt/issues/299.
Blocked by https://github.com/rust-lang/rust/issues/28472.
=> Format foreign functions and statics

src/expr.rs, tests/source/expr.rs, tests/target/expr.rs
Failure to rewrite a macro does not imply failure to rewrite its expr
=> fix for #355 and test cases

src/expr.rs, src/issues.rs, tests/source/expr.rs, tests/target/expr.rs
=> Add support for formatting "return" expressions.

src/comment.rs, src/expr.rs, src/lists.rs, src/string.rs, src/visitor.rs
Fixes https://github.com/nrc/rustfmt/issues/343, closes https://github.com/nrc/rustfmt/issues/217.
=> Make rewrite_string return `Option<String>`

src/types.rs, tests/source/multiple.rs, tests/target/multiple.rs
=> Formatting of some types

src/chains.rs, src/comment.rs, src/config.rs, src/expr.rs, src/filemap.rs, src/issues.rs, src/items.rs, src/lib.rs, src/lists.rs, src/macros.rs, src/missed_spans.rs, src/modules.rs, src/types.rs, src/visitor.rs, tests/system.rs, tests/target/closure.rs, tests/target/tuple.rs
=> Use vertical formatting when function args width > limit

src/imports.rs, tests/source/imports.rs, tests/target/imports.rs
Closes #366 
I guess we could check widths for single imports, but seems like an edge case and not worth it.
=> Format imports with aliases.

src/config.rs, src/items.rs, tests/config/small_tabs.toml, tests/target/enum.rs, tests/target/fn-custom.rs, tests/target/multiple.rs
Fixes #372 
Well, for some definition of fix, really this just makes it more unlikely for us to hit the issue. But I don't think there is a proper fix, as such.
=> Use max width for function decls, not ideal width

src/items.rs, tests/target/enum.rs
Closes https://github.com/nrc/rustfmt/issues/375.
=> Fix variant name duplication on rewrite failure

src/expr.rs, tests/source/match.rs, tests/target/match.rs
Closes https://github.com/nrc/rustfmt/issues/383.
=> Prevent arithmetic overflow handling match arm comments

src/lib.rs, src/types.rs, tests/target/fn_once.rs
Adds a test to prevent future regressions.
I hope it's ok that I enabled the slice patterns feature.
Fixes #401
=> Fix 1-tuple regression.

Cargo.toml
This keeps everything under dependencies, which is nice.
=> Use newer style in Cargo.toml

src/macros.rs
Closes https://github.com/nrc/rustfmt/issues/414.
=> Prevent panics on list-like macro uses with trailing commas

src/items.rs, src/lists.rs, tests/source/enum.rs, tests/source/structs.rs, tests/target/enum.rs, tests/target/structs.rs
This is a re-post of PR #407 with only one commit (the original branch was f'ed beyond my rebase abilities).
=> Fix https://github.com/nrc/rustfmt/issues/270

src/items.rs, src/lists.rs, src/types.rs, tests/source/multiple.rs, tests/target/multiple.rs
=> Handle multi-line return types and multi-line tuples

src/items.rs
We could and should unify our formatting code for enum variants and structs now that their representation in the AST is identical. In this PR I just made the necessary changes to things to compile again.
This closes https://github.com/nrc/rustfmt/issues/468.
=> Adjust for unified enum variants and structs

src/items.rs, src/visitor.rs, tests/source/static.rs, tests/target/static.rs
Fixes https://github.com/nrc/rustfmt/issues/499.
=> Format visibility for statics and consts

src/comment.rs, tests/source/comment2.rs, tests/source/comment3.rs, tests/target/comment2.rs, tests/target/comment3.rs
Fixes #502.
I tried to follow the code style already present.
=> Fix doc comment regression and add tests.

src/expr.rs, tests/source/match.rs, tests/target/match.rs
=> Improve handling of commas after match arms.

src/chains.rs, tests/source/chains.rs, tests/target/chains-no-overflow.rs, tests/target/chains.rs
Fix https://github.com/nrc/rustfmt/issues/509.
=> Restore idempotence for chain formatting

src/patterns.rs, tests/source/pattern.rs, tests/target/pattern.rs
Fix https://github.com/nrc/rustfmt/issues/511.
=> Fix indentation for enum-style patterns

src/expr.rs, tests/source/match.rs, tests/target/match.rs
Fix https://github.com/nrc/rustfmt/issues/496.
=> Bump match inner block indent a level

src/bin/rustfmt.rs
For now `rustfmt.toml` file is searched in the current directory and its parents. This PR change this behaviour to start search of config file in the directory of the input file and recursively up to its parents.
I think it is much more logical and responsible concept of "project configuration".
=> Lookup of rustfmt.toml file should be relative from input file

src/bin/rustfmt.rs, src/config.rs
Fixes https://github.com/nrc/rustfmt/issues/532.
=> Print configuration options once in help message

src/expr.rs, src/items.rs, src/lib.rs, src/visitor.rs, tests/source/issue-510.rs, tests/target/issue-510.rs
Fix https://github.com/nrc/rustfmt/issues/510.
=> Address some issues with multiline patterns in let statements

README.md
=> Link in README

src/items.rs, tests/source/structs.rs, tests/target/structs.rs
=> Format tuple structs better

.travis.yml
... that I broke by introducing travis-cargo.
=> Try fixing OSX builds

src/chains.rs, tests/source/chains.rs, tests/target/chains.rs
Fixes https://github.com/rust-lang-nursery/rustfmt/issues/587.
=> Fix span issue with generic method calls

src/items.rs, tests/source/structs.rs, tests/target/structs.rs
Fixes https://github.com/rust-lang-nursery/rustfmt/issues/595.
=> Fix brace indentation after where clause

src/bin/rustfmt.rs, src/config.rs, src/lib.rs
=> Add verbose mode

Cargo.lock, src/items.rs, src/macros.rs, src/patterns.rs, src/visitor.rs
Note that this requires https://github.com/serde-rs/syntex/pull/22 to land before we can pass tests
=> Slightly awkward rustup

README.md, atom.md
=> Instructions for using Rustfmt from Atom.

README.md, atom.md
Updated atom instruction will correct image sizes and better wording.
=> Atom instructions

src/expr.rs, tests/source/struct_lits.rs, tests/source/struct_lits_multiline.rs, tests/target/struct_lits.rs, tests/target/struct_lits_multiline.rs
=> Comments in structs use appropriate style

src/chains.rs, tests/source/long_field_access.rs, tests/target/long_field_access.rs
=> Fix long field accesses not being broken onto separate lines

src/visitor.rs, tests/source/mod-1.rs, tests/source/mod-2.rs, tests/target/mod-1.rs, tests/target/mod-2.rs
Fix https://github.com/rust-lang-nursery/rustfmt/issues/621.
=> Rewrite module declarations

Contributing.md
Small nit, but it really annoys me.
=> Fix incorrect usage of 'it's'

src/items.rs, src/types.rs, src/utils.rs, src/visitor.rs, tests/source/fn-simple.rs, tests/target/extern.rs, tests/target/fn-simple.rs, tests/target/hard-tabs.rs
Fix https://github.com/rust-lang-nursery/rustfmt/issues/105.
Fix https://github.com/rust-lang-nursery/rustfmt/issues/616.
Fix https://github.com/rust-lang-nursery/rustfmt/issues/276.
Close https://github.com/rust-lang-nursery/rustfmt/issues/350.
=> Improve function type formatting

src/visitor.rs, tests/source/multiple.rs, tests/target/multiple.rs
=> Take rustfmt_skip attribute into account on modules

src/items.rs, src/visitor.rs, tests/source/type_alias.rs, tests/target/type_alias.rs
=> Format type aliases

src/items.rs, tests/source/fn-simple.rs, tests/target/fn-simple.rs
Closes https://github.com/rust-lang-nursery/rustfmt/issues/295.
First pull request for [24 pull requests](http://24pullrequests.com/).
=> Break function headers earlier

tests/source/string-lit.rs, tests/source/trait.rs, tests/target/string-lit.rs, tests/target/trait.rs
Regression test for https://github.com/rust-lang-nursery/rustfmt/issues/654.
Closes https://github.com/rust-lang-nursery/rustfmt/issues/459.
=> Regression tests

src/expr.rs, src/items.rs, src/lib.rs, src/patterns.rs, src/types.rs, tests/source/structs.rs, tests/target/structs.rs
Fixes https://github.com/rust-lang-nursery/rustfmt/issues/677.
=> Fixed named arguments in bare function types

README.md
New plugin for rust developers using sublime text 3.
=> add sublime text 3 binding plugin link

src/items.rs, tests/target/fn.rs
Fixes https://github.com/rust-lang-nursery/rustfmt/issues/688.
=> Don't panic on function return type rewrite failure

src/string.rs, tests/source/string-lit.rs, tests/target/string-lit.rs
Fixes https://github.com/rust-lang-nursery/rustfmt/issues/682.
=> Prevent backslash stripping in string literals

src/bin/cargo-fmt.rs
Quiet mode supresses rustfmt's stdout, verbose mode prints a list of targets that are going to be formatted.
=> Add verbose and quiet flags to cargo-fmt

src/chains.rs, src/items.rs, src/types.rs, tests/source/impls.rs, tests/target/impls.rs
Fixes https://github.com/rust-lang-nursery/rustfmt/issues/723.
=> format typed mut self

src/config.rs, src/expr.rs, tests/source/match-wildcard-trailing-comma.rs, tests/target/match-wildcard-trailing-comma.rs
=> Trailing commas for wildcard arms

src/filemap.rs
I'm open to any comments on how to do this in a better way
=> stop creating bk files if there are no changes. Fixes #733

src/expr.rs, tests/source/expr.rs, tests/target/expr.rs
Fixes #767 the span given to the sub-rewrites was too big and the body were searched for "else".
Where should the test be placed? Should I introduce a another file just for this piece of code?
=> fixes parsing issue #767

README.md
Add checkstyle and more detail on each of the write modes.
=> Update the README concerning write modes.

src/visitor.rs, tests/target/comment2.rs, tests/target/comment3.rs, tests/target/mod-1.rs
=> Put empty modules on one line

src/bin/rustfmt.rs
Adds a config-path option for rustfmt. If this argument is provided,
it recursively searches the config-path for a rustfmt.toml file.
If file is not found, reverts to searching the file input path for the
config file or uses default options.
Closes #778
=> Add support for the config-path option

Cargo.lock
This was missed in 82a177e.
Refs #805
=> Bump version in Cargo.lock

Cargo.lock
Some privacy stuff changed into a hard error.
=> Upgrade deps to make it compile again

src/types.rs, tests/source/issue-811.rs, tests/target/issue-811.rs
Attempts to fix https://github.com/rust-lang-nursery/rustfmt/issues/811.
Unit tests ran fine, fingers crossed. :grimacing:
=> Fix for issue #811

src/items.rs, tests/source/issue-850.rs, tests/target/issue-850.rs
=> Fix ordering of "const unsafe fn"

src/items.rs, tests/source/extern.rs, tests/target/extern.rs
=> Keep empty extern blocks on one line

src/chains.rs, src/comment.rs, src/expr.rs, src/items.rs, tests/source/issue-510.rs, tests/system.rs, tests/target/closure.rs, tests/target/issue-510.rs, tests/target/match.rs, tests/target/tuple.rs
=> Don't apply the function args heuristic to tuple lits.

Cargo.lock, src/items.rs, tests/source/impls.rs, tests/target/impls.rs
Fixes https://github.com/rust-lang-nursery/rustfmt/issues/875.
=> Fix tuple destructuring in impl fns

src/bin/cargo-fmt.rs
Previously `cargo-fmt` always returned `0` exit status. Now it returns `1` if command line flags are wrong and forwards status code of `rustfmt` oherwise
=> cargo-fmt: don't return zero on failure

src/expr.rs, src/items.rs, tests/source/struct_lits.rs, tests/source/structs.rs, tests/target/struct_lits.rs, tests/target/structs.rs
r? @marcusklaas (sorry for so many review requests!)
=> Empty structs and struct lits

src/expr.rs, src/types.rs, tests/source/type.rs, tests/target/type.rs
=> Handle variadic function types

src/expr.rs, src/utils.rs, tests/source/closure.rs, tests/target/chains-no-overflow.rs, tests/target/chains.rs, tests/target/closure.rs
And some general refactoring of closure code.
Fixes #863 
=> Be careful about where we change braces in closures

src/items.rs, tests/source/impls.rs, tests/target/impls.rs
Fixes https://github.com/rust-lang-nursery/rustfmt/issues/826.
=> Fix brace indentation for impl items

tests/target/issue-770.rs
Closes https://github.com/rust-lang-nursery/rustfmt/issues/770.
=> Add regression test for issue 770

LICENSE-APACHE, LICENSE-MIT, README.md
I know absolutely nothing about licensing, so I hope this makes sense. This is pretty much a carbon copy of license stuff of the rust project.
Closes https://github.com/rust-lang-nursery/rustfmt/issues/361.
=> Add license stuff

src/expr.rs, tests/source/issue-855.rs, tests/target/issue-855.rs
Fixes https://github.com/rust-lang-nursery/rustfmt/issues/855.
=> Check length of break and continue expressions

src/expr.rs, tests/source/type-ascription.rs, tests/target/type-ascription.rs
Closes https://github.com/rust-lang-nursery/rustfmt/issues/848.
=> Format type ascription

src/bin/rustfmt.rs
`update_config()` was parsing the `write-mode` option once for each file
argument. This commit parses them once up front into a `CliOptions`
struct, which is then applied to the config before calling `run()`.
=> rustfmt: Parse options once instead of once per file argument

src/patterns.rs, tests/source/issue-913.rs, tests/target/issue-913.rs
=> Fix off-by-one error in pattern formatting

src/config.rs, src/expr.rs, tests/source/control-brace-style-always-next-line.rs, tests/source/control-brace-style-always-same-line.rs, tests/source/else-if-brace-style-always-next-line.rs, tests/source/else-if-brace-style-always-same-line.rs, tests/source/else-if-brace-style-closing-next-line.rs, tests/target/control-brace-style-always-next-line.rs, tests/target/control-brace-style-always-same-line.rs, tests/target/else-if-brace-style-always-next-line.rs, tests/target/else-if-brace-style-always-same-line.rs, tests/target/else-if-brace-style-closing-next-line.rs
=> Added option to configure if/else brace style

src/visitor.rs, tests/source/static.rs, tests/target/static.rs
=> Format visibility of associated consts

src/lib.rs, src/macros.rs, tests/source/macros.rs, tests/target/macros.rs
Closes #915
Closes #930
Closes #931
=> Bail out on recovered errors.

src/comment.rs, src/visitor.rs, tests/target/attrib.rs, tests/target/structs.rs
And as a side-effect format doc comments
=> Handle attributes on modules

src/rustfmt_diff.rs
=> Fall back to basic stdout if we can't unwrap a fancy terminal

src/visitor.rs, tests/source/mod-2.rs, tests/target/mod-2.rs
=> Format inline attributes on out-of-line modules

src/comment.rs, src/expr.rs, tests/source/expr.rs, tests/target/expr.rs
Fixes https://github.com/rust-lang-nursery/rustfmt/issues/1002.
=> Fix constraints on pattern formatting of else arms

tests/source/assignment.rs, tests/target/assignment.rs
Closes https://github.com/rust-lang-nursery/rustfmt/issues/269 and possibly https://github.com/rust-lang-nursery/rustfmt/issues/497.
=> Add test for general assignment breaks

src/items.rs, src/types.rs
Potentially refactored several other joins that _may_ not have been in the scope of this issue, happy to weed those out if they shouldn't be covered in this PR.
This resolves #1014.
=> Refactor string collects to itertools join

src/expr.rs
Fixes https://github.com/rust-lang-nursery/rustfmt/issues/1058.
=> Fix integer underflow

src/expr.rs, tests/source/loop.rs, tests/target/loop.rs
=> Fix width computation in Loop::rewrite

src/file_lines.rs
=> Canonicalize file paths within the map of file line ranges

src/imports.rs, tests/source/imports.rs, tests/target/imports.rs
=> Fix imports with absolute paths

README.md
=> Put rustfmt on PATH so `cargo fmt` works on Travis

src/comment.rs, src/expr.rs, tests/source/tuple.rs
=> Fix #550: `if` nested in tuple is indented oddly

src/items.rs
=> Fix self test

src/filemap.rs
This change allows rustfmt to build again.
=> Fix broken import

src/types.rs, tests/source/type.rs, tests/target/type.rs
* Remove "TODO" conversion
* Add a couple of simple test cases
Fixes #1154
Fix courtesy of @singaraiona
=> Quick fix for "impl Trait"

src/missed_spans.rs, tests/source/issue-1192.rs, tests/target/issue-1192.rs
=> Remove extra whitespace after macro calls

src/config.rs, src/patterns.rs, tests/source/pattern-condense-wildcards.rs, tests/target/pattern-condense-wildcards.rs
Closes https://github.com/rust-lang-nursery/rustfmt/issues/1144.
=> Condense suffix strings of simple wildcards in patterns

src/items.rs, tests/target/indented-impl.rs
=> Indent open brace for impl when nested.

src/expr.rs, tests/source/long-match-arms-brace-newline.rs, tests/target/long-match-arms-brace-newline.rs
=> Don't drop opening brace on long line matches.

src/bin/cargo-fmt.rs
Addresses #828 and https://github.com/lunaryorn/emacs-module.rs/issues/4 and probably numerous others.
=> Recognize "rlib" and "cdylib" crates

src/lib.rs
I think having more unit tests will make it easier to spot regression, solve bug, etc, because when the test failed, it's closer to the components being tested. It will also help people understand how a particular function works.
This PR is just an initial work toward that, and to get feedback on the idea.
=> added unit tests for Indent and Shape

src/patterns.rs, tests/target/empty-tuple-no-conversion-to-unit-struct.rs
=> Prevent conversion of empty tuples to unit structs

src/lists.rs, tests/source/structs.rs, tests/target/structs.rs
=> Check existence of pre comment explicitly

src/expr.rs, tests/source/large_vec.rs, tests/target/large_vec.rs
=> Use block indent when visual indent exceeds max_width

src/expr.rs, tests/source/match.rs, tests/target/match.rs
This PR closes #1282, #1365 and #1460.
=> Use block when arm exceeds max_width

Cargo.lock, Cargo.toml, src/bin/cargo-fmt.rs, src/config.rs, src/file_lines.rs, src/lib.rs, src/utils.rs
=> Drop rustc-serialize, use serde, update toml dependency

src/visitor.rs, tests/source/issue-1158.rs, tests/target/issue-1158.rs
=> Format macros in trait item position

tests/source/closure.rs, tests/source/comment.rs, tests/source/issue-1350.rs, tests/source/structs.rs, tests/source/try-conversion.rs, tests/target/closure.rs, tests/target/comment.rs, tests/target/issue-1350.rs, tests/target/structs.rs, tests/target/try-conversion.rs
This PR adds tests for issues which can be closed on the current master.
Specifically, #470, #1291, #1350, #1364 and #1388 can be closed.
=> Add tests for issues which can be closed on master

src/expr.rs, src/visitor.rs, tests/source/large-block.rs, tests/target/large-block.rs
=> Use block indent if visual indent exceeds max_width when rewriting block

src/expr.rs, tests/source/match.rs, tests/target/match.rs
=> Apply closure exception to match in args

src/expr.rs, tests/source/nested-if-else.rs, tests/target/nested-if-else.rs
=> Remove visual_indent when rewriting else block

src/expr.rs, tests/source/issue-1468.rs, tests/target/issue-1468.rs
This PR fixes the latter example of #1468.
=> Inherit alignment to 'else'

src/expr.rs, tests/source/configs-fn_call_style-block.rs, tests/target/configs-fn_call_style-block.rs
Closes #1521 (with refactoring, sorry for noise).
=> Use multiline when args exceeds max_width in fn_call_style = "block"

src/patterns.rs, tests/source/configs-trailing_comma-never.rs, tests/target/configs-trailing_comma-never.rs
=> Add a missing trailing comma before elipses

src/comment.rs, src/expr.rs
=> Forbid early line breaks inside else if

src/items.rs, tests/source/configs-fn_args_layout-block.rs, tests/target/configs-fn_args_layout-block.rs
=> Use multiline when signature does not fit single line

Configurations.md, src/config.rs, src/visitor.rs, tests/source/configs-reorder_imports_in_group-false.rs, tests/source/configs-reorder_imports_in_group-true.rs, tests/target/configs-reorder_imports_in_group-false.rs, tests/target/configs-reorder_imports_in_group-true.rs
=> reorder imports in group

build.rs, src/chains.rs, src/expr.rs, src/items.rs, src/lists.rs, src/macros.rs, src/missed_spans.rs, src/patterns.rs, src/types.rs, src/visitor.rs, tests/source/configs-fn_call_style-block.rs, tests/source/macros.rs, tests/target/configs-fn_call_style-block.rs, tests/target/macros.rs, tests/target/match.rs
This PR closes #1563 and closes #1420.
=> Implement vec![expr; expr] and avoid unnecessary indent in chain

Configurations.md, src/chains.rs, src/config.rs, src/expr.rs, src/file_lines.rs, src/items.rs, src/lists.rs, src/macros.rs, src/modules.rs, src/patterns.rs, src/string.rs, src/utils.rs, tests/source/configs-fn_call_style-block.rs, tests/system.rs, tests/target/closure.rs, tests/target/configs-chain_split_single_child-false.rs, tests/target/configs-chain_split_single_child-true.rs, tests/target/configs-fn_call_style-block.rs
This PR
1. allows last method of chain to go multiline if `fn_call_style` is `Block`
2. adds `chain_split_single_child` option
3. fixes small bugs related to rewriting chain
Closes #1380 and closes #1579.
=> Enhance chain

src/visitor.rs, tests/target/associated_type_defaults.rs
=> Allow default associated types

src/items.rs, src/visitor.rs, tests/target/impl.rs
=> Allow comments after where clause

src/items.rs, src/types.rs, tests/source/impls.rs, tests/target/impls.rs
=> Allow attributes in generics of impl

src/missed_spans.rs, tests/target/issue-1598.rs
=> Fix index bug in write_snippet_inner

src/chains.rs, tests/source/tuple.rs, tests/target/tuple.rs
=> Put a space between nested tuple field

src/expr.rs, src/lib.rs, src/macros.rs, src/rewrite.rs, src/visitor.rs, tests/target/nested-visual-block.rs
Closes #1078, closes #1580 and closes #1581.
=> Use block indent style when visual indent style fails

src/items.rs, tests/target/issue-1113.rs
=> Preserve the layout of comment after return type

src/items.rs, src/visitor.rs, tests/target/comment-inside-const.rs
=> Use recover_comment_removed in rewrite_static

src/items.rs, tests/source/enum.rs, tests/target/enum.rs
Closes #1115 (Related PR: #1597).
=> Allow comments after attributes on enum fields

src/expr.rs
=> Do not add offset to match pattern when using Rfc style

src/filemap.rs
=> Do not overwrite files when there are no diffs in Overwrite mode

src/lib.rs
Closes #1128 and closes #1606.
What this PR is trying to do is to set `err_count` of `Handler` to 0.
However, since `err_count` is a private field, we need to reconstruct `Handler` each time.
Also I am not sure how to add tests for #1128 and #1606.
=> Reset the error count of parser from the previous file 

Configurations.md, src/lists.rs, tests/target/configs-struct_lit_style-visual.rs
=> Add offset to struct literal fields when `struct_lit_style` is `"Visual"`

src/items.rs, tests/source/configs-fn_args_layout-block.rs, tests/target/configs-fn_args_layout-block.rs
=> Use correct indent for return type when it goes multi line

src/expr.rs, tests/target/configs-control_style-rfc.rs, tests/target/match.rs
=> Put match arm's guard on new line if it exceeds max width

src/lib.rs
=> Use with_emitter instead of with_tty_emitter

.travis.yml, appveyor.yml, src/comment.rs, src/expr.rs, src/items.rs, src/macros.rs, src/string.rs, src/types.rs, src/visitor.rs, tests/target/configs-control_style-rfc.rs, tests/target/configs-trailing_comma-never.rs, tests/target/expr.rs, tests/target/fn_args_layout-block.rs, tests/target/hard-tabs.rs, tests/target/issue-1397.rs, tests/target/macros.rs, tests/target/match.rs
This PR makes rustfmt to pass tests again 😄 
Closes #1665.
A few changes are suspicious and I am not sure if they are correctly formatted (e.g. please take a look at comment.rs). Others look harmless to me.
=> Get tests passing again

src/chains.rs, src/comment.rs, src/expr.rs, src/file_lines.rs, src/imports.rs, src/items.rs, src/lists.rs, src/missed_spans.rs, src/patterns.rs, src/string.rs, src/types.rs, src/utils.rs, src/visitor.rs, tests/system.rs, tests/target/configs-chain_split_single_child-true.rs, tests/target/expr.rs, tests/target/match.rs
=> Allow overflowing the last item of chain only if it is multi-lined

src/expr.rs, src/macros.rs, tests/source/issue-1693.rs, tests/target/issue-1693.rs
=> Use correct indentaion for vec! with semicolon

src/expr.rs, src/visitor.rs, tests/target/issue-1703.rs
=> Preserve comments inside attributes

Cargo.lock, src/bin/cargo-fmt.rs, src/bin/rustfmt.rs, src/checkstyle.rs, src/expr.rs, src/file_lines.rs
=> Align multiline string literal

src/expr.rs, tests/source/tuple.rs, tests/target/expr-block.rs, tests/target/tuple.rs
=> Apply the same overflowing rule to tuple as function call

src/expr.rs, tests/source/closure.rs, tests/target/closure.rs
=> Disallow overflowing closure if there are multiple closures in args

src/expr.rs, src/items.rs, tests/source/configs-trailing_comma-never.rs, tests/target/configs-trailing_comma-never.rs
=> Apply config.trailing_comma wherever possible

src/bin/cargo-fmt.rs
=> Do not run cargo fmt if there are unnecessary arguments

src/file_lines.rs
Related to https://github.com/rust-lang-nursery/rls/pull/346
=> Public file-lines constructor

Configurations.md
Fixes https://github.com/rust-lang-nursery/rustfmt/issues/1679 and https://github.com/rust-lang-nursery/rustfmt/issues/1722
=> Fix defaults in Configurations.md

src/bin/rustfmt.rs, src/expr.rs, src/items.rs, src/visitor.rs, tests/source/expr.rs, tests/target/expr.rs
=> Allow single line block in expression context

README.md
=> remove link to old style guidelines

src/expr.rs, src/macros.rs, tests/source/macros.rs, tests/target/macros.rs, tests/target/tuple.rs
=> Preserve trailing comma of macro invocation

src/expr.rs, tests/source/expr.rs, tests/target/expr.rs
=> Put multi-lined index on the next line if it fits in one line

src/bin/rustfmt.rs
=> Suppress write mode warning

src/expr.rs, tests/source/configs-closure_block_indent_threshold--1.rs, tests/target/configs-closure_block_indent_threshold--1.rs
=> Use correct one line budget in rewrite_closure_block

src/expr.rs, tests/target/expr-block.rs, tests/target/expr.rs, tests/target/tuple.rs
cc https://github.com/rust-lang-nursery/fmt-rfcs/issues/61.
=> Rfc: Combine Array

src/expr.rs, tests/source/expr.rs, tests/target/expr.rs
=> Add a space before range if lhs ends with dot

src/expr.rs, tests/source/expr.rs, tests/target/expr.rs
=> Use correct one line budget when rewriting index

src/items.rs, src/visitor.rs, tests/source/unions.rs, tests/target/unions.rs
=> Format union

Configurations.md, src/bin/cargo-fmt.rs, src/chains.rs, src/comment.rs, src/config.rs, src/expr.rs, src/imports.rs, src/issues.rs, src/items.rs, src/lib.rs, src/lists.rs, src/macros.rs, src/patterns.rs, src/types.rs, src/utils.rs, src/visitor.rs, tests/source/configs-wrap_match_arms-false.rs, tests/source/configs-wrap_match_arms-true.rs, tests/target/configs-wrap_match_arms-false.rs, tests/target/configs-wrap_match_arms-true.rs, tests/target/expr-block.rs, tests/target/indent_match_arms.rs, tests/target/issue-1350.rs, tests/target/match-nowrap.rs, tests/target/match.rs, tests/target/nested-visual-block.rs
This PR implements combining against match arm (cc https://github.com/rust-lang-nursery/fmt-rfcs/issues/61).
=> Rfc: combining match arm

src/visitor.rs, tests/source/attrib.rs, tests/target/attrib.rs
=> Do not count the number of parens inside str or comment

tests/system.rs
=> assert no errors on formatting test source

tests/source/imports.rs, tests/target/imports.rs
=> add test for root glob imports

src/chains.rs, src/comment.rs, src/expr.rs, src/imports.rs, src/items.rs, src/lists.rs, src/string.rs, src/summary.rs, src/visitor.rs, tests/system.rs, tests/target/configs-control_style-rfc.rs, tests/target/expr.rs, tests/target/issue-1239.rs, tests/target/long-match-arms-brace-newline.rs, tests/target/macros.rs, tests/target/match.rs
This PR consists of small fixes and implementing RFC style.
Closes #1792.
=> Small fixes

src/expr.rs, src/lib.rs, tests/source/attrib.rs, tests/target/attrib.rs
=> Cover missing comments between attributes and expressions

Cargo.lock, Cargo.toml, Configurations.md, README.md, src/bin/rustfmt.rs, src/config.rs
=> Change the writemode to overwrite

src/items.rs, tests/target/issue-1802.rs
=> Consider max_width when rewriting struct in single-line

src/visitor.rs, tests/source/configs-item_brace_style-always_next_line.rs, tests/source/configs-item_brace_style-prefer_same_line.rs, tests/source/configs-item_brace_style-same_line_where.rs, tests/target/configs-item_brace_style-always_next_line.rs, tests/target/configs-item_brace_style-prefer_same_line.rs, tests/target/configs-item_brace_style-same_line_where.rs, tests/target/indented-impl.rs, tests/target/item-brace-style-always-next-line.rs
=> Apply item_brace_style to module

src/items.rs, tests/source/enum.rs, tests/source/structs.rs, tests/target/enum.rs, tests/target/structs.rs
=> Put braces on the next line if it exceeds max width

src/expr.rs, src/imports.rs, src/items.rs, src/lists.rs, src/types.rs, src/vertical.rs, src/visitor.rs, tests/source/expr.rs, tests/target/expr.rs
=> Remove newlines between list elements for expressions 

src/items.rs, src/utils.rs, tests/target/impl.rs
=> Format defaultness

src/items.rs, tests/target/issue-1824.rs, tests/target/trait.rs, tests/target/where-clause-rfc.rs
=> Use correct BytePos for where when rewriting trait

src/items.rs, tests/source/trait.rs, tests/target/trait.rs
=> Fix a typo in rewrite_associated_type

src/utils.rs, src/visitor.rs, tests/source/file-lines-item.rs, tests/target/file-lines-item.rs
This is on top of #1836, and fixes the issues I saw in bindgen.
=> visitor: A few file lines fixes

src/expr.rs, src/imports.rs, src/items.rs, src/lists.rs, src/types.rs, src/vertical.rs, tests/source/match.rs, tests/target/match.rs
=> Match with max width

src/items.rs
Previously, rust parser did not provide a span for `ast::WhereClause` so we needed to construct the missing span manually. Since now the latest nightly compiler provides a span for `ast::WhereClause`, we could use it in rustfmt.
=> Use Span from ast::WhereClause

src/items.rs, tests/target/trailing_commas.rs, tests/target/type_alias.rs
This PR is a follow up of https://github.com/rust-lang-nursery/rustfmt/pull/1847#discussion_r130773467.
Also closes #1368.
=> Refactor `rewrite_where_clause()`

src/expr.rs, src/lib.rs, src/utils.rs, src/visitor.rs, tests/source/match.rs, tests/target/match.rs
=> Format inner attributes in match expr

src/chains.rs, src/expr.rs, src/imports.rs, src/items.rs, src/lists.rs, src/missed_spans.rs, src/patterns.rs, src/types.rs, src/vertical.rs, src/visitor.rs, tests/target/chains-indent-visual.rs, tests/target/chains-visual.rs, tests/target/match.rs
This PR removes unnecessary rewriting to solve the performance issue.
=> Remove unnecessary rewriting

src/items.rs, tests/source/comment.rs, tests/target/comment.rs
=> Cover comments between function args and the brace

Cargo.lock, src/comment.rs, src/expr.rs, src/items.rs, src/lib.rs, src/macros.rs, src/utils.rs, src/vertical.rs, tests/source/enum.rs, tests/target/attrib.rs, tests/target/configs-struct_field_align_threshold-20.rs, tests/target/enum.rs, tests/target/macros.rs, tests/target/struct-field-attributes.rs, tests/target/structs.rs, tests/target/unions.rs
=> Allow attributes to stay on the same line with fields

src/patterns.rs, tests/source/pattern.rs, tests/target/pattern.rs
=> Allow empty tuple pattern

README.md
=> Explain how to solve missing dll's on Windows

src/macros.rs, tests/source/macros.rs, tests/target/macros.rs
=> Add indent to macro we could not format

src/items.rs, tests/source/configs-fn_args_layout-visual.rs, tests/target/configs-fn_args_layout-visual.rs
=> Fix a typo in calculating overhead for fn args

src/expr.rs
=> Avoid rewriting big block twice

src/lists.rs, src/vertical.rs, tests/source/configs-attributes_on_same_line_as_field-false.rs, tests/target/configs-attributes_on_same_line_as_field-false.rs
=> Take attributes_on_same_line_as_field into account

Configurations.md
=> Show examples of default values first and annotate them with "(default)"

tests/system.rs
=> Remove unused import

src/items.rs, tests/source/impls.rs, tests/target/impls.rs
=> Fix a budget bug in Arg::rewrite()

src/items.rs, src/types.rs, src/utils.rs, src/visitor.rs
This PR attempts to reduce the number of arguments in `rewrite_fn()`.
=> Reduce number of arguments in rewrite_fn()

src/expr.rs, src/string.rs, src/visitor.rs, tests/source/string-lit.rs, tests/target/string-lit.rs
=> Format strings in attributes when `format_strings = true`

src/items.rs, src/types.rs, tests/source/where-clause-rfc.rs, tests/target/where-clause-rfc.rs
=> Use a correct budget for where predicate 

tests/source/skip.rs, tests/target/skip.rs
=> Add a test that the skip attribute applies to other attributes.

src/types.rs
cc https://github.com/rust-lang/rust/pull/45175
=> Fix breakage from `dyn Trait`

src/items.rs, tests/source/struct-field-attributes.rs, tests/target/struct-field-attributes.rs
=> Simplify multiline case in rewrite_struct_field()

src/chains.rs, src/expr.rs, src/items.rs, src/string.rs, tests/source/chains.rs, tests/target/chains.rs
=> Fix a subtle bug in rewriting chain

src/items.rs, tests/source/fn-simple.rs, tests/target/fn-simple.rs
=> Use a correct span for fn with pub(crate) syntax

src/items.rs, tests/source/enum.rs, tests/target/enum.rs
=> Use rewrite_assign_rhs when rewriting unit variant

src/items.rs, src/types.rs, tests/source/enum.rs, tests/target/enum.rs
=> Remove redundant shrink_left

src/expr.rs, tests/source/match.rs, tests/target/match.rs
=> Format match expr with empty body 

src/lib.rs
Fix #1951  by adding checking if term supports attr Bold
=> fix output panics on unable to write to stderr

src/items.rs, src/visitor.rs
Breakage came from https://github.com/rust-lang/rust/pull/45247/
=> Fix compile on 2017-11-04 nightly

src/items.rs, tests/source/structs.rs, tests/target/structs.rs
=> Use correct span for tuple struct's body 

Cargo.lock, Cargo.toml, src/bin/cargo-fmt.rs, src/bin/rustfmt-format-diff.rs, src/bin/rustfmt.rs, src/comment.rs, src/config.rs, src/expr.rs, src/imports.rs, src/items.rs, src/lib.rs, src/macros.rs, src/modules.rs, src/patterns.rs, src/types.rs, src/utils.rs, src/visitor.rs
This PR applies refactoring from rust-clippy.
=> Refactor code via clippy

src/items.rs, tests/source/structs.rs, tests/target/structs.rs
=> Wrap long single field tuple struct

Configurations.md
---
Various fixes for the configuration documentation I noticed when making my `rustfmt.toml` file.
=> Configuration fixes

src/codemap.rs, src/lib.rs, src/visitor.rs, tests/source/issue-2025.rs, tests/target/issue-2025.rs, tests/target/loop.rs, tests/target/nestedmod/mod.rs, tests/target/nestedmod/mod2b.rs
=> Remove empty lines at the beginning of the file 

src/bin/git-fmt.rs, src/items.rs, tests/source/structs.rs, tests/target/structs.rs
=> Format generics on unit struct 

src/bin/rustfmt.rs, src/config.rs, src/filemap.rs, src/lib.rs, src/rustfmt_diff.rs, src/utils.rs, tests/system.rs
Fix #1479 by adding a new CLI option: color
=> add cli option for color

src/expr.rs, tests/source/match.rs, tests/target/match.rs
=> Return None when a literal exceeds budget 

src/lists.rs, tests/source/match.rs, tests/target/match.rs
=> Look for a newline after match arm only when there is one 

src/lists.rs, tests/source/comment.rs, tests/target/comment.rs
=> Prevent panicking by a nested comment

src/expr.rs, src/items.rs, tests/source/trait.rs, tests/target/trait.rs
=> Prevent long associated type from overflowing max width

src/bin/rustfmt.rs, src/items.rs, tests/source/enum.rs, tests/target/enum.rs
=> Force vertical layout for all variants if one of then use multiple lines 

src/closures.rs, tests/source/closure.rs, tests/target/closure.rs
=> Do not squash unsafe block on closure body

src/lists.rs, tests/source/issue-2111.rs, tests/target/fn-args-with-last-line-comment.rs, tests/target/issue-2111.rs, tests/target/type_alias.rs
=> Use vertical layout when there are single line comments in import

src/expr.rs, tests/source/issue-2179.rs, tests/target/issue-2179.rs
=> Put rhs on the same line as lhs if putting rhs on next line exceeds max width

src/config.rs
=> Print unstable option's name on warning

src/items.rs, tests/target/impl.rs
=> Format defualtness on specialized impl const 

src/expr.rs, src/macros.rs, tests/source/macros.rs, tests/target/macros.rs
=> Preserve trailing comma on array inside macro call

Configurations.md
=> Adds where_single_line in configuration documentation

src/expr.rs, tests/source/expr.rs, tests/target/chains-visual.rs, tests/target/expr.rs
=> Combine a short callee and a single argument

src/comment.rs, tests/target/issue-2197.rs
=> Do not format fenced code blocks in comment 

src/bin/cargo-fmt.rs
=> Use package name instead of target name for --package filter

src/imports.rs, tests/source/imports.rs, tests/target/imports.rs
=> Nested imports

src/macros.rs, src/patterns.rs, tests/source/macros.rs, tests/target/macros.rs
=> Format macro in pattern position 

src/chains.rs, src/closures.rs, src/expr.rs, src/items.rs, src/macros.rs, tests/source/closure.rs, tests/target/closure.rs, tests/target/configs-fn_call_indent-block.rs
=> Fix bugs related to closures

src/comment.rs, tests/source/configs-wrap_comments-true.rs, tests/target/configs-wrap_comments-true.rs
=> Trim a trailing whitespace on empty line inside code block comment 

src/comment.rs, tests/target/enum.rs, tests/target/issue-2123.rs, tests/target/structs.rs, tests/target/unions.rs
=> Respect leading whitespace when wrapping comment

CHANGELOG.md, src/bin/cargo-fmt.rs
=> Make 'cargo fmt' formats every workspace member

src/expr.rs, tests/source/expr.rs, tests/target/closure.rs, tests/target/expr.rs
=> Take the width of block's prefix into account only once 

src/items.rs, src/types.rs
=> Fixes compilation with rust version 2017-12-21

src/comment.rs, src/lib.rs, tests/target/issue-2197.rs
=> Format code block in comment

src/items.rs, tests/source/struct-field-attributes.rs, tests/target/struct-field-attributes.rs
=> Do not give up rewriting struct field when attribute is long

src/imports.rs, src/lib.rs, src/visitor.rs, tests/source/extern.rs, tests/target/extern.rs
=> Remove trailing comma from extern items snippet before comparing

src/issues.rs
So that it also reports Todo or FixME
=> case insensitive FIXME and TODO

src/imports.rs, tests/source/issue-2256.rs, tests/target/issue-2256.rs
=> Use correct BytePos when recovering comments on removed import 

Configurations.md
This is a minor rewording of a sentence. It can be seen live [here](https://github.com/davidalber/rustfmt/blob/reword-config-note/Configurations.md#horizontal).
=> Rewording configuration note

README.md
This is confusing a lot of people.
=> Fix installation instructions to use rustup

src/lib.rs
=> Explicitly disable colored output when it is not supported

rustfmt-config/src/config_type.rs, rustfmt-config/src/lib.rs, rustfmt-config/src/options.rs
=> scale WidthHeuristics by max_width

README.md
rustfmt-preview is now in stable
=> Simplify CI exaple in the readme

src/expr.rs, tests/source/paren.rs, tests/target/expr.rs, tests/target/paren.rs
=> Remove nested parens

Cargo.lock
=> Dedupe syn/quote

Cargo.lock, Cargo.toml, src/lib.rs, src/macros.rs
=> Update to the latest rustc-ap-syntax

Configurations.md
Just a minor typo fix, found while reading documentation.
=> /s/featuers/features

src/macros.rs, tests/source/macro_rules.rs, tests/target/macro_rules.rs
=> allow underscore in macro_rules!

Configurations.md, src/closures.rs, src/expr.rs, src/format-diff/main.rs, src/lists.rs, src/macros.rs, src/overflow.rs, src/rustfmt_diff.rs, tests/lib.rs, tests/target/chains.rs, tests/target/expr-block.rs, tests/target/match.rs
This PR applies heuristics used for function calls to array and vice versa.
cc #2196.
=> Combine simple heuristics for function calls and array 

src/macros.rs, tests/source/macro_rules.rs, tests/target/macro_rules.rs
Replaced unreachable! with error handling using Option.
Closes #2558
=> Remove unreachable! from macros.rs

tests/source/macros.rs, tests/target/macros.rs
Add test for https://github.com/rust-lang-nursery/rustfmt/issues/2574
=> Add test #2574

README.md
=> Include instructions to install on nightly

Configurations.md, src/config/mod.rs, src/items.rs, tests/source/configs/reorder_impl_items/false.rs, tests/source/configs/reorder_impl_items/true.rs, tests/target/configs/reorder_impl_items/false.rs, tests/target/configs/reorder_impl_items/true.rs
=> Add reorder_impl_items config option

Cargo.lock, Cargo.toml, src/bin/main.rs, src/lib.rs
=> Output xml header and footer only once 

Configurations.md
Default value changed in #2605
=> Fix example for reorder_imports

src/items.rs, src/utils.rs, tests/source/trait.rs, tests/target/trait.rs
Fixes [#2637](https://github.com/rust-lang-nursery/rustfmt/issues/2637)
=> keep auto trait

Cargo.lock, Cargo.toml, src/bin/main.rs, src/config/config_type.rs, src/config/mod.rs, src/config/options.rs, src/format-diff/main.rs, src/lib.rs
=> Use failure crate

Cargo.lock, Cargo.toml, src/items.rs, src/lib.rs, src/utils.rs
=> add rustc_target to dependencies

src/attr.rs, tests/source/attrib.rs, tests/target/attrib.rs
=> Use correct one line width for list attribute

.travis.yml, src/test/mod.rs
Also add a travis matrix entry for emulating the beta tests
=> Ensure tests pass on the beta compiler

src/chains.rs, src/closures.rs, src/comment.rs, src/config/options.rs, src/expr.rs, src/git-rustfmt/main.rs, src/imports.rs, src/items.rs, src/lib.rs, src/lists.rs, src/missed_spans.rs, src/overflow.rs, src/patterns.rs, src/test/mod.rs, src/types.rs, src/utils.rs, src/visitor.rs, tests/target/chains.rs, tests/target/configs/indent_style/block_call.rs, tests/target/expr-block.rs, tests/target/expr.rs, tests/target/try-conversion.rs
=> Apply small parent heuristic only when the chain is at the beginning of the line

src/bin/main.rs
=> Fix build failure

Cargo.lock, src/macros.rs, tests/source/macro_rules.rs, tests/target/macro_rules.rs
=> Fix treating the delimiter right after repeat as repeat as well 

Cargo.lock, Cargo.toml, tests/source/fn-simple.rs, tests/target/fn-simple.rs
=> Cargo update

ci/integration.sh
As suggested in https://github.com/rust-lang-nursery/rustfmt/pull/2715#issuecomment-390397152
=> Don't fail integration tests if the subject is not passing its own tests

Cargo.lock, Cargo.toml, src/items.rs, src/patterns.rs, tests/source/structs.rs, tests/target/structs.rs
=> Avoid inserting the closing paren after tuple struct containing parentheses and a where clause

src/matches.rs, src/overflow.rs, tests/source/expr.rs, tests/target/expr.rs
=> Avoid panicking on deeply nested expressions

README.md
=> add emit flag documentation

src/expr.rs, tests/target/raw_identifiers.rs
This addresses the issue raised in https://github.com/rust-lang-nursery/rustfmt/issues/2871.
=> Support raw identifiers in struct expressions

src/expr.rs, src/items.rs, src/utils.rs, src/visitor.rs, tests/source/async_block.rs, tests/source/async_fn.rs, tests/target/async_block.rs, tests/target/async_fn.rs
=> Format Async block and async fn

ci/integration.sh
=> Fix the Failure integration test

src/imports.rs, tests/source/imports.rs, tests/target/imports.rs
=> Handle imports with items whose name contains digits

.travis.yml
This should fix broken Travis.
=> Remove before_script

.travis.yml, src/comment.rs
=> Fix parsing '#'-hiding of rustdoc

src/comment.rs, src/utils.rs, tests/source/issue-2896.rs, tests/target/issue-2896.rs
=> Ignore comment in wrap_str

src/modules.rs
=> Use custom path value if one exists when searching modules

src/patterns.rs, tests/source/pattern.rs, tests/target/pattern.rs
=> Do not show wildcard pattern in slice pattern

src/expr.rs, src/lib.rs, tests/target/obsolete_in_place.rs
=> Format in-place expression like assignment 

src/attr.rs, tests/source/attrib.rs, tests/target/attrib.rs
=> Use span_ends_with_comma to find a trailing comma in an attribute

README.md
Is this the correct content to remove from https://github.com/rust-lang-nursery/rustfmt/issues/2923?
=> Remove old readme content

src/chains.rs, tests/target/raw_identifiers.rs
=> Handle raw identifiers in chain

src/chains.rs, tests/source/chains_with_comment.rs, tests/target/chains_with_comment.rs
=> Handle chain w/ try operators with spaces

src/formatting.rs
I've dabbled recently in seeing how hard it would be to compile rustfmt to wasm
and then run it in a web browser, and it turns out that it's [not too
hard][wasm]! In addition to patching a few dependencies which already have a
number of patches out rustfmt also needed some modifications to get it to work,
namely avoiding the usage of `Instant::now()` on the "happy path" which doesn't
work on wasm (it just panics).
This commit is an attempt to add a support for this by avoiding using
`Instant::now()` on the wasm target, but panicking if the actual time elapsed is
requested (which doesn't happen unless verbosely logging I believe).
[wasm]: https://alexcrichton.github.io/rustfmt-wasm/
=> Support platforms without a timer

src/items.rs, tests/source/long-fn-1.rs, tests/target/long-fn-1.rs
=> Refactor the corner case of handling long function

src/items.rs, src/visitor.rs, tests/source/trait.rs, tests/target/trait.rs
=> Format generics on associated types

src/config/options.rs
After running `rustfmt --unstable-features --help=config` 
Before
```
edition [2015|2018] Default: Edition2015 (unstable)
The edition of the parser (RFC 2052)
```
After
```
edition [2015|2018] Default: 2015 (unstable)
The edition of the parser (RFC 2052)
```
=> Fix help message for edition config option

src/comment.rs
=> comment: Add documentation to `is_doc_comment` public method

src/chains.rs, src/config/file_lines.rs, tests/source/expr.rs, tests/target/expr.rs
=> Consider a multi-lined array as a block-like expression 

src/macros.rs, tests/source/macros.rs, tests/target/issue-2523.rs, tests/target/macros.rs
=> Format macro calls with item-like arguments

.gitignore
=> .gitignore: Ignore Emacs backup files

src/test/mod.rs
=> Enable `stdin_disable_all_formatting_test` test

src/rewrite.rs
=> rewrite: adjust comment as it refers to `is_if_else_block`

Cargo.lock, Cargo.toml
=> Update rustc-ap-* to 272.0.0

src/bin/main.rs, src/closures.rs, src/config/config_type.rs, src/expr.rs
=> Replace `.unwrap_or` with `.map_or` in few places

src/types.rs, tests/source/type.rs, tests/target/type.rs
=> Do not add parens around lifetimes 

src/expr.rs, src/items.rs, tests/source/trait.rs, tests/target/trait.rs
=> Fix poor formatting of empty trait with generic bounds

src/expr.rs, src/lists.rs, src/macros.rs, src/pairs.rs, src/string.rs, src/utils.rs, tests/source/chains.rs, tests/target/chains.rs
=> Simplify multi-lining binop exprs

src/items.rs, tests/source/type.rs, tests/target/type.rs
=> Use correct width when formatting type on local statement 

Configurations.md, src/config/mod.rs
=> Stabilize `edition` configuration option

src/types.rs, tests/source/type.rs, tests/target/type.rs
=> Do not remove path disambiugator inside macro 

.travis.yml, ci/integration.sh
Refs: https://github.com/rust-lang-nursery/crater/issues/358
=> CI: only run unit tests for `crater`

src/missed_spans.rs, src/visitor.rs, tests/target/issue-3032.rs
=> fix logic for adding or not a newline after a missed span

src/types.rs, tests/source/type.rs, tests/target/fn-simple.rs, tests/target/issue-2164.rs, tests/target/type.rs
=> Prefer to break arguments over putting output type on the next line 

src/expr.rs, src/reorder.rs, tests/source/issue-3217.rs, tests/target/issue-3217.rs
=> fix the visitor's starting position when visiting a labelled block

Configurations.md, Contributing.md, Design.md, README.md, atom.md
Signed-off-by: Lucian <lucian.buzzo@gmail.com>
=> Fix minor typos and grammar

Configurations.md
=> Fix formatting in Configurations.md

.travis.yml, src/expr.rs, tests/source/expr.rs, tests/target/expr.rs
=> Fix shape when formatting return or break expr on statement position

src/closures.rs, src/types.rs, tests/source/macros.rs, tests/target/macros.rs
=> Do not modify original source code inside macro call

src/overflow.rs, tests/source/issue-3272/v1.rs, tests/source/issue-3272/v2.rs, tests/source/macros.rs, tests/source/single-line-macro/v1.rs, tests/source/single-line-macro/v2.rs, tests/target/issue-3272/v1.rs, tests/target/issue-3272/v2.rs, tests/target/macros.rs, tests/target/single-line-macro/v1.rs, tests/target/single-line-macro/v2.rs
=> Use the same rule between function and macro

tests/source/issue-3234.rs, tests/target/issue-3234.rs
this issue is already resolved
related: https://github.com/rust-lang/rustfmt/issues/3234
=> add issue-3234 test

Cargo.toml, ci/integration.sh, rustfmt.toml
=> Use edition 2018

src/lib.rs, src/macros.rs, src/utils.rs, tests/source/issue-3302.rs, tests/target/issue-3302.rs
=> fix formatting of strings within a macro

Configurations.md
=> do not put tracking issue as part of the option's title

src/items.rs, tests/source/no_arg_with_commnet.rs, tests/target/no_arg_with_commnet.rs
I cannot find the issue but found the comment about the error. So I fixed it.
=> fix not to remove comment in the case of no arg

src/lists.rs, src/spanned.rs, src/types.rs, tests/source/const_generics.rs, tests/target/const_generics.rs
related:
- https://github.com/rust-lang/rustfmt/issues/3418
- https://github.com/rust-lang/rustfmt/issues/3336
=> implement for const generics

src/expr.rs, tests/source/async_block.rs, tests/target/async_block.rs
=> Fix formatting of async blocks

src/formatting.rs
=> Discard error report in silent_emitter

src/types.rs, tests/source/type.rs, tests/target/type.rs
=> Do not add a space after empty impl

src/cargo-fmt/main.rs
- Make sure that we run rustfmt against every edition
- Use BTreeMap to guarantee consistent ordering
Closes #3461.
=> Fix cargo fmt inconsistency

.travis.yml, appveyor.yml, src/test/mod.rs
=> Test with larger stack size

src/bin/main.rs
Basically this is an attempt to implement #3283 so that the config that would be used to format a file can be written to stdout. Suggestions welcome :open_hands:.
This is a duplicate of the closed PR #3471 as I mistakenly deleted the base fork.
=> Add option to print current config to stdout

src/lists.rs, tests/source/issue-2995.rs, tests/target/issue-2995.rs
=> Fix indexing panic on unicode whitespaces

README.md
=> Fix Travis-CI badge url

docs/index.html, index.html
related: https://github.com/rust-lang/rustfmt/issues/3455
=> create GitHub page for Configuration.md

README.md
=> update README.md for GitHub page

src/chains.rs, src/closures.rs, src/comment.rs, src/config/file_lines.rs, src/config/mod.rs, src/formatting.rs, src/git-rustfmt/main.rs, src/imports.rs, src/items.rs, src/lib.rs, src/lists.rs, src/macros.rs, src/reorder.rs, src/source_file.rs, src/source_map.rs, src/string.rs, src/test/mod.rs, src/vertical.rs, src/visitor.rs
clippy::needless_return
clippy::redundant_closure
clippy::or_fun_call
clippy::len_zero
clippy::expect_fun_call
clippy::assertions_on_constants
clippy::identity_conversion
clippy::chars_last_cmp
=> fix a bunch of clippy warnings

src/cargo-fmt/main.rs
related: https://github.com/rust-lang/rustfmt/issues/3505
=> fix not to emit version

src/matches.rs, tests/source/attrib.rs, tests/target/attrib.rs
=> Fix duplication of attributes on a match arm's body

src/expr.rs, src/overflow.rs, tests/source/expr.rs, tests/target/expr.rs
=> Avoid overflowing item with attributes

src/macros.rs
cc https://github.com/rust-lang/rust-clippy/issues/4016
found by grepping the rustc source since I was just looking at another instance of this
=> "first" element check does nothing

docs/index.html
I want to the feature like [this](https://rust-lang.github.io/rust-clippy/master/index.html#borrowed_box)
It's a convenience when writing the issue.
=> use filter by hash when first rendering

.travis.yml, src/imports.rs, tests/source/issue-3515.rs, tests/target/issue-3515.rs, tests/target/long-use-statement-issue-3154.rs
=> Attempt to format attributes if only they exist

src/types.rs, tests/target/issue-3539.rs
fix https://github.com/rust-lang/rustfmt/issues/3539
=> correct to get wrong BytePos

src/formatting.rs
can you place this into a branch so that https://github.com/rust-lang/rust/pull/60907 can point to it?
This is needed to get rls fixed before the beta cutoff
=> Update to rustc changes for rls/clippy fixes

src/config/config_type.rs, src/lib.rs, src/release_channel.rs, src/test/mod.rs
=> Add option to run a test only on nightly

src/config/mod.rs, src/config/options.rs
=> Implement Serialize on IgnoreList

src/format-diff/main.rs
Continuing my work on porting all `rustfmt` binaries to `structopt`
=> Use structopt for rustfmt-format-diff arguments parsing

src/macros.rs, tests/source/macros.rs, tests/target/macros.rs
=> Catch panics from the parser while rewriting macro calls

tests/target/issue-3595.rs
#3595 is already resolved. Just add a test.
If this PR isn't needed, close this with #3595.
=> add tests for issue-3595

src/formatting.rs, src/modules.rs, tests/source/configs/skip_children/true.rs, tests/target/configs/skip_children/true.rs
=> Ignore sub-modules when skip-children is used

tests/source/configs/normalize_doc_attributes/false.rs, tests/source/configs/normalize_doc_attributes/true.rs, tests/target/configs/normalize_doc_attributes/false.rs, tests/target/configs/normalize_doc_attributes/true.rs
=> add normalize_doc_attributes config tests

src/test/mod.rs
Refs #3627 and #3628 
Adds simple sanity checks to ensure that the system and idempotence tests were executed
=> Add checks to ensure system and idempotence tests were executed

src/imports.rs, tests/target/issue-3645.rs
=> remove unreachable!()

src/types.rs, tests/source/issue-3651.rs, tests/target/issue-3651.rs
=> fix internal error for long closure types

src/comment.rs, tests/source/issue-3639.rs, tests/target/issue-3639.rs
=> fix extraction of missing comments when rewriting an empty where clause

src/chains.rs, tests/source/async_fn.rs, tests/target/async_fn.rs
=> Do not consider macro-origin await as chain item

src/lists.rs, tests/source/issue-3675.rs, tests/target/issue-3675.rs
=> fix 'extra comma inserted due to comment'

src/patterns.rs, tests/target/issue-3718.rs
=> fix underscore in slice patterns are removed

src/items.rs, tests/source/issue-3740.rs, tests/target/issue-3740.rs
=> Use the correct BytePos for the opening brace position

src/lib.rs, src/reorder.rs
=> Take the inner macro_use attr into acocunt while reordering

src/patterns.rs, tests/target/issue-3759.rs
=> fix the bug  removing attrs

src/items.rs, tests/source/enum.rs, tests/target/enum.rs
=> do not remove discriminant value if exists (#3771)

src/visitor.rs, tests/target/issue-3741.rs
=> fix 'left behind trailing whitespace'

src/imports.rs, tests/source/merge_imports.rs, tests/target/merge_imports.rs
=> fix erroneous flattening of `{self}` in imports

src/comment.rs, tests/source/issue-3751.rs, tests/target/issue-3751.rs
=> fix rust code in comment with a line containing only a hash sign

src/items.rs, tests/target/raw_identifiers.rs
=> add static support for raw prefix identifiers

src/lists.rs, tests/source/issue_3839.rs, tests/target/issue_3839.rs
=> handle block comments with trailing line comments

src/items.rs, tests/target/issue-3882.rs
=> fix Unparsable code when formmating

ci/integration.sh
=> Add --locked

src/closures.rs, src/expr.rs, tests/target/issue-3934.rs
=> change last_pos when expr has attribute

src/types.rs, tests/source/issue-3929.rs, tests/target/issue-3929.rs
=> rewrite generic params no matter what kind it may be

src/chains.rs, src/macros.rs, tests/source/issue-3908.rs, tests/target/issue-3908.rs
=> fix span of Try expression when converting from try! macro to the ? keyword

src/closures.rs, tests/target/async_closure.rs
=> Do not add block around async closure

src/config/file_lines.rs, tests/source/file-lines-8.rs, tests/target/file-lines-8.rs
=> fix (de)ser of FileLines between lib and cli opt

src/expr.rs, tests/target/issue-3992.rs
=> not to remove field literal for tuple

src/comment.rs, src/stmt.rs, tests/source/issue-3981.rs, tests/target/issue-3981.rs
=> fix internal error when stmt has doc attribute

README.md
"cargo test" does nothing, so remove it.
=> readme: update testing section

Configurations.md
I found it's frequent for me to searching tracking issues on unstable options. Hope this can be easier.
=> Link tracking issues in Configurations.md

rustfmt-core/rustfmt-lib/src/matches.rs, rustfmt-core/rustfmt-lib/tests/source/match.rs, rustfmt-core/rustfmt-lib/tests/target/match.rs
=> Do not flatten match arm block with leading attributes

Cargo.lock, Cargo.toml, rustfmt-core/rustfmt-bin/Cargo.toml, rustfmt-core/rustfmt-bin/src/bin/main.rs, rustfmt-core/rustfmt-bin/src/cargo-fmt/main.rs, rustfmt-core/rustfmt-lib/Cargo.toml, rustfmt-core/rustfmt-lib/src/config.rs, rustfmt-core/rustfmt-lib/src/config/file_lines.rs, rustfmt-core/rustfmt-lib/src/lib.rs, rustfmt-core/rustfmt-lib/src/utils.rs
This PR is a successor of #4131.
=> Use duncet to fix path issues

rustfmt-core/rustfmt-lib/src/emitter/diff.rs
Be able to jump to the file and line easily.
Close #4092
=> Fix output of diff

rustfmt-core/rustfmt-lib/src/formatting/matches.rs, rustfmt-core/rustfmt-lib/tests/source/issue-4125.rs, rustfmt-core/rustfmt-lib/tests/target/issue-4125.rs, rustfmt-core/rustfmt-lib/tests/target/match.rs
=> Do not break empty blocks in match arm patterns

docs/index.html
just nice to have :)
https://tawdriestswedish.htmlpasta.com/
=> Add github-style highlighting for code blocks

intellij.md
Add information about ["Run Rustfmt on Save"](https://github.com/intellij-rust/intellij-rust/pull/3490) action in Intellij Rust
Also replace some screenshots (because plugin page in settings has changed), and update info about debugging support in IntelliJ
=> Update IntelliJ Integration

tests/target/issue-2323.rs
No longer looks to be an unfixed issue, adding regression test.
Closes #2323
=> Regression test for #2323

tests/source/issue-4254.rs, tests/target/issue-4254.rs
=> Regression test for #4254

Cargo.lock, Cargo.toml, src/formatting/chains.rs, src/formatting/items.rs, src/formatting/visitor.rs
Not a ton of breaking changes over the last two weeks, but figured I'd be better to go ahead and incorporate them to make things easier later on.
=> bump rustc-ap-* to v666

src/config/file_lines.rs, src/rustfmt/main.rs, src/test/mod.rs, tests/writemode/target/stdin.json, tests/writemode/target/stdin.xml
=> Use <stdin> when emitting stdin as filename

docs/index.html
- Preserve search and version parameter updates in the url
- Render headings with an anchor to itself for easier linking to config
options, variants, etc.
Demo: https://5efeb81ca3f0d.htmlsave.net/
=> docs: Preserve updated query param content and add config option links

src/formatting/items.rs, src/formatting/spanned.rs, tests/target/issue-4310.rs
=> Include const generic type bounds in their spans

config_proc_macro/src/attrs.rs, config_proc_macro/src/utils.rs, src/config/file_lines.rs, src/emitter/rustfmt_diff.rs, src/format_report_formatter.rs, src/formatting.rs, src/formatting/chains.rs, src/formatting/closures.rs, src/formatting/comment.rs, src/formatting/expr.rs, src/formatting/generated.rs, src/formatting/imports.rs, src/formatting/items.rs, src/formatting/lists.rs, src/formatting/macros.rs, src/formatting/matches.rs, src/formatting/overflow.rs, src/formatting/patterns.rs, src/formatting/report.rs, src/formatting/syntux/parser.rs, src/result.rs
I used rustfmt-nightly to format the changes in the latest commit, is that correct or do I have to use git-master rustfmt?
=> some clippy fixes

src/formatting/missed_spans.rs, tests/source/issue-4398.rs, tests/target/issue-4398.rs
=> Correctly indent skipped-over code

src/config.rs
=> Change directory name in test_merged_config test

Contributing.md
Fixed the badge urls in Contributing.md
=> Fix badge url

Configurations.md, src/config/mod.rs, src/config/options.rs, src/reorder.rs, tests/source/configs/group_imports/StdExternalCrate-merge_imports.rs, tests/source/configs/group_imports/StdExternalCrate-nested.rs, tests/source/configs/group_imports/StdExternalCrate-no_reorder.rs, tests/source/configs/group_imports/StdExternalCrate.rs, tests/target/configs/group_imports/StdExternalCrate-merge_imports.rs, tests/target/configs/group_imports/StdExternalCrate-nested.rs, tests/target/configs/group_imports/StdExternalCrate-no_reorder.rs, tests/target/configs/group_imports/StdExternalCrate.rs
Backport of 17d90ca (see #4445)
=> [Backport] Option to create groups for imports

src/formatting/items.rs, tests/source/negative-impl.rs, tests/target/negative-impl.rs
=> Preserve polarity on negative non-trait impl

tests/source/issue-3434/lib.rs, tests/source/issue-3665/lib.rs, tests/target/issue-3434/lib.rs, tests/target/issue-3665/lib.rs
=> Add recursive config to some tests

tests/source/cfg_mod/mod.rs, tests/source/issue-3253/lib.rs, tests/target/cfg_mod/mod.rs, tests/target/issue-3253/lib.rs
=> Add recursive option some tests

Contributing.md
A follow-up of https://github.com/rust-lang/rustfmt/pull/4597.
=> Fix broken links in Contributing.md

docs/index.html
Fixes (mostly) #4633
Changes:
Updates the default version to the latest version released.
Also fixes the issue raised at https://github.com/rust-lang/rustfmt/pull/4644#issuecomment-764679536
Sry about that.
=> Fixed Updated default version to Rustfmt docs config

LICENSE-APACHE, LICENSE-MIT
=> meta(licenses): add missing claim, correct years

CHANGELOG.md, Cargo.lock, Cargo.toml
Refs https://github.com/rust-lang/rust/issues/83460
=> prepare v1.4.37 release

Configurations.md
Scope of change restricted to docs
=> fix(docs): Corrected typo in Configurations.md

rust-toolchain, src/macros.rs, src/modules.rs
=> backport changes for latest rustc api comaptibility

Contributing.md
Link to "good first issue" was broken.
=> Fix link in Contributing.md

src/bin/main.rs
A small fix in addition to #4847.
=> fix: make --edition 2021 visible in --help

Cargo.lock, Cargo.toml, src/bin/main.rs, src/cargo-fmt/main.rs, src/types.rs, tests/source/issue-4816/lib.rs, tests/target/issue-4816/lib.rs
Grabbed from various branches to pull into the mainline for the next sync/release
=> more cherry picks

src/comment.rs, tests/target/issue_4031.rs, tests/target/issue_4110.rs
1.x backport of #4123 that resolved #4031
=> backport fix for newline width calcs

src/comment.rs, src/items.rs, src/spanned.rs, tests/source/issue_4032.rs, tests/source/issue_4579.rs, tests/target/issue_4032.rs, tests/target/issue_4579.rs
=> backport fixes for long params with attrs

src/missed_spans.rs, tests/source/issue_4963.rs, tests/target/issue_4963.rs
=> resolve idempotency issue in extern body elements

src/items.rs, tests/target/issue_4936.rs
=> handle param doc comments for macro scenarios

src/cargo-fmt/main.rs
=> opts: rephrase wording for `--all` and `-p`

src/overflow.rs, src/patterns.rs, tests/source/issue-4530.rs, tests/target/issue-4530.rs
=> Wrap long array and slice patterns.

src/syntux/parser.rs
This has bugged me every time I've seen it while browsing but always kept forgetting to circle back and clean it up
=> minor parser cleanup

src/config/options.rs
See also: https://github.com/rust-lang/rust/pull/90482
=>  Remove grave accent that shouldn't be there

intellij.md
This backports:
* https://github.com/rust-lang/rustfmt/pull/4238
=> Backport "Update IntelliJ Integration"

src/items.rs, tests/source/empty-item-single-line-false.rs, tests/source/item-brace-style-always-next-line.rs, tests/target/empty-item-single-line-false.rs, tests/target/item-brace-style-always-next-line.rs
=> Put empty trait braces on same line if possible

src/items.rs, src/visitor.rs
From my perspective we've got a good chunk of unnecessarily duplicative code handling type alias formatting, and even more generally, visitation of associated items. This not only increases the blast radius when there's relevant upstream changes in rustc, but also created a more difficult mental model for tracking how ty aliases get formatted.
Have been meaning to get around to trying to clean this up, and finally had some bandwidth this morning. This is the first part of a refactor that essentially encapsulates the handling of the `TyAliasKind` nodes in one place, and allows for a side-by-side view on how the generic bounds and right hand side of aliases are formatted depending on the respective context in which the aliases appear.
=> dedupe and simplify type alias formatting

src/visitor.rs
Followup and completion of minor refactoring started in #5068
=> dedupe associated item visitation

src/items.rs, src/types.rs, tests/source/issue_4823.rs, tests/source/issue_5027.rs, tests/source/issue_5086.rs, tests/target/issue_4823.rs, tests/target/issue_5027.rs, tests/target/issue_5086.rs
Fixes #4823
Fixes #5027 
Fixes #5086
=> More type alias fixes

src/ignore_path.rs
I went through all the tests and I think this is the last one that needed to be nightly only that wasn't using the 
``#[nightly_only_test]`` attribute.
=> Update nightly only test with #[nightly_only_test] attribute

src/config/file_lines.rs, src/config/options.rs, src/rustfmt_diff.rs
The aforementioned lint is being enhanced upstream, so updating some of ours accordingly
=> reduce some visibilities for updated unreachable_pub lint

src/overflow.rs, src/test/mod.rs
refactor: rename some private whitelist names (#4326)
=> Backport 4326

tests/target/issue_4573.rs
It's unclear which PR resolved this issue, however the behavior of adding inline comments to the next line can't be reproduced.
These test cases should serve to prevent a regression.
Closes #4573
=> Add tests for issue 4573

CHANGELOG.md, Configurations.md
Documentation follow up to #5311
=> clarify imports_granularity behavior with comments

tests/source/issue_1306.rs, tests/target/issue_1306.rs
Closes #1306
It's unclear when the issue was fixed, but it cannot be reproduced.
See https://github.com/rust-lang/rustfmt/issues/1306#issuecomment-1179611528
=> Add test case for issue 1306 which was resolved

Configurations.md
- Fix duplicated names example on [website](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=)
=> Docs: fix duplicated names example

tests/target/issue_3033.rs
Closes #3033
The issue is no longer reproducible.
=> Add test for issue 3033

Configurations.md
=> Update Configurations.md to point to dirs 4.0 docs

tests/source/issue-3987/format_macro_bodies_true.rs, tests/target/issue-3987/format_macro_bodies_false.rs, tests/target/issue-3987/format_macro_bodies_true.rs
Closes #3987
It's unclear which commit resolved this issue, but it can no longer be reproduced.
=> Add test for issue 3987

src/cargo-fmt/main.rs, src/cargo-fmt/test/mod.rs
Run and fix some issues from `cargo clippy`
=> Fix some clippy issues

src/types.rs, tests/target/issue-4689/one.rs
Add version gating for PR #5390
=> version gate changes for multiline single generic bound

CHANGELOG.md, Cargo.lock, Cargo.toml
r? @ytmimi 
If you can do a quick pass over the relnotes that'd be great, but no worries if not. These don't have to be perfect, and I'd really like to complete this sync cycle as quickly as possible
=> prep v1.5.2 release

CHANGELOG.md
=> Add release notes for merged PRs with `release-notes` label

CHANGELOG.md, README.md
=> fix a few links

triagebot.toml
cc @ytmimi would this be reasonable?
=> automatically add pr-not-reviewed to new PRs

CHANGELOG.md
fix link syntax to make it work.
=> chore: fix link syntax

src/config/mod.rs
per https://github.com/rust-lang/rust/pull/127230#discussion_r1661751845
=> chore: remove duplicate word

src/imports.rs, src/reorder.rs
This pr implements `rewrite_result` method for `UseTree`, and `UseSegment`.
=> update rewrite functions in imports.rs

src/items.rs, src/types.rs, src/visitor.rs
=> Impl rewrite_result for ForeignItem, TraitAliasBounds, WherePredicate
