rust-lang/rustfmt

src/comment.rs
src/formatting.rs
tests/source/issue-539.rs
tests/source/issue-683.rs
tests/target/doc-comment-with-example.rs
tests/target/issue-539.rs
tests/target/issue-683.rs

discard trailing blank comments

---

src/config/file_lines.rs
src/imports.rs
tests/source/imports-impl-only-use.rs
tests/target/imports-impl-only-use.rs

Would close https://github.com/rust-lang-nursery/rustfmt/issues/2887
- [This](https://github.com/rust-lang-nursery/rustfmt/compare/master...max-sixty:impl-only-use?expand=1#diff-5313d4043350f728c500f20b510ee48dR353) is the only meaningful change
- Is this too hacky? I can't find a type of the relevant '`_`' Symbol or anything more than its name to match on. Its span is `Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }`
- Would there have been a more focused way to test this rather than the system test? The existing unit tests do no rewriting - they don't access a Context object (which I didn't easily see how to create)
- I cleaned up some other bits when working my way through the code. LMK if you want to retain

Impl only use

---

src/patterns.rs
tests/source/issue-2936.rs
tests/target/issue-2936.rs

This should fix the issue brought up in issue #2936
Previously, the code generated by Rustfmt turned valid code into code that Rust was not able to parse. This PR should fix this.
I opened up this PR to gain feedback because although it fixes a codegen bug, it does not pretty print the resulting code. I am still working on tracing that problem down, but I wanted to get feedback in the while doing so. Thanks!

Fix Issue with ellipsis matching in pattern.rs

---

src/imports.rs
tests/source/issue-2927-2.rs
tests/source/issue-2927.rs
tests/target/issue-2927-2.rs
tests/target/issue-2927.rs

This PR fixes issue #2927
Everything seems pretty straightforward, although I am curious if there is a better way to handle the edition comparison?

Fixed modsep operator for various rustlang editions

---

src/comment.rs
src/config/config_type.rs
src/config/lists.rs
src/lists.rs
src/matches.rs
src/overflow.rs
src/types.rs

I'm trying to familiarize myself with the library (and with intermediate rust) - I find going through clippy's suggestions a reasonable way of doing that. 
Let me know if these are helpful and I can continue. Some of them seem helpful; some very marginal

Some clippy changes

---

src/items.rs
tests/source/fn-simple.rs
tests/target/fn-simple.rs

We could either retry with larger width or use the original code. I opted for latter.
Closes #2956.

Keep formatting fn even if there is an unformattable argument 

---

.travis.yml
Configurations.md
README.md
rustfmt.toml
src/config/options.rs
tests/source/async_block.rs
tests/source/async_fn.rs
tests/source/catch.rs
tests/source/issue-2927-2.rs
tests/source/issue-2927.rs
tests/target/async_block.rs
tests/target/async_closure.rs
tests/target/async_fn.rs
tests/target/catch.rs
tests/target/issue-2927-2.rs
tests/target/issue-2927.rs

It seemed odd to me when playing with Rust2018 that `Cargo.toml` wants `edition = "2018"` but `rustfmt.toml` wants `edition = "Edition2018"`. This PR changes the rustfmt edition parsing to match the parsing in Cargo.toml.
This is my first time trying to work with complex macros so there probably is a better way to make the changes to `configuration_option_enum!`. I'm very open to improvement suggestions there.
I didn't make an issue first so I'm unaware if this is wanted. I felt it would be a small enough change to have fun for a couple hours so I just went and did it. If this is not wanted, I understand.

Accept 2015 and 2018 instead of Edition2015 and Edition2018 for edition option

---

src/expr.rs
tests/source/issue-2930.rs
tests/target/issue-2930.rs

Fixes #2930
As an added bonus, fixes the missing offset in calls like this:
```diff
if let Some((&mut (ref Y_buf, ref U_buf, ref V_buf), pro_que)) =
get_yuv_buffers_and_pro_que(engine,
(frame.data(0).len(),
-                                        frame.data(1).len(),
-                                        frame.data(2).len()))
+                                         frame.data(1).len(),
+                                         frame.data(2).len()))
{
let kernel = pro_que.kernel_builder(func_name)
.global_work_size(image.dims())
```
which was a sub-case of #2930.

Use correct shape in Visual tuple rewriting

---

src/comment.rs
tests/source/macro_rules.rs
tests/target/macro_rules.rs

Handle raw string literals in CharClasses

---

src/test/mod.rs

test::verify_check_works was failing in relase mode on my machine.
The problem was it would check for target/debug/rustfmt in release mode instead of
target/release/rustfmt and fail an assert.
This commit fixes it so that cargo check looks for target/debug/rustfmt and
cargo check --release looks for target/release/rustfmt

fix cargo test --release

---

src/types.rs
tests/source/issue-2922.rs
tests/target/issue-2922.rs

Fixes #2922.
I'm not sure the fix is "right" since I'm not very familiar with the code base. Looking at the debug log output, the final item in `tests/target/where_clause.rs`:
https://github.com/rust-lang-nursery/rustfmt/blob/430f848c75b100f1fab3fbaa67ba35ab7a8fbfcb/tests/target/where-clause.rs#L101-L103
passes `format_function_type()` a shape that has both `indent.alignment` and `offset` set to the same value. Before the fix in this PR, `rewrite_bare_fn()` would pass `format_function_type()` a shape with correct offset but `indent.alignment` set to zero, which caused the incorrect formatting (since `format_function_type()` ignores `offset` for Visual style).

Use correct indent in rewrite_bare_fn with Visual style

---

src/types.rs
tests/source/visual-fn-type.rs
tests/target/visual-fn-type.rs

An extra blank line was inserted after the function types sometimes (like in the test source file).

Fix extra new line in fn type aliases with indent_style = "Visual"

---

src/rustfmt_diff.rs

The `print_diff` function should output the diff starting from `line_number_orig`, because that is the line number which corresponds to the original file.
**Output before:**
```
Diff in /home/robert/rustfmt/src/rustfmt_diff.rs at line 162:
for mismatch in diff {
let title = get_section_title(mismatch.line_number);
-        writer.writeln(&title,
-                       None);
+        writer.writeln(&title, None);
for line in mismatch.lines {
match line {
Diff in /home/robert/rustfmt/src/rustfmt_diff.rs at line 174: // <-- 174 is incorrect
Some(term::color::GREEN),
),
DiffLine::Resulting(ref str) => writer.writeln(
-                    &format!("-{}{}", str,
-                             line_terminator),
+                    &format!("-{}{}", str, line_terminator), …
```

Change `print_diff` to output the correct line number.

---

Configurations.md
src/config/lists.rs
src/expr.rs
src/matches.rs
tests/source/issue-2496.rs
tests/source/match-flattening.rs
tests/target/issue-2496.rs
tests/target/match-flattening.rs

The match arm block flattening was using two different heuristics for when the initial expression was in a block or not. This lead to inconsistent formatting on default settings:
```rust
// Both of these were left untouched!
match option {
None => if condition {
true
} else {
false
},
}
match option {
None => {
if condition {
true
} else {
false
}
}
}
```
and to a much worse cycle on indent_style = "Visual" (#2496).
I factored out the check into a closure so this mistake doesn't happen again and added tests for both the default behavior (match-flattening.rs) and #2496.
I had to change `Configurations.md` as the existing `force_multiline_blocks` was actually invalid according to the preferred heuristic.
Fixes #2496.

Fix match arm block flattening

---

Configurations.md
src/attr.rs
src/config/mod.rs
tests/source/attrib.rs
tests/source/doc-attrib.rs
tests/target/attrib.rs
tests/target/doc-attrib.rs

In order to help out with https://github.com/servo/servo/issues/21059, I started looking at #2883.
This PR converts `#![doc = ""]` and `#[doc = ""]` attributes to `//!` and `///` doc comments. 
I marked it as WIP because of these points I'm unsure about:
- it's been a while since I've contributed and there were no mentoring instructions on the issue: is this how you were expecting this feature to be done ? There might be obvious problems with this approach/code, but that the tests don't cover currently ?
- should I offset or shrink the shape before passing it to `rewrite_doc_comment` ?
- I've documented the option as unstable in Configurations.md, is that correct ?
- what kind of tests should I add in addition to the one in the PR ? Do you foresee possible problems interacting with other …

normalize_doc_attributes option: convert doc attributes to comments

---

src/comment.rs
src/macros.rs
tests/source/issue-2973.rs
tests/target/issue-2973.rs

The leading whitespace of a multine string was taken into account when
computing the `min_prefix_space_width`, even if that line couldn't be
trimmed. The consequence is it was always shifting the macro's content
to the right.
close #2973

Fix indent computation of a macro with braces.

---

src/imports.rs
tests/target/issue-3043.rs

Fix bug in import where two consecutive module separators were possible.
Fixes #3043.

Fix bug in import where two consecutive module separators were possible.

---

src/comment.rs
tests/source/issue-2917/packed_simd.rs
tests/target/issue-2896.rs
tests/target/issue-2917/minimal.rs
tests/target/issue-2917/packed_simd.rs

Lines that didn't start with a comment sigil were returned unchanged in
comment::rewrite_comment. Then these unchanged lines were indented in
MacroBranch::rewrite.
Close #2917

Prevent right-shifting of block comments with bare lines.

---

src/items.rs
tests/target/big-impl-block.rs
tests/target/impls.rs

Hi there, this is my first PR :) Let me know if there's a better way to fix this.
This PRs ends up bypassing the 'empty_item_single_line' configuration when the `{` is on a new line. (related to #2771).
According to the comments from #3046, this is the expected behavior. Fixes #3046

Trait Implementation - Adds a newline before the last brace on impls without a body if the first brace is also on a newline

---

src/string.rs
tests/target/format_strings/issue-202.rs
tests/target/format_strings/issue-2833.rs
tests/target/format_strings/issue-687.rs
tests/target/format_strings/issue564.rs

Close #202 
Close #564
Close #687
Close #2833

format_strings: take into account newline occurring within a rewritten line

---

.travis.yml
src/attr.rs
src/closures.rs
src/expr.rs
src/items.rs
src/lib.rs
src/macros.rs
src/overflow.rs
src/patterns.rs
src/rewrite.rs
src/spanned.rs
src/types.rs
tests/target/enum.rs

This PR adds `println!` like heuristic to the `fail` attribute from the failure crate. See https://github.com/rust-lang-nursery/rustfmt/commit/6e901c8f37235913a6361a97c84689f8768bf8b7 for a concrete example.
The first 4 commits are refactoring in order to achieve this. Essentially those remove `ToExpr` trait (which should have been a temporal fix...) and replacegg it with `OverflowableItem` enum.
cc https://github.com/rust-lang-nursery/rustfmt/issues/2929.

Add println!-like heuristic to the fail attribute

---

src/expr.rs
tests/source/match.rs
tests/target/match.rs

Format a paren expr with double slash comment

---

Configurations.md
src/expr.rs
tests/source/issue-3066.rs
tests/target/chains-visual.rs
tests/target/configs/indent_style/visual_struct_lit.rs
tests/target/issue-3066.rs
tests/target/struct_lits_visual.rs
tests/target/struct_lits_visual_multiline.rs

This fixes #3066, however I'm still unsure if maybe this behavior was expected (I haven't got a response).
I think not inserting the final commas is better since in the Visual style, a closing brace immediately follows the expression. There's a similar situation in function arguments where the final commas aren't inserted either.
Besides, the current behavior of the one line case of inserting the final comma if the expression is longer than a certain number of characters (see lines 3 and 4 in the source test case) seems definitely wrong.

Get rid of extra commas in Visual struct literal formatting

---

Configurations.md
src/chains.rs
src/expr.rs
tests/source/issue-3049.rs
tests/source/issue-3066.rs
tests/target/chains-visual.rs
tests/target/configs/indent_style/visual_struct_lit.rs
tests/target/issue-2985.rs
tests/target/issue-3049.rs
tests/target/issue-3066.rs
tests/target/struct_lits_visual.rs
tests/target/struct_lits_visual_multiline.rs

Fixes #3049. I based this on #3077 because they change the same test file (first two commits here are from #3077), I can rebase to master instead if necessary.
I picked this approach, as opposed to disabling overflow in the second case, because it looks as well if not better, and gives more of the frequently much needed in Visual style space. Compare:
```rust
impl Something {
fn something(&self) {
if (condition) {
// The approach I picked.
let variable = something_really_long.some_function_name(|x| {
if let Some(_) = x {
println!("A good amount of space here");
}
});
// The other approach.
let variable = something_really_long.some_function_name(|x| {
if let Some(_) = x {
println!("Help me");
}
});
}
}
}
```
This approach also makes iterator/future chains like these look more consistent …

Fix inconsistent overflow behavior in Visual style

---

Cargo.lock
Cargo.toml
src/config/options.rs
src/lib.rs

Two bumps for the crates in use. The main update is `atty` which replaces the `isatty` deprecated one.

Bump dependencies

---

src/comment.rs
src/string.rs
tests/source/itemized-blocks/no_wrap.rs
tests/source/itemized-blocks/rewrite_fail.rs
tests/source/itemized-blocks/urls.rs
tests/source/itemized-blocks/wrap.rs
tests/target/comment5.rs
tests/target/enum.rs
tests/target/itemized-blocks/no_wrap.rs
tests/target/itemized-blocks/rewrite_fail.rs
tests/target/itemized-blocks/urls.rs
tests/target/itemized-blocks/wrap.rs
tests/target/struct_lits.rs
tests/target/struct_lits_multiline.rs

Some problems with rewrite_string got fixed while trying to fix the issue. I am not too happy about making `rewrite_comment_inner` bigger that it was though...
Close #627

Handle itemized blocks in comments

---

src/lib.rs

In the `LineOverflow` error message, the `found` and `max` values were switched. In the diff below, the max is 100 and 140 is what got found:
```diff
fn foo() {
-    let file_name =
-        format!("{}", self.testpaths.file.display())
-        .replace(r"\", "/"); // on windows, translate all '\' path separators to '/'
+    let file_name = format!("{}", self.testpaths.file.display()).replace(r"\", "/"); // on windows, translate all '\' path separators to '/'
}
internal error: line formatted, but exceeded maximum width (maximum: 140 (see `max_width` option), found: 100)
```

fixed display message for the LineOverflow error

---

Configurations.md
src/comment.rs
src/config/mod.rs
tests/source/doc-comment-with-example.rs
tests/target/doc-comment-with-example.rs

This PR adds `format_doc_comments` configuration option. When this option is set to `true`, rustfmt will format code block that appears in doc comment. This was implicitly enabled by setting `wrap_comments = true`. I think the current behavior is confusing, especially to new users.

Add format_doc_comments

---

src/overflow.rs
tests/source/issue-3029.rs
tests/target/issue-3029.rs

This improves the formatting and reading of code avoiding the
condition expression to be rewrite, if it goes multi line.
Fixes: #3029.

Only combine `match` if its condition expression fits in a single line

---

src/overflow.rs
tests/source/issue-3029.rs
tests/target/issue-3029.rs

Extends the multi line condition to over other control flow
expressions, it now covers: `if`, `if let`, `for`, `loop`, `while`,
`while let` and `match`.
Refs: #3029

Avoid control flow expressions conditions to go multi line

---

src/comment.rs
src/vertical.rs
tests/source/wrapped_hidden_code_block.rs
tests/target/issue-2633.rs
tests/target/wrapped_hidden_code_block.rs

part of #2633 
This does not close the issue because the use case described in https://github.com/rust-lang-nursery/rustfmt/issues/2633#issuecomment-404679937 is not fixed, but the rest seems fine.

do not vertically align list items in case the tactic is Horizontal

---

Cargo.lock
Cargo.toml
src/lib.rs
src/utils.rs

utils: rewrite `count_newlines` using `bytecount::count`

---

src/comment.rs
src/expr.rs
src/string.rs
tests/source/issue-3059.rs
tests/target/issue-3059.rs
tests/target/itemized-blocks/wrap.rs

This an attempt to solve #3059 . I _think_ the problem was that `rewrite_string` was using `shape.max_chars_with_indent` to reset the maximum chars per line, while there could be more possibly. This PR adds a new parameter that is the number of characters per line and use that when `break_string` returns `LineEnd`.
It's my first pr, so I might be completely wrong :)

try to fix comment bad wrapping

---

src/chains.rs
src/matches.rs
src/utils.rs
tests/source/match.rs
tests/target/match.rs

 Only put `{` on a newline in a match arm where necessary 

---

src/expr.rs
tests/source/issue-3038.rs
tests/target/issue-2985.rs
tests/target/issue-3038.rs

force a newline after the `if` condition if there is a different indentation level

---

src/lists.rs
src/macros.rs
src/overflow.rs
src/pairs.rs
src/visitor.rs

simplify a comparison with "true"
fn can_be_overflowed: remove unused lifetime
fn rewrite_pairs_one_line: pass "list" by reference (it is not consumed in the function)
fn span_for_token_stream: pass "token_stream" by reference since it is not consumed
use tool lints for clippy suppressions

fix a couple of clippy lint warnings

---

README.md

From now on, the `Cargo.toml` is taken into account when triggering
formatting using `cargo fmt`.
It is considered editor's duty to pass the proper `--edition` argument
for `rustfmt` if it is being called manually.
Refs: #3104.
Refs: #3129.

README: remove old requirement for Rust 2018 edition use

---

src/macros.rs
tests/target/issue-2810.rs

When `newline_style` is set to `Windows`, an empty line inside of a macro results in `\r` being passed to the `fold()` in `MacroBranch::rewrite()`. `\r` is technically _not_ an empty string, so we try to indent it, leaving trailing whitespaces behind, even thought that was not intended (as far as I can see).
There is a handy `is_empty_line()` function in the same file. This PR replaces the `!l.is_empty()` check with calling this function (since trying to indent any whitespace-only string will probably result in trailing whitespaces), but I'm not really sure if this is the best way to fix the root problem. Any feedback is appreciated.

Try to fix formatting failures on Windows (issue #2810)

---

README.md

`tool_attributes` are stable since 1.30: [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=c5d53f8225f99e892fbef865935bcd88) The old `cfg_attr(rustfmt, rustfmt_skip)` attributes aren't necessary anymore and everyone should switch to `#[rustfmt::skip]` sooner or later.
There is also a Clippy lint in the making for this: rust-lang-nursery/rust-clippy#3123

Remove deprecated cfg_attr from README

---

src/bin/main.rs

Currently putting `edition = "2018"` in rustfmt.toml does not work because `config` is overwritten even when no command line argument is passed.

Use edition in rustfmt.toml when no command line argument is passed

---

src/comment.rs
src/macros.rs
src/utils.rs
tests/source/issue-3132.rs
tests/target/issue-3132.rs

This is fixed by taking the method `macros::indent_macro_snippet` which
essentially does the same: it indents a paragraph while preserving the
layout.
It has in addition some logic about strings, which anyway is not relevant to the content that was handled by `trim_left_preserve_layout`: it was applied to comments.
Close #3132

The method trim_left_preserve_layout didn't handle tabs properly.

---

src/attr.rs
tests/source/doc-attrib.rs
tests/target/doc-attrib.rs

I missed a subtlety from issue #2883 in PR #3002, sorry about that. 
It came up in using `normalize_doc_attributes` for the [servo/bindgen use case](https://github.com/rust-lang-nursery/rust-bindgen/pull/1409/commits/b8b824730569d41f94727e46d8952d59d9204cb5#diff-2c6bbf8594ddf8d43ae8f26b83110b7cL218) that the spaces in `CommentStyle::opener()` were mixed in with the attribute literal, currently preventing doc attributes without leading spaces.
This is most useful for tools to allow for example: machine-readable comments with precise syntax rules (like Doxygen's), or most commonly round-tripping idempotently between the proc-macro API and rustfmt.
This PR fixes that so that the literal itself has control over the comment's leading spaces.

normalize_doc_attributes: remove whitespace from the doc comment opener

---

src/comment.rs
src/macros.rs
src/test/mod.rs
src/utils.rs
tests/source/macros.rs
tests/target/macros.rs

1. Fixes https://github.com/rust-lang-nursery/rustfmt/issues/3174.
2. Avoids re-introducting issues similar to https://github.com/rust-lang-nursery/rustfmt/issues/1712.  
-----------------------------------------------
In __Issue 1712__ an example is presented where trimming the leading whitespace on lines of an unparsable macro provides undesirable behavior.
It appears to me that the issues of the sort will most frequently be a result in differences in indentation strategy between the _macro's grammar_ and _rust's grammar_.  I would imagine over time that macro grammar's would diverge more and more from rust given the new [function-like proc macro](https://blog.rust-lang.org/2018/10/25/Rust-1.30.0.html#procedural-macros) support, for things like `sql!(SELECT * FROM example)`.
This change …

Trim the indentation on macros which heuristically appear to use block-style indentation

---

src/matches.rs
tests/source/issue-3131.rs
tests/target/issue-3131.rs

fix the logic for retaining a comment before the arrow in a match

---

Configurations.md
src/config/mod.rs
src/expr.rs
src/overflow.rs
tests/source/expr-overflow-delimited.rs
tests/target/expr-overflow-delimited.rs

Not sure if `overflow_delimited_expr` is the best name for the config option, so recommendations very much appreciated.  Very happy to fix/change anything in the PR as necessary.
I presume this is common for most folks adding a config option, but I'd obvi- love if this could be enabled by default 😊 .

Add config option to more aggressively allow overflow

---

src/items.rs
tests/source/issue-3194.rs
tests/target/issue-3194.rs

close #3194 
As described in the issue, the `generics.span.lo()` value is equal to `BytePos(0)` which is incorrect in case of a struct with a `where` clause but no parameter. The issue is fixed by taking the `span` of the `ident` instead of the `generics`.
Do you think that problem should be reported upstream ?

compute the span after a struct-like item based on the ident description

---

src/config/file_lines.rs
src/expr.rs
src/patterns.rs
src/test/mod.rs
src/types.rs

types.rs:
fix single_char_pattern (use character patters instead of string for .ends_with() and .starts_with()
patterns.rs
expr.rs
file_lines.rs:
fix into_iter_on_ref_ptr (use iter() or iter_mut() instead of into_iter()
tests/mod.rs:
check_files(): take Option<PathBuf> by reference

fix a few clippy warnings

---

src/macros.rs
tests/source/macros.rs
tests/target/issue-2917/packed_simd.rs
tests/target/lazy_static.rs
tests/target/macros.rs
tests/target/match.rs

This change was motivated by this current behavior:
```rust
// Original
let _: DefaultFields = request! { a: "Boop" };
let _: DefaultFields = request! { };
// Formatted
let _: DefaultFields = request! { a: "Boop" };
let _: DefaultFields = request!{};
// "Fixed"
let _: DefaultFields = request! { a: "Boop" };
let _: DefaultFields = request! {};
```
Currently `rustfmt` skips modifying block like macros, unless they are empty with no comments.
If they are empty, it formats them as `mymacro!{}`.
This changes the behavior to preserve optionally one space between `mymacro!` and `{}` (e.g. `example!     {}` becomes `example! {}`.
This change seems preferable to me from a forward-stability perspective, where I would imagine its likely that any (hypothetical) formatting of brace-delimited macros …

Format brace-delimited macros with a space after the name

---

src/cargo-fmt/main.rs

allow to run a rustfmt command from cargo-fmt even when there is no target

---

build.rs
src/comment.rs
src/expr.rs
src/imports.rs
src/items.rs
src/lists.rs
src/macros.rs
src/missed_spans.rs
src/pairs.rs
src/string.rs
src/types.rs
src/utils.rs
src/vertical.rs

I saw these in the rustc tool build logs. Should I add a `#![deny(deprecated)]` as well?

Fix trim_right/trim_left deprecation warnings

---

src/formatting.rs
src/test/mod.rs

When using `new_parser_from_source_str` sometimes it can panic on incomplete input (e.g. bare `}`), so here we use the `Result`-returning `maybe_new_parser_from_source_str` variant to catch possible errors and diagnostics to emit later.
Closes #3239 
related #753 
cc @topecongiro

Catch possible tokenizer panics

---

Contributing.md
src/matches.rs

Related to #3229 
In response to https://github.com/rust-lang/rustfmt/issues/2877#issuecomment-448460946, this PR is to make the version-gate a bit more clear, although I got a `E0317` compile error on what I proposed (which is nice!).
Although the change is a bit verbose for what it does, I think it makes the future gate-cleaning easier: just keep what is in the `else` block. @topecongiro Up to you if it's better ;o)
I also profited and added a section to the contributing file about version-gates.

Clarify version gate used for #3229

---

src/comment.rs

self.base.peek().is_none() case is already caught by the line above.

Remove a trivial redundant code.

---

src/comment.rs
tests/source/issue-3265.rs
tests/target/issue-3265.rs

In Windows, the "multiple \\
line text" format in macro was not well formatted. PL #3028 was fixing this for single LF newline environment, but not for CRLF environment.
The cause was something like this:
rewrite_macro_inner() function calls trim_left_preserve_layout() function, and it is using LineClasses iterator to split lines. But LineClasses splits the text into line only using LF, so CR remains at the end of the lines.
This CR was preventing the parser to detect '\\' at the end-of-line, because CR is always existing at the end-of-line.

Fix issue #3265

---

src/comment.rs
tests/target/issue-3224.rs

rewrite_comment: fix block fallback when failing to rewrite an itemized block

---

Cargo.lock
Cargo.toml
src/comment.rs
src/lib.rs
src/overflow.rs
src/string.rs
src/utils.rs
tests/source/comment6.rs
tests/source/string_punctuation.rs
tests/target/comment6.rs
tests/target/string_punctuation.rs

This PR includes several fixes related to #3235 .
Clearing the terminology: Replaced some identifier's "chars" into "width".
Introduce unicode_width crate, which implements UAX#11: Replaced some of the `str::len()` calls into this unicode width method calls to support characters occupying != 1 width (e.g. CJK, combined chars).
Introduce unicode_categories crate just to make `is_punctuation()` method unicode supported: Without this CJK strings almost cannot be wrapped because it does not include whitespaces, and the old `is_punctuation()` method was only supporting ASCII delimiters.
But by this fix we may over-detect the punctuation characters. For example, do we really want to insert newline after like "§" or "¶"? I'm not sure.
I believe the next step is to support UAX#14, which is …

Unicode text wrapping in comments and string literals.

---

Cargo.lock
Cargo.toml
Configurations.md
src/config/config_type.rs
src/lib.rs

If no rustfmt.toml is found in the usual way, the directory 'rustfmt' in
the user's config directory is checked.
- $XDG_CONFIG_HOME/rustfmt/ (or $HOME/.config/rustfmt/), or
- $HOME/Library/Preferences/rustfmt/ on Mac, or
- %AppData%\rustfmt\ on Windows.

Look for a global rustfmt.toml.

---

README.md
src/imports.rs
tests/source/issue-3241.rs
tests/target/issue-3241.rs

Keep leading colons for global paths

---

Configurations.md
src/expr.rs
tests/source/configs/indent_style/block_trailing_comma_call/one.rs
tests/source/configs/indent_style/block_trailing_comma_call/two.rs
tests/source/issue-2179/one.rs
tests/source/issue-2179/two.rs
tests/source/issue-3295/two.rs
tests/target/configs/indent_style/block_trailing_comma_call/one.rs
tests/target/configs/indent_style/block_trailing_comma_call/two.rs
tests/target/issue-2179/one.rs
tests/target/issue-2179/two.rs
tests/target/issue-3295/two.rs

related: https://github.com/rust-lang/rustfmt/issues/3295
I don't have the confidence this PR.
But this fixs #3295 at least.

fix "internal error: left behind trailing whitespace" with long lines

---

src/items.rs
tests/source/issue-2835.rs
tests/target/configs/brace_style/item_always_next_line.rs
tests/target/fn-custom-7.rs
tests/target/issue-2835.rs

When either one of these two options are set to `true`, each should take
precedence over the brace_style option.
This commit does not introduce any formatting change to the default
configuration, so no version gate is required.
Closes #2835.

Prioritize single_line_fn and empty_item_single_line over brace_style

---

src/comment.rs
tests/source/issue-3314.rs
tests/target/issue-3314.rs

related: https://github.com/rust-lang/rustfmt/issues/3314

fix Removed indentation after nested comments error

---

src/macros.rs
src/overflow.rs
src/spanned.rs
tests/source/macros.rs
tests/target/macros.rs

Handle a macro argument with a single keyword

---

.travis.yml

The `stdsimd` crate fails to compile with the following. Setting the TARGET envar fixes the problem.
```
error: custom attribute panicked
--> crates/core_arch/src/x86/fxsr.rs:102:5
|
102 |     #[simd_test(enable = "fxsr")]
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: message: TARGET environment variable should be set for rustc: NotPresent
```

set the TARGET envar for the stdsimd integration test

---

Configurations.md
src/config/mod.rs
src/imports.rs
src/reorder.rs
tests/source/issue-3343.rs
tests/target/issue-3343.rs

related: https://github.com/rust-lang/rustfmt/issues/3343
If the line width is width within config width, attribute is inline.
I don't want to change default rustfmt behavior, so config default value is 0.

add config inline_attribute_width

---

src/items.rs
src/lists.rs
tests/source/issue-3198.rs
tests/target/issue-3198.rs

related: https://github.com/rust-lang/rustfmt/issues/3198
This is a bug fix, so I don't need to add Version Gate. Did I get that right?

fix the comment for self are swallowed

---

src/formatting.rs
src/lib.rs
src/rustfmt_diff.rs
src/source_file.rs
src/test/mod.rs

Main motivation is to handle the case where we have an input from stdin and we're mostly interested in a diff rather than whole file and trying to come up with this information ourselves. The `EmitMode::ModifiedLines` should still support writing to a specified `Write` sink - we mostly lacked the information on what was the input text so we ask that the passed `source_map`.
Currently works with https://github.com/Xanewok/rls/tree/rustfmt-modified-lines branch on the RLS side.
related #1173 (although this still has to go through (de)serialization)

Support EmitMode::ModifiedLines with stdin input

---

src/macros.rs
tests/target/issue-3439.rs

related: https://github.com/rust-lang/rustfmt/issues/3439

fix 'Ident of macro+ident gets duplicated' error

---

Configurations.md

Just adding the information that `rustfmt` can pick up the default edition from `Cargo.toml`.

Additional info to default value of edition.

---

src/missed_spans.rs
tests/source/issue-3423.rs
tests/target/issue-3423.rs

remove trailing whitespaces in missing spans

---

src/formatting.rs
src/lib.rs
src/modules.rs
src/test/mod.rs
tests/source/configs/skip_children/foo/mod.rs
tests/source/path_clarity/foo.rs
tests/source/path_clarity/foo/bar.rs
tests/target/configs/skip_children/foo/mod.rs
tests/target/path_clarity/foo.rs
tests/target/path_clarity/foo/bar.rs

Support path clarity module even when we start from internal module

---

src/macros.rs
tests/source/macros.rs
tests/target/macros.rs

Avoid duplication on the presence of spaces between macro name and !

---

src/missed_spans.rs
src/source_map.rs
src/visitor.rs
tests/target/issue-3442.rs

- a leading/trailing newline character in missed spans was throwing off the
start/end of ranges used to compare against file_lines
- fix handling of file_lines when closing a block
Close #3442

fix line numbering in missed spans and handle file_lines in edge cases

---

src/expr.rs
tests/source/match_overflow_expr.rs
tests/target/match_overflow_expr.rs

I've tried looking into the issue I've opened and noticed that it seems
quite trivial to resolve it.
I'm not sure if there are any issues with this, since this almost seems
too trivial to be correct, but I've tried adding some test cases which
seem to be functioning and do not fail.
Please let me know if there's anything that needs to be fixed.
This fixes https://github.com/rust-lang/rustfmt/issues/3482.

Enable overflow_delimited_expr for structs

---

src/expr.rs
src/items.rs
src/types.rs
src/utils.rs
tests/target/issue-2976.rs

keep comment appearing between parameter's name and its type

---

src/comment.rs
src/items.rs
src/missed_spans.rs
tests/target/issue-1096.rs

keep missed comments appearing after the struct/enum ident

---

ci/integration.sh
src/ignore_path.rs

The `cargo test --all` command failed and exited the main process with a
SIGINT. Trapping the signal or trying to get the code of a subshell
didn't work.
Close #2724

exit integration test successfully if the crate build failed before applying rustfmt

---

Cargo.lock
Cargo.toml
src/bin/main.rs
src/format_report_formatter.rs
src/formatting.rs
src/git-rustfmt/main.rs
src/lib.rs
src/test/mod.rs

Resolves #2729.
There are a couple of things that I'm not sure if I did them correctly:
- `annotate-snippets` doesn't have an "internal error" annotation type. I'm currently printing "internal" as the annotation id (where the error id usually is in `rustc`):
- Does `rustfmt` have any guarantees about the public API when used as a library? Because I removed `fancy_print` and the `Display` impl from `FormatReport` both of which were `pub`.
- Is there a particular reason that "warning" was previously printed in red? It is now printed in yellow:

Use annotate-snippets for emitting errors

---

src/source_map.rs
src/types.rs
tests/source/issue-3508.rs
tests/target/issue-3508.rs

leave the comment in parentheses of argumentless Fn

---

src/config/config_type.rs
src/config/mod.rs
src/config/options.rs
src/formatting.rs
src/ignore_path.rs
src/test/mod.rs

Paths users specify in `ignore` configuraiton option is relative to the
directory which contains the rustfmt.toml file. When processing the ignore paths
internally, rustfmt should add a path to the directory as a  prefix since
RealPath passed from libsyntax is a full path.
Closes #3521.

Add a path to the parent dir of rustfmt.toml as a prefix to paths in ignore

---

tests/target/issue-2941.rs

Test that rustfmt won't crash when parsing backslash in doc comment. Close #2941.

Add a test for #2941.

---

src/lists.rs
tests/source/issue-3532.rs
tests/target/issue-3532.rs

fix: #3532 
this issue causes internal error like below
```
rchaser53nombp:rustfmt rchaser53$ cargo run --bin rustfmt -- issue-3532.rs
Finished dev [unoptimized + debuginfo] target(s) in 0.25s
Running `target/debug/rustfmt issue-3532.rs`
error[internal]: not formatted because a comment would be lost
--> /Users/rchaser53/Desktop/rustfmt/issue-3532.rs:2
|
2 |     match a {
|
= note: set `error_on_unformatted = false` to suppress the warning against comments or string literals
warning: rustfmt has failed to format. See previous 1 errors.
```

fix Comma in comment causes no formatting

---

src/test/mod.rs

This PR fixes a mistake in a condition that was added in #2409.
Current: the condition has two, identical clauses.
New: the condition has a guard clause for each value unwrapped inside the `if` block.

Fix condition typo

---

Processes.md

add document describing rustfmt's stabilisation process

---

CHANGELOG.md
Configurations.md
src/comment.rs
src/config/mod.rs
tests/source/doc-comment-with-example.rs
tests/source/invalid-rust-code-in-doc-comment.rs
tests/source/issue-2520.rs
tests/source/issue-2523.rs
tests/source/issue-3055/original.rs
tests/source/itemized-blocks/no_wrap.rs
tests/source/itemized-blocks/wrap.rs
tests/source/normalize_doc_attributes_should_not_imply_format_doc_comments.rs
tests/source/wrap_comments_should_not_imply_format_doc_comments.rs
tests/target/doc-comment-with-example.rs
tests/target/invalid-rust-code-in-doc-comment.rs
tests/target/issue-2520.rs
tests/target/issue-2523.rs
tests/target/issue-3055/original.rs
tests/target/itemized-blocks/no_wrap.rs
tests/target/itemized-blocks/wrap.rs
tests/target/normalize_doc_attributes_should_not_imply_format_doc_comments.rs
tests/target/wrap_comments_should_not_imply_format_doc_comments.rs

Add two tests first for #3417. Close #3417.

Try to solve issue 3417.

---

src/comment.rs
src/items.rs
src/visitor.rs
tests/target/issue-3554.rs

fix `Const generics are handled incorrectly`

---

Cargo.lock
Cargo.toml
src/cargo-fmt/main.rs

This is part of work on #3310 
I've started with only porting `cargo-fmt` to `structopt` (since it was causing problems with arguments parsing on Windows). But if this pull request is fine, I can proceed with porting the rest of binaries to `structopt`.
I would appreciate if someone with Windows machine can check whether it fixes Windows command line issues (e.g. #2694 and others).

Use structopt for command line arguments parsing in cargo-fmt

---

src/attr/doc_comment.rs
tests/source/normalize_multiline_doc_attribute.rs
tests/target/normalize_multiline_doc_attribute.rs

Insert an empty line when normalizing `#[doc = ""]`

---

src/expr.rs
src/items.rs
src/shape.rs
tests/source/enum.rs
tests/target/enum.rs

Allow overflowing rhs of unit variant

---

src/expr.rs
src/patterns.rs
tests/target/issue-3592.rs

fix Erasing inner attributes in struct

---

src/items.rs
tests/source/trait.rs
tests/target/trait.rs

Format trait aliases with where clauses

---

src/items.rs
src/reorder.rs
src/visitor.rs
tests/source/issue-3585/extern_crate.rs
tests/source/issue-3585/reorder_imports_disabled.rs
tests/source/issue-3585/reorder_imports_enabled.rs
tests/source/issue-3585/use.rs
tests/target/issue-3585/extern_crate.rs
tests/target/issue-3585/reorder_imports_disabled.rs
tests/target/issue-3585/reorder_imports_enabled.rs
tests/target/issue-3585/use.rs

inline the attribute with its item even with the macro_use attribute or when reorder_imports is disabled

---

src/items.rs
tests/target/issue-3601.rs

fix the bug add unwanted code to impl (#3601)

---

tests/source/attrib.rs
tests/source/doc-attrib.rs
tests/source/issue-3343.rs
tests/target/attrib.rs
tests/target/doc-attrib.rs
tests/target/issue-3343.rs

bitrig support has been removed (by me) in https://github.com/rust-lang/rust/pull/60775

removed bitrig support

---

config_proc_macro/src/item_enum.rs
src/config/config_type.rs
src/config/file_lines.rs
src/config/options.rs

Implementing `Display` was motivated by the default value of `edition` being `Edition2015` although it should have been `2015`. Also, it provides a `to_string` method which could be used in #3620.
Below are the differences this PR makes on the output of `--help=config --unstable-features`:
```diff
137c137
<                      edition [2015|2018] Default: Edition2015
---
>                      edition [2015|2018] Default: 2015
164c164
<             required_version <string> Default: "1.3.0" (unstable)
---
>             required_version <string> Default: 1.3.0 (unstable)
191c191
<                       ignore [<string>,..] Default: IgnoreList { path_set: {}, rustfmt_toml_path: "" } (unstable)
---
>                       ignore [<string>,..] Default: [] (unstable)
```

implement Display for enums with attribute config_type

---

src/test/mod.rs

Fix is_subpath

---

src/expr.rs
src/lists.rs
src/matches.rs
tests/source/unicode.rs
tests/target/unicode.rs

The `NotUnicode` branch was unnecessarily put on a new line, although it
was within max width:
```diff
fn baz() {
let our_error_b = result_b_from_func.or_else(|e| match e {
NotPresent => Err(e).chain_err(|| "env var wasn't provided"),
-        NotUnicode(_) => Err(e).chain_err(|| "env var was very very very borkæ–‡å­—åŒ–ã"),
+        NotUnicode(_) => {
+            Err(e).chain_err(|| "env var was very very very borkæ–‡å­—åŒ–ã")
+        }
});
}
```
Related to #6

handle unicode chars in closures

---

src/expr.rs
src/items.rs
src/lib.rs
src/stmt.rs
src/visitor.rs
tests/source/fn-single-line/version_one.rs
tests/source/fn-single-line/version_two.rs
tests/target/fn-single-line/version_one.rs
tests/target/fn-single-line/version_two.rs
tests/target/issue-3614/version_one.rs
tests/target/issue-3614/version_two.rs

Format the last expression-statement as expression

---

src/formatting.rs
src/visitor.rs
tests/source/issue-3636.rs
tests/target/issue-3636.rs

avoid not to truncate necessary chars

---

src/cargo-fmt/main.rs

Add a newline after help text is shown for a smoother experience.
Solves #3644

Add newline after help text

---

src/cargo-fmt/main.rs

Fixes #3647 and I _believe_ fixes #2694 as well 
Builds on @scampi's solution from #3309 to support running `cargo fmt` from subdirectories in single-package projects as well as in workspaces.
Tested/confirmed on my Windows machine

fix: support running in sub directories/workspace member directories

---

src/formatting.rs

Without this case, an ErrorKind::LicenseCheck results in a panic:
thread 'main' panicked at 'internal error: entered unreachable code', src/tools/rustfmt/src/formatting.rs:320:18
N.B.: errors of this type are only raised when the configuration file
contains `license_tempate_path = "TEMPLATE_FILE"`.

Don't panic on license check errors

---

Configurations.md
src/ignore_path.rs

Fixes #3537 
I also checked on my windows machine and confirmed this works

Add support for windows-style paths in ignore patterns

---

src/types.rs
tests/source/associated_type_bounds.rs
tests/target/associated_type_bounds.rs

fix handling on associated type bounds

---

src/cargo-fmt/main.rs

Refs #3643 (the `cargo fmt --all` portion)
Fixes issue running `cargo fmt --all` when local dependencies reside in a directory name that differs from the package name. 
I created a sample repo [here](https://github.com/calebcartwright/rustfmt-local-deps-test) with local dependencies that reside in directories named differently than their package names that can be used to test against. Run `cargo fmt --all -- --check` in the root of the project, and note the formatting errors coming from the local dependency directories.

fix: handling of --all when local dep name and dir name differ

---

src/cargo-fmt/main.rs
tests/cargo-fmt/main.rs

When running `cargo fmt -- --help`, no output would be displayed.
Closes rust-lang/cargo#7027.

Fix using --help, --verbose, etc.

---

src/cargo-fmt/main.rs

Add --manifest-path support to cargo fmt

---

src/bin/main.rs
tests/rustfmt/main.rs

fix print-config minimal option

---

src/bin/main.rs
src/config/file_lines.rs
src/missed_spans.rs
src/source_map.rs
src/utils.rs
src/visitor.rs
tests/source/file-lines-7.rs
tests/source/issue-3494/crlf.rs
tests/source/issue-3494/lf.rs
tests/source/issue-3636.rs
tests/target/file-lines-7.rs
tests/target/issue-3494/crlf.rs
tests/target/issue-3494/lf.rs
tests/target/issue-3636.rs

This PR fixes the following bugs related to `file-lines`:
- Avoid trimming whitespaces outside of the specified file-lines range
- Fix handling of CRFL (closes #3494)

Fix bugs related to file-lines

---

.travis.yml
Cargo.toml
appveyor.yml
src/chains.rs
src/config/license.rs
src/macros.rs
src/utils.rs
tests/cargo-fmt/main.rs
tests/rustfmt/main.rs
tests/source/issue-3055/original.rs
tests/target/issue-3055/original.rs

~This PR adds `test-binary` feature to work around test failures which appears in the rustc repo [1].~
This PR adds `#[ignore]` to test that runs an external process to work around test failures that appears in the rustc repo [1].
[1] https://github.com/rust-lang/rust/pull/62688#issuecomment-511589355

Add #[ignore] to test that runs external process

---

CHANGELOG.md
README.md
src/attr.rs
src/formatting.rs
src/lib.rs
src/macros.rs
src/rewrite.rs
src/skip.rs
src/test/mod.rs
src/utils.rs
src/visitor.rs
tests/source/issue-3665/lib.rs
tests/source/issue-3665/not_skip_attribute.rs
tests/source/issue-3665/sub_mod.rs
tests/target/issue-3665/lib.rs
tests/target/issue-3665/not_skip_attribute.rs
tests/target/issue-3665/sub_mod.rs

Implement #3665
- Implementation and test based on rustfmt::skip::macros() feature #3434
- Refactoring to encapsulate both macros and attributes
- Removed useless RefCell

#3665: Implemented

---

src/config/file_lines.rs
src/coverage.rs
src/format-diff/main.rs
src/lib.rs
src/missed_spans.rs
src/visitor.rs
tests/source/assignment.rs
tests/source/configs/empty_item_single_line/false.rs
tests/source/configs/empty_item_single_line/true.rs
tests/source/issue-977.rs
tests/target/assignment.rs
tests/target/comment.rs
tests/target/comments-fn.rs
tests/target/configs/empty_item_single_line/false.rs
tests/target/fn.rs
tests/target/issue-977.rs
tests/target/match.rs
tests/target/mod-1.rs

In this PR I have updated `close_block` so that it does not rely on `missed_spans` when dealing with the comment between the last statement and the closing brace. This fixes some issues related to the block formatting: see the commits that update tests for detail.
The background and the motivation of this PR: `missed_spans` is a necessary evil for recovering unformattable code and formatting missing comments. However, it should be the last resort since it's extremely complicated and buggish, especially on handling comments. Also, it's nigh-impossible to implement `blank_lines_lower_bound` and `blank_lines_upper_bound` correctly if we rely on `missed_spans` for handling comments between items, statements and blocks.
The current implementation is not really well-thought, adding a better …

Implement closing-block procedure without relying on missed_span module

---

Cargo.toml

I tried to update Rustfmt 1.4.1 in the RLS and encountered the following error:
```
Checking rustfmt-nightly v1.4.1
error[E0277]: `config::options::__define_config_type_on_enum_NewlineStyle::NewlineStyle` doesn't implement `std::fmt::Display`
--> /home/xanewok/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-1.4.1/src/config/mod.rs:36:34
|
31  | / create_config! {
32  | |     // Fundamental stuff
33  | |     max_width: usize, 100, true, "Maximum width of each line";
34  | |     hard_tabs: bool, false, true, "Use tab characters for indentation, spaces for alignment";
35  | |     tab_spaces: usize, 4, true, "Number of spaces per tab";
36  | |     newline_style: NewlineStyle, NewlineStyle::Auto, true, "Unix or Windows line endings";
| | …
```

Bump rustfmt-config_proc_macro to min v0.1.2

---

src/cargo-fmt/main.rs

fix issue with --all when workspace member crate also exists in dep tree

---

Configurations.md

Configuration options were in a semi-sorted order.  I was getting frustrated, trying to find particular options, so I sorted them, and separated out the two Internal Options into their own section.
If it's helpful, I'd also be happy to open a PR to separate them into Stable and Unstable groups.
Rendered version can be seen at https://github.com/jcdyer/rustfmt/blob/sort-configuration-docs/Configurations.md
VSCode allows nice text-folding of markdown at any header level, if that's helpful for review.  I used that to ensure I was cutting the full text of config entries. (Fold all, then for each: select, cut, find insertion point, paste, refold).

sorted configuration docs

---

README.md

As rustfmt checks fail, they might hide errors of more importance.
Running it last makes sure that the serious bugs have been found and is less frustrating.

Recommend running rustfmt last

---

src/macros.rs
src/overflow.rs
tests/source/issue-3709.rs
tests/target/issue-3709.rs

remove trailing space inserted with empty dyn macro arg

---

src/config/mod.rs

Fixes the [failing default config unit test](https://ci.appveyor.com/project/rust-lang-libs/rustfmt/builds/26667172/job/xq7a7ev2f68r6ra9) after the 1.4.5 release. Also switches the `required_version` to be set automatically which should eliminate the need to have to manually update this test on each release

fix failing default config unit test

---

src/items.rs
src/types.rs
tests/source/issue-3701/one.rs
tests/source/issue-3701/two.rs
tests/target/issue-3701/one.rs
tests/target/issue-3701/two.rs

Use correct indent when formatting complex fn type

---

Configurations.md
src/bin/main.rs
src/config/mod.rs
src/emitter/diff.rs
src/emitter/files.rs
src/lib.rs

Closes #3738 
Adds new command line flag (`-l,--files-with-diff` as suggested in https://github.com/rust-lang/rustfmt/issues/3738#issuecomment-520640244) to list the names of misformatted files

add new flag to list names of misformatted files

---

src/cargo-fmt/main.rs

Closes #3274
`--message-format` in the other `cargo` subcommands accepts 3 values:
1. human
2. short
3. json
In the context of rustfmt, my thinking was:
1. human -> basically a noop, defaults to the standard/regular output
2. short -> list the names of files with diffs
3. json -> maps to the `json` emit mode
IIRC, using `--message-format short` with `clippy` lists the file names along with the line numbers with lint violations, but I didn't think trying to include line numbers made as much sense for rustfmt in the `short` mode.
Each of these output/message formats is already available via other flags/options that have been recently added (`--emit json`, `-l`, `--files-with-diff`), so the implementation is basically just mapping the `--message-format` value to those corresponding args …

add support for --message-format option in `cargo fmt`

---

src/imports.rs
tests/source/issue-3750.rs
tests/target/issue-3750.rs

Fixes  #3750
As per https://github.com/rust-lang/rust/issues/60941#issuecomment-493691039, rustc works as intended. This PR solves the issue by avoiding `self` in path segments of depth past 2.
```rust
use self::foo; // it's fine
use foo::{self, bar}; // `foo` can't be a function/macro
// Intentional duplication of `vec` segment, because `vec` can be a function/macro
use alloc::{vec, vec::Vec};
```

Merge imports fix

---

src/matches.rs
tests/source/macros.rs
tests/target/macros.rs

Forbid adding or removing a block from match arms inside macro calls

---

src/modules.rs
src/modules/visitor.rs
src/test/mod.rs
tests/source/issue-3253/bar.rs
tests/source/issue-3253/foo.rs
tests/source/issue-3253/lib.rs
tests/source/issue-3253/paths/bar_foo.rs
tests/source/issue-3253/paths/excluded.rs
tests/source/issue-3253/paths/foo_bar.rs
tests/target/issue-3253/bar.rs
tests/target/issue-3253/foo.rs
tests/target/issue-3253/lib.rs
tests/target/issue-3253/paths/bar_foo.rs
tests/target/issue-3253/paths/excluded.rs
tests/target/issue-3253/paths/foo_bar.rs

Refs #3253 
As this fix will allow mods defined within `cfg_if` macro to be formatted, I suspect that #3253 could probably be closed, unless the ask in that issue is to cover _any_ macro.

fix formatting mods inside cfg_if macro

---

src/formatting.rs
src/macros.rs
src/rewrite.rs
src/visitor.rs
tests/target/issue-2916.rs

fix TrailingWhitespace when using line breaks in macros arguments

---

src/imports.rs
tests/target/configs/imports_layout/merge_mixed.rs

Sorry, my previous PR https://github.com/rust-lang/rustfmt/pull/3753 didn't fix https://github.com/rust-lang/rustfmt/issues/3750 for all cases. This should finally fix it.

Another fix for `merge_imports`

---

config_proc_macro/src/item_enum.rs
src/bin/main.rs
src/config/config_type.rs
tests/rustfmt/main.rs

Closes #3549 
Adds `--config` command line option that takes comma-separated list of `key=value` pairs. This option can be passed multiple times, keys that are encountered latter override former ones. 
I also tweaked error message in `config_proc_macro` - this helped me very much when I was trying to figure out why my code wasn't working. If you think it's not welcome - I can roll it back.
Also I wrote a simple test, I'll add more this evening (~5 hours from now)

Add --config command line option

---

src/macros.rs
src/matches.rs
src/rewrite.rs
src/visitor.rs
tests/source/match.rs
tests/target/match.rs

Fix handling of match arm's rewrite

---

src/utils.rs
tests/source/expr.rs
tests/target/expr.rs

Resolves #3765 and adds explicit arms for each ast exp. node

fix async expression indentation

---

src/chains.rs
src/macros.rs
src/overflow.rs
src/rewrite.rs
src/visitor.rs

Their only uses are `*foo.borrow()` and `foo.replace(..)`, which is not taking any advantage of `RefCell` over `Cell`.

Use Cell instead of RefCell

---

src/expr.rs
tests/source/issue-3786.rs
tests/target/issue-3786.rs

fix: https://github.com/rust-lang/rustfmt/issues/3786

fix the error with long string in raw string

---

src/items.rs
tests/source/fn-param-attributes.rs
tests/target/fn-param-attributes.rs

Resolves #3623 
Believe the tests added here provide sufficient validation, but please let me know if there's any other scenarios I should add

add support for function parameter attributes

---

src/config/config_type.rs
src/config/mod.rs
tests/config/issue-3802.toml
tests/license-template/lt.txt
tests/source/license-templates/empty_license_path.rs
tests/source/license-templates/license.rs
tests/target/license-templates/empty_license_path.rs
tests/target/license-templates/license.rs

ignore empty string for `license_template_path`

---

src/closures.rs
src/items.rs
src/spanned.rs

refactor to use param naming where appropriate

---

src/imports.rs
tests/source/imports_raw_identifiers.rs
tests/target/imports_raw_identifiers.rs

Resolves #3791 
Does this need to be version gated? It looks more like a sorting bug fix IMO, but I can certainly add a version gate if this is indeed a formatting change.

fix sorting of use statements with raw identifiers

---

src/cargo-fmt/main.rs

add --offline mode fallback to cargo fmt

---

src/test/configuration_snippet.rs
src/test/mod.rs

Add `init_log()` function which attempts to init logger, and
ignores failure. The function is called at the beginning of
every test and will fail if the logger is already initialized.
The logger must be initialized in every test because cargo runs
the tests in parallel, with no guarantees about the order and time
each starts.
Fixes: #3828

Fixes: #3828 Init Logger for unit tests

---

src/expr.rs
src/items.rs
tests/source/existential_type.rs
tests/target/existential_type.rs
tests/target/issue-3815.rs

stop to strip 'impl' from impl trait type alias

---

src/missed_spans.rs
src/utils.rs
src/visitor.rs
tests/source/trailing_comments.rs
tests/target/trailing_comments.rs

The proposed change assumes that a trailing comment belongs to the code on the same line. To prevent it being mixed with possible comments below it, that trailing comment is not rewritten together with the rest. For the same reason, it does not attempt to wrap the trailing comment.
Close #3792
Close #3826
Close #2996
Close #3254

do not force comments to be indented with a comment trailing a line of code

---

Cargo.lock
Cargo.toml
src/attr.rs
src/chains.rs
src/closures.rs
src/expr.rs
src/formatting.rs
src/imports.rs
src/items.rs
src/macros.rs
src/matches.rs
src/modules.rs
src/modules/visitor.rs
src/overflow.rs
src/pairs.rs
src/patterns.rs
src/reorder.rs
src/spanned.rs
src/stmt.rs
src/types.rs
src/utils.rs
src/visitor.rs

cc https://github.com/rust-lang/rust/issues/65085.

Update rustc-ap-* crates to 606.0.0

---

src/string.rs
tests/source/issue-3787.rs
tests/target/issue-3787.rs

improve detection of URL inside a string that is being rewritten.

---

src/closures.rs
tests/target/issue-3845.rs

fix to swallow attribute on brace expression

---

src/items.rs
tests/source/issue-3840/version-one_hard-tabs.rs
tests/source/issue-3840/version-one_soft-tabs.rs
tests/source/issue-3840/version-two_hard-tabs.rs
tests/source/issue-3840/version-two_soft-tabs.rs
tests/target/issue-3840/version-one_hard-tabs.rs
tests/target/issue-3840/version-one_soft-tabs.rs
tests/target/issue-3840/version-two_hard-tabs.rs
tests/target/issue-3840/version-two_soft-tabs.rs

The fix consists in removing the call to `generics_shape_from_config` which was indenting generics unnecessarily regardless of the `hard_tabs` option. The `Visual` indent style was also adding [2 leading whitespaces](https://github.com/rust-lang/rustfmt/pull/3856/files#diff-5db152a52bdaeae9dacd35f43a4a78ddR2618) which seemed odd; below is a diff of the two formatting versions.
```diff
impl<Target: FromEvent<A> + FromEvent<B>,
-      A: Widget2<Ctx = C>,
-      B: Widget2<Ctx = C>,
-      C: for<'a> CtxFamily<'a>> Widget2 for WidgetEventLifter<Target, A, B>
+     A: Widget2<Ctx = C>,
+     B: Widget2<Ctx = C>,
+     C: for<'a> CtxFamily<'a>> Widget2 for WidgetEventLifter<Target, A, B>
{
type Ctx = C;
type Event = Vec<Target>;
}
```
Are the 2 leading whitespaces added on purpose ? Is it OK …

do not indent impl generics

---

Cargo.lock
Cargo.toml

For some reason I also had to do
```
cargo update -p crossbeam-utils --precise 0.6.5
```
as otherwise things wouldn't build. Even `rustfmt` master does not build for me. See https://github.com/crossbeam-rs/crossbeam/issues/435.

bump rustc-ap crates

---

src/cargo-fmt/main.rs

Refs #3811, #3813, and #3831 
There was discussion on #3811 with concerns raised that the solution in #3813 (keep the default `online` just like current/existing behavior, with an `offline` fallback) doesn't fully solve the problem, so opening this for consideration as an alternative (a mutually exclusive alternative to #3831)

use offline by default with `cargo fmt` with online fallback

---

src/items.rs
src/vertical.rs
tests/source/issue-2869.rs
tests/target/configs/struct_field_align_threshold/20.rs
tests/target/issue-2869.rs

the `items::rewrite_struct_field` method was already handling multiline
field names via `last_line_width`, which was rendered moot by the
previous logic in
`vertical::AlignedItem::struct_field_prefix_max_min_width`.
Close #2869

handle field attributes when aligning a struct's fields

---

src/emitter/diff.rs
src/formatting.rs
src/source_file.rs

Fixes #3849 
There were two underyling issues with the way we were handling newline style differences that only surfaced when the source files have Windows style line feeds and/or when the `newline_style` config was set to `Windows`. 
Details inline below

fix handling of newline_style conflicts

---

src/expr.rs
src/utils.rs
tests/target/multiline_string_in_macro_def.rs
tests/target/should_not_format_string_when_format_strings_is_not_set.rs

Try to solve issue3456.

---

src/comment.rs
src/expr.rs
src/patterns.rs
tests/source/issue_3853.rs
tests/target/issue_3853.rs

Fixes #3853 
The previous behavior was dropping all these nested comments which had the cascading effect of the expression blocks being left unformatted as well. This updates the relevant logic to combine strings with `combine_strs_with_missing_comments` instead of `format!`

fix handling of nested comments in patterns and ControlFlows

---

src/bin/main.rs

The intention is to implement these cases, but return an error is better than silently ignoring them in the meantime.
See #3871 .

Return an error if `--check` or `--emit json` are used with stdin.

---

Cargo.toml
src/closures.rs
src/comment.rs
src/expr.rs
src/formatting.rs
src/ignore_path.rs
src/items.rs
src/lib.rs
src/lists.rs
src/macros.rs
src/matches.rs
src/missed_spans.rs
src/modules.rs
src/modules/visitor.rs
src/reorder.rs
src/rewrite.rs
src/source_file.rs
src/source_map.rs
src/syntux.rs
src/syntux/parser.rs
src/syntux/session.rs
src/types.rs
src/utils.rs
src/visitor.rs

This PR adds a `syntux` module which aims to provide a thin and safe abstraction layer on top of `libsyntax`. The idea is to make rustfmt resistant to breaking changes in the rustc codebase. The ultimate goal is to factor out the `syntux` module into a separate crate and avoid using `rustc-ap-*` crates directly from rustfmt codebase.

Add syntux module

---

src/cargo-fmt/main.rs

add --check flag to cargo fmt

---

src/comment.rs
src/expr.rs
src/items.rs
tests/source/issue-3851.rs
tests/target/issue-3851.rs

fix to extract comments to stop internal error

---

.travis.yml
Cargo.lock
Cargo.toml
Configurations.md
src/bin/main.rs
src/config/config_type.rs

deprecate skip_children option

---

src/cargo-fmt/main.rs
src/config/mod.rs
tests/config/issue-3779.toml
tests/source/issue-3779/lib.rs
tests/target/issue-3779/lib.rs

This PR fixes a few tests added by me in some recent PRs that were missing some things 😞 
Two tests (`config::test::test_valid_license_template_path` and a system tests for handling ignored files that contain parser errors) were missing the unstable/nightly check, so they were failing on the Travis job that runs on beta: https://travis-ci.com/rust-lang/rustfmt/jobs/250084463
The other test fixed here is one of the tests I added in https://github.com/rust-lang/rustfmt/pull/3777 that was a little flaky as originally written. This updates the asserts in the test to eliminate that flakiness.
Below job links show the original version failing due to the ordering of the discovered files in the vec
https://travis-ci.com/rust-lang/rustfmt/jobs/250683618
and …

fix a few tests

---

src/imports.rs
src/matches.rs
tests/source/imports_raw_identifiers.rs
tests/source/issue-3170.rs
tests/target/imports_raw_identifiers.rs
tests/target/issue-3170.rs

Thought it might be helpful to go ahead and merge these commits to minimize the chance of potential conflicts, but can close this if it'd be better to wait
Follow up of #3906

merge commits from rustfmt-2.0 branch

---

.gitignore

```cargo test``` created many files.  I think some files don't need to track by git, so I send the PR.

add unnecessary directories and files to .gitignore

---

src/cargo-fmt/main.rs

Tiny wording change as discussed in https://github.com/rust-lang/rustfmt/issues/3911.

opts: rephrase wording for --all and -p

---

src/emitter/diff.rs
src/test/mod.rs

This would also fix a panic with stdin on line ending differences, but these aren't detected as the saved source is kept with unix line endings so compares equal to the output.

Fix --check -l with stdin.

---

src/formatting.rs

This changeset make it so the entire comment line is printed when `report_todo` or `report_fixme` finds an issue.
It is motivated by the following example. Consider the following source:
```
// TODO implement something!
fn main() {}
```
Currently `rustfmt` will output something similar to:
```
warning: found TODO without issue number
--> path/to/source/file.rs
|
1 | // TODO
|
```
This change accumulates all the TODO and FIXME issues for each line and outputs the entire comment in the error message:
```
warning: found TODO without issue number
--> path/to/source/file.rs
|
1 | // TODO implement something!
|
```
Some concerns:
- I'm not sure if `CharClasses` or files always end in a `\n`, or if we need to handle the "todo in a comment at the end of a file with no trailing newline" edge case …

Print entire comment line for report_todo/report_fixme

---

Configurations.md
src/config/mod.rs
src/config/options.rs
src/macros.rs
tests/source/configs/indent_style/block_call.rs
tests/source/configs/use_try_shorthand/false.rs
tests/source/configs/use_try_shorthand/true.rs
tests/source/configs/use_try_shorthand/true_2015_edition.rs
tests/source/imports_2015_edition.rs
tests/source/trait_2015_edition.rs
tests/source/try-conversion.rs
tests/target/configs/indent_style/block_call.rs
tests/target/configs/use_try_shorthand/false.rs
tests/target/configs/use_try_shorthand/true_2015_edition.rs
tests/target/imports_2015_edition.rs
tests/target/issue-1681.rs
tests/target/trait_2015_edition.rs

Resolves #3517 and refs #3887 
Unsurprisingly changing the default edition from 2015 to 2018 required updates to a few tests as well to account for changes. 
* The `try!` macro was deprecated in Rust v1.39.0, and since `try` is a reserved word in the 2018 edition, the raw identifier has to be used (`r#try!`) when using the 2018 edition - https://doc.rust-lang.org/std/macro.try.html
* The 2015 edition supported anonymous trait parameters, but that was dropped in the 2018 edition https://doc.rust-lang.org/nightly/edition-guide/rust-2018/trait-system/no-anon-params.html

change default edition to 2018

---

Cargo.lock
Cargo.toml
src/syntux/session.rs

A couple minor updates to the handling of parser errors in order to cover a few additional scenarios. Follow up to #3782 and refs https://github.com/rust-lang/rustfmt/issues/3916#issuecomment-552069343
* now when the parser error level is Fatal, the parse error details will be emitted (unless `hide_parse_errors` is true), regardless of whether the source file is `ignore`d because the parser won't be able to give rustfmt the ast anyway in the event of a fatal error. Previously rustfmt was suppressing the fatal parser error text if the source file was `ignore`d even though rustfmt wouldn't be able to continue and would have to exit with an error.
* even when `hide_parse_errors` is true, the same logic checks are applied to see if DB source file origin was in an `ignore`d file so that the …

update handling of parser errors

---

tests/source/issue-3908.rs

CI build was failing on master branch due to a test with a `try!` added in a recent PR that crossed wires with the PR that changed the default edition to 2018 (which requires the raw identifier `r#try!`)

fix try! test for 2018 edition

---

Configurations.md
src/bin/main.rs
src/cargo-fmt/main.rs
src/config/config_type.rs
src/config/mod.rs
src/formatting.rs
src/syntux/parser.rs
src/test/mod.rs
tests/source/configs/recursive/disabled/foo.rs
tests/source/configs/recursive/disabled/lib.rs
tests/source/configs/recursive/enabled/foo.rs
tests/source/configs/recursive/enabled/lib.rs
tests/target/configs/recursive/disabled/foo.rs
tests/target/configs/recursive/disabled/lib.rs
tests/target/configs/recursive/enabled/foo.rs
tests/target/configs/recursive/enabled/lib.rs

Resolves #3587 and refs #3887 
This PR updates the default mode of `rustfmt` to not format submods in external files, with an accompanying new CLI arg (`--recursive`)/config option to enable recursive submod formatting mode (which was the default behavior of rustfmt 1.x).
`cargo fmt` behavior remains unchanged, as `cargo fmt` will automatically pass the `--recursive` flag to `rustfmt`.
I went ahead and marked the new `recursive` config option as stable because it is relatively simple. Also because it would be pretty weird IMO if both `recursive` and `skip_children` were only available on nightly, especially with `skip_children` now deprecated (that would make it impossible to format sub mods on stable).
Lastly, I did a bit of refactoring in cargo fmt to consolidate/simplify the adding of …

switch to non-recursive mode by default

---

tests/config/issue-3933.toml
tests/source/issue-3933/imp-a.rs
tests/source/issue-3933/imp-b.rs
tests/source/issue-3933/lib.rs
tests/source/issue-3933/utils.rs
tests/target/issue-3933/imp-a.rs
tests/target/issue-3933/imp-b.rs
tests/target/issue-3933/lib.rs
tests/target/issue-3933/utils.rs

related: https://github.com/rust-lang/rustfmt/pull/3938
It needs to add a config file for the test. The default behavior is not to recursive now. And should ignore files except for lib.rs.

fix test for issue-3933

---

src/formatting.rs

We're seeing that rustfmt just fails to run with no error message whatsoever without `--verbose` in https://github.com/rust-lang/rust/pull/65939, and once that was passed managed to track it down to rustfmt printing "Rust parser panicked" (see [this log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/16212/logs/87) for example). This is my attempt to try and get rustfmt to print some more information in the hope that once this propagates into nightly we can run it by that PR.
If you have thoughts on how to debug the failure I'd love to hear that too!
r? @topecongiro

Print out error message and file when detecting that rust parser panicked

---

src/modules.rs
tests/config/issue-3956.toml
tests/target/issue-3956/graphics.rs
tests/target/issue-3956/graphics_emu.rs
tests/target/issue-3956/lib.rs

fix not to overwrite on other platforms

---

.github/workflows/windows.yml

I've been meaning to try out GitHub Actions (GHA) for a while, and I also feel like the AppVeyor jobs for rustfmt can take a while, get backed up in a queue, etc. so figured I'd try setting up windows jobs for rustfmt on GHA. 
If folks are interested in giving GHA a try, my suggestion would be that we enable GHA alongside the current AppVeyor jobs for a trial period, and if it works well then we can disable the AppVeyor jobs later on. 
The main benefits I see for using GHA:
* **faster builds/parallelization** - AppVeyor only supports running 1 job at a time, resulting in a sequential execution of the channel/target combinations whereas GHA allows for running jobs in parallel. The result is that for rustfmt, AppVeyor takes 20+ minutes to complete whereas GHA will only take ~6-7 minutes …

setup windows builds on GitHub Actions

---

src/matches.rs
tests/target/issue-3974.rs

Use correct span for match arms with the leading pipe and attributes

---

tests/source/cfg_if/detect/arch/aarch64.rs
tests/source/cfg_if/detect/arch/arm.rs
tests/source/cfg_if/detect/arch/mips.rs
tests/source/cfg_if/detect/arch/mips64.rs
tests/source/cfg_if/detect/arch/powerpc.rs
tests/source/cfg_if/detect/arch/powerpc64.rs
tests/source/cfg_if/detect/arch/x86.rs
tests/target/cfg_if/detect/arch/aarch64.rs
tests/target/cfg_if/detect/arch/arm.rs
tests/target/cfg_if/detect/arch/mips.rs
tests/target/cfg_if/detect/arch/mips64.rs
tests/target/cfg_if/detect/arch/powerpc.rs
tests/target/cfg_if/detect/arch/powerpc64.rs
tests/target/cfg_if/detect/arch/x86.rs

Replace `issue = "0"` with `"none"`
CC: rust-lang/rust#67496

Use issue = "none" instead of "0"

---

src/config/config_type.rs

It is recommended to do that as I could remember.

use let to bind value from a macro expression

---

rustfmt-core/rustfmt-lib/src/imports.rs
rustfmt-core/rustfmt-lib/tests/source/imports.rs
rustfmt-core/rustfmt-lib/tests/target/imports.rs

Do not remove comment from an import with a single item

---

Cargo.lock
rustfmt-core/rustfmt-lib/Cargo.toml

changes back to the main `ignore` crate now that the crossbeam dep issue has been fixed upstream
https://github.com/rust-lang/rustfmt/pull/3998#issuecomment-570876650
https://github.com/rust-lang/rustfmt/pull/3998#issuecomment-573187139

switch back to ignore crate

---

rustfmt-core/rustfmt-lib/src/closures.rs
rustfmt-core/rustfmt-lib/tests/source/issue-3502.rs
rustfmt-core/rustfmt-lib/tests/target/issue-3502.rs

resolve: #3502 
I send this PR to resolve the task on milestone v2.0.0.

separate by a new line for `move ||` and `match`

---

Contributing.md

Fixed the broken links in [Contributing.md](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md).
Decided to remove `src/` and not add the current parent path, as I felt it added to much clutter. I'll happily add it if needed.

Fixed broken links

---

rustfmt-core/rustfmt-lib/src/expr.rs
rustfmt-core/rustfmt-lib/tests/source/expr.rs
rustfmt-core/rustfmt-lib/tests/target/expr.rs

support raw reference operator

---

rustfmt-core/rustfmt-lib/src/expr.rs

This fixes a recent compiler warning I've been seeing (may have started with the updated rustc-ap versions)
```bash
warning: unnecessary parentheses around block return value
--> rustfmt-lib/src/expr.rs:1171:5
|
1171 | /     (block.stmts.len() == 1
1172 | |         && stmt_is_expr(&block.stmts[0])
1173 | |         && !block_contains_comment(context, block)
1174 | |         && attrs.map_or(true, |a| a.is_empty()))
| |________________________________________________^
|
= note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
```

fix compiler warning

---

rustfmt-core/rustfmt-lib/src/types.rs
rustfmt-core/rustfmt-lib/tests/source/type.rs
rustfmt-core/rustfmt-lib/tests/target/type.rs

support trait bounds const opt out syntax

---

rustfmt-core/rustfmt-bin/build.rs
rustfmt-core/rustfmt-bin/src/bin/main.rs
rustfmt-core/rustfmt-config/src/config_type.rs
rustfmt-core/rustfmt-config/src/file_lines.rs
rustfmt-core/rustfmt-config/src/lib.rs
rustfmt-core/rustfmt-emitter/src/diff.rs
rustfmt-core/rustfmt-emitter/src/rustfmt_diff.rs
rustfmt-core/rustfmt-lib/src/closures.rs
rustfmt-core/rustfmt-lib/src/stmt.rs
rustfmt-core/rustfmt-lib/src/test/configuration_snippet.rs
rustfmt-core/rustfmt-lib/src/test/mod.rs

fix self_tests

---

rustfmt-core/rustfmt-lib/src/expr.rs
rustfmt-core/rustfmt-lib/tests/source/issue_3979.rs
rustfmt-core/rustfmt-lib/tests/target/issue_3979.rs
rustfmt-core/rustfmt-lib/tests/target/issue_4049.rs

fix comment handling in control flows

---

rustfmt-core/rustfmt-lib/src/spanned.rs
rustfmt-core/rustfmt-lib/tests/source/issue_4032.rs
rustfmt-core/rustfmt-lib/tests/target/issue_4032.rs

handle long param attributes

---

rustfmt-core/rustfmt-lib/src/items.rs
rustfmt-core/rustfmt-lib/tests/source/structs.rs
rustfmt-core/rustfmt-lib/tests/target/structs.rs

Use the correct shape when formatting comment in empty struct

---

rustfmt-core/rustfmt-lib/src/string.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4023.rs

fix not to break relative path link

---

rustfmt-core/rustfmt-config/src/lib.rs
rustfmt-core/rustfmt-emitter/src/diff.rs
rustfmt-core/rustfmt-emitter/src/rustfmt_diff.rs
rustfmt-core/rustfmt-lib/src/closures.rs
rustfmt-core/rustfmt-lib/src/expr.rs
rustfmt-core/rustfmt-lib/src/macros.rs
rustfmt-core/rustfmt-lib/src/stmt.rs
rustfmt-core/rustfmt-lib/src/test/configuration_snippet.rs
rustfmt-core/rustfmt-lib/src/test/mod.rs
rustfmt-core/rustfmt-lib/tests/source/lazy_static.rs
rustfmt-core/rustfmt-lib/tests/target/catch.rs
rustfmt-core/rustfmt-lib/tests/target/expr.rs
rustfmt-core/rustfmt-lib/tests/target/lazy_static.rs
rustfmt-core/rustfmt-lib/tests/target/match.rs

- Parse the rhs as statement
- Do not format unsafe block on the statement position in a single line
Close #3419.

Avoid poor-formatting of the rhs of lazy_static macro

---

Cargo.lock
Cargo.toml
src/utils.rs
tests/source/issue_4086.rs
tests/target/issue_4086.rs

[rustfmt 1.x] fix formatting arbitrary extern abi

---

rustfmt-core/rustfmt-lib/src/visitor.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4068.rs

related: #4068
I think #4068 code is invalid, but rustfmt should not cause an internal error. So I send this PR.

suppress internal error

---

Cargo.lock
rustfmt-core/rustfmt-lib/Cargo.toml
rustfmt-core/rustfmt-lib/src/utils.rs
rustfmt-core/rustfmt-lib/tests/source/issue_4086.rs
rustfmt-core/rustfmt-lib/tests/target/issue_4086.rs

fix formatting arbitrary extern abi

---

rustfmt-core/rustfmt-lib/src/comment.rs
rustfmt-core/rustfmt-lib/tests/source/issue-4079.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4079.rs

fixes #4079 
Without this fix:
```
Mismatch at tests/source/issue-4079.rs:3:
/*!
* Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lacinia
* ullamcorper lorem, non hendrerit enim convallis ut. Curabitur id sem
- * volutpat
+  * volutpat
*/
/*! Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lacinia
Mismatch at tests/source/issue-4079.rs:10:
- * ullamcorper lorem, non hendrerit enim convallis ut. Curabitur id sem
- * volutpat */
+  * ullamcorper lorem, non hendrerit enim convallis ut. Curabitur id sem
+  * volutpat */
```

Issue 4079

---

rustfmt-core/rustfmt-lib/src/comment.rs
rustfmt-core/rustfmt-lib/tests/source/issue-4020.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4020.rs

Fixes #4020 
prior to the fix, the tests fail like this:
```
Mismatch at tests/source/issue-4020.rs:1:
// rustfmt-wrap_comments: true
-/** foobar */
+/** foobar **/
const foo1: u32 = 0;
/**
Mismatch at tests/source/issue-4020.rs:7:
- * foobar
- */
+ ** foobar
+ **/
const foo2: u32 = 0;
```

fix Issue 4020: problem reformatting block comments

---

rustfmt-core/rustfmt-lib/src/comment.rs
rustfmt-core/rustfmt-lib/tests/target/issue_4031.rs
rustfmt-core/rustfmt-lib/tests/target/issue_4110.rs

Resolves #4031, refs #4110 
This address the binding formatting in #4110, but doesn't include any updates for the sub pattern formatting

fix newline width calc in combine w/ comments

---

rustfmt-core/rustfmt-config/src/lib.rs

Resolves #2183. I saw these again the other day when I was in the config module and decided to take a closer look at them.
`CFG_RELEASE_CHANNEL` is now checked at compile time, so the original issue with sequencing of tests that were mutating the shared env vars during test exection is no longer relevant. 
https://github.com/rust-lang/rustfmt/blob/9124dd88d6ef14d0ae77dc52ff5e9598f24a75a0/rustfmt-core/rustfmt-config/src/config_type.rs#L338-L342
Instead, I split out the tests for nightly vs. non-nightly with their respective assertions accordingly, and the latter set of tests will run as part of one of the CI jobs (ex: https://travis-ci.com/rust-lang/rustfmt/jobs/291200498). 
All that being said.. 😄 
@topecongiro in https://github.com/rust-lang/rustfmt/issues/3387#issuecomment-574150626 you …

restore some config tests

---

Configurations.md
rustfmt-core/rustfmt-config/src/config_type.rs
rustfmt-core/rustfmt-config/src/lib.rs
rustfmt-core/rustfmt-config/src/options.rs
rustfmt-core/rustfmt-lib/src/attr.rs
rustfmt-core/rustfmt-lib/src/chains.rs
rustfmt-core/rustfmt-lib/src/expr.rs
rustfmt-core/rustfmt-lib/src/items.rs
rustfmt-core/rustfmt-lib/src/lists.rs
rustfmt-core/rustfmt-lib/src/macros.rs
rustfmt-core/rustfmt-lib/src/overflow.rs
rustfmt-core/rustfmt-lib/tests/source/chains.rs
rustfmt-core/rustfmt-lib/tests/source/configs/width_heuristics/max.rs
rustfmt-core/rustfmt-lib/tests/source/configs/width_heuristics/off.rs
rustfmt-core/rustfmt-lib/tests/source/configs/width_heuristics/scaled.rs
rustfmt-core/rustfmt-lib/tests/target/chains.rs
rustfmt-core/rustfmt-lib/tests/target/configs/width_heuristics/max.rs
rustfmt-core/rustfmt-lib/tests/target/configs/width_heuristics/off.rs
rustfmt-core/rustfmt-lib/tests/target/configs/width_heuristics/scaled.rs
rustfmt-core/rustfmt-lib/tests/target/issue_4049.rs

Closes #3710 
The diff makes this seem bigger than it actually is, but there's really not all that much in this PR. 
In addition to `max_width`, rustfmt has internally used 7 different max width settings for specific code constructs as part of the heuristics for determining whether to use multi-line/vertical formatting.  These private settings were set based on the value provided for the public/user-facing `use_small_heuristics` config option. Essentially, `use_small_heuristic` was the public facing knob that controlled 7 private options.
That's helpful in scenarios where users want a minimal config and want to be able to simply update and manage one "width" config option (`max_width`), but it was problematic for users that wanted to have more granular control over those individual width …

Update width heuristic configuration

---

rustfmt-core/rustfmt-lib/src/imports.rs
rustfmt-core/rustfmt-lib/src/items.rs
rustfmt-core/rustfmt-lib/src/reorder.rs
rustfmt-core/rustfmt-lib/tests/source/imports-reorder-lines.rs
rustfmt-core/rustfmt-lib/tests/source/imports-reorder.rs
rustfmt-core/rustfmt-lib/tests/source/issue-2863.rs
rustfmt-core/rustfmt-lib/tests/target/imports-reorder-lines.rs
rustfmt-core/rustfmt-lib/tests/target/imports-reorder.rs
rustfmt-core/rustfmt-lib/tests/target/issue-2863.rs

This change has been initially discussed in rust-dev-tools/fmt-rfcs#143 and is motivated by the following example from using `nom`:
```rust
// Formatting before this PR
use nom::number::complete::{le_u128, le_u16, le_u32, le_u64, le_u8};
// Formatting after this PR
use nom::number::complete::{le_u8, le_u16, le_u32, le_u64, le_u128};
```
I've covered imports with `use` (including renames), `mod` and `extern crate` statements (including renames), and item names. Is there anything else I've missed?
Technically this is a **breaking change**; however, in most cases it results in more readable code, so I'd consider it a bugfix. The only case I know that this change makes worse is names including fixed-width hex value which are ordered fine today but may become misordered
```rust
use …
```

Use versionsort for everything that's auto-reordered by name

---

Cargo.lock
rustfmt-core/rustfmt-bin/src/bin/main.rs
rustfmt-core/rustfmt-bin/src/cargo-fmt/main.rs
rustfmt-core/rustfmt-lib/Cargo.toml
rustfmt-core/rustfmt-lib/src/config.rs
rustfmt-core/rustfmt-lib/src/config/file_lines.rs
rustfmt-core/rustfmt-lib/src/lib.rs
rustfmt-core/rustfmt-lib/src/test/mod.rs
rustfmt-core/rustfmt-lib/src/utils.rs
rustfmt-core/rustfmt-lib/tests/source/mods-relative-paths/lib.rs
rustfmt-core/rustfmt-lib/tests/source/mods-relative-paths/mod_b.rs
rustfmt-core/rustfmt-lib/tests/target/mods-relative-paths/lib.rs
rustfmt-core/rustfmt-lib/tests/target/mods-relative-paths/mod_b.rs

This PR is a successor of #3590.

Use absolute_path instead of fs::canonicalize

---

.cargo/config
.github/workflows/integration.yml
.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/windows.yml

Follow up to #3969 that enables GHA for Linux, Mac, and the Integration test jobs that are currently executed on Travis. I decided to go ahead and work on this since some of the other issues I was eyeing are blocked 😄 
Similar to my experience enabling GHA for Windows in #3969, I found a few things took a little longer to set up due to the immaturity of the platform/features that haven't yet been released. However, overall it still seems really promising with several opportunities for continued improvement.

more GitHub Actions enablement

---

rustfmt-core/rustfmt-lib/src/attr.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4029.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4115.rs

Fixes #4115. Fixes #4029. Fixes #3898.
The new tests fail on master as follows:
```diff
Mismatch at tests/target/issue-4115.rs:1:
-#[derive(
-    A,
-    B,
-    C,
-    D,
-    // E,
-)]
+#[derive(A, B, C, D)]
fn foo() {}
Mismatch at tests/target/issue-4029.rs:1:
// issue #4029
-#[derive(Debug, Clone, Default Hash)]
+#[derive()]
struct S;
// issue #3898
Mismatch at tests/target/issue-4029.rs:6:
-#[derive(Debug, Clone, Default,, Hash)]
+#[derive()]
struct T;
```
They (and all other tests) pass with the proposed fix.
At the root of all three issues is the use of `ast::Attribute:: meta_item_list()` which returns `None` if the `derive` is malformed. In addition no affordance was made for comments interspersed with derive components. This fix checks for errors from `meta_item_list()` and …

fixes #4115, #4029, #3898

---

Configurations.md

docs: clarify config opts availability

---

Cargo.lock
rustfmt-core/rustfmt-lib/Cargo.toml

I gets past the error in #4132 🎉 
But compiling my app, I end up with this error:
```
Compiling rustc-ap-rustc_data_structures v656.0.0
Compiling rustc-ap-arena v656.0.0
Compiling synstructure v0.12.3
Compiling wasm-bindgen-backend v0.2.62
Compiling wasm-bindgen-macro-support v0.2.62
Compiling rustc-ap-rustc_macros v656.0.0
Compiling serde_derive v1.0.106
Compiling thiserror-impl v1.0.16
Compiling rustfmt-config_proc_macro v0.5.0 (/Users/cameron/rs/rustfmt/rustfmt-core/rustfmt-lib/config_proc_macro)
Compiling wasm-bindgen-macro v0.2.62
Compiling thiserror v1.0.16
Compiling rustc-ap-rustc_span v656.0.0
thread 'rustc' panicked at 'src/librustc_resolve/imports.rs:906: inconsistent resolution for an import', /rustc/2454a68cfbb63aa7b8e09fe05114d5f98b2f9740/src/libstd/macros.rs:13:23
note: run …
```

update to rustc 656

---

Configurations.md
rustfmt-core/rustfmt-lib/src/config.rs

Servo has used this since forever, and it'd be useful to be able to use
rustfmt stable there so that we can use the same rustfmt version in
both Firefox and Servo.
Feel free to close this if there's any reason it shouldn't be done.
Closes #3368

Stabilize binop_separator.

---

rustfmt-core/rustfmt-lib/src/lib.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4152.rs

Previously the indetation of a line was compared with the configured
number of spaces per tab, which could cause lines that were formatted
with hard tabs not to be recognized as indented ("\t".len() < "    ".len()).
Closes #4152

Compare code block line indentation with config whitespace

---

rustfmt-core/rustfmt-lib/src/comment.rs
rustfmt-core/rustfmt-lib/tests/source/issue-4158.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4158.rs

Exclude code block delimiters when wrapping comments

---

Configurations.md
rustfmt-core/rustfmt-lib/src/config.rs
rustfmt-core/rustfmt-lib/src/config/options.rs
rustfmt-core/rustfmt-lib/src/matches.rs
rustfmt-core/rustfmt-lib/tests/source/configs/match_arm_leading_pipes/always.rs
rustfmt-core/rustfmt-lib/tests/source/configs/match_arm_leading_pipes/keep_existing.rs
rustfmt-core/rustfmt-lib/tests/source/configs/match_arm_leading_pipes/never.rs
rustfmt-core/rustfmt-lib/tests/target/configs/match_arm_leading_pipes/always.rs
rustfmt-core/rustfmt-lib/tests/target/configs/match_arm_leading_pipes/keep_existing.rs
rustfmt-core/rustfmt-lib/tests/target/configs/match_arm_leading_pipes/never.rs

Resolves #3973 (at least the leading pipe, not the `=>` on its own line)

Add config option to control leading match arm pipes

---

rustfmt-core/rustfmt-lib/src/comment.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4104.rs

I'm not sure there's a better way to do this without a larger refactor
of this method.
Closes #4104

Remove spaces added by comment opener when creating itemized block

---

rustfmt-core/rustfmt-lib/src/lists.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4151.rs

For an end user, the number of characters in a string is most likely
interpreted as the number of [grapheme cluster](http://www.unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries)s in the string,
which may be different than either the number of unicode codepoints or
bytes. Use the number of graphemes to determine list comment alignment
rather than the byte length of the line.
Closes #4151

Properly align comments in unicode lines

---

rustfmt-core/rustfmt-lib/src/items.rs
rustfmt-core/rustfmt-lib/src/visitor.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4159.rs

Previously, non-trivial type aliases in extern blocks were dropped by
rustfmt because only the type alias name would be passed to a rewritter.
This commit fixes that by passing all type information (generics,
bounds, and assignments) to a type alias rewritter, and consolidates
`rewrite_type_alias` and `rewrite_associated_type` as one function.
Closes #4159

Preserve and format type aliases in extern blocks

---

rustfmt-core/rustfmt-lib/src/items.rs
rustfmt-core/rustfmt-lib/tests/source/issue-4001.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4001.rs

rustfmt tries to preserve the comment between a fn return type and the
start of the fn body if there are no where clauses following the return
type. However, even if there are no where clauses present, the "where"
keyword may be. To elide the "where" keyword in this context, just get
the comment snippet starting after the where clause span, which always
includes the "where" keyword if present.
Closes #4001

Exclude where kw from comment following fn return type

---

Configurations.md
rustfmt-core/rustfmt-lib/src/config.rs

Servo has used this since forever, and it'd be useful to be able to use
rustfmt stable there so that we can use the same rustfmt version in
both Firefox and Servo.
Feel free to close this if there's any reason it shouldn't be done.
Closes #3380

Stabilize match_block_trailing_comma.

---

.travis.yml
Cargo.lock
Cargo.toml
appveyor.yml
ci/integration.sh
src/chains.rs
src/imports.rs
src/items.rs
src/lib.rs
src/macros.rs
src/modules.rs
src/syntux/session.rs
src/utils.rs
src/visitor.rs

cc https://github.com/rust-lang/rust/issues/72232.

Update rustc-ap-* crates to 659.0.0 for rustfmt-1.4.15

---

.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/windows.yml
.travis.yml
Cargo.lock
appveyor.yml
ci/integration.sh
rustfmt-core/rustfmt-lib/Cargo.toml
rustfmt-core/rustfmt-lib/src/chains.rs
rustfmt-core/rustfmt-lib/src/imports.rs
rustfmt-core/rustfmt-lib/src/items.rs
rustfmt-core/rustfmt-lib/src/lib.rs
rustfmt-core/rustfmt-lib/src/macros.rs
rustfmt-core/rustfmt-lib/src/modules.rs
rustfmt-core/rustfmt-lib/src/syntux/session.rs
rustfmt-core/rustfmt-lib/src/utils.rs
rustfmt-core/rustfmt-lib/src/visitor.rs

Update rustc-ap crates to 659.0.0

---

rustfmt-core/rustfmt-lib/src/formatting/stmt.rs
rustfmt-core/rustfmt-lib/src/formatting/visitor.rs
rustfmt-core/rustfmt-lib/tests/source/issue-4018.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4018.rs

Preserve comments in empty statements

---

rustfmt-core/rustfmt-lib/tests/source/issue-3550.rs
rustfmt-core/rustfmt-lib/tests/target/issue-3068.rs
rustfmt-core/rustfmt-lib/tests/target/issue-3550.rs
rustfmt-core/rustfmt-lib/tests/target/issue-3638.rs
rustfmt-core/rustfmt-lib/tests/target/issue-3858.rs
rustfmt-core/rustfmt-lib/tests/target/issue-3936.rs

The cases with `hard_tabs: true` were fixed in 2836f9bd84a3f8bed96dc6aaa5e8cfd219171245.
Not sure about the rest, but this suggests a number of open issues are
already resolved.
Closes #3068
Closes #3550
Closes #3638
Closes #3858
Closes #3936

Add test cases for fixed issues

---

rustfmt-core/rustfmt-lib/src/formatting/macros.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4111.rs
rustfmt-core/rustfmt-lib/tests/target/macro_rules.rs

A "macro" definition like
```rust
macro m {
() => {},
($a:expr) => {$a},
}
```
has its branches separated by commas. Previously rustfmt only parsed
branches separated by semicolons, which is applicable only to
"macro_rules" definitions.
Closes #4111

Parse comma-separated branches in macro definitions

---

Configurations.md

Writing `2018` for the edition, like it suggests it results in
```
Error: Decoding config file failed:
invalid type: integer `2018`, expected string for key `edition`
Please check your config file.
```
So just like other strings, make it sure it has to be a string

Align string type for edition

---

ci/integration.sh
rustfmt-core/rustfmt-bin/src/bin/main.rs
rustfmt-core/rustfmt-lib/src/config.rs
rustfmt-core/rustfmt-lib/src/config/config_type.rs
rustfmt-core/rustfmt-lib/src/config/options.rs

Currently, `rustfmt` stops building its configuration after one
configuration file is found. However, users may expect that `rustfmt`
includes configuration options inhereted by configuration files in
parent directories of the directory `rustfmt` is run in.
The motivation for this commit is for a use case involving files that
should be ignored by `rustfmt`. Consider the directory structure
```
a
|-- rustfmt.toml
|-- b
|-- rustfmt.toml
|-- main.rs
```
Suppose `a/rustfmt.toml` has the option `ignore = ["b/main.rs"]`. A user
may expect that running `rusfmt` in either directory `a/` or `b/` will
ignore `main.rs`. Today, though, if `rustfmt` is run in `b/`, `main.rs`
will be formatted because only `b/rustfmt.toml` will be used for
configuration.
Although motivated by the use case for ignored …

Merge configs from parent directories

---

Configurations.md
rustfmt-core/rustfmt-lib/src/config.rs

Stabilize ignore config option

---

Cargo.lock
rustfmt-core/rustfmt-lib/Cargo.toml
rustfmt-core/rustfmt-lib/src/format_report_formatter.rs

I made major changes to this library. In the previous version we worked with owned while in the current one with borrowed.
I have adapted it without changing the behavior.

Update annotate-snippets-rs to 0.8.0

---

rustfmt-core/rustfmt-bin/src/bin/main.rs
rustfmt-core/rustfmt-lib/src/formatting.rs
rustfmt-core/rustfmt-lib/src/formatting/modules.rs
rustfmt-core/rustfmt-lib/src/formatting/syntux/parser.rs
rustfmt-core/rustfmt-lib/src/result.rs

Improve error message when module resolution failed

---

.cargo/Makefile.toml

I ran into an issue while using rustfmt and found rust-lang/rust#72423
I saw how you solved it locally and decided to do the same as well, but the actual values provided are not accurate.
I believe CFG_RELEASE should hold the rustc version number and not channel.
so this should hopefully provide a more accurate value.

Fix CFG_RELEASE value

---

rustfmt-core/rustfmt-lib/src/formatting/vertical.rs
rustfmt-core/rustfmt-lib/tests/source/issue-4099.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4099.rs

This PR addresses https://github.com/rust-lang/rustfmt/issues/4099. 
It looks to me that fields are separated into groups based on newlines. However, the trailing comma for each group may be removed. I added code that ensures that only the final group of fields can have their trailing comma removed.

#4099: trailing_comma + struct_field_align_threshold -> removing a struct's commas

---

.cargo/Makefile.toml
Makefile.toml
rustfmt-core/rustfmt-lib/config_proc_macro/Cargo.toml
rustfmt-core/rustfmt-lib/config_proc_macro/src/lib.rs
rustfmt-core/rustfmt-lib/config_proc_macro/src/utils.rs

In this PR, I'm going to make a few changes to the Makefile configuration.
- Add a `cargo make bb`. This task builds only the `rustfmt` binary.
- Remove a feature used by config_proc_macro for debugging. Replace it with the environment variable instead.

Fix makefile

---

rustfmt-core/rustfmt-lib/src/formatting.rs
rustfmt-core/rustfmt-lib/src/formatting/modules.rs
rustfmt-core/rustfmt-lib/src/formatting/syntux/parser.rs
rustfmt-core/rustfmt-lib/src/test/mod.rs
rustfmt-core/rustfmt-lib/tests/parser/issue-4126/invalid.rs
rustfmt-core/rustfmt-lib/tests/parser/issue-4126/lib.rs

handle recoverable submod parse errors correctly

---

rustfmt-core/rustfmt-lib/src/formatting/items.rs
rustfmt-core/rustfmt-lib/tests/source/const_generics.rs
rustfmt-core/rustfmt-lib/tests/target/const_generics.rs

Use the span after generics and where clause

---

rustfmt-core/rustfmt-lib/src/formatting/visitor.rs
rustfmt-core/rustfmt-lib/tests/source/issue-4167.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4167.rs

Properly skip macros in impl and trait blocks

---

rustfmt-core/rustfmt-lib/src/formatting/items.rs
rustfmt-core/rustfmt-lib/src/formatting/utils.rs
rustfmt-core/rustfmt-lib/tests/source/impls.rs
rustfmt-core/rustfmt-lib/tests/target/impls.rs

Include constness in impl blocks

---

rustfmt-core/rustfmt-lib/src/formatting/comment.rs
rustfmt-core/rustfmt-lib/tests/target/issue-4210.rs

Don't wrap comments that are part of a table

---

docs/index.html

A demonstration of the fix is included in the PR associated with this
commit.

Fix stable toggle on gh pages configuration site

---

src/formatting/items.rs
tests/target/issue-4218.rs

Handle const generic bounds in structs

---

Configurations.md
docs/index.html

See https://pithecoidstreet.htmlpasta.com/ for a demo of this change.
Part of #4178

Show configs from different versions on github pages

---

Configurations.md

I realized documentation was never added for 796cc584aa66afa4f89550d97181cf3dbfd77662.
It's useful to have because the behavior may be non-obvious to users who
are not already aware of the change.

Add documentation for additive configs from parent directories

---

src/rustfmt/main.rs

Currently, rustfmt emits `stdin:` prefix unnecessarily on stdin mode:
```
$ rustfmt
fn main()
{}^D
stdin:
fn main() {}
```
This PR fixes it so that rustfmt no longer emits the prefix.

Do not emit file name on stdin mode

---

src/formatting/missed_spans.rs
tests/source/issue-4227.rs
tests/target/issue-4227.rs

Rewriting may change the context of a later item (in this case, a
comment), so looking at the original snippet to determine the context
may not be correct. Since for any given item, all previous items should
already be rewritten, it is enough to determine the item's context in
the new source but looking back at the rewrite buffer.
This commit also gets rid of variables no longer used due to the change.
Closes #4227

Use rewrite buffer to determine if comment should be on a newline

---

.github/workflows/integration.yml
.travis.yml
Configurations.md
src/config.rs
src/config/config_type.rs
src/test/configuration_snippet.rs
src/test/mod.rs
tests/config/small_tabs.toml

One of two possible approaches to resolve #4081, and my vote would be for this approach.
AIUI, `unstable_features` is basically an no-op configuration item today that rustfmt doesn't actually use. With config options set in the configuration file, all unstable options are already allowed on nightly and disallowed on stable/beta. For config options specified/overriden via the CLI, rustfmt doesn't do any stability/channel checks whatsoever (unstable config opts can be used on stable even with `unstable_features` not set/set to false, see #4081) 
With the changes in this PR:
* unstable options are still always available on nightly
* unstable options on stable/beta can be leveraged, but _only_ when `unstable_features` is set to true (regardless of whether the unstable config options are set …

feat: conditionally allow unstable opts on stable/beta

---

src/formatting/visitor.rs
tests/source/issue-4222.rs
tests/target/expr.rs
tests/target/issue-4222.rs

Per the Rust grammar, trailing semicolons on an item statement may be
optional (i.e. if the statement is a block). Keeping the semicolon in
such cases is unnecessary and may be confusing (does the semicolon
terminate the last statement, or is it an empty statement?), so just
drop it.
Closes #4222

Drop trailing semicolons on item statements

---

src/formatting/comment.rs
src/formatting/macros.rs
src/formatting/utils.rs
tests/target/issue-3659.rs

Rust has a lot of doc comment types, perhaps too many. This adds outer
block (`/**`) and inner block (`/*!`) doc comments and ensures their
trailing whitespace is preserved in cases it makes a difference in the
output Markdown.
Closes #3659

Preserve Markdown line breaks in inner and outer block doc comments

---

src/config/file_lines.rs
src/emitter.rs
src/formatting.rs
src/formatting/report.rs
src/formatting/syntux/session.rs
src/formatting/visitor.rs
src/result.rs

Read the original file for comparing/detecting newline

---

src/formatting/items.rs
tests/source/issue-2781.rs
tests/target/issue-2781.rs

I don't think this hurts to fix. #2781, which surfaced this issue, has
a number of comments relating to similar but slightly different issues
(i.e. dropped comments in other places). I can mark #2781 as closed and
then will open new issues for the comments that are not already resolved
or tracked.
Closes #2781

Pick up comments between visibility modifier and item name

---

tests/source/issue-2947.rs
tests/source/issue-2978.rs
tests/source/issue-3206.rs
tests/target/issue-1762.rs
tests/target/issue-2388.rs
tests/target/issue-2672.rs
tests/target/issue-2755.rs
tests/target/issue-2947.rs
tests/target/issue-2978.rs
tests/target/issue-3148.rs
tests/target/issue-3206.rs

Adds regression tests for the following issues which seem to be fixed on
master:
Closes #1762
Closes #2388
Closes #2672
Closes #2755
Closes #2947
Closes #2978
Closes #3148
Closes #3206
@topecongiro @calebcartwright appologies for the large number of issues
in this commit; if you prefer I can split it up into 2+.

Prune stale issues

---

Contributing.md
README.md

Refs various issues, for example #4230

docs: update dev instructions and unstable opts info

---

Cargo.lock
Cargo.toml
src/bin/main.rs
src/comment.rs
src/config/file_lines.rs
src/config/mod.rs
src/expr.rs
src/format-diff/main.rs
src/format_report_formatter.rs
src/formatting.rs
src/lib.rs
src/macros.rs
src/modules.rs
src/source_file.rs
src/syntux/parser.rs
src/syntux/session.rs
src/test/mod.rs
src/utils.rs
tests/parser/issue-4126/invalid.rs
tests/parser/issue-4126/lib.rs
tests/source/issue-4079.rs
tests/target/issue-4020.rs
tests/target/issue-4079.rs
tests/target/skip/foo.rs
tests/target/skip/main.rs

Refs rust-lang/rust#73200, rustfmt 1.x pair to #4252. 
~~There's one last parser bug which has been fixed in source, but that I want to also backport to rustfmt 1.x as part of this~~
* bumps rustc-ap-* crate versions to latest v644.0.0
* cherry-pick backport of switch from `failure` to `anyhow/thiserror` from #3948 (in part because `failure` is deprecated and because our subsequent err handling on master is based on `anyhow` and `thiserror`)
* backports the module resolution error handling from #4198 
* backports the fix for handling of parser errors in non-inline mods from #4200
* also backports some minor bug fixes (from #4080 and #4071) given how small they were and the discussion in https://github.com/rust-lang/rustfmt/pull/4080#issuecomment-615884887

bump rustfmt 1.x rustc-ap* crates to v644

---

Cargo.lock
Cargo.toml
src/config/file_lines.rs
src/formatting/expr.rs
src/formatting/macros.rs
src/formatting/syntux/session.rs
src/formatting/utils.rs

Refs https://github.com/rust-lang/rust/issues/73200
~~There's newer versions of several of crates, but due to the publishing issue described in https://github.com/alexcrichton/rustc-auto-publish/issues/23, v660 is the most recent version that exists for _all_ the crates we need.~~
~~Hopefully v664 will have all the requisite fixes and we can bump to that once published~~

bump rustc-ap* to v664.0.0

---

Cargo.toml
src/formatting/modules.rs
src/formatting/modules/visitor.rs
src/lib.rs

Avoid using Symbol::intern

---

docs/index.html

Closes #4261 
Separates out search and direct linking, uses header ids for direct linking and `?search=term` for filtering configurations.
Once the app mounts the page is scrolled to the current header set in the url hash.

Adds direct linking using header ids

---

src/formatting/report.rs
src/rustfmt/main.rs

don't reformat with errors unless --force flag supplied

---

docs/index.html

Fixes #4260 
This adds support for using a query parameter to select the version no.
Note: If the provided version number in the query string cannot be found then the page is shown as blank since the axios get call returns a 404 and isn't being caught. If this is a concern then a proper 404 message can be shown something like `No such version number found`.

Adds query param for version no

---

.github/workflows/upload-assets.yml
Makefile.toml

Add upload-assets.yml

---

src/formatting/items.rs
tests/source/extern.rs
tests/target/extern.rs

Do not remove fn headers (e.g., async) on extern fn items

---

src/formatting/items.rs
tests/source/issue-4289.rs
tests/target/issue-4289.rs

Previously rustfmt only picked up comments between a trait "signature"
and its block when there was no `where` clause on the trait. Amending
this to work for comments following a `where` clause and preceding the
trait block is straightforward; we simply get rid of the branch and
adjust the span to search for a comment in accordingly.
Closes #4289

Pick up comments between trait where clause and open block

---

src/formatting/items.rs
src/formatting/types.rs
src/formatting/utils.rs
src/formatting/visitor.rs
tests/source/extern.rs
tests/target/extern.rs

Fixes #2908 (option 3 from https://github.com/rust-lang/rustfmt/issues/2908#issuecomment-650588865)
Happy to open a separate/alternative PR with option 2 if we'd rather go that route :+1:

don't convert implict ABI when doing so could fail to preserve semantics

---

Cargo.lock
Cargo.toml
src/formatting/spanned.rs
src/formatting/types.rs
tests/source/const_generics.rs
tests/target/const_generics.rs

Kudos to @ayazhafiz for updating the rustc frontend; now, the rustc AST has enough information to calculate the correct span of generic parameters.
Close #4263.

Do not duplicate const keyword on parameters

---

Configurations.md
src/formatting/macros.rs
src/formatting/missed_spans.rs
src/formatting/reorder.rs
src/formatting/visitor.rs
tests/source/configs/blank_lines_lower_bound/2.rs
tests/target/assignment.rs
tests/target/configs/blank_lines_lower_bound/2.rs
tests/target/control-brace-style-always-next-line.rs
tests/target/control-brace-style-always-same-line.rs
tests/target/else-if-brace-style-always-next-line.rs
tests/target/else-if-brace-style-always-same-line.rs
tests/target/else-if-brace-style-closing-next-line.rs
tests/target/extern.rs
tests/target/multiple.rs
tests/target/remove_blank_lines.rs

With this PR, we no longer normalize the number of vertical lines unless those are in between items.
Since this PR changes the default formatting style, I would like to include this PR to the 2.0 release.
Close #2954.

Do not normalize vertical spaces unless they are between items

---

src/formatting.rs
src/formatting/visitor.rs
src/test/configuration_snippet.rs
tests/target/skip/skip-with-trailing-comma.rs

Do not touch module with #![rustfmt::skip]

---

Configurations.md
src/config/options.rs
src/formatting/matches.rs
tests/source/configs/match_arm_leading_pipes/preserve.rs
tests/target/configs/match_arm_leading_pipes/preserve.rs

Discussed briefly in https://github.com/rust-lang/rustfmt/pull/4090#issuecomment-650588081, but basically `Preserve` feels like a better variant name than `KeepExisting`. 
It's more succinct and direct, and though not terribly important, another minor benefit is that it also happens to be consistent with the equivalent config option values seen in other code formatting tools

rename KeepExisting->Preserve variant for leading match arm pipe config option

---

src/formatting/comment.rs
tests/source/issue-4251.rs
tests/target/issue-4251.rs

Currently, the first line pushed in a code block is a comment line
delimiter that includes a trailing space, even if the content of that
line is empty. Later lines are handled correctly because their content
is checked before adding the comment line delimiter. So, just apply the
same logic as is done for later lines to the first line.
Closes #4251

Do not add trailing space to empty lines in comment code blocks

---

src/formatting/closures.rs
tests/source/issue-4308.rs
tests/target/issue-4308.rs

The problem here was that if an expression in a closure fails to be
formatted without an enclosing block, as in the case of a multiline
range prior to this commit, we try to put the expression in the block.
But then we try to check what expressions should be "vetoed" from being
in a block, which includes ranges. The non-breaking fix is to let
multiline ranges be formatted without a block.
On the big picture, though, it may be the case that there is no need for
a "veto" check when formatting expressions in a closure block, or that
there is a better way to structure the work being done here. I added a
todo for this, since it's relatively low priority (IMO).
Closes #4308

Permit ranges on multiple lines in closures, without an enclosing block

---

Configurations.md
src/config.rs
src/formatting.rs
src/formatting/generated.rs
src/test/mod.rs
tests/source/configs/format_generated_files/false.rs
tests/source/configs/format_generated_files/true.rs
tests/target/configs/format_generated_files/false.rs
tests/target/configs/format_generated_files/true.rs

This PR adds `format_generated_files`. When this value is `false`, rustfmt skips formatting generated files. If the value is `true`, rustfmt formats generated files. `format_generated_files` is set to `false` by default.
rustfmt considers files as generated if the file starts with a comment which includes `@generated` ( e.g., `// @generated`).
Close #3958.

Skip formatting generated files

---

tests/source/where-clause.rs
tests/target/where-clause.rs

This was fixed in 1e9af9fa2eb6ba4e0ad1e2e275003ada7e5a27e2 but it seems
that a test was never added.
Closes #4315

Add test for generic bounds on associated types

---

src/formatting/comment.rs
tests/target/issue-4312.rs

Recognize when a block comment has been ended inside a string literal

---

Configurations.md
src/config.rs
src/formatting/items.rs
src/formatting/visitor.rs
tests/source/configs/preserve_block_start_blank_lines/false.rs
tests/source/configs/preserve_block_start_blank_lines/true.rs
tests/target/configs/preserve_block_start_blank_lines/false.rs
tests/target/configs/preserve_block_start_blank_lines/true.rs

Adds the option for
- Functions
- Control flow blocks
- Expression statements (i.e. `let x = { ... };`)
- Traits
- Trait Impls
- Mods
- Foreign Mods
If I am missing a kind of item, let me know :)
Closes #2868

Configuration option to preserve blank lines at start of block

---

src/formatting/items.rs
src/formatting/visitor.rs
tests/target/issue-4313.rs

A code like
```rust
extern "C" {
fn f() {
fn g() {}
}
}
```
is incorrect and does not compile. Today rustfmt formats this in a way
that is correct:
```rust
extern "C" {
fn f();
}
```
But this loses information, and doesn't have to be done because we know
the content of the block if it is present. During development I don't
think rustfmt should drop the block in this context.
Closes #4313

Don't drop blocks on foreign functions

---

src/formatting/overflow.rs
src/test/mod.rs

There's obviously been a lot of discussion within the tech industry about various terms and language, and I'm in agreement with ensuring communities are inclusive and use inclusive language. 
Some of the specific terms that are being revisited and renamed are `whitelist` and `blacklist`, including in the [Linux kernel](https://www.zdnet.com/article/linux-team-approves-new-terminology-bans-terms-like-blacklist-and-slave/) and in the [main Rust repo](https://github.com/rust-lang/rust/pull/74127). 
We didn't have much usage of those terms within rustfmt (couple private variables and function names), but this PR renames those handful of instances with what I feel are genuinely better names that more clearly convey their purpose.
For example, we previously used `SKIP_FILE_WHITE_LIST` for the …

refactor: rename some private whitelist naming

---

docs/index.html

Demo: https://5f0fad2f06c62143ac519413--festive-golick-afb5e0.netlify.app
Closes #4319

Warn when rate limit is on docs page

---

Cargo.lock
Cargo.toml
src/chains.rs
src/config/mod.rs
src/formatting.rs
src/items.rs
src/matches.rs
src/types.rs
src/visitor.rs
tests/config/issue-3779.toml
tests/source/issue-3779/lib.rs
tests/target/issue-3779/lib.rs
tests/target/issue-3974.rs

We don't have any explicit plans for another rustfmt 1.x release, but opening this against a 1.4.19 branch proactively in case we do end up having to do another release.
This includes a bump of the rustc-ap-* crates to ~~v668~~ v669 which had some minor breaking changes, and also backports the fix from #3975 to ensure that fix will be in the next released version of rustfmt regardless of whether that's a 1.x or 2.x release (Refs #4282 and #3974)

preparation for potential rustfmt 1.4.19

---

src/formatting/utils.rs
tests/target/issue-4325.rs

Today rustfmt bails when trying to handle a code block that, after
formatting, has lines >100 chars. The reasoning was that if there were
lines longer than 100 chars it wasn't clear if we failed to format or
that was the intended result, so to be cautious the handler would bail.
However, if formatting the snippet fails the code block formatter will
already have jumped out by the time this line-width check is done:
https://github.com/rust-lang/rustfmt/blob/ff57cc6293ce450380dbb6da6a1a3656dbae538d/src/formatting/util.rs#L81
So I am not sure that this check is needed, and removing it broke no
tests except one designed explicitly for it. NB w.r.t. that unit test,
formatting a code like
```
fn main() {
let expected = "this_line_is_100_characters_long_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx …
```

Don't bail out of formatting code blocks if lines are >100 chars

---

src/config.rs
src/formatting.rs

This commit has a few tweaks necessary to get a wasi binary of `rustfmt`
working. Timers were flagged as being allowed on wasi targets (but still
not allowed on wasm32), and path canonicalization errors are now also
ignored. This is also somewhat beneficial for other filesystems as well
where canonicalization sometimes does not work in esoteric situations.

Improve support for wasm32-wasi

---

README.md

This time we try to clean up a lot of the README, after its structure
was reorged in #4345.
cc @calebcartwright
Closes #4336

Update documentation, round 2

---

Cargo.lock
Cargo.toml

Needed to fix broken toolstate https://github.com/rust-lang/rust/issues/74812
Master was already addressed via #4354 
Racer PR for the same rustc-ap bump opened https://github.com/racer-rust/racer/pull/1124

rustfmt 1.x bump rustc-ap to v671

---

src/formatting/items.rs
tests/target/configs/space_before_fn_sig_paren/max_width.rs
tests/target/issue-4306.rs

#3891 removed Version One formatting that did this correctly (https://github.com/rust-lang/rustfmt/pull/3891/files#diff-5db152a52bdaeae9dacd35f43a4a78ddL2342-L2344),
but at seemingly at the time there were no tests to catch the
regression.
This commit fix-forwards the formatting regression, though via a different
implementation because the original implementation would muddle the branch
for visual indentation and this fix, which is probably not preferrable
giving the existing complexity of the rewrite_required_fn method.
Closes #4366

Indent return types separated from params by newline

---

src/formatting/closures.rs
src/formatting/expr.rs
tests/source/issue-4382.rs
tests/target/issue-4382.rs

This commit partially reverts #3934, opting to create a span that covers
the entire body of a closure when formatting a closure body with a
block-formatting strategy, rather than having the block-formatting code
determine if the visitor pointer should be rewound. The problem with
rewinding the visitor pointer is it may be incorrect for other (i.e.
non-artificial) AST nodes, as in the case of #4382.
Closes #4382

Correctly create artificial span for formatting closure body

---

src/formatting/closures.rs
src/formatting/expr.rs
tests/source/issue-4384.rs
tests/target/issue-4384.rs

A closure like this:
```
let x = ||
// a comment
some_body_expr;
```
should be a block instead of a single expression, as per the [fmt-rfcs](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#closures).
Closes #4384

Turn closure bodies from exprs into blocks if there are comments

---

Contributing.md

Apparently the GitHub feature that identities issues needing help in a repo requires spaces between the label words (e.g. `help wanted` vs `help-wanted`) in order to actually work. I've updated the label names so that these types of issues will be recognized properly for rustfmt, and this PR updates the label references to reflect the rename accordingly

update GitHub label references in Contributing guide

---

src/formatting/types.rs
tests/source/type.rs
tests/target/type.rs

These two cases are simple enough; I might as well support it instead of panicking.
Also, in a bit extreme case the current implementation can panic against valid Rust code when macro is involved:
```rust
macro_rules! foo {
(typeof($e:expr)) => {}
}
fn main() {
foo!(typeof(3));
}
```
Close #4357.

Format error and typeof types

---

src/formatting/expr.rs
tests/source/configs/brace_style/unsafe_always_next_line.rs
tests/target/configs/brace_style/unsafe_always_next_line.rs

* Unsafe blocks can now get an opening brace on a new line
* Add test case for unsafe blocks
Hello relating to this issue : https://github.com/rust-lang/rustfmt/issues/3376 and this issue : https://github.com/rust-lang/rustfmt/issues/3377
All comments or suggestions are very welcome, I'm far from being a rust pro :)
Cheers

BraceStyle AlwaysNewLine for unsafe blocks

---

Cargo.lock
Cargo.toml
src/formatting/closures.rs
src/formatting/imports.rs
src/formatting/items.rs
src/formatting/macros.rs
src/formatting/syntux/parser.rs
src/formatting/utils.rs
src/formatting/visitor.rs
tests/source/unsafe-mod.rs
tests/target/unsafe-mod.rs

I need this for being able to use https://github.com/rust-lang/rust/pull/75857.

Bump rustc-ap to v679

---

Cargo.lock
Cargo.toml
src/attr.rs
src/closures.rs
src/imports.rs
src/items.rs
src/macros.rs
src/spanned.rs
src/syntux/parser.rs
src/utils.rs
src/visitor.rs
tests/source/unsafe-mod.rs
tests/target/unsafe-mod.rs

This is a backport of https://github.com/rust-lang/rustfmt/pull/4423 and https://github.com/rust-lang/rustfmt/pull/4433.

1.x: Bump rustc-ap to v679

---

.editorconfig
.github/workflows/integration.yml
.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/upload-assets.yml
.github/workflows/windows.yml
Configurations.md
src/config/mod.rs
src/config/options.rs
src/matches.rs
tests/source/configs/match_arm_leading_pipes/always.rs
tests/source/configs/match_arm_leading_pipes/never.rs
tests/source/configs/match_arm_leading_pipes/preserve.rs
tests/target/configs/match_arm_leading_pipes/always.rs
tests/target/configs/match_arm_leading_pipes/never.rs
tests/target/configs/match_arm_leading_pipes/preserve.rs

Backports the GitHub Actions Workflows as well as the `match_arm_leading_pipes` config option as requested

Backport some things for rustfmt 1.4.22

---

src/items.rs
src/visitor.rs
tests/target/issue-4159.rs

This is a straightforward backport of #4164 to resolve rustfmt deleting important code when using the `cxx` crate; see https://github.com/dtolnay/cxx/issues/330#issuecomment-702233661.

1.x: Preserve and format type aliases in extern blocks

---

src/formatting/items.rs
tests/source/configs/brace_style/extern_always_next_line.rs
tests/target/configs/brace_style/extern_always_next_line.rs

* extern blocks can now get an opening brace on a new line
* add test case for extern blocks
I also made sure that there are no trailing spaces for the `extern "C"` line after formatted.
fixes issue #4428

BraceStyle AlwaysNewLine for extern blocks

---

docs/index.html

Add code to the doc/index.html file to handle the specific cases for version 0.8.1 and 0.7
of rustfmt where they don't have a explicit configuration.md file. Updated to pull the data
that is within the "Configuring Rustfmt" section of the original README

[#4429] Fix Error Retrieving Old Config Options

---

Configurations.md

Removed an unused third level heading.

Fix header typo

---

Contributing.md
src/format-diff/main.rs
src/git-rustfmt/main.rs
src/rustfmt/main.rs

`cargo fmt` is very noisy when the env var `RUST_LOG` is set to `debug`. Developers set this variable for debugging their own code and almost never want to see debug output from rustfmt. Note that rustc and clippy do not output any debug logging, regardless of the `RUST_LOG` variable.
This change is to use a different variable, `RUSTFMT_LOG` instead, so that the rustfmt developers can still control  logging as before, but without user log settings affecting rustfmt.

Use a custom env var for log settings intead of default RUST_LOG

---

src/formatting/comment.rs
src/formatting/items.rs
tests/target/issue_4032.rs

try to write the parameter on a new line in case the attribute/parameter together are over max_width

---

README.md

This PR the `RUSTFMT` environment variable in the readme of this repo, added in #4419.
Closes #4426 once the PR to the [cargo book](https://github.com/rust-lang/cargo/pull/8767) gets accepted.

Document RUSTFMT environment variable

---

tests/source/try_block.rs
tests/target/try_block.rs

They failed to parse in rustfmt on me in https://github.com/rust-lang/rust/pull/77877, which looks like it's since been fixed, but I figured I'd send in some basic tests (mostly copied from `async{}`'s) anyway.

Add some basic tests for `try{}` expressions

---

Cargo.lock
Cargo.toml

deps: bump rustc-ap crates to v683

---

Cargo.lock
Cargo.toml
src/formatting/expr.rs
src/formatting/macros.rs
src/formatting/utils.rs

deps: bump rustc-ap crates to v684

---

Cargo.lock
Cargo.toml
src/expr.rs
src/macros.rs
src/missed_spans.rs
src/stmt.rs
src/utils.rs
src/visitor.rs
tests/source/issue-4018.rs
tests/source/issue-4398.rs
tests/target/issue-4018.rs
tests/target/issue-4398.rs

Mostly just pulls in the commits to bump the rustc-ap crates to v684 (which contains some crucial upstream parser/span fixes) and also backporting a few bug fixes

prepare for v1.4.23 release

---

src/config/config_type.rs
src/config/mod.rs

Closes https://github.com/rust-lang/rustfmt/issues/4487.

Fix overriding license header bug

---

Cargo.lock
Cargo.toml
src/formatting/macros.rs

This seems to be required to fix rustfmt build on latest nightly. See https://github.com/rust-lang/rust/issues/78341#issuecomment-716178002.

deps: bump rustc-ap crates to v686

---

.github/workflows/upload-assets.yml
.github/workflows/windows.yml

@calebcartwright 
Please review the Github Action updated commands for issue #4480 . I have also updated set-env command.

Update deprecated add-path and set-env Github Action commands

---

src/formatting/matches.rs
tests/target/configs/match_arm_blocks/false.rs
tests/target/configs/match_arm_blocks/true.rs
tests/target/issue-2936.rs
tests/target/match.rs

We no longer flatten a block that looks like this:
```rust
match val {
pat => { macro_call!() }
}
```
Currently, rust ignores trailing semicolons in macro expansion in
expression position (see https://github.com/rust-lang/rust/issues/33953)
If this is changed, flattening a block with a macro call may break the
user's code - the trailing semicolon will no longer parse if the macro
call occurs immediately on the right-hand side of the match arm
(e.g. `pat => macro_call!()`)

Don't flatten a block containing a single macro call

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/lib.rs
src/matches.rs
tests/target/configs/match_arm_blocks/false.rs
tests/target/configs/match_arm_blocks/true.rs
tests/target/issue-2936.rs
tests/target/match.rs

Refs https://github.com/rust-lang/rust/issues/78341, needed due to subsequent breaking changes being merged upstream (more detail in https://github.com/rust-lang/rust/pull/78775)

prepare v1.4.24 release

---

src/formatting.rs
src/formatting/comment.rs
src/formatting/macros.rs
src/formatting/rewrite.rs
src/formatting/utils.rs
src/formatting/visitor.rs
src/lib.rs
src/rustfmt/main.rs
tests/target/macro_rules_semi.rs

Currently, rustfmt inserts semicolons for certain trailing expressions
(`return`, `continue`, and `break`). However, this should not be done in
the body of a `macro_rules!` arm, since the macro might be used in
expression position (where a trailing semicolon will be invalid).
Currently, this rewriting has no effect due to https://github.com/rust-lang/rust/issues/33953
If this issue is fixed, then this rewriting will prevent some macros
from being used in expression position.
This commit prevents rustfmt from inserting semicolons for trailing
expressions in `macro_rules!` arms. The user is free to either include
or omit the semicolon - rustfmt will not modify either case.

Don't insert semicolons inside of a `macro_rules!` arm body

---

.github/workflows/integration.yml
.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/windows.yml

Only run workflows on pushes to `master`, and do some mingw cleanup on Windows

ci: GHA Workflow Updates

---

src/formatting/expr.rs
tests/source/issue_4534.rs
tests/target/issue_4534.rs

fix: between span derivation on cast exprs

---

src/items.rs
tests/target/configs/where_single_line/true-with-brace-style.rs

Fixes #4547.
This PR is based off of the `rustfmt-1.4.28` branch, although it should be trivially portable to `master`, if you'd prefer. A new test file is included.

fix: don't force a newline after an empty where clause

---

src/formatting/expr.rs
tests/source/configs/brace_style/const_block_always_next_line.rs
tests/source/configs/brace_style/const_block_same_line_where.rs
tests/target/configs/brace_style/const_block_always_next_line.rs
tests/target/configs/brace_style/const_block_same_line_where.rs

Refs #4483 
**Testing**
`cargo make test`

enhance const block formatting

---

src/items.rs
src/visitor.rs
tests/source/extern.rs
tests/target/extern.rs
tests/target/issue-4313.rs

This PR is a clean backport of the 2 commits from https://github.com/rust-lang/rustfmt/pull/4291 and 1 commit from https://github.com/rust-lang/rustfmt/pull/4314, followed by 1 new commit to delete some test cases from #4291 involving `async fn` which fail on 1.x due to difference in default edition. #4291 is adequately tested by almost identical signatures using `const fn` and `unsafe fn` (the latter being what I actually care about) instead of async.
Backport motivated by the broken behavior being quite problematic for https://github.com/dtolnay/cxx.

1.x: Backport fixes around deleting pieces of extern functions

---

src/items.rs
tests/source/negative-impl.rs
tests/target/negative-impl.rs

Clean backport of #4567. I am considering using this syntax for something in https://github.com/dtolnay/cxx but would first need it to be not erased by at least the version of rustfmt shipping with the latest stable toolchain.
I saw 1.4.28 is released already but there wasn't a 1.4.29 branch yet -- you may need to [change the base branch](https://github.blog/2016-08-15-change-the-base-branch-of-a-pull-request/) after creating one.

1.x: Preserve polarity on negative non-trait impl

---

src/formatting/closures.rs
tests/source/issue-4577.rs
tests/target/issue-4577.rs

If the closure's body fits in a line, the block is removed but it is
necessary if the closure has a return type.
Close #4577

Fix rewrite of closures with a return type

---

src/formatting/items.rs
tests/target/configs/where_single_line/true-with-brace-style.rs

Rebase of #4548 onto `master`. Clean.

fix: don't force a newline after an empty where clause (master)

---

src/formatting/attr.rs
tests/source/issue_4584.rs
tests/target/issue_4584.rs

don't strip nonexistent trailing comma in derive with Visual indent_style

---

src/formatting/lists.rs
tests/source/issue-4546.rs
tests/target/issue-4546.rs

Fix for issue #4546 to properly indent multiline post-comments in a list.
The approach taken is that **each multiline comment is considered a "comments indentation group" of its own**, so each multiline comment is indented per the list item it belongs to and is not dependent on other list items` comments.  This makes sure that the internal comment lines are properly indented.
Multiline comments already terminates the indentation-group before this change.  Therefore assuming that in any case using multiline comments for list items is relatively rare, it is expected that this change will not cause major backward compatibility issues.

Proper indentation of multiline post-comments in a list

---

src/formatting/syntux/session/ignore_path.rs
src/test/mod.rs
tests/source/issue-3779/lib.rs
tests/target/issue-3779/lib.rs

Fix #4592 
Part of #4113 
Test config with `tests/config/` make ignore dir root to `tests/` and it return false with files like `tests/source/foo/bar.rs`.
I remove `config/` and add test cases to ignore_path module.

Fix test config dir

---

src/formatting/attr.rs
src/formatting/closures.rs
src/formatting/comment.rs
src/formatting/expr.rs
src/formatting/items.rs
src/formatting/lists.rs
src/formatting/macros.rs
src/formatting/overflow.rs
src/formatting/pairs.rs
src/formatting/patterns.rs
src/formatting/stmt.rs
src/formatting/string.rs
src/formatting/syntux/parser.rs
src/formatting/types.rs
src/formatting/vertical.rs
src/rustfmt/main.rs

Fixes
clippy::single_char_pattern
clippy::manual_strip
clippy::unneccessary_wraps
clippy::redundant_closure
clippy::single_char_add_str
clippy::search_is_some
clippy::clone_on_copy
clippy::into_iter_on_ref

Fix clippy warnings

---

src/formatting/expr.rs

Change `ControlFlow` `rewrite_pat_expr()` to use `rewrite_assign_rhs_with_comments()` (subset of proposed changes in PR #4578).

Use rewrite_assign_rhs_with_comments by ControlFlow rewrite_pat_expr

---

src/formatting/expr.rs
tests/target/issue_3868.rs

Improve check for presence of statements in a block

---

src/formatting/types.rs
tests/source/issue_4636.rs
tests/target/issue_4636.rs

fix: correct generic bound indentation [2.x/master]

---

Configurations.md
src/config/config_type.rs
src/config/mod.rs
src/config/options.rs
src/imports.rs
src/reorder.rs
tests/source/configs/group_imports/StdExternalCrate-merge_imports.rs
tests/source/configs/imports_layout/merge_mixed.rs
tests/source/imports_granularity_crate.rs
tests/source/imports_granularity_module.rs
tests/source/issue-3750.rs
tests/source/merge_imports_true_compat.rs
tests/target/configs/group_imports/StdExternalCrate-merge_imports.rs
tests/target/configs/imports_layout/merge_mixed.rs
tests/target/imports_granularity_crate.rs
tests/target/imports_granularity_module.rs
tests/target/issue-3750.rs
tests/target/merge_imports_true_compat.rs

Backport of #4600 to 1.x. I presume that a rustfmt-1.4.32 branch needs to be created, though.

1.x: Rename `merge_imports` to `imports_granularity` and add a `Module` option.

---

src/formatting/items.rs
tests/source/issue-4646.rs
tests/target/issue-4646.rs

Fixes #4646
Thought the issue I encountered would be straightforward to fix, so I decided to give it a go.
Fixed by inserting a newline while maintaining current indentation, if the result of `rewrite_fn_base` ends in a comment.

Fixed semicolon getting moved into trait method comment

---

src/types.rs
tests/source/issue_4636.rs
tests/target/issue_4636.rs

A bug was reported (#4636) that currently exists in the rustfmt version on beta (1.4.30) which has been fixed in rustfmt v1.4.32. We need to get this fixed to avoid shipping a known bug on stable, but we cannot readily do the typical roll-forward approach due to conflicting needs in the rustc-ap crates that had to be bumped between those two rustfmt versions (refs https://github.com/rust-lang/rust/pull/81151#issuecomment-761949761)
Instead, cherry-picking these commits that fixed the bug back onto the rustfmt 1.4.30 branch so the bug fix can still be pulled in for the 1.50 release

v1.4.30 backport of bounds indentation issue

---

Configurations.md
src/config/options.rs
src/formatting/imports.rs
src/formatting/reorder.rs
tests/source/imports_granularity_item.rs
tests/target/imports_granularity_item.rs

This option splits all imports into their own `use` statement.

Add imports_granularity="Item".

---

docs/index.html

Fixes (mostly) #4633 
**Changes:**
Updates the default version to the latest version released.

Added Updated default version to Rustfmt docs config

---

CHANGELOG.md
src/items.rs
src/spanned.rs
src/utils.rs
tests/source/const_generics.rs
tests/source/impls.rs
tests/target/const_generics.rs
tests/target/impls.rs
tests/target/issue-4310.rs

Backports some of the const generic related fixes in preparation for the upcoming v1.4.33 release
Includes backported fixes for:
* #4084
* #4204
* #4263
* #4310

[1.x] backport some const generic fixes for v1.4.33

---

src/lib.rs
src/modules.rs
src/test/mod.rs
tests/source/issue-4656/format_me_please.rs
tests/source/issue-4656/lib.rs
tests/source/issue-4656/lib2.rs
tests/target/issue-4656/format_me_please.rs
tests/target/issue-4656/lib.rs
tests/target/issue-4656/lib2.rs

1.x fix: Avoid incorrect global 'cfg_if' Symbol interning

---

src/formatting/expr.rs
tests/source/issue_4675.rs
tests/target/issue_4675.rs

Don't insert trailing comma on struct lit rest (no base) in a macro definition

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/expr.rs
tests/source/issue_4675.rs
tests/target/issue_4675.rs

One more bug fix atop the v1.4.33 release, bumping the version since the GH release+tag was already created for 1.4.33

prepare v1.4.34 release

---

.github/workflows/upload-assets.yml

This is helpful for my [ubi tool](https://github.com/houseabsolute/ubi). It also prepares for doing ARM builds for macOS, which will probably be a thing in the near future.

Add arch name to archive files created in the upload workflow

---

Cargo.toml

A local `cargo check --all-targets` did not emit any errors so let's see what CI thinks.

Bump rustc-ap-* crates to version 706

---

src/formatting/types.rs
tests/source/type.rs
tests/source/where-clause.rs
tests/target/type.rs
tests/target/where-clause.rs

Fixes Rustfmt deleting generics on associated type bounds

Format generic associated type bounds

---

src/comment.rs
src/formatting.rs
src/git-rustfmt/main.rs
src/syntux/parser.rs
src/test/mod.rs

- Fix nightly warning about `format!`
- Remove unused functions and fields
This will be needed for https://github.com/rust-lang/rust/pull/82208 since rust-lang/rust denies warnings, but is also helpful without that change.

Fix warnings

---

src/formatting.rs
src/lib.rs
tests/source/issue-4603.rs
tests/target/issue-4603.rs

1.x fix for issue #4603 - infinite macro body indentation because of "missing comment".  The fix is per the [approach](https://github.com/rust-lang/rustfmt/pull/4629#issuecomment-774201165) discussed in #4629.
As discussed, the fix includes handling both `LostComment` and `TrailingWhitespace` errors, although I am not sure if `TrailingWhitespace` is needed.
UPDATE: the **tests fail** because an issue that i cannot understand.  When running `cargo make test` in my local machine it fails on the same errors.  However, when running manually the created `./target/debug/rustfmt` the **output is o.k**.  I hoped that this is a problem in my local machine, but unfortunately it seems it isn't.  I will be glad to get help with this issue.

1.x fix for missing comments extra macro body indentation

---

src/comment.rs
src/expr.rs
src/items.rs
tests/source/issue-4427.rs
tests/target/issue-4427.rs

Adding the use of `rewrite_assign_rhs_with_comments()` to 1.x.

1.x use of rewrite_assign_rhs_with_comments()

---

src/bin/main.rs
src/cargo-fmt/main.rs
src/format-diff/main.rs
src/git-rustfmt/main.rs

This commit can be replicated with
`cargo clippy --fix -Z unstable-options && cargo +nightly-2021-02-10 fmt`.

Fix some clippy warnings

---

src/formatting/expr.rs
tests/source/lhs-to-rhs-between-comments/assignment.rs
tests/target/lhs-to-rhs-between-comments/assignment.rs

Add handling of comments between assignment (without let) lhs and rhs by using `rewrite_assign_rhs_with_comments()` (one of the cases identified in [#4626 discussion](https://github.com/rust-lang/rustfmt/pull/4626#issuecomment-761817663)).

Comments between assignment (without let) lhs and rhs handling

---

src/formatting/comment.rs
tests/source/comment2.rs
tests/source/comment4.rs
tests/source/issue-4668.rs
tests/target/comment2.rs
tests/target/comment4.rs
tests/target/issue-4668.rs

Opening a new PR as I accidentally deleted the forked rustfmt repo! This PR aims at resolving #4668.

Issue 4668

---

src/formatting/imports.rs
tests/source/issue-4681-imports_granularity_default.rs
tests/source/issue-4681-imports_granularity_module.rs
tests/target/issue-4681-imports_granularity_default.rs
tests/target/issue-4681-imports_granularity_module.rs

Suggested fix for  #4681: when `imports_granularity = "Module"`, the formatting output of `use crate::lexer::{self, tokens::TokenData}` includes now `crate::lexer::{self}` instead of `crate::lexer::self`.
The change in `merge_use_trees()` is based on the code in `flatten_use_trees()` that handles similar issue.

`imports_granularity = "Module"` with path contains `self`

---

src/formatting/lists.rs
tests/source/imports/imports_granularity_crate-with-comments.rs
tests/source/imports/imports_granularity_default-with-comments.rs
tests/source/imports/imports_granularity_item-with-comments.rs
tests/source/imports/imports_granularity_module-with-comments.rs
tests/target/imports/imports_granularity_crate-with-comments.rs
tests/target/imports/imports_granularity_default-with-comments.rs
tests/target/imports/imports_granularity_item-with-comments.rs
tests/target/imports/imports_granularity_module-with-comments.rs

Fix an issue identified in [#4737 evaluation](https://github.com/rust-lang/rustfmt/pull/4737#discussion_r594374489), where an extra semicolon was added for import with comment preceding the `;`.  For example, with imports granularity `Crate/Module/Item` the following code:
```rust
use crate::bar::self /* bar 1 */;
use crate::bar::self;
```
was formatted as:
```rust
use crate::bar; /* bar 1 */;
```
The fix is extending handling that was done by `extract_post_comment()` to `,` after the comment, to be for the `separator` parameter instead of the constant `,`.
The test files added include some additional tests for imports with comments, as a basis for tests for other imports comments issues.  This is because 4 files are needed to test imports by granularity (`Crate/Module/Item` and default), …

Fix issue with extra semicolon when import comment precedes semicolon

---

src/modules.rs

Noticed when checking my PR's CI log :)

Fix a `legacy_derive_helpers` warning

---

Configurations.md
src/config/options.rs
src/formatting/imports.rs
src/formatting/reorder.rs
tests/source/imports_granularity_one.rs
tests/target/imports_granularity_one.rs

This implements a new option `One` for `imports_granularity`, which merges all imports into a single `use` statement as long as they have the same visibility.
Resolves #4669

Implement `One` option for imports_granularity

---

.github/workflows/windows.yml
appveyor.yml

The linker in the PATH in the Gitlab runner environment causes build failures. Fixes #4765.

Use linker provided by Rust for Windows GNU in CI build

---

.gitattributes
.github/workflows/integration.yml
.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/windows.yml
Cargo.lock
Cargo.toml
config_proc_macro/src/lib.rs
rust-toolchain
src/attr.rs
src/config/file_lines.rs
src/lib.rs
src/source_file.rs
src/syntux/session.rs
src/visitor.rs

These changes can be replicated by checking out https://github.com/rust-lang/rust/pull/82208 and then running `git subtree push --prefix=src/tools/rustfmt <some remote here> subtree`. That command took only a few seconds to run, I didn't run into any issues with repo size like Clippy has in the past.
This shouldn't be merged until there's some sort of decision on https://github.com/rust-lang/rust/pull/82208.

Add changes needed to use rustfmt as a subtree in rust-lang/rust

---

Configurations.md
src/attr.rs
src/chains.rs
src/config/config_type.rs
src/config/mod.rs
src/config/options.rs
src/expr.rs
src/items.rs
src/lists.rs
src/macros.rs
src/overflow.rs
tests/source/configs/chain_width/always.rs
tests/source/configs/chain_width/small.rs
tests/source/configs/chain_width/tiny.rs
tests/source/configs/use_small_heuristics/default.rs
tests/source/configs/use_small_heuristics/off.rs
tests/target/configs/chain_width/always.rs
tests/target/configs/chain_width/small.rs
tests/target/configs/chain_width/tiny.rs
tests/target/configs/use_small_heuristics/default.rs
tests/target/configs/use_small_heuristics/off.rs
tests/target/issue_4049.rs

This is a rebasing of #4063 onto rustfmt-1.4.37 (but let me know if that's not the right target!) with a number of edits.
I've been careful to avoid the replacement of `use_small_heuristics` with `width_heuristics` on the original PR, as that'd be a breaking change. But I have kept the improved documentation introduced there.
Finally, I added some tests that cover the behaviour rustls is relying on.
This is for #4769.

Expose `chain_width` et al in 1.4

---

rust-toolchain
src/config/file_lines.rs
src/source_file.rs
src/syntux/session.rs

https://github.com/rust-lang/rust/pull/83813 made some changes to `SourceMap` and `RealFileName` which need to be reflected here once they land in nightly
Closes - after updating rustfmt submodule - https://github.com/rust-lang/rust/issues/85226

Sync with `rustc_span` changes

---

docs/index.html

This got out of sync when we swapped the default branch (refs #4801) so cherry-picking the various commits that had improved our configuration documentation site on the 2.0 rc branch

Fix configuration documentation site

---

src/items.rs
src/lib.rs
src/types.rs

A single https://github.com/rust-lang/rust/commit/64acb7d92135ae722dfce89f0ca9d7cf6576de66 commit from the https://github.com/rust-lang/rust/pull/84571 that modified the subtree there.

Allow formatting `Anonymous{Struct, Union}` declarations

---

src/bin/main.rs

Support for Rust 2021 was added in #4618, but it wasn't actually made available through `rustfmt`'s command line. This should let people who are testing Rust 2021 on nightly rustc run `cargo fmt` again. Please let me know if I should add a test for this or if this should be gated somehow!

Allow `--edition 2021` to be passed to rustfmt

---

src/formatting/types.rs
tests/source/issue-4816/lib.rs
tests/target/issue-4816/lib.rs

Fix const param defaults being yeeted out of code

---

src/config/config_type.rs

Add double quotes around `Crate` so that it can be copied directly into a `Cargo.toml` file

Improve pasta copyability of `merge_imports` deprecation message

---

src/bin/main.rs

**NOTE**: Originally had #4812 open to merge these changes, but checks were failing in weird ways. @calebcartwright suggested rebasing my branch onto `master`, but I decided to just delete my fork and start again, and make the changes again on a new feature branch ([`remove-nightly-help-from-stable`](https://github.com/murchu27/rustfmt/tree/remove-nightly-help-from-stable)). I then [merged](https://github.com/murchu27/rustfmt/pull/1) into the `master` branch on my fork, and the checks passed there, so hopefully they'll be fine here.
***
On stable, running with `--help|-h` shows information about `file-lines`
which is a nightly-only option. This commit removes all mention of
`file-lines` from the help message on stable.
There is room for improvement here; perhaps a new struct called, e.g., …

Adjusting help message

---

Contributing.md
README.md

Updating the links to the docs and source code for `ast.rs`. Seems like it was moved to a new crate at some point.
EDIT: also updating some links in the README ([comment below](https://github.com/rust-lang/rustfmt/pull/4869#issuecomment-860965546))

Updating outdated links

---

src/matches.rs
tests/source/configs/match_arm_leading_pipes/preserve.rs
tests/target/configs/match_arm_leading_pipes/preserve.rs
tests/target/issue_4868.rs

Correct approach for detecting leading pipes in match arms

---

Configurations.md

docs: clarify match_arm_blocks config documentation

---

src/attr.rs
src/cargo-fmt/main.rs
src/chains.rs
src/closures.rs
src/comment.rs
src/config/file_lines.rs
src/config/license.rs
src/emitter/diff.rs
src/expr.rs
src/formatting/newline_style.rs
src/imports.rs
src/issues.rs
src/items.rs
src/lib.rs
src/lists.rs
src/macros.rs
src/missed_spans.rs
src/overflow.rs
src/patterns.rs
src/rustfmt_diff.rs
src/skip.rs
src/source_file.rs
src/string.rs
src/syntux/parser.rs
src/types.rs
src/utils.rs
src/visitor.rs

clippy::bind_instead_of_map
clippy::branches_sharing_code
clippy::collapsible_match
clippy::inconsistent_struct_constructor
clippy::int_plus_one
clippy::iter_count
clippy::iter_nth_zero
clippy::manual_range_contains
clippy::match_like_matches_macro
clippy::needless::collect
clippy::needless_question_mark
clippy::needless_return
clippy::op_ref
clippy::option_as_ref_deref
clippy::ptr_arg
clippy::redundant_clone
clippy::redundant_closure
clippy::redundant_static_lifetimes
clippy::search_is_some
clippy::#single_char_add_str
clippy::single_char_pattern
clippy::single_component_path_imports
clippy::single_match
clippy::skip_while_next
clippy::unnecessary_lazy_evaluations
clippy::unnecessary_unwrap
clippy::useless_conversion
clippy::useless_format

fix a bunch of clippy warnings

---

docs/index.html

Fix for issue #4665.  The issue was that version selection field id was `version`, so `search=#version` navigated to the search field instead of the version config option section.  Changed the selection field id to `viewVersion` (and changed other variables name accordingly for easier reading of the code).
There is no change from the user point of view (no UI changes).

Version config option anchor

---

src/items.rs
src/visitor.rs
tests/source/issue_4911.rs
tests/target/issue_4911.rs

handle GAT types in impls with self bounds

---

src/types.rs
tests/target/issue_4943.rs

don't drop drop generic args on assoc ty constraints

---

src/items.rs
src/visitor.rs
tests/source/impls.rs
tests/source/trait.rs
tests/target/impls.rs
tests/target/trait.rs

Preserve visibility on trait items

---

Configurations.md
src/config/options.rs
src/imports.rs
src/reorder.rs
tests/source/imports_granularity_one.rs
tests/target/imports_granularity_one.rs

Somehow the merge of #4680 didn't work out, and the commit doesn't appear in the history of the current `master` branch.
My guess is that this wasn't intended, and the expectation was that the new `One` option would become available, so this PR contains the original commit cherry-picked onto the latest `master`, with no changes.
@calebcartwright @magurotuna FYI.

Implement `One` option for imports_granularity (#4669) (Repeat PR)

---

docs/index.html

Added a title tag since the document currently has no title set.
It seems that the h1 tag is showing up in the search results.

Add <title> to docs

---

tests/source/issue_4257.rs
tests/source/issue_4322.rs
tests/source/issue_4943.rs
tests/source/issue_4954.rs
tests/target/issue_4257.rs
tests/target/issue_4322.rs
tests/target/issue_4954.rs

Hi there 👋  I wanted to tackle this task as a first time contributor.
Adding GAT-related tests for the following issues:
- https://github.com/rust-lang/rustfmt/issues/4257
- https://github.com/rust-lang/rustfmt/issues/4322
- https://github.com/rust-lang/rustfmt/issues/4943
- https://github.com/rust-lang/rustfmt/issues/4954
Thanks!
Closes #4969.

Add GAT related tests

---

Configurations.md
src/config/mod.rs
src/config/options.rs
src/expr.rs
tests/source/hex_literal_lower.rs
tests/source/hex_literal_upper.rs
tests/target/hex_literal_lower.rs
tests/target/hex_literal_preserve.rs
tests/target/hex_literal_upper.rs

A small feature to consistently case hexadecimal literals in your Rust code.

Feature: upper- or lowercase hexadecimal literals

---

src/comment.rs
tests/source/issue-3158.rs
tests/target/issue-3158.rs

Added test covering this. Chose to treat the code block
as rust if and only if all of the comma-separated attributes
are rust-valid. Chose to allow/preserve whitespace around commas
Fixes #3158

rustfmt doc code blocks with multiple comma-separated attributes

---

Configurations.md
src/config/mod.rs
src/config/options.rs
src/expr.rs
src/formatting.rs
src/formatting/generated.rs
src/syntux/session.rs
src/test/mod.rs
tests/source/configs/format_generated_files/false.rs
tests/source/configs/format_generated_files/true.rs
tests/source/hex_literal_lower.rs
tests/source/hex_literal_upper.rs
tests/target/configs/format_generated_files/false.rs
tests/target/configs/format_generated_files/true.rs
tests/target/hex_literal_lower.rs
tests/target/hex_literal_preserve.rs
tests/target/hex_literal_upper.rs

Backport some changes

---

src/matches.rs
tests/source/match-block-trailing-comma.rs
tests/target/match-block-trailing-comma.rs

After making some changes to a guard on a match arm, I noticed that `rustfmt` was removing a comma from the end of the block even though I had  `match_block_trailing_comma` set to `true`. Here's an example program where you can see the behaviour:
```rust
fn main() {
let val = Some(5);
match val {
Some(abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ) if abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ < 1000 => {
println!("a");
},
Some(a) if a > 1000 => {
println!("b");
},
Some(_) => {
println!("c");
},
None => {
println!("d");
},
}
}
```
Running `rustfmt --emit stdout --config match_block_trailing_comma=true test.rs` on this file, you can see that all branches but the one where the guard needed to be wrapped keep the comma:
```rust
fn main() {
let val = Some(5);
match val { …
```

Trailing comma on match block goes missing when guard is on its own line

---

Configurations.md

Continuing on from discussion in https://github.com/rust-lang/rustfmt/issues/4948
This PR improves both the idempotentency test and the users comprehension of the documentation.
condense_wildcard_suffixes is an example where this approach is already used.
I'm not sure if the new code added to the noop cases should also be added to the non-noop cases as well. condense_wildcard_suffixes doesnt do that, so I did the same. Let me know if I should change that though.
I havent touched configuration that sorts elements into alphabetical order, as the unsorted elements in the noop case should demonstrate that its not touched by rustfmt just fine.
`brace_style: SameLineWhere` doesn't seem to fit its own description , so I just skipped that one...

In Configurations.md demonstrate both cases for noop selections

---

src/patterns.rs
tests/target/issue-5005/minimum_example.rs

fixes #5005 
This was very similar to #4964 and the fix was to extract and pass along
the ``qself`` of the ``PatKind::TupleStruct``

Prevent removal of qualified path for tuple struct inside macro

---

src/attr.rs
tests/source/issue-4984/minimum_example.rs
tests/source/issue-4984/multi_line_derive.rs
tests/source/issue-4984/multiple_comments_within.rs
tests/target/issue-4984/minimum_example.rs
tests/target/issue-4984/multi_line_derive.rs
tests/target/issue-4984/multiple_comments_within.rs
tests/target/issue-4984/should_not_change.rs

Resolves #4984
When a block comment comes before the traits of a derive attribute
the string "#[derive(" is included as part of the the pre snippet, and as
a result gets duplicated.
For example:
#[derive(/*Debug, */Clone)] -> #[derive(#[derive(/*Debug, */ Clone)]
Now the string "#[derive(" is trimmed from the start of the pre snippet
before looking for the pre comment.

Handle block comment before Traits in derive attribute (issue 4984)

---

README.md

These seemed useful to backport even if @calebcartwright is rewriting most of the readme.
* https://github.com/rust-lang/rustfmt/pull/3926
* https://github.com/rust-lang/rustfmt/pull/4554
* https://github.com/rust-lang/rustfmt/pull/4464
Just for the protocol, these here I did not backport:
* https://github.com/rust-lang/rustfmt/pull/4250
* https://github.com/rust-lang/rustfmt/pull/4345
* https://github.com/rust-lang/rustfmt/pull/4361

Backport minor readme changes

---

src/expr.rs
tests/target/issue-5012/trailing_comma_always.rs
tests/target/issue-5012/trailing_comma_never.rs
tests/target/issue_4850.rs

Resolves #5012
Resolves #4850
This behavior was noticed when using the ``trailing_comma = "Never"``
configuration option (5012).
This behavior was also noticed when using default configurations (4850).
rustfmt would add a trailing space to where clause bounds that had an
empty right hand side.
Now no trailing space is added to the end of these where clause bounds.

Prevent trailing whitespace in where clause bound predicate

---

Contributing.md
src/bin/main.rs
src/format-diff/main.rs
src/git-rustfmt/main.rs

This backports
* #4458
A comment in there sounded like a backport was intended.

Backport "Use a custom env var for log settings intead of default RUST_LOG"

---

Configurations.md

This backports 
* #4096 
with a few merge conflicts fixed.

Backport "Link tracking issues in Configurations.md"

---

src/items.rs
src/visitor.rs

Diff looks noisier than it actually is. We had multiple duplicative checks for the `Impl` item kind with if/else and `unreachable!` blocks to get at the underlying boxed Impl which added both noise and extra indentation layers. This change instead grabs the Impl at the top and passes it down to the underlying functions.
Also includes a first step at trying to simplify the reordering logic of assoc items in impls in prep for extracting out some reusable bits to support traits as well.

refactor/cleanup duplicative Impl handling code

---

src/lists.rs
tests/source/issue-4909/wrap-comments-not-normalized.rs
tests/source/issue-4909/wrap-comments-true.rs
tests/target/issue-4909/wrap-comments-false.rs
tests/target/issue-4909/wrap-comments-not-normalized.rs
tests/target/issue-4909/wrap-comments-true.rs

Fixes #4909
This issue was that a multi-line comment starting on a new line after the last item of a list is considered a post-comment.
This adds a check for whether a post-comment in a list starts with a newline and doesn't force the comment to become a block comment in that case.

Preserve normalized comments after last list item

---

Configurations.md

Follow-up to https://github.com/rust-lang/rustfmt/pull/5052.
I went through all the unstable opts in Configurations.md, reopened some existing tracking issues, and created new ones where necessary.
I also verified the stable yes/no annotations actually match the code, they did.
I noticed the following options from the code do not appear in configurations.md, @calebcartwright let me know whether that should be changed.
* file_lines ("Lines to format; this is not supported in rustfmt.toml and can only be specified  via the --file-lines option")
* newline_style ("Unix or Windows line endings")
* verbose ("How much to information to emit to the user")
* width_heuristics ("'small' heuristic values")

Add a few missing tracking issues in Configurations.md

---

src/comment.rs
tests/target/issue-5095.rs

Changes the behaviour of `wrap_comments` to ignore reference link lines.
I've put this `Regex` behind a `lazy_static` to avoid compiling it each time `has_url` is run (every comment line?) which is relatively slow:
* Initialising the `Regex` where it is used:
```
test has_url ... bench:      33,346 ns/iter (+/- 17,023)
```
* Using a global with `lazy_static`:
```
test has_url ... bench:         141 ns/iter (+/- 2)
```
There's a few more places this optimisation can be applied - I'd be happy to open a follow-up PR to change them all if you're happy with the approach :+1:
Fixes #5095, #4933.
---
* fix: do not wrap reference-style doc links (d85fd07e)
Prevents wrap_comments from incorrectly wrapping reference-style doc links.

fix: do not wrap reference-style doc links

---

README.md

Just a minor improvement: When reading "as we approach a 1.0 release" on a project that is already past 1.0, one is tempted to discard the paragraph as outdated, although it really isn't in this case.

Minor readme tweak

---

tests/source/comments-in-lists/wrap-comments-not-normalized.rs
tests/source/comments-in-lists/wrap-comments-true.rs
tests/target/comments-in-lists/format-doc-comments.rs
tests/target/comments-in-lists/wrap-comments-false.rs
tests/target/comments-in-lists/wrap-comments-not-normalized.rs
tests/target/comments-in-lists/wrap-comments-true.rs

Add more tests for comments in lists

---

.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/windows.yml

Trying to see if I can toggle the ``CFG_RELEASE_CHANNEL`` in CI to test some code that is only reachable when ``CFG_RELEASE_CHANNEL`` is not set to ``nightly``

Toggle CFG_RELEASE_CHANNEL between nightly and stable on Windows, Linux, and Mac CI

---

config_proc_macro/src/lib.rs
src/config/mod.rs
src/syntux/session.rs
src/test/mod.rs

Adds the ``nightly_only_test`` and ``stable_only_test`` attribute macros
that prevent or allow certain tests to compile on nightly and stable
respectively. This is achieved through conditionally outputting the
tests TokenStream.
If CFG_RELEASE_CHANNEL is not set, it's assumed that we're running in a
nightly environment.
To mark a test as nightly only:
#[nightly_only_test]
#[test]
fn only_run_on_nightly() {
...
}
To mark a test a stable only:
#[stable_only_test]
#[test]
fn only_run_on_stable() {
...
}

Conditionally compile tests based on CFG_RELEASE_CHANNEL env var

---

src/expr.rs
src/items.rs
src/macros.rs
src/types.rs

We currently utilize generics, primarily bound on our `Rewrite` trait, when formatting a RHS (e.g. on an assignment) which makes perfect sense given the high number of expression variants, bounds, etc. that can be encountered. However, in doing so the functions that actually define the logic which handles orchestrating the rewriting of the RHS and then combining it with the LHS are missing various data points from the respective AST nodes.
That's not been a problem historically, however, we have a few outstanding requests for more optionality around formatting of chains including formatting results which knowingly exceed the `max_width` boundary. In order to support these use cases while still being able to block indent the start of the RHS some additional AST metadata will be needed, and …

maintain more AST info when formatting a RHS

---

src/comment.rs
tests/source/issue-5088/deeply_nested_long_comment_wrap_comments_true.rs
tests/source/issue-5088/start_with_empty_comment_very_long_itemized_block_wrap_comments_true.rs
tests/source/issue-5088/very_long_comment_wrap_comments_true.rs
tests/target/issue-5088/deeply_nested_long_comment_wrap_comments_false.rs
tests/target/issue-5088/deeply_nested_long_comment_wrap_comments_true.rs
tests/target/issue-5088/multi_line_itemized_block_wrap_comments_false.rs
tests/target/issue-5088/multi_line_itemized_block_wrap_comments_true.rs
tests/target/issue-5088/multi_line_text_with_itemized_block_wrap_comments_false.rs
tests/target/issue-5088/multi_line_text_with_itemized_block_wrap_comments_true.rs
tests/target/issue-5088/single_line_itemized_block_wrap_comments_false.rs
tests/target/issue-5088/single_line_itemized_block_wrap_comments_true.rs
tests/target/issue-5088/start_with_empty_comment_very_long_itemized_block_wrap_comments_false.rs
tests/target/issue-5088/start_with_empty_comment_very_long_itemized_block_wrap_comments_true.rs
tests/target/issue-5088/start_with_empty_comment_wrap_comments_false.rs
tests/target/issue-5088/start_with_empty_comment_wrap_comments_true.rs
tests/target/issue-5088/very_long_comment_wrap_comments_false.rs
tests/target/issue-5088/very_long_comment_wrap_comments_true.rs

Fixes #5088
Previously, ``rustfmt`` would add a new comment line anytime it reformatted
an itemized block within a comment. This would lead to ``rustfmt`` adding
empty comments with trailing whitespace.
Now, new comment lines are only added if the original comment spanned
multiple lines, if the comment needs to be wrapped, or if the comment
originally started with an empty comment line.

Determine when new comment lines are needed for itemized blocks

---

src/patterns.rs
tests/target/issue-5066/multi_line_struct_trailing_comma_always_struct_lit_width_0.rs
tests/target/issue-5066/multi_line_struct_trailing_comma_never_struct_lit_width_0.rs
tests/target/issue-5066/multi_line_struct_with_trailing_comma_always.rs
tests/target/issue-5066/multi_line_struct_with_trailing_comma_never.rs
tests/target/issue-5066/with_trailing_comma_always.rs
tests/target/issue-5066/with_trailing_comma_never.rs

Fixes #5066
When a struct pattern that contained a ".." was formatted, it was
assumed that a trailing comma should always be added if the struct
fields weren't formatted vertically.
Now, a trailing comma is only added if not already included in the
reformatted struct fields.

Prevent duplicate comma when formatting struct pattern with ".."

---

src/closures.rs
tests/source/async_block.rs
tests/target/async_block.rs

Fixes #5149.
Previously rustfmt would produce `async static || ...` which is not valid syntax. The ordering that rustc accepts is `static async || ...`.

Fix static async closure qualifier order

---

src/expr.rs
tests/target/issue-5151/minimum_example.rs

Fixes #5151
Details about the qualified path are now passed along so that rustfmt
can include them when formatting struct literal expressions

Retain qualified path when rewriting struct literal expressions

---

src/matches.rs
tests/source/match.rs
tests/target/match.rs

This is a backport of #4124.
Fixes #4109

Do not flatten match arm block with leading attributes

---

src/items.rs
tests/target/issue-5125/attributes_in_formal_fuction_parameter.rs
tests/target/issue-5125/long_parameter_in_different_positions.rs
tests/target/issue-5125/minimum_example.rs
tests/target/issue-5125/with_leading_and_inline_comments.rs

Fixes #5125
Previously, a newline was always added, even if the parameter name was
not preceded by any param attrs.
Now a newline is only added if there were param attrs.

Prevent adding trailing whitespace when rewriting ast::Param

---

src/string.rs
tests/source/issue-5023.rs
tests/target/issue-5023.rs

Handle non-ascii character at boundary

---

src/lists.rs
tests/source/issue-5042/multi-line_comment_with_trailing_comma.rs
tests/source/issue-5042/multi-line_comment_without_trailing_comma.rs
tests/source/issue-5042/single-line_comment_with_trailing_comma.rs
tests/source/issue-5042/single-line_comment_without_trailing_comma.rs
tests/target/issue-5042/multi-line_comment_with_trailing_comma.rs
tests/target/issue-5042/multi-line_comment_without_trailing_comma.rs
tests/target/issue-5042/single-line_comment_with_trailing_comma.rs
tests/target/issue-5042/single-line_comment_without_trailing_comma.rs

Fixes #5042
Previously, trailing commas were removed from the last inline comment.
This lead to rustfmt refusing to format code snippets because
the original comment did not match the rewritten comment.
Now, when rustfmt extracts the last inline comment it leaves trailing
separators alone. Rustfmt does not need to remove these separators
because they are commented out.

Retain trailing separator when extracting the last inline post comment

---

CHANGELOG.md
src/utils.rs
tests/source/issue-4036/one.rs
tests/source/issue-4036/three.rs
tests/source/issue-4036/two.rs
tests/target/issue-4036/one.rs
tests/target/issue-4036/three.rs
tests/target/issue-4036/two.rs

Fix incorrect string indentation in macro defs with `format_strings`

---

src/bin/main.rs
tests/rustfmt/main.rs

This PR removes the `rustfmt` executable path from usage string.
Fixes #5214

chore(rustfmt): remove executable path from usage string

---

src/comment.rs
tests/source/issue-5157/indented_itemized_markdown_blockquote.rs
tests/source/issue-5157/nested_itemized_markdown_blockquote.rs
tests/source/issue-5157/support_itemized_markdown_blockquote.rs
tests/target/issue-5157/indented_itemized_markdown_blockquote.rs
tests/target/issue-5157/nested_itemized_markdown_blockquote.rs
tests/target/issue-5157/support_itemized_markdown_blockquote.rs

Fixes #5157
Doc comments support markdown, but rustfmt didn't previously assign any
semantic value to leading ``'> '`` in comments. This lead to poor formatting
when using ``wrap_comments=true``.
Now, rustfmt treats block quotes as itemized blocks, which greatly
improves how block quotes are formatted when ``wrap_comments=true``.

Leverage itemized blocks to support formatting markdown block quotes

---

src/bin/main.rs
src/config/mod.rs

Handles #5188 
```
$ cargo b --bin rustfmt && HOME=/root ./target/debug/rustfmt --check /dev/null
Permission denied (os error 13)
```
```
$ cargo b --bin rustfmt && HOME=/root ./target/debug/rustfmt --check /dev/null
Failed to get metadata for config file "/root/.rustfmt.toml": Permission denied (os error 13)
```

Add context to get_toml_path() error

---

config_proc_macro/src/utils.rs
src/test/mod.rs
tests/cargo-fmt/main.rs

simpler and includes more code!

Use cargo-fmt in self_tests

---

tests/rustfmt/main.rs

Minor fallout from #5216 being merged prior to #5212, since the former included a test function that wasn't properly formatted but also wasn't part of the self tests until the latter was introduced

fix formatting in new test

---

.github/workflows/linux.yml
src/ignore_path.rs
src/lib.rs

Our CI has been silently generating warnings about unused imports on the one matrix leg where we trick it into thinking it's running on stable. That was happening because we had imports at the test mod level which were used by the single, nightly-only test contained within that mod.
This caused a bit of a hiccup on the beta build, so both fixing the underlying issue and adding CI checks so that it won't happen again

fix unused test imports on non-nightly, prevent regression

---

src/parse/session.rs
src/test/mod_resolver.rs
tests/mod-resolver/issue-5198/a.rs
tests/mod-resolver/issue-5198/lib.rs
tests/mod-resolver/issue-5198/lib/b.rs
tests/mod-resolver/issue-5198/lib/c/d.rs
tests/mod-resolver/issue-5198/lib/c/d/explanation.txt
tests/mod-resolver/issue-5198/lib/c/d/f.rs
tests/mod-resolver/issue-5198/lib/c/d/g/mod.rs
tests/mod-resolver/issue-5198/lib/c/e.rs
tests/mod-resolver/issue-5198/lib/c/mod.rs
tests/mod-resolver/issue-5198/lib/explanation.txt

We only want to fall back if two conditions are met:
1) Initial module resolution is performed relative to some nested directory.
2) Module resolution fails because of a ``ModError::FileNotFound`` error.
When these conditions are met we can try to fallback to searching for the module's file relative to the ``dir_path`` instead of the nested relative directory.
Fixes #5198
As demonstrated by 5198, it's possible that a directory name conflicts with a rust file name. For example, ``src/lib/`` and ``src/lib.rs``.
If ``src/lib.rs`` references an external module like ``mod foo;``, then module resolution will try to resolve ``foo`` to ``src/lib/foo.rs`` or ``src/lib/foo/mod.rs``. Module resolution would fail with a file not found error if the ``foo`` module were defined at ``src/foo.rs``.
When …

fallback to dir_path when relative external mod resolution fails

---

src/comment.rs
tests/source/issue-5238/markdown_header_wrap_comments_false.rs
tests/source/issue-5238/markdown_header_wrap_comments_true.rs
tests/target/issue-5238/markdown_header_wrap_comments_false.rs
tests/target/issue-5238/markdown_header_wrap_comments_true.rs

Fixes #5238
A markdown header is defined by a string that starts with `#`.
Previously, rustfmt would wrap long markdown headers when
`wrap_comments=true`. This lead to issues when rendering these headers
in HTML using rustdoc.
Now, rustfmt leaves markdown headers alone when wrapping comments.

Prevent wrapping markdown headers in doc comments

---

src/imports.rs
tests/source/imports_granularity_module.rs
tests/target/imports_granularity_module.rs

Closes #4681
(unintentionally) ports #4716 from `rustfmt-2.0.0-rc.2` to `master`, with some additional refactoring.
It looks like this issue was already fixed, but was then lost in the `rustfmt-2.0.0-rc.2` branch on this commit: https://github.com/rust-lang/rustfmt/commit/0e908555273391bc3aba087abae72791451fd84a
I implemented this separately but came up with a satisfyingly similar implementation - I've read the review comments on the original PR, so I don't think there should be much to add, but do let me know if anything needs changing!

fix: imports_granularity module with path containing self

---

Configurations.md
src/test/configuration_snippet.rs

This PR makes two changes:
* Fixes the tracking issue link for `skip_children` to point to the correct tracking issue
* Adds a new test to ensure tracking links match the displayed reference number.

Fix and verify tracking issue links

---

src/parse/session.rs

Obviously not utilized yet, however, figured we could go ahead and get this incorporated.
Pulling it out separately from some chain efforts I'd been working on as it is sufficiently general purpose and would ostensibly be utilized in supporting some similar requests for greater flexibility/control over how call args (and potentially fn params) are formatted regarding their relative line positioning/wrapping
r? @ytmimi

Add a minor utility function for relative span positions

---

src/items.rs
tests/target/issue_5273.rs

Fixes #5273
Previously, rustfmt searched for the start of a struct body after the opening `{`. In most cases this works just fine, but const values can also be defined inside `{ }`, which lead to issues when rewriting the struct body (as highlighted by the linked issue).
Now, rustfmt will search for the `{` after the generic argument list to guarantee that the `{` it finds is the start of the struct body.

Search for struct body span after any generic arguments

---

Configurations.md
src/config/mod.rs
src/overflow.rs
tests/source/configs/short_array_element_width_threshold/10.rs
tests/source/configs/short_array_element_width_threshold/20.rs
tests/source/configs/short_array_element_width_threshold/greater_than_max_width.rs
tests/target/configs/short_array_element_width_threshold/10.rs
tests/target/configs/short_array_element_width_threshold/20.rs
tests/target/configs/short_array_element_width_threshold/greater_than_max_width.rs

Allow custom short item threshold values via config
Closes #5225

Add `short_item_threshold` config option

---

src/attr.rs
tests/source/issue-5270/merge_derives_true.rs
tests/target/issue-5270/merge_derives_false.rs
tests/target/issue-5270/merge_derives_true.rs

Fixes #5270
Previously, rustfmt only checked the `merge_derives` configuration value
to determine if it should merge_derives. This lead to derives being
merged even when annotated with the `rustfmt::skip` attribute.
Now, rustfmt also checks if derives are explicitly being skipped in the
current context via the `rustfmt::skip` attribute.

Honor `#[rustfmt::skip::attributes(derive)]` attribute

---

src/macros.rs
tests/source/extern.rs
tests/target/extern.rs

Fixes #5281.
```console
$ echo 'extern { x!(-); x!(x); }' | cargo run --bin rustfmt
extern "C" {
x!(-)
x!(x);
}
```
```console
$ echo 'extern { x!(-); x!(x); }' | cargo run --bin rustfmt
extern "C" {
x!(-);
x!(x);
}
```

Preserve semicolon after macro call inside foreign mod

---

Cargo.lock
Cargo.toml
src/cargo-fmt/main.rs
src/cargo-fmt/test/mod.rs
src/format-diff/main.rs

StructOpt features have been integrated into clap v3, and it is now in maintenance mode.
The maintainer recommends migrating away from it: https://github.com/TeXitoi/structopt/issues/525
This touches argument parsing for `cargo fmt`. The behavior was kept the same.
There are visual differences in the `cargo fmt --help` output.
`cargo fmt --help` before:
```
This utility formats all bin and lib files of the current crate using rustfmt.
USAGE:
cargo fmt [FLAGS] [OPTIONS] [-- <rustfmt_options>...]
FLAGS:
--check      Run rustfmt in check mode
--all        Format all packages, and also their local path-based dependencies
-h, --help       Prints help information
-q, --quiet      No output printed to stdout
-v, --verbose    Use verbose output
--version    Print rustfmt version and exit
OPTIONS: …
```

Replace `structopt` dependency by `clap`

---

Configurations.md
tests/source/configs/group_imports/StdExternalCrate-non_consecutive.rs
tests/target/configs/group_imports/StdExternalCrate-non_consecutive.rs

Closes #4767
Clarifies the documented configuration options for `group_imports`, to make clear how non-consecutive imports are handled (they aren't).
This was raised in #4767 as a potential bug, so updating docs and tests to make clear it is expected behaviour.

group_imports: test and document non-consecutive imports

---

src/imports.rs
src/reorder.rs
tests/source/issue-5030.rs
tests/target/issue-5030.rs

Driving #5031 to completion - the original PR has been stale for a month, so I have:
- rebased on master
- applied the outstanding feedback
- added an additional test case (happy to add more if required)
Will squash once ready for merge.

Preserve attributes for imports_granularity=Item

---

src/expr.rs
src/formatting.rs
src/rewrite.rs
src/shape.rs
src/visitor.rs
tests/source/performance/issue-4476.rs
tests/source/performance/issue-5128.rs
tests/target/performance/issue-4476.rs
tests/target/performance/issue-4867.rs
tests/target/performance/issue-5128.rs

fix #4476 
fix #4867
fix #5128 
The problem in those issues is, when `max_width` is tight, rustfmt should check all possible formattings, which is exponential relative to input size. By [memoization](https://en.wikipedia.org/wiki/Memoization) of `format_expr` function, worst case execution time becomes `O(n*max_width^3)`. I tried codes in those issues and it completed in a fraction of second.

Fix exponential execution time by memoizing format_expr

---

.github/workflows/integration.yml
.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/rustdoc_check.yml
.github/workflows/upload-assets.yml
.github/workflows/windows.yml

The v2 implementation uses Node 12, which is end-of-life on April 30, 2022. See https://nodejs.org/en/about/releases/. Update to v3, which is based on Node 16 whose support lasts until April 30, 2024.
They made this a major version change (v2 to v3) because old GitHub Enterprise versions aren't necessarily compatible with Node 16, but for github.com-supplied runners (SaaS) there is no other practical difference.

Update GitHub Actions actions/checkout@v2 to v3

---

src/comment.rs
src/string.rs
tests/source/issue-5260.rs
tests/target/issue-5260.rs

Fixes #5260 by checking if it is part of a type '::'
Add possibility to run single test e.g. `TEST_FILE=5250 cargo test system` to run test files containing 5250

Fixes #5260

---

src/cargo-fmt/main.rs

Follow up https://github.com/rust-lang/rust/pull/96861.
This PR uses the traits added to the Rust 2021 Edition prelude.
> The `TryInto`, `TryFrom` and `FromIterator` traits are now part of the prelude.
https://doc.rust-lang.org/edition-guide/rust-2021/prelude.html

Use the traits added to the Rust 2021 Edition prelude

---

tests/target/issue_3937.rs

ref #3937
~~It's unclear which change fixed the `format_code_in_doc_comments=true`
issue brought up in this issue, however~~ I'm unable to reproduce the
error on the current master.
The added test cases should serve to prevent a regression.
Edit: ref #4420 describes the `format_code_in_doc_comments=true` issue and #5091 fixed that issue, so it's also responsible for fixing the `format_code_in_doc_comments=true` behavior described in #3937

Add test for issue 3937

---

src/imports.rs
tests/source/imports_granularity_crate.rs
tests/source/imports_granularity_item.rs
tests/source/imports_granularity_module.rs
tests/source/imports_granularity_one.rs
tests/target/imports_granularity_crate.rs
tests/target/imports_granularity_item.rs
tests/target/imports_granularity_module.rs
tests/target/imports_granularity_one.rs

import_granularity: Don't normalize imports with comments

---

Configurations.md

For `rustfmt 1.4.38-stable (fe5b13d6 2022-05-18)`, if I run:
```bash
rustfmt --unstable-features
```
I get the following error:
```
Unrecognised option: 'unstable-features'
```
The "[Configuring Rustfmt](https://github.com/rust-lang/rustfmt/blob/243cec7a0b9cc0ba3fba6e5ed849b0635f3496db/README.md#configuring-rustfmt)" section of the `README.md` file says that in order to enable unstable options, it is necessary to use a nightly toolchain.
In this changeset, I suggest to copy that information as is to the "Configuring Rustfmt" document (i.e., to the `Configurations.md` file).

Make it clear that unstable options are only available on a nightly toolchain

---

CHANGELOG.md

from revision  v1.4.38..2d9bc460

Updated Unreleased CHANGELOG entries

---

src/formatting.rs
src/test/mod.rs

fix handling of inner ignore attributes on stdin

---

src/test/mod.rs

Context: `rustc` added a few month ago `--check-cfg` support and enable it in the `rust-lang/rust` repo for every build.
I found out that `rustfmt` has a `cfg!(release)` condition that was triggering the unstable `unexpected_cfgs` lint. The problem is that nothing (nor `rustc`, nor `cargo`, or anything` is setting the `release` cfg.
This PR removes the code behind the cfg. I have tested the patch with and without `--release`, with and without running the tests.

Remove useless conditional compilation

---

ci/integration.sh

There was recently an issue where `cargo install` was installing a newer version of a dependency than the one listed in our Cargo.toml. The newer version added deprecation warnings that caused our continuous integration tests to break.
As mentioned in the `cargo help install` docs, passing the `--locked` flag should force cargo to use the `Cargo.lock` file included with the repository.
ref: https://github.com/rust-lang/rustfmt/pull/5384#issuecomment-1154158644

Pass `--locked` when installing rustfmt in integration tests

---

Cargo.toml

By setting this value in the Cargo.toml rust-analyzer understands that rustfmt uses compiler-internals using `extern crate`.
This is a universal step that all developers will need to take in order to get better type hints and code completion suggestions for compiler-internals in their editor.
**Note**: users will also need to install the `rustc-dev` component [via rustup](https://rust-lang.github.io/rustup/concepts/components.html) and add the following to their rust-analyzer configuration:
```json
{
"rust-analyzer.rustcSource": "discover",
"rust-analyzer.updates.channel": "nightly"
}
```

Set `package.metadata.rust-analyzer.rustc_private=true` in Cargo.toml

---

src/cargo-fmt/main.rs

Fixes #5395
In PR #5239 we switched from using `structopt` to `clap`. It seems that the default behavior for `clap` is to override the `--version` flag, which prevented our custom version display code from running.
The fix as outlined in https://github.com/clap-rs/clap/issues/3405 was to set
`#[clap(global_setting(AppSettings::NoAutoVersion))]` to prevent clap from setting its own default behavior for the `--version` flag.

Fix issue where `cargo fmt --version` would not display version info

---

ci/build_and_test.bat
ci/build_and_test.sh
config_proc_macro/src/lib.rs
tests/cargo-fmt/main.rs
tests/rustfmt/main.rs

There are some tests in the rustfmt test suite that are ignored by default. I believe these tests are ignored because they have caused issues with the the `rust-lang/rust` test suite.
However, we recently experienced an issue (#5395) that would have been avoided had these tests been running.
With the introduction of the new `#[rustfmt_only_ci_test]` attribute macro we can run these tests when the `RUSTFMT_CI` environment variable is set, which will presumably only be set during rustfmts CI runs. When the environment variable is not set the `#[rustfmt_only_ci_test]` will be replaced with an `#[ignore]`.

Allow `#[ignore]` tests to run in rustfmt's test suite

---

Cargo.lock
Cargo.toml
config_proc_macro/Cargo.lock
config_proc_macro/Cargo.toml
config_proc_macro/src/attrs.rs
config_proc_macro/src/item_enum.rs
config_proc_macro/tests/smoke.rs
src/config/config_type.rs
src/config/mod.rs

First pass at #5378
Adds new functionality to the existing `config_proc_macro` crate, such that enums used for configuration can have their variants annotated as `unstable_variant`:
```rust
#[config_type]
/// How to merge imports.
pub enum ImportGranularity {
/// Do not merge imports.
Preserve,
/// Use one `use` statement per crate.
Crate,
...
/// Adapt import granularity, based on internal heuristics.
#[unstable_variant]
Adaptive
}
```
This will be checked upon loading config, and a warning emitted similar to using current unstable options on stable toolchain:
```log
Warning: can't set `imports_granularity = Adaptive`, unstable variants are only available in nightly channel.
```

config_type: add unstable_variant attribute

---

src/test/mod.rs

Follow-up to https://github.com/rust-lang/rustfmt/pull/5375 where I forgot to remove the same useless condition compilation 5 lines below 😅.

Remove useless conditional compilation - 2

---

tests/target/issue-2534/format_macro_matchers_false.rs
tests/target/issue-2534/format_macro_matchers_true.rs

Closes #2534
The behavior described in the original issue can no longer be reproduced. The tests show that to be the case regardless of if `format_macro_matchers` is `true` or `false`.

Add tests for issue 2534

---

tests/cargo-fmt/main.rs
tests/cargo-fmt/source/issue_3164/Cargo.toml
tests/cargo-fmt/source/issue_3164/src/main.rs
tests/rustfmt/main.rs

Closes #3164
Show that when `error_on_line_overflow=true` is set in the rustfmt.toml that an error message is written to stderr.

test for issue 3164

---

tests/target/issue_4350.rs

Closes #4350
It's unclear which commit resolved this, but the original issue is not longer reproducible.

Add test for issue 4350

---

tests/source/issue-4643.rs
tests/target/issue-4643.rs

* Two tests were added, in order to ensure that the PR #5446 successfully addresses the issue at hand as well.

Improvements: Adding tests for the issue-4643.

---

src/attr.rs
src/macros.rs
src/skip.rs
src/visitor.rs

Follow up from https://github.com/rust-lang/rustfmt/pull/5347#discussion_r895000579 in discussion with @ytmimi 
Refactors the way named items are skipped such that:
- skipping each item is constant time
- implementation is the same for attributes/macros
- either all items can be skipped, or a set of named items
This should result in no change in behaviour.

feat: nicer skip context for macro/attribute

---

src/chains.rs

Another step in the saga to support a variety of additional chain scenarios (overflows, dev discretion over line breaks, etc.)
Trying to break things up into atomic batches as small as possible to make it easier for review, as the total diff to support the relevant issues will end up being quite large and I suspect require some mental gymnastics. Feel that will be easier in smaller, more easily digested chunks. This is perhaps the last batch that will be relatively small though, and does contain a couple unused pieces that are prep for the next step, but aren't really utilized/may not be clear why the exist just yet.
r? @ytmimi

more chain updates

---

.github/workflows/check_diff.yml
ci/check_diff.sh

This new action is intended to help us maintainers determine when feature branches cause breaking formatting changes by running rustfmt (master) and the feature branch on various rust repositories.
Over time I expect the list of checked projects to increase.
With this action in place we can more  easily test that a new feature or bug fix doesn't introduce breaking changes. Although this action needs to be manually triggered right now, we might consider adding it to our CI runs in the future.
To run the new action we can head over to the actions tab and click `Run workflow` to supply the inputs that the script expects.
For example to test out the proposed `fn_call_layout` changes (#5337) you could supply the following form arguments.
```
https://github.com/ytmimi/rustfmt.git
issue_5218
``` …

Add GitHub Action to test master rustfmt formatting vs a feature branch

---

.github/workflows/integration.yml
ci/integration.sh

The failure crate has been deprecated and the integration failure no longer gets fixed, so removed.
This also clean-ups Git repo URLs in integration tests.
Signed-off-by: Yuki Okushi <jtitor@2k36.org>

Remove `failure` from integration test

---

src/items.rs
tests/target/issue_5668.rs

Fixes #5668 
r? @ytmimi 
Working on doing a sync today but wanted to get this trivial fix in as part of it. Should be able to start cranking through the backlog of PRs afterwards

correct span for structs with const generics

---

Configurations.md
src/comment.rs

Cf: https://github.com/rust-lang/rustfmt/issues/5634

Document which comments are excluded from wrapping

---

tests/source/issue-5586.rs
tests/target/issue-5586.rs

closes #5586
Show that there are no idempotency issues when using `version=Two`.

issue #5586 - added tests

---

src/comment.rs
tests/source/issue-5234.rs
tests/target/issue-5234.rs

Fixes #5234
Suggested fix is by trimming the code block, as discussed in (now obsolete) PR #4902.

Fix for handling empty code block in doc comment

---

.github/workflows/upload-assets.yml

actions-rs is currently inactive and has an issue like https://github.com/actions-rs/cargo/issues/216, we could directly invoke Cargo instead.
Signed-off-by: Yuki Okushi <jtitor@2k36.org>

Remove use of actions-rs

---

src/comment.rs
tests/config/issue-4041.toml
tests/source/issue-4041.rs
tests/target/issue-4041.rs

Lists doc comments fix4041

---

src/expr.rs
tests/source/issue-5488.rs
tests/target/issue-5488.rs

Closes #5488
Fix for #5488. Before applying shorthand initialization for structs,
check if identifier is a literal (e.g. tuple struct). If yes, then do
not apply short hand initialization.
Added test case to validate the changes for the fix.

Fix #5488 - prevent shorthand init for tuple struct

---

src/items.rs
tests/target/issue_5691.rs

use correct span for struct generics

---

src/parse/macros/cfg_if.rs
tests/rustfmt/main.rs
tests/target/issue_5728.rs

Fixes #5728
Previously we were ignoring the diagnostic error, which lead to the ICE. Now we properly cancel the error.

Prevent ICE when calling parse_attribute in parse_cfg_if_inner

---

src/parse/session.rs

Pass color option into default_handler() and use that to determine the ColorConfig to use when creating EmitterWriter for stderr in parse session in the case where stderr supports color.
Fixes #5717.

Honor --color option when emitting errors from parse session

---

src/config/options.rs

This patch fixes the broken markdown that can be seen [here](https://doc.rust-lang.org/nightly/nightly-rustc/rustfmt_nightly/enum.NewlineStyle.html#variant.Unix).
It has been found by a [new rustdoc lint](https://github.com/rust-lang/rust/pull/105848) and this patch will be required to deny the lint in the rust-lang/rust repository.

Add a friend for lonely backtick

---

Cargo.lock
Cargo.toml

The `rustc-workspace-hack` dependency was removed in https://github.com/rust-lang/rust/pull/109133 and should no longer be needed.

Remove rustc-workspace-hack

---

src/overflow.rs
src/types.rs
tests/target/doc-of-generic-item.rs

Recover comments between attrs and generic param

---

Contributing.md
README.md

also add "run from source" in contributing.md
@calebcartwright PTAL

doc: remove installing from source

---

Cargo.lock
Cargo.toml
config_proc_macro/Cargo.lock
config_proc_macro/Cargo.toml
config_proc_macro/src/attrs.rs
src/attr/doc_comment.rs
src/cargo-fmt/main.rs
src/formatting.rs
src/lib.rs
src/macros.rs
src/pairs.rs

* Updates clap from 3.X to 4.X. This part is partially reviewed in https://github.com/rust-lang/rust/pull/110077/files#r1161312743.
* Bumped `serde` and `thiserror`.
* Updated `config_proc_macro` to use `syn` 2.0
* Removed `derive_new`: all usages of it didn't need a procedural macro, and it was trivial to replace them with manual impls, so I did.

Bump dependencies and update crates to use `syn` 2.0

---

src/parse/macros/cfg_if.rs
tests/rustfmt/main.rs
tests/target/issue_5729.rs

Fixes #5729
[`parse_attribute` will panic if the first token is not a `#`](https://github.com/rust-lang/rust/blob/b869e84e581612f4a30a4bca63bd9e90e9a17003/compiler/rustc_parse/src/parser/attr.rs#L122). To prevent this we return early instead of trying to parse an invalid attribute.

Prevent ICE when calling parse_attribute without an attribute

---

src/items.rs
tests/source/issue_5686.rs
tests/target/issue_5686.rs

Fixes #5686
For reference, explicit discriminants were proposed in [RFC-2363], and I believe the feature is stabilized. 
`ast::Variant` spans extend to include explicit discriminants when they are present.
Now we'll adjust the span of enum variants to exclude any explicit discriminant.
[RFC-2363]: https://rust-lang.github.io/rfcs/2363-arbitrary-enum-discriminant.html

Adjust enum variant spans to exclude any explicit discriminant

---

Cargo.lock
Cargo.toml
src/cargo-fmt/main.rs
src/cargo-fmt/test/targets.rs

Allows removing some duplicate dependencies in rust-lang/rust's Cargo.lock (except for `dirs`, that crate isn't depended upon anywhere else).

Update dependencies `cargo_metadata`, `env_logger` and `toml`

---

src/comment.rs
tests/source/itemized-blocks/no_wrap.rs
tests/source/itemized-blocks/wrap.rs
tests/target/itemized-blocks/no_wrap.rs
tests/target/itemized-blocks/wrap.rs

Handling of numbered markdown lists.

---

src/expr.rs
src/items.rs
tests/source/let_else.rs
tests/target/let_else.rs

ref #4914
r? @calebcartwright 
Implements `let-else` formatting based on the rules outlined in https://github.com/rust-lang/rust/pull/107312. The examples listed in the style guide are included as simple test cases to validate `let-else` formatting.
**Note** This PR does not implement a ["short" config for `let-else`](https://github.com/rust-lang/rustfmt/issues/5684).

Implement `let-else` formatting

---

Configurations.md
src/config/config_type.rs
src/config/mod.rs
src/config/options.rs
src/items.rs
tests/source/configs/single_line_let_else_max_width/100.rs
tests/source/configs/single_line_let_else_max_width/50.rs
tests/source/configs/single_line_let_else_max_width/zero.rs
tests/source/configs/use_small_heuristics/default.rs
tests/source/configs/use_small_heuristics/max.rs
tests/source/configs/use_small_heuristics/off.rs
tests/source/let_else.rs
tests/target/configs/single_line_let_else_max_width/100.rs
tests/target/configs/single_line_let_else_max_width/50.rs
tests/target/configs/single_line_let_else_max_width/zero.rs
tests/target/configs/use_small_heuristics/default.rs
tests/target/configs/use_small_heuristics/max.rs
tests/target/configs/use_small_heuristics/off.rs
tests/target/let_else.rs

This is a follow up PR to #5690
This allows users to configure the maximum length of a single line `let-else` statements. `let-else` statements that otherwise meet the requirements to be formatted on a single line ([as described by the style guide](https://github.com/rust-lang/rust/blob/master/src/doc/style-guide/src/statements.md#else-blocks-let-else-statements)) will have their divergent `else block` formatted over multiple lines if they exceed this length.

implement `single_line_let_else_max_width`

---

CHANGELOG.md
Cargo.lock
Cargo.toml

The versioning approach for rustfmt around minor vs. patch bumps has always been fairly nebulous. I've some thoughts on where we should try to go on that front, but for now, opting to stick with the typical model of bumping the minor version when there's something "significant". I also feel like knowing that let-else support is available from 1.6+ will be helpful vs. e.g. 1.5.4

prep v1.6.0 release

---

src/chains.rs
src/expr.rs
tests/source/issue-5791.rs
tests/target/issue-5791.rs

Rewrite float literals ending in dots with parens in method calls

---

src/config/macro_names.rs
tests/config/issue-5816.toml
tests/source/skip_macro_invocations/config_file.rs
tests/target/skip_macro_invocations/config_file.rs

fixes #5816
We need to keep the `FromStr` impl for `MacroSelector` (e.g. to support command line config args), so seems reasonable to just have the serde deserializer use that impl too.
I'm not sure whether there's a better/simpler approach to achieve that (e.g. an item-level serde attribute), but adding our own `Deserialize` impl seems trivial enough

handle skip_macro_invocations from config file

---

src/lib.rs

tested:
```
> echo "fn main() {}" | RUSTFMT_LOG=rustfmt=debug cargo run --bin rustfmt --
Compiling rustfmt-nightly v1.6.0 (/home/beef/rustfmt)
Finished dev [unoptimized + debuginfo] target(s) in 5.05s
Running `target/debug/rustfmt`
2023-07-06T05:22:03.430286Z DEBUG rustfmt_nightly::items: compute_budgets_for_params 7 Indent { block_indent: 0, alignment: 0 }, 0, SameLine
2023-07-06T05:22:03.430340Z DEBUG rustfmt_nightly::items: rewrite_fn_base: one_line_budget: 89, multi_line_budget: 95, param_indent: Indent { block_indent: 4, alignment: 0 }
2023-07-06T05:22:03.430420Z DEBUG rustfmt_nightly::formatting: track truncate: 14 2
fn main() {}
```
cc @ytmimi @calebcartwright

Actually use `tracing` for logging

---

.github/workflows/check_diff.yml
ci/check_diff.sh

A few fixes for the diff-check job. The first bullet below is the most impactful, and to my knowledge the current job is broken without it. The other two are mostly quality of life improvements.
* Since we build rustfmt from source we also need to add the correct sysroot to `LD_LIBRARY_PATH`. See #5675
* `set -e` to propagate errors so we'll be alerted to issues more quickly in the future
* A minor bug fix for scenarios where you want to pass optional configs to the feature rustfmt binary, but don't specify a commit hash.

Fix diff check Job

---

src/comment.rs

1. Use `matches!()` macro in `is_line_comment` and `is_block_comment` to improve readability.
2. Very sightly improve the wording of the doc comment for these two functions.
I came across these small refactoring/improvements while reading the code in pursuit of
fixing a different bug.
Note to reviewer: This change should produce no difference in functionality; it is a pure refactor.

Use matches!() macro to improve readability

---

src/lib.rs
tests/source/issue_5730.rs
tests/target/issue_5730.rs

Fixes #5730
Previously rustfmt was attempting to slice a string with an invalid range (`start > end`), leading to the ICE.
When formatting a macro transcriber snippet consisting of a lone semicolon, the snippet was being formatted into the empty string, leading the enclosing `fn main() {\n}` added by `format_code_block` to be formatted into `fn main() {}`. However, rustfmt was assuming that the enclosing function string's length had been left unchanged. This was leading to an invalid range being constructed when attempting to trim off the enclosing function.
The fix is to just clamp the range's start to be less than or equal to the range's end, since if `end < start` there's nothing to iterate over anyway.
---
Hi rustfmt'ers! This is my first PR to the project. I'm still not too familiar …

Prevent ICE when formatting an empty-ish macro arm

---

Contributing.md

`cargo-fmt` uses `rustfmt` from `PATH`, so `cargo run --bin cargo-fmt` still uses installed `rustfmt` instead of built one.

doc: fix instruction about running Rustfmt from source code

---

src/closures.rs
src/types.rs
tests/source/issue_5721.rs
tests/source/non-lifetime-binders.rs
tests/target/issue_5721.rs
tests/target/non-lifetime-binders.rs

Makes it so we stop yeeting non-lifetime binders into the void. Rustfmt already generally supports formatting `ast::GenericParam` anyways, so this just is piggybacking on that formatting.
Fixes #5721

Support non-lifetime binders

---

src/types.rs
tests/target/issue_5542.rs

Resolves #5542
Prior to rust-lang/rust#101212 the `ast::TraitObjectSyntax` enum only had two variants `Dyn` and `None`. The PR that introduced the `dyn*` syntax added a new variant `DynStar`, but did not update the formatting rules to account for the new variant.
Now the new `DynStar` variant is properly handled and is no longer removed by rustfmt.

Handle `dyn*` syntax when rewriting `ast::TyKind::TraitObject`

---

src/chains.rs
tests/source/issue-4808.rs
tests/target/issue-4808.rs

Fixes #4808
I think this is (perhaps?) okay without a version gate as the formatted code would be invalid before now, might be wrong though ^^

fix: Add parenthesis around `..` closure if it's a method call receiver

---

src/bin/main.rs

This is something incredibly small but as someone new to using rustfmt I found the --file-lines example quite frustrating
```
rustfmt --file-lines '[
{"file":"src/lib.rs","range":[7,13]},
{"file":"src/lib.rs","range":[21,29]},
{"file":"src/foo.rs","range":[10,11]},
{"file":"src/foo.rs","range":[15,15]}]' 
```
This leads me to believe that the file is going to be taken based on the json I passed as an argument but that is not the case, it also need to the files that are going to be modified as extra parameters, so since this `--help=file-lines` represents a complete example the message should be something like this:
```
rustfmt --file-lines '[
{"file":"src/lib.rs","range":[7,13]},
{"file":"src/lib.rs","range":[21,29]},
{"file":"src/foo.rs","range":[10,11]}, …
```

improve the --file-lines help

---

Cargo.lock
Cargo.toml
src/string.rs

This replaces the usage of `unicode_categories` crate which hasn't been updated for 7 years with the new `unicode-properties` crate under `unicode-rs` organization.
Also bumps dependencies version of other `unicode-*` crates in lockfiles.
cc https://github.com/rust-lang/rust/issues/101840

Update Unicode data to 15.0

---

src/macros.rs
tests/source/issue_5882.rs
tests/target/issue_5882.rs

Improve formatting of empty macro_rules! definitions

---

Cargo.lock
Cargo.toml
ci/build_and_test.bat
ci/build_and_test.sh

Fixes #5859
In addition to the fix, CI is updated to hopefully avoid this issue moving forward.

Enable rustfmt to compile when using the `generic-simd` feature

---

src/matches.rs
tests/target/issue_5676.rs

Fixes #5676
This PR prevents rustfmt from flattening a match arm's body block if that block was labeled.
I wonder if it would be worth making this change a little smarter to allow flattening in cases where the label isn't used inside the block?

Don't flatten blocks that have labels

---

src/items.rs
src/types.rs
src/utils.rs
tests/target/extern-rust.rs
tests/target/extern_not_explicit.rs

whenever we see an `extern "Rust"` on a function, we don't strip it from the function (which fixes #5701)

refactor ABI formatting

---

src/items.rs
tests/source/issue-5655/one.rs
tests/source/issue-5655/two.rs
tests/target/issue-5655/one.rs
tests/target/issue-5655/two.rs

Fixes #5655.
Closes #5679. This PR is an alternative that feature-gates the fix per the [comment in that PR](https://github.com/rust-lang/rustfmt/pull/5679#discussion_r1091116166).

Remove newlines in where clauses for v2

---

src/macros.rs
tests/source/issue_5735.rs
tests/target/issue_5735.rs

Prevent ICE when formatting item-only `vec!{}`
Fixes #5735
Attempting to format invocations of macros which are considered "forced bracket macros" (currently only `vec!`), but are invoked with braces instead of brackets, and contain only items in their token trees, currently triggers an ICE in rustfmt. This is because the function that handles formatting macro invocations containing only items, `rewrite_macro_with_items`, assumes that the forced delimiter style of the macro being formatted is the same as the delimiter style in the macro's source text when attempting to locate the span after the macro's opening delimiter. This leads to the construction of an invalid span, triggering the ICE.
The fix here is to pass the old delimiter style to `rewrite_macro_with_items` as well, so that it …

Prevent ICE when formatting item-only `vec!{}`

---

docs/index.html

I was looking through the code and noticed typos. In this PR I've fixed some.

Fix typos in index.html

---

src/comment.rs
tests/source/issue-5835.rs
tests/target/issue-5835.rs

fix: reject leading `.`, `)` without prefix as item marker

---

src/items.rs
tests/source/let_else.rs
tests/source/let_else_v2.rs
tests/target/let_else.rs
tests/target/let_else_v2.rs

Fix checking if newline is needed before `else` in let-else statement

---

src/comment.rs
tests/target/issue-5568.rs
tests/target/issue_5533.rs
tests/target/issue_5907.rs

This pull request adapts the plan 2 of [@ytmimi's comment](https://github.com/rust-lang/rustfmt/issues/5533#issuecomment-1238224735), and it won't touch any comment which is not a documentation comment now.
However, it did not fixed the root cause (which is partially indicated in Plan 1): [`block_comment` is `true` if the length is too long…?](https://github.com/rust-lang/rustfmt/blob/38659ec6ad5f341cf8eb3139725bf695872c6de7/src/lists.rs#L363). As it seems not related to #5533, it may be fixed in another PR.

Fix #5533: Prefer light_rewrite_comment if it is not a doccomment

---

Cargo.lock
Cargo.toml
src/cargo-fmt/main.rs

As of rust-lang/cargo#12578, nightly cargo's help has terminal styling applied to it.  This PR updates cargo-fmt to match so commands that appear built-in to the user all behave the same.
Other differences not address
- Help headings
- A footer recommending to run `cargo help fmt` (and providing an accompanying man page to be shown instead)
See rust-lang/cargo#12578 for screenshots of `cargo` and `cargo run` with different themes.

feat(cargo): Style help like cargo nightly

---

CHANGELOG.md

Add CHANGELOG entries for the next release

---

src/items.rs
tests/source/issue-5935.rs
tests/target/issue-5935.rs

Fixes #5935
r? @ytmimi if you have time, otherwise I may just pull this in for the release later given the trivial nature of the change

adjust span derivation for const generics

---

src/expr.rs
src/pairs.rs
tests/source/let_chains.rs
tests/source/match.rs
tests/target/let_chains.rs
tests/target/match.rs

This PR builds off of the work from #5203, and extendeds it to support the single-line formatting rules described in [r-l/rust#110568](https://github.com/rust-lang/rust/pull/110568)

Support let-chains

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Bumping from v1.6.0 -> v1.7.0 since we added support for let-chains.

Bump version to 1.7.0

---

src/matches.rs
tests/rustfmt/main.rs
tests/source/issue_5912.rs
tests/target/issue_5912.rs

Fixes #5912 
When `control_brace_style = "AlwaysNextLine"`, the code seems to always assume that `body_prefix` is `{`. This is however not the case when `match_arm_blocks = false`. This causes [`block_sep`](https://github.com/rust-lang/rustfmt/blob/a1fabbf3865c1044c7e96e8ac337131ebdf411b6/src/matches.rs#L453C1-L460C32) to introduce extra white space that causes the error.
The fix was to check if `body_prefix` is empty before matching on `ControlBraceStyle::AlwaysNextLine`. If you prefer however, I can add a match guard instead of changing the ordering of the match arms.

Fixed error caused by combination of match_arm_blocks and control_brace_style

---

src/items.rs
tests/target/impl.rs

Fixes #5941
The issue was caused by the trailing comment handling for where-clauses. For this particular issue, the problem was that we added a trailing comma if our where-clause's last line had a single line comment. Then we proceeded to add a comma to said single line comment.

Fixes comma added to comment in where-clause

---

ci/check_diff.sh

rustfmt currently has a runtime dependency on the sysroot. So when we build a standalone rustfmt binary we need to set `LD_LIBRARY_PATH` so each rustfmt binary knows where to find it's dependencies.
When running our `Diff-Check` job to test PRs for breaking changes it's often the case that both the master rustfmt binary and the feature branch binary have the same runtime dependencies so we only need to set `LD_LIBRARY_PATH` once.
However, when running the diff-check job against a subtree sync PR that assumption doesn't hold. The subtree sync PR bumps the required toolchain used to build rustfmt and therefore the binary that gets built for the subtree sync PR has a different runtime dependency than the master rustfmt binary.
Now we set `LD_LIBRARY_PATH` twice to account for this potential …

Fix Diff-Check job for subtree sync PRs

---

src/config/mod.rs
src/config/options.rs
src/config/style_edition.rs

**Note** This does not add the `style_edition` config option to rustfmt. The `StyleEdition` enum will eventually be used to allow users to configure `style_edition`, but for now it's added so we can introduce the the `StyleEditionDefault` trait.
This PR is an alternative to https://github.com/rust-lang/rustfmt/pull/5854 that doesn't use proc macros. 

Add `StyleEdition` enum and `StyleEditionDefault` trait

---

Configurations.md
src/config/config_type.rs
src/config/mod.rs
src/lib.rs
src/macros.rs
src/parse/session.rs

Fix of [3390 issue](https://github.com/rust-lang/rustfmt/issues/3390), changed `hide_parse_errors` to `show_parse_errors`

#3390: hide_parse_errors to show_parse_errors

---

Configurations.md
src/config/mod.rs

The `format_macro_bodies` option was added prior to the addition of procedural macros, and the existing description can be a little unclear in describing what this option actually does.

Clarify `format_macro_bodies` description

---

src/items.rs
tests/config/issue-5801-v1.toml
tests/config/issue-5801-v2.toml
tests/source/issue-5801/attribute_unexpectedly_wraps_before_max_width.rs
tests/source/issue-5801/comment_unexpectedly_wraps_before_max_width.rs
tests/target/issue-5801/attribute_does_not_wrap_within_max_width.rs
tests/target/issue-5801/attribute_unexpectedly_wraps_before_max_width.rs
tests/target/issue-5801/comment_does_not_wrap_within_max_width.rs
tests/target/issue-5801/comment_unexpectedly_wraps_before_max_width.rs

Fixes https://github.com/rust-lang/rustfmt/issues/5801

5801 enum variant doc comments are wrapped before `comment_width`

---

src/emitter/diff.rs

Instead of {filename} at {line}, use {filename}:{line} as this is a
format that many editors allow to be clicked to navigate directly to the
line.
---
This is a small papercut issue. I like being able to Cmd+Click a filename and navigate directly to the problematic code when I'm running `rustfmt check`.

Format diff line to be easily clickable

---

src/macros.rs
tests/source/issue-3805.rs
tests/target/issue-3805.rs

Fixes #3805
For wrapping macros with body block that starts with more than one `{`, i.e. starts with "nested blocks". The issue cause was that the nested block(s) `{` were not considered for calculating the remaining line width.

Fix for #3805 - wrap macro that starts with nested body blocks

---

src/test/mod.rs

fixes #6056
I confirmed that after messing with files in `src` and running `RUSTC_BLESS=1 cargo test` the self-test re-formatted itself still.

Bless the target file instead of the source file

---

Contributing.md

`$env:RUSTFMT_LOG=rustfmt=DEBUG` didn't work in PowerShell, `$env:RUSTFMT_LOG="rustfmt=DEBUG"` worked.

doc: make environment variable setting more explicit.

---

src/cargo-fmt/main.rs
src/format-diff/main.rs

Run `cargo check --features clap/deprecated` and fix all warnings

fix clap deprecations

---

src/matches.rs
tests/source/arrow_in_comments/arrow_in_single_comment.rs
tests/source/arrow_in_comments/multiple_arrows.rs
tests/target/arrow_in_comments/arrow_in_single_comment.rs
tests/target/arrow_in_comments/multiple_arrows.rs

Fixes #5998 
(1) Comment without arrow `=>`
```rust
fn main() {
match a {
_ =>
// comment with ==
{
println!("A")
}
}
}
```
(2) Comment without arrow `=>`
```rust
fn main() {
match a {
_ =>
// comment with =>
{
println!("A")
}
}
}
```
Previously, second example fails to reformat unlike the first example. The cause was rustfmt returns original code snippet when comment is lost after rewrite. When `rewrite_match_body`, there's logic to check if comment exists between `=>` and match body, but it tries to find another `=>` in arrow_snippet considering the case with nested match. Since `=>` in comment was also caught with `rfind()`, the comment was lost, which led to silent failure. 
Add extra check whether found `=>` was included in single line comment.

Fix failure with `=>` in comment after match `=>`

---

src/header.rs
src/lib.rs
src/macros.rs
tests/target/keywords.rs

This PR should be one of a series of PRs that formats _headers_. An item's header can include its keywords, its name, and its visibility. With generic header formatting facility, this would solve most, if not all issues with comments being deleted between keywords. In addition, this intends to replace the `rewrite_*` functions in `utils.rs`.
This PR is intentionally minimal, as I am not completely sure if this is desirable.

Initial work on formatting headers

---

Cargo.lock
Cargo.toml

changelog: https://github.com/rust-itertools/itertools/blob/v0.12.1/CHANGELOG.md

itertools bump to 0.12

---

Configurations.md
src/ignore_path.rs

I was looking into the source code to check how to add support for negated ignore because I didn't find any mention of it into the documentation until I went through the `ignore` crate source code, [here in particular](https://docs.rs/ignore/latest/src/ignore/gitignore.rs.html#463-466). Would have saved me a lot of time if such an example existed so here we are. :)

Add documentation for negated ignored files and add a test for it as well

---

Cargo.lock
Cargo.toml
src/comment.rs
src/lib.rs
src/test/configuration_snippet.rs

Split off from rust-lang/rust#124475. The functionality of the `lazy_static` crate is now available in the standard library as `OnceLock`. Rustfmt can now use this directly and drop the dependency.

Remove lazy_static dependency

---

src/expr.rs
tests/target/issue_6158.rs

fixes #6158
`cargo test` 0 failed
first time contributed on this project🥳

Fix: rustfmt should not remove inner attributes from inline const blocks

---

src/types.rs

Hello,
There are a lot of warns that detected by clippy, is there is any plan to work on them for example as good first issue? many of them are related to nested if else that can be collapsed

Collapse nested if detected by clippy

---

docs/index.html

Hi! It seems like [the docs site](https://rust-lang.github.io/rustfmt/) is currently broken. Previous to this commit, the cdn markedjs url was not versioned, so when [markedjs v13](https://github.com/markedjs/marked/releases/tag/v13.0.0) introduced breaking changes on 2024-06-12, the rustfmt docs site automatically pulled them in.
In addition to fixing that problem by pinning to v12, this PR:
* Expands the cdnjs links and script tags to reflect their recommendations, including an `integrity` hash so the browser can check that the retrieved executable content is in fact as-expected.
* Switches markedjs and vue from jsdelivr to cdnjs, which should be slightly faster as the browser already will have a reusable http/tls connection to cdnjs from other resources.
* Uses the minified vue file, …

docs: pin a version of markedjs from cdnjs

---

src/items.rs
tests/target/unsafe_extern_blocks.rs

This includes both `ast::StaticItem` and `ast::StaticForeignItem`. `safety` was added to both `ast::StaticItem` and `ast::SaticForeignItem` in https://github.com/rust-lang/rust/pull/124482.

format safety keywords on static items

---

src/items.rs
src/rewrite.rs
src/utils.rs
src/vertical.rs

- added `RewriteError` and blanket implementation for `rewrite_result` 
- above 6 ast nodes that implements rewrite, replaced rewrite function body with `rewrite_result` for 4 nodes; 
**ast::Local, ast::FieldDef, ast::Param, ast::FnRetTy**

Impl rewrite_result for ast nodes in items.rs

---

src/types.rs

Tracked by https://github.com/rust-lang/rustfmt/issues/6206

Impl rewrite_result for ast nodes in types.rs

---

tests/rustfmt/main.rs
tests/target/issue-6109.rs

Adding a test to prevent regression with regards to code snippet in doc comments as mentioned in this issue: https://github.com/rust-lang/rustfmt/issues/6109 The expected behavior is that the test shouldn't fai.

Test do nothing with doc comment with code

---

src/closures.rs
src/expr.rs
src/items.rs
src/overflow.rs

modify the signature of `rewrite_block` and `rewrite_closure` to return `RewriteResult`
- I did not change the return type of `rewrite_empty_block`(it returns None when given block is not empty) since every caller tries `rewrite_empty_block` first and then applies formatting logic for non empty block if it returns None. It seems that there's no need to propagate RewriteError upward from this function currently.

return RewriteResult for `rewrite_block` and `rewrite_closure`

---

src/config/config_type.rs
src/config/mod.rs
src/config/options.rs
src/config/style_edition.rs

This PR is a follow up to https://github.com/rust-lang/rustfmt/pull/5933, ~~but currently includes all the changes from that PR since it hasn't been merged yet~~.
This PR makes internal changes to define each configuration in terms of the `StyleEditionDefault` trait, and hard codes `StyleEdition::Edition2015` anywhere the new `style_edition` is needed.
**Note** users are still unable to configure `style edition`.
r? @calebcartwright 
Edit: https://github.com/rust-lang/rustfmt/pull/5933 was merged and I rebased this PR.

Impl `StyleEditionDefault` trait for all configs

---

src/attr.rs
src/expr.rs
src/patterns.rs
src/types.rs
src/vertical.rs

Tracked by https://github.com/rust-lang/rustfmt/issues/6206
Modify following functions to return `RewriteResult`
- rewrite_path and its caller (rewrite_struct_lit / pat)
- method rewrite_aligned_item of AlignedItem trait
Impl rewrite_result for `PreciseCapturingArg`, `AssocItemConstraint`, `PolyTraitRef`, `TraitRef` in types.rs
(These are the nodes that were waiting for certain rewrite_*** to return RewriteResult. see #6220) 
- rewrite_prefix, another method of the AlignedItem trait remains `Option<String>` since it is used for the possible range of width for struct prefix (see struct_field_prefix_max_min_width)
- Additionally, there are some messy `unknown_error()` calls since I haven't modified `write_list`, `itemize_list`, and similar functions. There's ongoing concern about modifying …

return RewriteResult for rewrite_path & rewrite_struct_***

---

src/expr.rs
src/matches.rs

Tracked by https://github.com/rust-lang/rustfmt/issues/6206
This pr implements `rewrite_result` for `ArmWrapper` (wrapper for ast `Arm`), while modifying functions used for formatting match expression like `rewrite_match`, `rewrite_match_arm` and so on.

impl rewrite_result for ArmWrapper

---

src/attr.rs
src/closures.rs
src/expr.rs
src/imports.rs
src/items.rs
src/lists.rs
src/macros.rs
src/matches.rs
src/overflow.rs
src/patterns.rs
src/reorder.rs
src/rewrite.rs
src/types.rs
src/vertical.rs

We often use `itemize_list` & `write_list` to format list-like expressions. Since `ListItem` holds `Option<String>` as the item field, we cannot propagate `RewriteError` from these functions. This pr replaces the type for the item field with `RewriteResult`, while modifying bound for `itemize_list` and `write_list`.

modify ListItem to hold RewriteResult as the item field 

---

src/attr.rs
src/chains.rs
src/expr.rs
src/items.rs
src/macros.rs
src/overflow.rs
src/pairs.rs
src/patterns.rs
src/spanned.rs
src/types.rs

- This pr modifies following functions to return RewriteResult 
: `rewrite_array`, `rewrite_pair`, `rewrite_tuple`, `rewrite_call` 
and `rewrite_with_***` in `src/overflow.rs` 
- Impl rewrite_result for `ast::MetaItem` in `src/attrs.rs` 
I used `DUMMY_SP` for generating dummy span of `max_width_error` in `rewrite_pair`, `rewrite_all_pairs` and its callees. There might be a better way to manually create an appropriate span for PairPart, and I need to give it more thought.

refactor rewrite_array, pair, tuple, call

---

src/bin/main.rs
src/config/config_type.rs
src/config/file_lines.rs
src/config/mod.rs

resolves #6252
There's more detail in that linked issue, but rustfmt internally needs to know whether the user explicitly specified a configuration value via a top level cli flag, e.g. `--edition` or `--style-edition`. This PR adds a separate boolean flag on configuration options that indicates whether the user specified it via a top level cli flag.
Notably, this intentionally does not make any changes to the `config.set().*` calls, nor the `config.was_set().*` behavior. That's because I'm unclear on the historical reasons why those ignored the CLI flag method, at this time I'm unclear on the potential side effects of changing that behavior, and we don't need to resolve nor risk any of that for the purposes of the 2024 work (i left an inline FIXME to revisit)

track configs set from cli flags

---

src/attr.rs
src/chains.rs
src/comment.rs
src/expr.rs
src/imports.rs
src/items.rs
src/lists.rs
src/matches.rs
src/missed_spans.rs
src/patterns.rs
src/types.rs
src/vertical.rs
src/visitor.rs

Tracked by https://github.com/rust-lang/rustfmt/issues/6206
1. modify rewrite_literal to return RewriteResult
2. refactor `combine_strs_with_missing_comments` and its call sites

refactor rewrite_literal & combine_strs_with_missing_comments

---

check_diff/Cargo.lock
check_diff/Cargo.toml
check_diff/src/lib.rs
check_diff/src/main.rs
check_diff/tests/bash_commands.rs
check_diff/tests/git.rs
ci/build_and_test.bat
ci/build_and_test.sh

TLDR: Added repo cloning to check-diff. Included sample execution as screenshot.
This PR adds git functionalities to the `check-diff` crate. The current script has a `init_submodules` function. However, it seems that the repos used does not require initialising of submodules. Hence, this function was not converted to Rust. 
Sample execution attached. Parameters to the program is currently not in used.
The screenshot shows the following things:
- runs the script to clone `rustfmt` into a `tmp` directory created
- show that `tmp` contains the entire `rustfmt` repo

Add repo cloning to check-diff crate

---

build.rs

Previously, `rustfmt --version` would print nondeterministic output when built from the exact same source code and git commit. The number of hex digits printed in the commit hash would vary based on how many other branches and tags you had fetched so far, what other commits you had been working on in other branches, how recently you had run `git gc`, platform-specific variation in git's default configuration, and platform differences in the sequence of steps performed by the release pipeline.
You can see this in the official build of `rustfmt` that is part of the Rust 1.80.0 stable release.
The rustfmt for x86_64-unknown-linux-gnu prints:
```console
$ rustfmt +1.80.0 --version
rustfmt 1.7.0-stable (0514789 2024-07-21)
```
Whereas for aarch64-apple-darwin it prints:
```console
$ rustfmt …
```

Print a deterministic length of commit hash in --version

---

build.rs
src/bin/main.rs

The git commands `git rev-parse HEAD` and `git log -1 --date=short --pretty=format:%cd` in rustfmt's build script might fail with **"fatal: not a git repository (or any of the parent directories): .git"** if rustfmt is being built from a source tarball rather than a git repository. That message is written by git to stderr, and nothing is written to stdout.
Previously, rustfmt's build script would take that empty stdout and treat it like valid commit info, unlike what it does when `git` cannot be spawned in the first place, and contradicting this comment about the build script's intended behavior in the case of there not being a git repository:
https://github.com/rust-lang/rustfmt/blob/17c5869dffc21356559f223770cbfa0648692808/build.rs#L24-L25
```console
$ curl -L …
```

Check exit status of git commands spawned by build script

---

src/expr.rs
src/patterns.rs
src/types.rs

- impl rewrite_result for `Pat`, `TuplePatField`
- also update `rewrite_unary_***` to return `RewriteResult`

impl rewrite_result for Pat, TuplePatField

---

src/config/mod.rs
src/config/options.rs

This commit ensures that `fn config_path` in `rustfmt/src/config/mod.rs` always returns canonicalized paths.  This is achieved by canonicalizing both: 1) paths received via `CliOptions` (after checking if the path exists) as well as 2) paths returned via `get_toml_path` (canonicalizing within `fn get_toml_path`).
Fixes https://github.com/rust-lang/rustfmt/issues/6178

Ensure that `fn config_path` returns canonicalized paths.

---

src/chains.rs
src/expr.rs

- impl `rewrite_result` for `Chain` 
- update `rewrite_chain` and methods of the trait `ChainFormatter` to return RewriteResult
I'll add some comments to the code shortly

update rewrite_chain to return RewriteResult

---

src/expr.rs
src/items.rs
src/macros.rs
src/patterns.rs
src/rewrite.rs
src/types.rs
src/visitor.rs

- update both `rewrite_macro` and `rewrite_macro_def` to return RewriteResult
- add a new enum variant that represents macro rewrite failure

update macro rewrite functions to return RewriteResult

---

.github/workflows/mac.yml

Per [the documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources), `macos-latest` now refers to macOS 14.

Remove outdated comment from `mac.yml`

---

src/expr.rs
src/items.rs
src/macros.rs
src/types.rs

tracked by #6206 
update `rewrite_assignment` to return `RewriteResult`

update rewrite_assignment to return RewriteResult

---

src/comment.rs
src/expr.rs
src/items.rs
src/overflow.rs
src/stmt.rs
src/types.rs

tracked by #6206 
- impl `rewrite_result` for `Stmt`, `ControlFlow` `OverflowableItem`, `Lifetime` 
There are still `unknown_error()`s due to calling `format_expr`, but they will be removed after updating `format_expr` in later pr.    
- update `rewrite_index` to return `RewriteResult`  
- removed a few `unknown_error()` if possible

impl rewrite_result for ControlFlow, Stmt, update rewrite_index

---

src/config/mod.rs

The `get_edition_toml` closure was returning `()`.

Fix `test_editions_2015_2018_2021_identical`

---

src/bin/main.rs
src/comment.rs

Avoid allocating intermediate strings in `ItemizedBlock::trimmed_block_as_string` and `determine_operation`.

Avoid some string allocations

---

src/expr.rs
src/matches.rs
src/stmt.rs
src/types.rs
src/utils.rs

tracked by #6206 
This pr impl `rewrite_result` for `Expr` by updating `format_expr` to return `RewriteResult`. 
Now we don't call `.ok()` after calling `rewrite_***` functions in `format_expr` :)

impl rewrite_result for ast::Expr

---

.github/workflows/check_diff.yml
.github/workflows/integration.yml
.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/rustdoc_check.yml
.github/workflows/upload-assets.yml
.github/workflows/windows.yml

Required for using Node.js 20.x in CI
* Changelog for actions/checkout@v4 https://github.com/actions/checkout/blob/main/CHANGELOG.md?rgh-link-date=2024-09-04T18%3A38%3A10Z#v400
* GitHub Blog post https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Refs: https://github.com/rust-lang/rust/pull/130124#issuecomment-2336871149

ci: bump actions/checkout to v4

---

Cargo.lock
Cargo.toml

This removed unused `tracing-attributes` dep (https://github.com/tokio-rs/tracing/blob/tracing-0.1.37/tracing/Cargo.toml) which provides `#[instrument]` macro.

remove unused tracing-attributes

---

config_proc_macro/Cargo.toml

This reduces syn's features to "full", "parsing", "proc-macro", "printing" only for that proc macro.
Also bumped edition to 2021.

config_proc_macro: reduce syn's features

---

src/items.rs
tests/source/type-alias-where-clauses-with-comments.rs
tests/source/type-alias-where-clauses.rs
tests/target/type-alias-where-clauses-with-comments.rs
tests/target/type-alias-where-clauses.rs

Self-explanatory. cc rust-lang/rust#114901
This implementation is probably super busted. I have no idea what most of these options in rustfmt mean, lol.

Format trailing where clauses in type aliases

---

src/bin/main.rs
src/config/file_lines.rs
src/test/mod.rs

Avoid `unwrap()` by using infallible `std::path::Path::display()`.

Non-panicking `fmt::Display` for `FileName`

---

CHANGELOG.md

[rendered](https://github.com/ytmimi/rustfmt/blob/release_notes/CHANGELOG.md#unreleased)

Document changes for the next release

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Most notably this release adds `style_edition` and soft deprecates `version`. `version` is superseded by `style_edition`. `style_edtion={2015|2018|2021}` are equivalent to `version=One`, and `style_edition=2024` is equivalent to `version=Two`. `style_edition=2024` is still marked as unstable.

chore: prep v1.8.0 release

---

src/emitter/json.rs

Write directly to the output instead of creating an intermediate `String`.

Avoid allocation in `JsonEmitter::emit_footer`

---

src/emitter/json.rs

The mismatches length is known to be equal to `diff.len()`.

Preallocate missmatches in `JsonEmitter::add_misformatted_file`

---

Configurations.md
src/config/config_type.rs

To resolve https://github.com/rust-lang/rustfmt/issues/6340. 
Did not add too many information as to maintain succinct the warnings. I don't know if a link to relevant info in the warning would be useful.

Hint which style_edition to use instead of version

---

src/attr.rs
src/chains.rs
src/closures.rs
src/expr.rs
src/imports.rs
src/items.rs
src/lists.rs
src/macros.rs
src/matches.rs
src/overflow.rs
src/pairs.rs
src/patterns.rs
src/reorder.rs
src/rewrite.rs
src/shape.rs
src/stmt.rs
src/types.rs
src/vertical.rs
src/visitor.rs

* The `Shape` modifier methods now return `Result<Shape, ExeedsMaxWidthError>`
* There are `_opt` variants of the methods for when an Option is still needed
* I believe this will remain useful in the long term, since sometimes we want to fallback and never error out
* There is a minor change in behavior for when multiple methods are chained together - the width used in the error will be the last successfully modified width. I think this is okay?

Return Result from Shape methods

---

src/modules/visitor.rs

Save a few cycles by using the existing `path` symbol from rustc

Use preinterned `path` symbol

---

src/items.rs
src/reorder.rs
src/visitor.rs

Use RewriteResult in visit_item

---

src/expr.rs
tests/target/issue-6411.rs

This PR fix #6411 
This PR fixes an issue where rustfmt incorrectly removes the r# prefix in raw labels(introduced in 1.83 https://github.com/rust-lang/rust/pull/126452), causing invalid label names like 'if instead of 'r#if.

Fix incorrect strip r# prefix from labels

---

src/comment.rs
tests/target/issue-5244/unwrapped.rs
tests/target/issue-5244/wrapped.rs

Fixes https://github.com/rust-lang/rustfmt/issues/5244
This PR fixes the issue in ~#6416~ (duplicate of https://github.com/rust-lang/rustfmt/issues/5244), I have added both the before and after case of the formatting in `tests/`.
Edit (ytmimi): I updated the description

fix: wrap_comments creating invalid code blocks

---

docs/index.html

I hacked a quick fix to  #6485.

docs: pull latest version from tags instead of releases in docs page

---

Configurations.md
README.md

When using `rustfmt` directly on a project targeting the 2024 edition, the formatting differs from `cargo fmt` because `rustfmt` defaults to the 2015 edition. This discrepancy causes inconsistencies, especially when tools like editors automatically run `rustfmt` on save, leading to files being reformatted to the 2015 edition style.
I tried to explain this behavior concisely in the docs.
Fixes #6483.

docs: clarify the editions behavior and it's consequences on formatting

---

src/pairs.rs
tests/source/let_chains.rs
tests/target/let_chains.rs

Also allow literals as the first item in a single line let chain, not just idents. This will most probably not occur in most real-world code, but it makes things a little bit more consistent. While rustfmt allows any literal type, like also string literals, those will not create valid rust code. Only bool literals will.
Implements suggestion from https://github.com/rust-lang/rust/pull/110568#discussion_r1841155819 .

Allow also allow literals as first item of single line let chain

---

src/chains.rs
src/closures.rs
src/expr.rs
tests/source/ergonomic_clones.rs
tests/target/ergonomic_clones.rs

Tracking issue https://github.com/rust-lang/rust/pull/134797
Closes #6512

Add `#![feature(ergonomic_clones)]` formatting

---

Configurations.md
src/config/mod.rs
src/config/options.rs
src/matches.rs
tests/source/configs/match_arm_indent/attrs.rs
tests/source/configs/match_arm_indent/guards.rs
tests/source/configs/match_arm_indent/leading_pipes.rs
tests/source/configs/match_arm_indent/nested.rs
tests/source/configs/match_arm_indent/patterns.rs
tests/source/configs/match_arm_indent/unindent.rs
tests/target/configs/match_arm_indent/attrs.rs
tests/target/configs/match_arm_indent/guards.rs
tests/target/configs/match_arm_indent/leading_pipes.rs
tests/target/configs/match_arm_indent/nested.rs
tests/target/configs/match_arm_indent/noindent-tabs.rs
tests/target/configs/match_arm_indent/noindent.rs
tests/target/configs/match_arm_indent/patterns.rs
tests/target/configs/match_arm_indent/unindent.rs

Allows to disable the indentation of match arms.
Related issue: #2937

Add `match_arm_indent` option

---

src/expr.rs
tests/source/issue-6202/long_pat.rs
tests/target/issue-6202/long_pat.rs

The trailing `  =` was not taken into account when rewriting the pattern. This caused an error of the pattern exceeding the `max_width`.
This PR is nearly identical to #6224, but the change is gated on `StyleEdition::Edition2027` or newer.
Fixes #6202.

fix: split a line exceeding the maximum width

---

src/cargo-fmt/main.rs

Instead of resolving `rustfmt` path from RUSTFMT or PATH envs, use the one located in the same directory as `cargo-fmt`. So that `cargo-fmt` uses the expected version of `rustfmt` to avoid accidental use of unrelated versions.
This shouldn't change anything on the current behavior but it should make it easier to test the bootstrapped `cargo-fmt` in rust-lang/rust, since it currently always points to the globally installed `rustfmt`.
Moved from https://github.com/rust-lang/rust/pull/141100

Fix path resolution of `rustfmt` in `cargo-fmt`

---

CHANGELOG.md

Most notably this release stabalizes `style_edition=2024` and the `--style-edition` CLI option.

update changelog for v1.9.0 release
