rust-lang/rustfmt

Cargo.lock

Do this so you can reliably build `rustfmt` in the future, even if one of the
dependencies (in this case, only `strings.rs`) makes backward-incompatible
changes.
See also http://doc.crates.io/guide.html#cargo.toml-vs-cargo.lock.

Add `Cargo.lock` file, because this application is a program

---

src/changes.rs
src/functions.rs
src/imports.rs
src/mod.rs
src/visitor.rs

This means that it doesn't have to go through the formatting hierarchy and can
just immediately reserve enough memory.

Change `to_string` to `to_owned` when it just creates a `String` from a `&str`

---

README.md

This is probably how it was meant. The imaginary HIR is pretty much equivalent to semantics, as far as I understand.

Add a missing "not" to readme

---

src/functions.rs
tests/idem/fn.rs

`mut` was eaten out of `mut self` in fn args.

---

src/functions.rs
src/imports.rs
tests/idem/fn.rs

Changes lists such as ``use std::{fmt}`` to a form without a list, eg ``use std::fmt``.

Change import lists with one item to single import

---

src/bin/rustfmt.rs
src/functions.rs
src/visitor.rs
tests/idem/trait.rs

This should close https://github.com/nrc/rustfmt/issues/15. The main problem is that `rewrite_fn` and `rewrite_required_method` share a lot of code. I haven't found the ideal way to reduce this duplication. Any feedback would be greatly appreciated!

Format required methods on traits

---

Cargo.lock
Cargo.toml
tests/idem.rs

Adds diffs between expected output and actual output for failings tests. Shows return character to quickly identify trailing whitespace.
Closes https://github.com/nrc/rustfmt/issues/66.

Show diffs for failing tests

---

src/expr.rs
tests/idem/paren.rs

I'm quite new to Rust, so I picked this for practice. Please tell me if it's not idiomatic for Rust.

Add reformating for parentheses

---

src/config.rs
src/default.toml
src/items.rs

Added new config option `fn_args_paren_newline` to control this (defaults to previous behavior). Only tested locally --- I can add some testcases but I don't think there's support for per-test Config options.

Optionally put the opening paren on the previous line for args (Issue #31)

---

src/config.rs
src/default.toml
src/expr.rs
src/imports.rs
src/items.rs
src/utils.rs
src/visitor.rs
tests/idem/enum.rs

This PR adds formatting for enums with tuple-like variants.
cc https://github.com/nrc/rustfmt/issues/76

Implement basic enum formatting

---

src/changes.rs
src/config.rs
src/default.toml
src/issues.rs
src/lib.rs
src/lists.rs
src/utils.rs
tests/config/small_tabs.toml

This PR does two things: it saves the errors rustfmt finds in a report instead of immediately printing them, making some progress on https://github.com/nrc/rustfmt/issues/9.
It also adds checks for unnumbered TODOs and FIXMEs in the code. Basically we just check that any line containing a TODO matches the following regex:
```
/TODO\([^)#]*#\d+[^)]*\)/
```
But since we go through the results character by character, I implemented a state machine myself.
The output can get quite noisy --especially for rustfmt's own code--, so I added an option to forgo the check.
Note: the check treats all text equally. We're not making sure that we're in a comment. It may happen that we get false positives when there's a FIXME or TODO in a string literal, for example.

Implement checks for unnumbered TODOs and FIXMEs

---

src/items.rs
src/utils.rs
tests/target/fn.rs

Resolves several issues with comments containing problematic characters.

Deal with problematic characters in comments

---

src/expr.rs
tests/source/string-lit.rs
tests/target/string-lit.rs

Rustfmt currently loops indefinitely on very long string literals without whitespace.

Fix off-by-one errors in rewrite_string_lit

---

src/utils.rs

This handles a underflow panic on round_up_to_power_of_two(0).
Fixes a panic on empty files (same situation as #115, but not same cause).

Use wrapping operations for bit-level functions

---

src/expr.rs
src/lib.rs
src/rewrite.rs
src/utils.rs
src/visitor.rs

This PR is just a proposal of a new trait, and is primarily intended for discussion. It's a draft of implementation of an idea I wanted to share and discuss. It's just an idea, that will maybe not well work.
Because it might change a lot of code, I prefer to discuss it before a complete implementation.
Motivation
---------
We have a recurrent pattern in the code: rewrite some code with a given offset and width. (It's very common in `expr.rs`, for example).
I wanted to abstract "something that can be rewritten into offset and width" when working on list formatting. Format a list (of args, types parameters...) is also something useful. With the current `lists` module, it needs some recurrent code, essentially : rewrite all items of the list within a maximal width, but the last one within …

Add a Rewrite trait

---

src/imports.rs
src/visitor.rs

Removes imports of the form `use std::convert::{};`.

Remove empty list imports

---

src/changes.rs
src/config.rs
src/expr.rs
src/items.rs
src/lib.rs
src/rewrite.rs
src/visitor.rs
tests/system.rs

This should make it possible to run idempotence/ system tests concurrently.

Remove global mutable config to allow for concurrency

---

src/comment.rs
src/config.rs
src/default.toml
src/imports.rs
src/lib.rs
src/lists.rs
src/string.rs
src/visitor.rs
tests/config/reorder_imports.toml
tests/source/imports-reorder.rs
tests/source/imports.rs
tests/target/imports-reorder.rs
tests/target/imports.rs

Adds comments and sorts items alphabetically. This is based on https://github.com/nrc/rustfmt/pull/93, to use the updated `write_list`.

Update import list formatting

---

src/expr.rs
tests/source/expr.rs
tests/target/expr.rs
tests/target/paren.rs

I experimented quite a bit and think this is a decent heuristic for formatting binary operations. It's not very clear when a binary operation triggers a line break inside a function call, as it breaks the '1 parameter per line' pattern.
cc https://github.com/nrc/rustfmt/issues/29, https://github.com/nrc/rustfmt/issues/30

Format expressions with binary and unary operators

---

src/expr.rs
tests/source/expr.rs
tests/target/expr.rs

I didn't had enough time to review and test @nrc merged, so I correct here a bug in #99 : `lhs` was formatted into `width`, and `rhs` into `max_width`, while the inverse should be done.

Fix bugs in width computation for bin op

---

src/changes.rs
src/comment.rs
src/expr.rs
src/imports.rs
src/issues.rs
src/items.rs
src/lib.rs
src/lists.rs
src/missed_spans.rs
src/types.rs
src/utils.rs
src/visitor.rs
tests/source/mod-2.rs
tests/source/nestedmod/mod.rs
tests/source/nestedmod/mod2a.rs
tests/source/nestedmod/mod2b.rs
tests/source/nestedmod/mod2c.rs
tests/source/nestedmod/submod2/a.rs
tests/source/nestedmod/submod2/mod.rs
tests/target/enum.rs
tests/target/fn.rs
tests/target/mod-2.rs
tests/target/nestedmod/mod.rs
tests/target/nestedmod/mod2a.rs
tests/target/nestedmod/mod2b.rs
tests/target/nestedmod/mod2c.rs
tests/target/nestedmod/submod2/a.rs
tests/target/nestedmod/submod2/mod.rs

The trickiest part was to identify the file a module belongs to. The technique previously used doesn't work with modules that contains only comments (no items), so I used the same algorithm as rustc, looking for the `path` attribute and then defaulting to `X.rs` and `X/mod.rs`.
At the end, we get all our code reformatted ! (There was a lot of misformatted code ;)
The first two commits are two small issues I discovered while reformatting the code of rustfmt. (I you feel these needs separate issues/PR, please ask it.)
Closes #118

Reformat modules in external files

---

src/expr.rs
tests/target/tuple.rs

Wasn't using all width available when the lenght is more than 1.

Fix bug in rewrite_tup_lit

---

src/changes.rs
src/expr.rs
src/rewrite.rs
src/visitor.rs
tests/source/loop.rs
tests/target/loop.rs

This was previously attempted by @chellmuth in https://github.com/nrc/rustfmt/pull/103. It hasn't seen any activity in three weeks, so I've taken the liberty to try as well.
My approach was as suggested in https://github.com/nrc/rustfmt/pull/103#issuecomment-111297423. While it is not optimal performance-wise, it has a low complexity. If this deemed acceptable for now, we can use it to easily format a whole class of expressions like if-else statements and even match blocks!

Format loops

---

src/changes.rs
src/comment.rs
src/config.rs
src/default.toml
src/expr.rs
src/imports.rs
src/issues.rs
src/items.rs
src/lib.rs
src/visitor.rs
tests/config/reorder_imports.toml
tests/config/visual_struct_lits.toml
tests/source/struct_lits.rs
tests/source/struct_lits_visual.rs
tests/target/struct_lits.rs
tests/target/struct_lits_visual.rs

I change the default, but leave the old formatting as an option.
Closes #83
r? @marcusklaas or @cassiersg

Options for formatting struct literals

---

src/expr.rs
tests/target/fn.rs

Closes https://github.com/nrc/rustfmt/issues/148. Rustfmt should be able to run on servo with this fix.
It now properly propagates the rewrite failure instead of panicking. Added regression test from servo code. 
This example will be properly rewritten when https://github.com/nrc/rustfmt/issues/17 is fixed. I'm working on that.

Fix underflow bug in rewrite_call

---

src/expr.rs
tests/source/expr.rs
tests/target/expr.rs

Closes https://github.com/nrc/rustfmt/issues/154.

Preserve box syntax

---

src/comment.rs
src/expr.rs
src/visitor.rs
tests/source/expr.rs
tests/target/expr.rs

Unfortunately does not fix https://github.com/nrc/rustfmt/issues/156.

Use new module code from libsyntax

---

src/comment.rs
src/config.rs
src/expr.rs
src/imports.rs
src/issues.rs
src/items.rs
src/lib.rs
src/lists.rs
src/utils.rs
src/visitor.rs
tests/config/expr_visual_indent.toml
tests/config/reorder_imports.toml
tests/config/small_tabs.toml
tests/config/visual_struct_lits.toml
tests/source/expr-visual-indent.rs
tests/source/expr.rs
tests/source/loop.rs
tests/source/struct_lits.rs
tests/source/struct_lits_visual.rs
tests/target/expr-visual-indent.rs
tests/target/expr.rs
tests/target/loop.rs
tests/target/struct_lits.rs
tests/target/struct_lits_visual.rs

Since a lot of code is inside these expressions, this should significantly increase coverage!
Blocked by https://github.com/rust-lang/rust/pull/27065.
Single line if-else expressions are not implemented yet.
Closes https://github.com/nrc/rustfmt/issues/102.

Format if expressions & loops

---

src/expr.rs
src/imports.rs
src/visitor.rs
tests/source/expr.rs
tests/target/expr.rs
tests/target/imports.rs
tests/target/multiple.rs

Implements Rewrite for ViewPath
Behavior change: always use max_width instead of ideal_width for use
list rewrite. I think it looks better, was also suggested by @nrc in
https://github.com/nrc/rustfmt/issues/82#issuecomment-105314265

Move 'use' to Rewrite

---

src/expr.rs
tests/source/expr.rs
tests/target/expr.rs

Operator width was counted twice.

Fix width computation in rewrite_binary_op

---

src/expr.rs
src/visitor.rs
tests/source/expr.rs
tests/target/expr.rs

This mostly fixes https://github.com/nrc/rustfmt/issues/166. The leading blank line seems to be a different issue.

Properly format unsafe blocks

---

src/items.rs
src/utils.rs
tests/target/trait.rs

This closes https://github.com/nrc/rustfmt/issues/153.

Correctly format typed self in function arguments

---

src/expr.rs
src/imports.rs
src/items.rs
src/lists.rs
src/types.rs
src/utils.rs
src/visitor.rs
tests/source/fn-simple.rs
tests/source/paths.rs
tests/source/struct_lits.rs
tests/target/fn-simple.rs
tests/target/fn.rs
tests/target/paths.rs
tests/target/struct_lits.rs

Closes https://github.com/nrc/rustfmt/issues/17, which wasn't nearly as easy as advertised! :o
This actually does not split paths, as I feel we should avoid this at all costs (except exceeding column limits). I am curious to see what others think about this, though.

Format paths

---

src/expr.rs
src/imports.rs
src/items.rs
src/lists.rs
src/types.rs

This enables us to itemize lists without allocating. We currently need still need a vector in order to use `write_list`, but when https://github.com/nrc/rustfmt/issues/133 is addressed, that may not be necessary any more.

Refactor itemize list so that it produces an iterator

---

src/comment.rs
src/expr.rs

This make a base for all functions searching for comments, or searching
code excluding comments, etc. These functions where too simple and
didn't handle complicated cases like nested comments or comment marks
inside string litterals ("/*").
r? @nrc @marcusklaas 
I welcome any idea to improve this code (I'm not entirely satisfied by this, though it works.)

Add a generic tool for searching comments in code

---

src/bin/rustfmt.rs

Fixes missing output described in #212 and ensures all destructors are run before exiting.

Only exit after running all destructors and flushing stdout

---

Cargo.lock
Cargo.toml
tests/system.rs

This splits the generation and display of mismatches. Mismatches now include a few lines of context. Finally, diffs are now coloured.

Refactor diff handling in tests

---

src/expr.rs

No idea if this is correct, but it allowed me to continue formatting display_list_builder.rs.

Avoid an integer underflow panic. Fixes #229.

---

src/comment.rs
src/expr.rs
tests/source/string-lit.rs
tests/target/string-lit.rs

Rustfmt would leave the literal unchanged when it did not exceed the column limit in its original position, not considering its position after formatting.

Remove faulty shortcut in `rewrite_string_lit`

---

src/comment.rs
src/lib.rs
src/lists.rs
src/modules.rs
src/types.rs
src/visitor.rs

Removed a few needless returns, replaced .iter()s by slice refs, and de-referenced some matches.
Yay for readabiltiy. :smile:

code improvements suggested by clippy

---

src/bin/rustfmt.rs

I was looking for how to get rid of the `.bk` files and the `-h` flag was actually not helpful ;)

fix outdated help text

---

tests/source/fn-simple.rs
tests/target/fn-simple.rs

The PR https://github.com/nrc/rustfmt/pull/246 includes a similar test. Here, both bounds are trait bounds.
Closes https://github.com/nrc/rustfmt/issues/152.

Add regression test for trait reference formatting

---

src/expr.rs
src/imports.rs
src/items.rs
src/lists.rs
src/types.rs
src/utils.rs
src/visitor.rs
tests/source/imports.rs
tests/source/paths.rs
tests/target/imports.rs
tests/target/paths.rs
tests/target/tuple.rs

Fixes some cases where we would exceed the column limit.

Add failure mode to `write_list`

---

src/config.rs
src/expr.rs
tests/source/struct_lits_multiline.rs
tests/source/struct_lits_visual_multiline.rs
tests/target/struct_lits_multiline.rs
tests/target/struct_lits_visual_multiline.rs

With struct_lit_force_multiline set to true
rustfmt won't ever mangle multiple struct properties
into one line.
Fixes #253

Implements struct_lit_force_multiline

---

src/expr.rs
tests/source/closure.rs
tests/target/closure.rs

This would happen when the callee contained parentheses.
Fixes https://github.com/nrc/rustfmt/issues/311.

Prevent generation of bogus comment in some function calls

---

Cargo.lock
Cargo.toml

This should make the computation of diffs quite a bit faster, which is particularly noticable in tests.
Before:
```bash
time cargo run -- /home/rustfmt/src/lib.rs --write-mode=diff
...
26.18user 0.07system 0:26.29elapsed 99%CPU (0avgtext+0avgdata 58512maxresident)k
```
After:
```bash
time cargo run -- /home/rustfmt/src/lib.rs --write-mode=diff
...
1.44user 0.05system 0:01.49elapsed 100%CPU (0avgtext+0avgdata 47588maxresident)k
```

Bump diff.rs version

---

src/bin/rustfmt.rs
src/config.rs
src/utils.rs

Added to the create_config! macro to automatically create usage output when config options are added, as well as outputting all possible values for them.

Fixed https://github.com/nrc/rustfmt/issues/291

---

src/bin/rustfmt.rs
src/comment.rs
src/config.rs
src/expr.rs
src/filemap.rs
src/items.rs
src/lib.rs
src/types.rs
src/visitor.rs
tests/system.rs

In this PR, we propose a new public function `format`, which simply returns the result of the reformatting, without any side effects. This should give us more freedom and control than wrapping logic in a callback.
We use this extra control to update the test code, which no longer needs to rely on `thread::catch_panic`, and run some extra checks. From now on, when rustfmt's own code exceeds the maximum_width, the tests will no longer pass.
Fixes https://github.com/nrc/rustfmt/issues/183.

Refactor rustfmt's interface and test code

---

src/items.rs

https://github.com/rust-lang/rust/pull/28440

rustc update: Remove variant visibility

---

src/chains.rs
src/comment.rs
src/config.rs
src/expr.rs
src/imports.rs
src/items.rs
src/lib.rs
src/lists.rs
src/macros.rs
src/missed_spans.rs
src/rewrite.rs
src/string.rs
src/types.rs
src/utils.rs
src/visitor.rs
tests/source/hard-tabs.rs
tests/target/hard-tabs.rs

This is a draft, as perhaps not all implementation choices I made are ideal. I also wasn't sure what to do with tests.
The general idea of this change is to switch from using a plain `usize` to track indentation to a special `Indent` type which tracks block indentation and alignment (for visual alignment) separately. Adding the hard tab mode on top of that is then trivial. This increased type safety should prevent bugs where width is passed instead of offset and vice versa (e.g. see a possible bug in `src/items.rs:61-62`).
I've tested the patch and it seems to work fine in most cases. It doesn't interact well with visual indentation for function arguments + closures, but I don't think there's expectation that every possible indentation configuration option should result in a sensible …

Initial implementation of hard tab indentation.

---

src/visitor.rs
tests/source/mod-1.rs
tests/target/mod-1.rs

Fixes https://github.com/nrc/rustfmt/issues/319.
Blocked by https://github.com/rust-lang/rust/pull/28534.

Place the closing brace of an inline mod on a new line

---

src/expr.rs
tests/source/expr.rs
tests/target/expr.rs
tests/target/match.rs

Few things
- we had a test case that violated this anyway, changed that case assuming this is the desired behaviour
- functionalised nop-block-collapsing because `if`,`fn`, `struct`, `loop` etc. might want the same treatment
- this code only executes for match arms, the above constructs could use same idea, but currently dont, implementing it for all (i.e. in Block.rewrite) causes many test-cases to fail.
Outstanding:
- vertical whitespace issues.  Awaiting what to do about vertical whitespace,
cant format:
```
a => {
//some comment
}
```
to
```
a => {
//some comment
}
```
as expected, without some policy on vertical whitespace, which will be global, not just match arms

match arms collapse for issue #339

---

src/expr.rs
src/items.rs
src/lists.rs
tests/source/structs.rs
tests/target/structs.rs

Previously, we'd use an approximation for the maximum width since the configuration wasn't available in `write_list`.
Fixes https://github.com/nrc/rustfmt/issues/360.

Use the maximum available width in struct formatting

---

src/bin/rustfmt.rs
src/config.rs
src/issues.rs
src/utils.rs

@marcusklaas requested this
Intial attempts to add license support (removed the license options for now)
Refactored configuration options:
* Reduced code duplication by defining enums in a macro
* Usage printout is determined statically (inside the make_config! macro)
* [New usage printout](http://pastebin.com/JAWYSjw2)
This code does not solve any outstanding issues

Refactoring configuration

---

src/string.rs
tests/source/string_punctuation.rs
tests/target/string_punctuation.rs

rewrite_string now prefers to look for punctuation to split on, and then goes to the nearest non-escape character as a last resort.

Fix https://github.com/nrc/rustfmt/issues/389

---

src/expr.rs
src/items.rs
src/lists.rs
src/missed_spans.rs
src/visitor.rs
tests/source/expr.rs
tests/target/expr.rs

Closes https://github.com/nrc/rustfmt/issues/395 and possibly https://github.com/nrc/rustfmt/issues/4. Maybe even https://github.com/nrc/rustfmt/issues/26?
Pretty much all expressions are deeply rewritten at this point. We only skip some types of literals and inline ASM.

Format casts, indices and repeated elements

---

Cargo.lock
src/comment.rs
src/config.rs
src/expr.rs
src/filemap.rs
src/imports.rs
src/issues.rs
src/items.rs
src/lib.rs
src/lists.rs
src/macros.rs
src/types.rs
src/visitor.rs

This PR does several things. 
- It moves the list tactic decision logic to its own function. As a result, it should become easier to implement custom logic for issues such as https://github.com/nrc/rustfmt/issues/263. It's now also possible to do list itemization and serialization, e.g. `itemize_list` and `write_list`, without storing the intermediate results in a vector.
- It adds a failure mode to `ListItem`. Failures to rewrite list items need no longer result in panics, but can be gracefully handled as we do other rewrite failures. This addresses parts of https://github.com/nrc/rustfmt/issues/133.
- Take into account the length of the separators for the line splitting heuristic in functions and items. To compensate for this, the limits have been raised from 50 to 55 and from 12 to 16 …

List formatting refactoring

---

tests/system.rs

This PR is in response to issue #306
The code that manipulates paths to try and find files in the target dir was not handling windows file separators correctly. The code has been updated to use the path module, and hopefully will play nicer across operating systems.
I've tested the code on Windows, but have not yet had a chance to test on other operating systems.
I've got a somewhat ugly bit of code in there that calls next() twice on an iterator to skip the first two elements. I was unable to get this working with .skip(2), as the iterator returned by doing so no longer exposed the functions required. Please advise if there is a better way to do this.

Fix path issue with tests on Windows

---

src/visitor.rs
tests/target/fn.rs

Actually just skips inner attributes, because its a pain to track them, and lets missed spans handle them.
Closes #413

Format inner and outer attributes separately.

---

src/expr.rs
src/missed_spans.rs
tests/source/chains.rs
tests/target/chains.rs
tests/target/hard-tabs.rs

This means that we try formatting the last argument of a function call with block indentation instead of visual indentation when it is a closure and its first line fits on the same line as the first arguments.
This closes https://github.com/nrc/rustfmt/issues/263.

Try "overflowing" the final function argument when it's a closure

---

src/expr.rs

There was an extra, unused, paramter int he match arm which causes an
error when compiling with the latest nightly.

Fix Build to Compile with 1.5.0-nightly (87cd2c082)

---

src/items.rs
tests/source/extern.rs
tests/target/extern.rs

Closes https://github.com/nrc/rustfmt/issues/441.

Format variadic arguments

---

src/expr.rs
tests/source/expr.rs
tests/target/expr.rs

This fixes https://github.com/nrc/rustfmt/issues/440.

Use visual block indentation for array literals

---

src/chains.rs
tests/source/hard-tabs.rs
tests/target/hard-tabs.rs

Fixes one of the issues detailed in https://github.com/nrc/rustfmt/issues/454.

Indent uncontinued chains to block level

---

src/expr.rs
src/visitor.rs
tests/source/expr.rs
tests/target/expr.rs
tests/target/match.rs

Close https://github.com/nrc/rustfmt/issues/422.
Close https://github.com/nrc/rustfmt/issues/353.

Force semicolons after break/continue/return. Remove after blocks.

---

src/expr.rs
src/items.rs
tests/source/extern.rs
tests/source/mod-1.rs
tests/target/extern.rs
tests/target/mod-1.rs

Closes https://github.com/nrc/rustfmt/issues/466.
I cannot reproduce the issue with inline modules..

Properly indent pub fns in extern blocks

---

src/expr.rs
src/items.rs
src/types.rs
src/utils.rs
tests/source/type.rs
tests/target/type.rs

Add formatting for almost all types. Only bare functions types are not formatted yet. We have a lot of function type formatting code already in function definitions and paths, it's just a matter of reusing that logic nicely now.
Also did some cleanups of instances where we assumed we wouldn't run over the width limit.

Format more type variants

---

src/items.rs
tests/source/fn-simple.rs
tests/target/fn-simple.rs

This fixes https://github.com/nrc/rustfmt/issues/424.

Fix indentation for function arguments

---

src/items.rs
src/visitor.rs
tests/source/static.rs
tests/target/static.rs

Closes https://github.com/nrc/rustfmt/issues/431 and https://github.com/nrc/rustfmt/issues/465.

Format constants and static variables

---

src/items.rs
src/visitor.rs
tests/source/enum.rs
tests/source/structs.rs
tests/target/enum.rs
tests/target/structs.rs

Unify formatting code for enum variants and structs.
Fix https://github.com/nrc/rustfmt/issues/406.

Refactor enum formatting

---

Cargo.lock
src/comment.rs
src/expr.rs
src/items.rs
src/missed_spans.rs
src/rewrite.rs
src/visitor.rs
tests/source/comment.rs
tests/target/closure.rs
tests/target/comment.rs
tests/target/doc.rs
tests/target/expr.rs
tests/target/match.rs
tests/target/multiple.rs

This tries to format comments in missed spans according to the rules laid out in https://github.com/nrc/rustfmt/issues/305#issuecomment-139401650.
I'm pretty content with the output, but the implementation is still *very* hacky. I'd like to give it a thorough cleanup before merging. Any tips on how this could be done would be much appreciated.
This should close https://github.com/nrc/rustfmt/issues/333 and https://github.com/nrc/rustfmt/issues/405.
It partially addresses https://github.com/nrc/rustfmt/issues/27 and https://github.com/nrc/rustfmt/issues/305.

Format more comments

---

src/visitor.rs
tests/source/trait.rs
tests/target/impl.rs
tests/target/trait.rs

This is much more straightforward to understand given how rustfmt
rewriting works, and it avoids walking into expressions in unexpected
places.
Fixes #513. Fixes #514.

Don't use `visit::walk_*`.  Instead, recurse by hand.

---

src/chains.rs
src/config.rs
tests/source/chains-block-indented-base.rs
tests/source/chains.rs
tests/target/chains-block-indented-base.rs
tests/target/chains.rs

One of many possible approaches. I think this one is most in line with the way we format closures; block indentation if it's the last link in the call chain, visual otherwise.
Typical output with this strategy:
```rust
let x = match x {
...
}
.foo()
.bar();
```
Other options to consider:
- format with block indent, continue chain on same line as closing brace/ parenthesis of parent
```rust
let x = match x {
...
}.foo()
.bar();
```
- format with block indent, continue on next line with extra indentation
```rust
let x = match x {
...
}
.foo()
.bar();
```
- format with visual indentation, continue on next line without extra indentation
```rust
let x = match x {
...
}
.foo()
.bar();
```
- format with block indentation, continue on next line without extra indentation
```rust
let x = match x { …
```

Deal with floaters

---

.travis.yml
Cargo.lock
Cargo.toml
README.md
src/bin/rustfmt.rs
src/chains.rs
src/comment.rs
src/lib.rs
src/macros.rs
src/utils.rs
tests/source/macro_not_expr.rs
tests/system.rs
tests/target/macro_not_expr.rs

These commits drop all dependencies on nightly features, primarily:
* `rustc` and `rustc_driver` were dropped as they were just lightly used
* `syntax` was dropped in favor of [`syntex_syntax`](https://crates.io/crates/syntex_syntax)
* `catch_panic` was dropped in favor of spawning a thread an managing the ident interner manually
The business around `catch_panic` is kinda sketchy (and slow in debug mode), but there's a number of benefits to building on stable!
* Stable is stable :)
* rustfmt binaries do not have a dynamic dependence on the compiler
* rustfmt will no longer periodically break due to upstream libsyntax changes
* `cargo install` should "just work" for many more compilers now (e.g. not just nightly ones)
The downsides I can think of are:
* libsyntax will need to be updated …

Move to stable Rust

---

src/expr.rs
src/lib.rs
src/macros.rs
src/rewrite.rs
src/visitor.rs
tests/source/macros.rs
tests/target/macros.rs

The problem is essentially that if we try to parse a token tree using a
CodeMap different from the one the tree was originally parsed with,
spans become nonsense. Since CodeMaps can't be cloned, we're basically
forced to use the original ParseSess for additional parsing.
Ideally, rustfmt would be a bit more clever and figure out how to parse
macro arguments based on the definition of the macro itself, rather than
just guessing that a particular token sequence looks like an expression,
but this is good enough for now.
Fixes #538.

Fix crash speculatively parsing macro arguments as expressions.

---

src/bin/rustfmt.rs
src/filemap.rs
src/lib.rs

I was trying to get rustfmt work with https://github.com/Chiel92/vim-autoformat and found to my surprise that there seems to be no support for receiving a string on stdin and outputting a simple formatting to stdout.
This is actually the default behavior of most formatting tools, like `gofmt`, and really vital for IDE and tooling integration. I'm sorry if I'm misunderstanding something and rustfmt already supports it somehow. Feel free to close in that case!
Most of the existing code seems to be built with a multiple-file codemap in mind, making it hard to whip up a perfect solution in trivial time. My approach is trying to get the job done without breaking existing behavior.
tl;dr
- `rustfmt` will now read from stdin if no file was specified and format that code without walking any other …

Stdin support

---

src/bin/rustfmt.rs

remove following warning
```
src/bin/rustfmt.rs:97:21: 97:25 warning: unused variable: `path`, #[warn(unused_variables)] on by default
src/bin/rustfmt.rs:97                 Ok((path, toml)) => {
^~~~
```

fix unused variable `path` warning

---

src/bin/rustfmt.rs

The existing help output is very verbose, overflowing a 50+ line
terminal. This moves the configuration options to a separate help flag
to make a mistyped command less annoying!

Move config help to dedicated --config-help flag

---

src/comment.rs
src/config.rs
tests/source/attrib.rs
tests/source/comment.rs
tests/source/comment2.rs
tests/source/comment3.rs
tests/source/enum.rs
tests/source/expr.rs
tests/source/hard-tabs.rs
tests/source/multiple.rs
tests/source/struct_lits.rs
tests/source/struct_lits_multiline.rs
tests/source/struct_lits_visual.rs
tests/source/struct_lits_visual_multiline.rs
tests/source/structs.rs
tests/target/attrib.rs
tests/target/comment.rs
tests/target/comment2.rs
tests/target/comment3.rs
tests/target/enum.rs
tests/target/expr.rs
tests/target/hard-tabs.rs
tests/target/multiple.rs
tests/target/struct_lits.rs
tests/target/struct_lits_multiline.rs
tests/target/struct_lits_visual.rs
tests/target/struct_lits_visual_multiline.rs
tests/target/structs.rs

Set to false by default for now, since we are having a lot of problems with comments. We should set to true once we have a better algorithm.

Option to disable line breaking in comments

---

src/bin/rustfmt.rs

Was kinda surprised to see my config file being ignored when I ran rustfmt from the project root directory, which is where I keep my rustfmt.toml.

Check if the CWD contains a config (previously it only checked parents)

---

.travis.yml
README.md

* Create release binaries when you created tags
* Build and test on OS X too (but archives aren't created)
* Add build status badge to README.md
You need to get API key for Github and encrypt it with travis CLI, then past it at `secure` section. (Supposing you have installed travis CLI, you can encrypt your API key with `travis encrypt -r nrc/rustfmt <API key>`.)
I tried to build binaries other than linux but
* Cross compilations aren't supported because you need to add some options when you build rust compilers
* You can't create release archives from multiple OS's because archive names conflicts at `file` section.
How do you like?

Create a binary from travis ci and so on

---

.travis.yml

As this project grows, it might be beneficial to require pull requests
to keep a certain level of test coverage. Plus it's a fun statistic.
Somebody with access to this repo would have to enable it in https://coveralls.io/.

Report test coverage with travis-cargo & coveralls

---

README.md

Reopening #586 .
The integration is a one-liner so the gist is no longer necessary. The details are available on [emacs-rustfmt)](https://github.com/fbergroth/emacs-rustfmt)'s readme.
/cc @fbergroth

Add emacs integration to readme.

---

src/bin/rustfmt.rs

Fix #580 by allowing rustfmt to accept a list of files. This also enables usage of shell wildcard expansion, although notably this does not work with cmd.exe on Windows. For example: `rustfmt *.rs` will format all rust files in the current working directory.
- Change usage text to show rustfmt will accept a list of files
- Change `Using rustfmt config file: {}` message to `Using rustfmt config file {} for {}`
- Change `Operation::Format(PathBuf, WriteMode)` to `Operation::Format(Vec<PathBuf>, WriteMode)`
- Loop through `Vec<PathBuf>`, load config and call 'run' for each path

Enable rustfmt to format a list of files

---

src/lib.rs

The Display implementation for FormatReport already prints
a newline after every error.
However, if the format report does not contain errors, we
don't want to print an empty newline.
This behavior clutters up the console output with
empty lines when rustfmt is invoked multiple times
(from .e.g a script or cargo-fmt).
So instead of using println! to print the report, we just
use print!.

Don't print an unnecessary newline after printing format report

---

src/chains.rs
src/config.rs
tests/source/chains-indent-inherit.rs
tests/source/chains-indent-tabbed.rs
tests/source/chains-indent-visual.rs
tests/target/chains-indent-inherit.rs
tests/target/chains-indent-tabbed.rs
tests/target/chains-indent-visual.rs

When breaking chains, the indentation was too large in "Tabbed" mode. Is this the correct way to fix this?

Chains tabbed indent

---

src/expr.rs
src/imports.rs
src/patterns.rs
src/types.rs
tests/source/paths.rs
tests/target/paths.rs

This gets rid of a slightly nasty hack involving scanning the source
expression for a ":".

Pass in whether an ast::Path is in an expression context.

---

src/config.rs
src/filemap.rs

By using it one will get `\r\n` line endings on Windows, and `\n` line endings on other platforms. This is the ideal case when using [git's autocrlf option](https://git-scm.com/book/tr/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace).

Adding a "Native" option to newline_style.

---

src/bin/rustfmt.rs

Usage messages traditionally use this as it contains the path that the
user provided to run the executable (e.g. `rustfmt` instead of
`/usr/local/bin/rustfmt`).

Use argv[0] for usage output

---

src/config.rs
src/expr.rs
src/items.rs
src/utils.rs
src/visitor.rs
tests/source/fn-single-line.rs
tests/target/attrib.rs
tests/target/comment.rs
tests/target/comments-fn.rs
tests/target/fn-simple.rs
tests/target/fn-single-line.rs
tests/target/fn.rs
tests/target/multiple.rs
tests/target/nestedmod/mod2c.rs
tests/target/nestedmod/mymod1/mod3a.rs
tests/target/nestedmod/submod2/a.rs
tests/target/no_new_line_beginning.rs
tests/target/paths.rs

Fixes #262.
Formats empty-body functions on a single-line if possible, and adds the `fn_single_line` option to do the same for single-statement/expression functions.
Organizational changes:
* `semicolon_for_stmt`, `semicolon_for_expr` moved to utils module; I wasn't sure if these were better suited in the expr module.
* `visit_stmt` logic split off into `impl Rewrite for ast::Stmt`. The visit function still takes care of the logic for visiting/rewriting Items and Macs.

Single-line Functions

---

src/missed_spans.rs
tests/source/comment_crlf_newline.rs
tests/target/comment_crlf_newline.rs

When block comments were rewritten to line comments they check if a new line needs to be added and adds one if needed. It only checked for '\n' however which would cause a newline to be added even if the comment was ended by "\r\n".

Avoid adding an extra newline after block comments

---

src/items.rs
src/lists.rs
tests/source/structs.rs
tests/target/imports.rs
tests/target/structs.rs

Fix https://github.com/rust-lang-nursery/rustfmt/issues/572.

Correct doc comment indentation for struct fields

---

src/items.rs
src/utils.rs
tests/source/impls.rs
tests/target/impl.rs
tests/target/impls.rs

Fixes #651, yo.
This also keeps comments that exist after impl items, e.g.
```rust
impl Foo() {
fn foo() {}
// Comment 3
}
```
However, I notice there's an existing test in impls.rs that removes such comments, so I can do the same if desired.

Keep comments in empty impl body

---

src/macros.rs

This was hidden by rust-lang/rust#30078.

Remove unused imports

---

src/config.rs
src/expr.rs
tests/source/match-block-trailing-comma.rs
tests/source/match-nowrap-trailing-comma.rs
tests/target/match-block-trailing-comma.rs
tests/target/match-nowrap-trailing-comma.rs

Attempt to implement an option for trailing commas for block based match arms (issue
#173). I'd appreciate any feedback. A smattering of questions and a comment:
- Style wise, is it preferable to pass the context into arm_comma, or use it to gate calling arm_comma?
- Is my supposition that the check around line 964 is to figure out if we have a block or not, if so, spit it out as is, otherwise fall through and wrap it as appropriate? I'm concerned there are some unknown unknown (to me) code paths around this area.

WIP: Trailing commas for match block arms

---

src/items.rs
tests/source/type_alias.rs
tests/target/type_alias.rs

Followup of #640 which fixes where clauses (which I forgot about) and an edge case where '=' was close or at the max width.

Fix missed edgecases in formatting of type aliases

---

src/bin/rustfmt.rs

Add --version switch, which prints a short hash of the current commit. Fix #612

Add --version switch

---

src/visitor.rs
tests/source/structs.rs
tests/target/fn.rs

Fix https://github.com/rust-lang-nursery/rustfmt/issues/661.

Don't include failed item rewrites in missed spans

---

src/comment.rs
src/config.rs
src/visitor.rs
tests/source/comment4.rs
tests/target/comment.rs
tests/target/comment4.rs

So block comments are not converted to line comments
Fixes #610 
cc #518

Add normalise_comments option.

---

Cargo.lock
Cargo.toml
README.md
src/bin/cargo-fmt.rs

Fix #613 by adding a new utility, which formats all readable `.rs` files in the `src` directory of the crate using `rustfmt` binary. Both binaries can be installed using `cargo install rustfmt`, users that don't need `cargo-fmt` can opt-out by disabling default features. `cargo-fmt` can be used as a Cargo subcommand - `cargo fmt`.
There is a downside to having 2 binaries in a crate: `cargo run` can no longer be used without the `--bin` flag to specify which binary to run.

Add cargo-fmt binary

---

src/bin/cargo-fmt.rs

Since replace is the default rustfmt write mode, there's no need to
call rustfmt with `--write-mode=replace`. As a bonus, it is now also
possible to override the write-mode.

Remove `--write-mode=replace` from cargo-fmt

---

src/bin/rustfmt.rs
src/config.rs
src/lib.rs

Fixes #400.
I'm not sure how should I add a test for the option :)

add option to ignore out of line modules

---

src/string.rs
tests/source/string-lit.rs
tests/target/string-lit.rs

This fixes the removal of backslashes as reported in https://github.com/rust-lang-nursery/rustfmt/issues/716. We still insert unnecessary line breaks, though.

Prevent incorrect backslash removal in strings

---

src/items.rs
src/utils.rs
tests/source/impls.rs
tests/target/impls.rs

Closes https://github.com/rust-lang-nursery/rustfmt/issues/724.

Make fn argument formatting more resilient for complex self types

---

src/utils.rs

This time the code is a true hack, I do not like that I had to switch it from a match to many if statements, but I did not see a different way of doing so.

ignore case for config enums. Fixes #738

---

src/expr.rs
src/items.rs
src/lists.rs
src/missed_spans.rs
src/types.rs
src/utils.rs

Clippy rustfmt

---

src/expr.rs
tests/source/match.rs
tests/target/match.rs

Add commas after skipped arms when needed

---

src/lib.rs

The '\r' character wasn't counted in the line length.
I think it's not possible to add regression tests for this due to git behavior with line endings.

Fix issue with windows line endings (#717).

---

src/comment.rs
src/expr.rs
tests/source/paths.rs
tests/target/comment-not-disappear.rs
tests/target/paths.rs

When the reformatted code doesn't contain the same quantity of comments
as the original code, use the original code instead of the reformatted
code.
This is done for all expressions and `let` statements.
This should be used at the finest grained level possible, to avoid that
a small disappearing comment prevents a big chunk of code to be
reformatted.
Kind of fixes (avoid disappearing comments, but prevents a good
formatting is such case) #285 #225 #563 #743
This allows to take a policy of deliberately ignoring a lot of the numerous weird places where comment can be, and only reformat comments that are in places where we expect them to be.
I think we should add a warning when this recovery mechanism is used, but I'm not sure how to best implement it: maybe put a list of `FormattingError` …

Detect (and recover) when comments disappear

---

src/items.rs
tests/source/fn-single-line.rs
tests/target/fn-single-line.rs
tests/target/fn.rs

If `fn_empty_single_line` is true, and a function's body is empty, its where clause is put on the same line as the `fn`.
ex:
```
+ fn Foo<T>() where T: Bar {}
- fn Foo<T>() 
-     where T: Bar 
- {
- }
```

Where clause is on same line as fn if fn is empty Fixes #760

---

src/expr.rs
src/utils.rs
tests/source/issue-447.rs
tests/target/comment-not-disappear.rs
tests/target/issue-447.rs

For a bit more history try to read the broken PR #754.
So it should now handle every possible comment position for a `if {} if else {} else` block except comments inside the pattern of a `if let X = Y` when this PR is accepted I would write another one that handles comments there if it's permitted. (Comments in the pattern are discarded but do not break the formating)
It was a bit cumbersome to find the right Span's where the comments where so it is understandable how I did it?
I didn't try to split it into smaller methods at the moment.

Fix #447 2. try

---

src/config.rs
src/items.rs
tests/source/impls.rs
tests/target/impls.rs

If the `where` clause is on the same line as the `impl`, `{` is put on a new line. Fixes issue #650

Fix for #650

---

src/config.rs
src/types.rs
tests/source/type-punctuation.rs
tests/target/type-punctuation.rs

Added config option type_punctuation_density that can be set to `TypeDensity::Compressed` or `TypeDensity::WhiteSpace`.
Default option is `WhiteSpace`, if `Compressed` is enabled it will format as follows:
```
- fn Foo<T = Foo, Output = Expr<'tcx> + Foo>() {
+ fn Foo<T=Foo, Output=Expr<'tcx>+Foo>() {
...
```

Added option for tighter punctuation in types. fixes #489

---

src/bin/rustfmt.rs
src/config.rs
src/filemap.rs
src/lib.rs
src/missed_spans.rs
src/visitor.rs
tests/system.rs

Also from @marcusklaas:
> Refactor code output functions          
> Specifically, `write_all_files` no longer returns a HashMap. It would sometimes
> contain items, and sometimes be empty. When "fixed" newlines are required, this
> must now be done with a separate call. The tests use this strategy and should now pass!
I did not know how to mantain his PR commit and do the clean rebase at the same time...
Refer to #764, and #735 for more information.

Allow for setting of write-mode via config file. FIxes #215

---

src/expr.rs
src/items.rs
tests/source/struct_lits.rs
tests/target/struct_lits.rs

Also allows splitting the field expression on a new line after the field name.
Fixes #698 

Fix an off-by-one error due to the comma in a struct lit field

---

src/macros.rs
src/visitor.rs
tests/source/macros.rs
tests/target/macros.rs

With macro spans fixed in Rust 1.6, we can now format ItemMac properly. Part of #438.

Format item macros

---

src/config.rs
src/items.rs
tests/config/small_tabs.toml
tests/source/where-trailing-comma.rs
tests/target/where-trailing-comma.rs

The default is 'false', since a lot of the time there's only a single predicate. Resolves #588.

Added where_trailing_comma option.

---

src/missed_spans.rs
tests/source/comment.rs
tests/target/comment.rs

The case where `line_start == snippet.len()` wasn't handled so we had a missing newline.
Since we can't get the next char after `line_start` in this case I handle the `None` implicitly with the match.

Fix for #784 edge case in comment handling

---

src/bin/rustfmt.rs

`lookup_project_file` could erroneously find a *directory* named
`rustmfmt.toml` if there was one in its lookup path, and so ignore any
configuration file it should have found further up. The error handling
resulted in this silently using the default configuration.

bin: Properly handle a directories named rustfmt.toml

---

tests/system.rs
tests/target/chains-no-overlow-2.rs

`Result::expect()` was added in Rust 1.4. Using it tidies up the code,
and also helps by printing error details, eg, printing syntax error
details if a regex fails to compile. It adds a colon followed by the
`Debug` output from any error, making the periods in messages
unnecessary.

tests: Use Result::expect() throughout

---

src/bin/rustfmt.rs

Previously errors were being silently ignored. Eg, if `rustfmt` did not
have permission to read a `rustfmt.toml` file, the default configuration
was used without informing the user.

bin: Improve error handling in project file lookup

---

src/lib.rs

The `args` parameter was removed in 579fb34.

cleanup: Remove documentation of deleted parameter

---

.gitignore

These clutter up `git status` output when working on rustfmt.

gitignore .rs.bk files

---

src/config.rs
src/expr.rs
tests/source/string-lit-2.rs
tests/source/string-lit.rs
tests/target/string-lit-2.rs
tests/target/string-lit.rs

Specifically if no line exceeds the allowed width and we aren't moving the string to a new offset

Don't reformat strings if we don't have to.

---

README.md

`cargo run -- --config-help` Simply runs a project without printing the config options.
`rustfmt --config-help` actually prints the config files.

Correct command that lists config options

---

src/imports.rs
src/patterns.rs
tests/source/pattern.rs
tests/system.rs
tests/target/match.rs
tests/target/pattern.rs

Format all patterns (well, except macros)

---

src/bin/rustfmt.rs

This allows one to redirect checkstyle and diff output directly to a file.
```
:;  cargo fmt -- --write-mode checkstyle > xml.xml
Using rustfmt config file /Users/solidsnack/sandbox/jsoncdc/rustfmt.toml for /Users/solidsnack/sandbox/jsoncdc/src/lib.rs
```

Write non-output to stderr when there is output

---

src/expr.rs
src/imports.rs
src/items.rs
src/macros.rs
src/patterns.rs
src/types.rs
src/utils.rs
src/visitor.rs

This commit adds a CodeMapExt extension trait on CodeMap, and moves some
functions to methods there:
- span_after
- span_after_last
- span_before
This better reflects them being lookup methods on the codemap.

utils: Add CodeMapExt extension trait for span_* methods

---

README.md

It was previously unclear that the `cfg_attr` version works in stable
Rust.

readme: Clarify the ways of specifying rustfmt_skip

---

src/config.rs
src/items.rs
tests/source/fn-custom-7.rs
tests/source/fn_args_density-vertical.rs
tests/target/fn-custom-7.rs
tests/target/fn_args_density-vertical.rs

I wanted this feature for my self, so I added it. I enjoy consistency, so sometimes I like to have the arguments formatted in a way that doesn't change when something gets renamed.
While writing the test, I noticed a bug in the comment formatting. Not strictly related to this feature, but it triggers with the test so I included the fix in the same pull request.

Add option for vertical function argument list

---

src/macros.rs
tests/source/macros.rs
tests/target/macros.rs

Fixes https://github.com/rust-lang-nursery/rustfmt/issues/839 and https://github.com/rust-lang-nursery/rustfmt/issues/536.
Empty macro invocations with comments and parens or brackets, e.g. `test!(/*comment*/)`, won't compile any longer for some reason.

Fix issues with empty macros with curly braces

---

src/types.rs
tests/source/type_alias.rs
tests/target/type_alias.rs

Fixes https://github.com/rust-lang-nursery/rustfmt/issues/830.

Remove trailing whitespace for fn types /w non-unit return

---

src/bin/cargo-fmt.rs

This is completely unimportant and may be not worth merging, but still.
When reading [`format_files`](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/bin/cargo-fmt.rs#L157) function I thought "So if we pass both `quite` and `verbose` then we print something, but it is not shown because we redirected stdout to null". A moment later I realized that we in fact enforce `!(verbose && quite)` invariant two functions up in the call stack. 
So let's, per Yaron Minsky advice, make this illegal state unrepresentable by using a Verbosity `enum`, proudly [stolen](https://github.com/rust-lang/cargo/blob/834b834db5e3b095e68f9881be35f020ac5e2aed/src/cargo/core/shell.rs#L15) from `cargo`.
You want to view only [the second](https://github.com/rust-lang-nursery/rustfmt/commit/c7e51d3994f3fc885b …

Introduce verbosity enum

---

src/string.rs
src/utils.rs

NB The custom method returned 0 on an input of 0, which is arguably
incorrect: 0 is not a power of two; the method in `std` returns 1 in
that case.

Use checked_next_power_of_two from std instead of custom method

---

src/expr.rs
src/macros.rs
src/visitor.rs
tests/source/macros.rs
tests/target/macros.rs

Fixes https://github.com/rust-lang-nursery/rustfmt/issues/806.

Properly format macro's with an extra ident

---

Cargo.lock
src/expr.rs
tests/source/expr.rs
tests/target/expr.rs

Closes https://github.com/rust-lang-nursery/rustfmt/issues/890.

Format closed ranges

---

src/items.rs
tests/source/fn-custom-6.rs
tests/source/fn-custom-7.rs
tests/source/fn_args_layout-block.rs
tests/target/fn-custom-6.rs
tests/target/fn-custom-7.rs
tests/target/fn_args_layout-block.rs

The closing parenthesis for the arg list was written on a new line without first applying the appropriate indent.
Fixes #707.

Fix incorrect indent with fn_args_layout: Block

---

src/bin/rustfmt.rs

rustfmt writes some messages like "Using rustfmt config file..." to stderr instead stdout, but it is not error.

Fix. rustfmt write to stderr instead stdout

---

src/macros.rs

The error handling in libsyntax changed to use a `DiagnosticBuilder`
type in the `Err` variant of `PResult`. This type has `emit()` and
`cancel()` methods. Once created, errors must be emitted or canceled; if
not, the `Drop` impl on `DiagnosticBuilder` will panic.
The first syntex_syntax release to include this change was v0.25.0. The
bump from v0.23.0 to v0.29.1 in #847 did not add any `cancel()` calls,
even though at least one was required. There may be others not caught in
this commit.

macros: Cancel DiagnosticBuilder when not emitting error

---

src/comment.rs
src/string.rs
tests/target/enum.rs
tests/target/hard-tabs.rs
tests/target/string-lit-2.rs
tests/target/string-lit.rs
tests/target/string_punctuation.rs
tests/target/struct_lits_visual.rs
tests/target/struct_lits_visual_multiline.rs

We will no longer break in the middle of words, only at whitespace or punctuation.
This means we sometimes over-run, but that seems better than some of the bad splits we see.
Closes #369 

Don't be so aggressive about line-breaking strings

---

src/config.rs
src/expr.rs
src/macros.rs
src/types.rs
src/utils.rs
src/visitor.rs
tests/source/match.rs
tests/target/match.rs

Refactor to use the list code, don't preserve original stacking-ness, base vertical vs mixed formatting on complexity of the patterns.
Closes #386 

Change the logic around breaking multiple patterns in match arms

---

src/lib.rs
tests/system.rs

unify format_string and format_file

---

src/bin/rustfmt.rs

These commits improve error handling in the `rustfmt` binary more
idiomatic by
- replacing the `Operation::InvalidInput` variant with `Result`
- using the `try!()` macro instead of explicit matching
- using guard patterns in a match expression

rustfmt: Make error handling more idiomatic

---

src/lib.rs

This `if` was used to separate error output from the formatting output, when they both used stdout. It was useful for integration with tools, which can submit input to stdin and read pretty printed result from stdout without worrying about errors intermingled with the actual result. 
But now we write errors to `stderr`, so the problem disappears and we can safely remove this `if`.
Related to #907

don't silence error unnecessary

---

README.md
src/bin/rustfmt.rs
src/lib.rs
src/summary.rs
tests/system.rs

closes #150
@nrc please review

return non-zero exit code if there are errors

---

src/expr.rs
tests/source/closure.rs
tests/target/closure.rs

Closes #934
Oh god, the rules for parsing closures are even more messed up than I thought - whether or not there is an inner block or depends not only on if there are braces, but also if there is a return type for the closure (!) and if there are statements in the block.

Fix closures again

---

src/lib.rs

if `rustffmt` is invoked like `rustfmt foo.rs bar.rs baz.rs`, it will print three blank lines to `stderr`. This fixes the behavior.

Don't print empty lines to stderr

---

src/config.rs
src/utils.rs

The `ConfigType` trait is implemented for non-enum types, so the name no
longer makes perfect sense.

config: Rename get_variant_names to doc_hint

---

src/config.rs
src/items.rs
src/types.rs
src/utils.rs
tests/source/extern_not_explicit.rs
tests/target/extern_not_explicit.rs

Closes https://github.com/rust-lang-nursery/rustfmt/issues/451.

Add option to force explicit extern ABI's

---

bootstrap.sh
src/bin/cargo-fmt.rs
src/bin/rustfmt.rs
src/chains.rs
src/comment.rs
src/config.rs
src/expr.rs
src/items.rs
src/lists.rs
src/macros.rs
src/missed_spans.rs
src/patterns.rs
src/rewrite.rs
src/string.rs
src/types.rs
src/utils.rs
src/visitor.rs
tests/source/chains-visual.rs
tests/system.rs
tests/target/chains-indent-visual.rs
tests/target/chains-no-overflow.rs
tests/target/chains-no-overlow-2.rs
tests/target/chains-visual.rs
tests/target/chains.rs
tests/target/hard-tabs.rs
tests/target/long_field_access.rs

Closes #690 
Closes #439 
cc #566 (not fixed, but an improvement).
This probably needs some polishing, but I'd like to land it and then weed out the bugs. I'm sure there are edge cases for chains that are now worse. We can probably apply the 'big closure' in other places, though I'm not sure where.

Block indent large closures and field/method chains

---

src/lib.rs

Outputting child module contents in the "Plain" write mode does not make sense, since there is no way to differentiate code that came from a child module from that which came from the parent file.
Fixes #939.  If this is merged, integrations that want to run a single file can send it on stdin and need not specify any flags--the output will contain only the reformatted code that was input.

Always skip children when using Plain write mode

---

src/types.rs
tests/target/associated-items.rs

The rewritten location of the :: on global paths for qpaths was wrong.
Fixes #972.

Don't misplace the :: on associated items.

---

src/visitor.rs

Generated spans were causing format to fail, as the format_missing methods expected continuous byte positions - this update used the callsite spans for those methods (and for setting last_pos) to circumvent this issue - no change on non-generated code.

Altered FmtVisitor to function correctly on generated code

---

Cargo.lock
src/filemap.rs
src/lib.rs
src/summary.rs
tests/system.rs

The old behaviour stored everything in memory until we were finished. Now we write as soon as we can.
This gives better behaviour when formatting large programs, since there is some progress indication. It also opens the door to optimising memory use by not storing everything in memory unless it is required (which it still might be). That is left as future work though.

Write each file as it is formatted

---

src/comment.rs
src/config.rs
tests/source/comment4.rs
tests/target/comment4.rs

Normalize as American english is more common across programming community

change  normalise spelling to American version - 

---

src/config.rs
src/issues.rs
src/items.rs
src/visitor.rs
tests/target/enum-no_trailing_comma.rs
tests/target/enum.rs
tests/target/where-trailing-comma.rs

Optionally put short struct variants on one line

---

src/items.rs
tests/target/fn-custom.rs
tests/target/fn.rs

Fixes #1000
This is a little conservative in some cases, but better than being wrong in others.

Fix off by 2 error in function sigs

---

Cargo.lock
src/patterns.rs
src/types.rs
tests/source/type.rs
tests/target/type.rs

Don't ignore universal quantification in function types

---

Cargo.lock
Cargo.toml
src/rustfmt_diff.rs

On unix, `term::stdout()` just reads the `TERM` environment variable to
decide what features are available. It does not check if the output file
descriptor is in fact a tty. This resulted in printing escape codes when
redirecting output.

print_diff: Don't print color codes if output is not a tty

---

src/items.rs
src/visitor.rs
tests/source/issue-945.rs
tests/target/issue-945.rs

Adds support for Defaultness on impl methods.
Fixes #945 
(3 of the tests don't pass on master right now on my machine: file-lines-1, file-lines-2, file-lines-3 and this PR doesn't change this behavior: the same tests pass on master and here, so hopefully everything is correct :)

Add support for the `default` keyword

---

src/chains.rs
tests/source/chains.rs
tests/target/chains.rs

Treat chains with just expr? specially.

---

README.md

It seems as though the official Vim plugin has added the option to run rustfmt on save. This is probably much easier for users to enable than the previous instructions.

Update Vim integration instructions

---

Cargo.lock
Cargo.toml
build.rs
src/bin/rustfmt.rs
tests/system.rs

This will help in debugging issues as rustfmt gets more users.
If the working tree is clean, output looks like
$ target/debug/rustfmt -V
0.5.0 (9f5ed3b)
If the working tree is dirty, output looks like
$ target/debug/rustfmt -V
0.5.0 (9f5ed3b worktree dirty)
If git is unavailable, output looks like
$ target/debug/rustfmt -V
0.5.0 (git commit unavailable)
To avoid rebuilds on changing tests, the build script will only rerun if
files under src/ are changed. This means the actual git status may show
changed files and this would not show up in the version. This should not
be an issue as files not in src/ should not affect the build output.

Include git commit and worktree status in version output

---

src/bin/rustfmt.rs
src/filemap.rs
src/lib.rs
src/summary.rs

This changes rustfmt to return the number
of found differences as exit code when run with
write mode diff.
Useful for CI to make sure your contributors actually ran rustfmt.

Return failure exit code on found diffs (fix #906)

---

Contributing.md

I searched for the `nrc` keyword in the repo and found out that it's also present in `.travis.yml`.Does it need to be updated there as well? I am not familiar with travis config files and do not know what that specific config is used for.

Links to the rust-lang-nursery/rustfmt issue list.

---

src/bin/cargo-fmt.rs

Show more helpful error if rustfmt is not in PATH.

---

src/comment.rs
tests/source/comment.rs
tests/target/comment.rs

#1086 
Fixes panic when formatting `/**/`.
Empty or whitespace comments next to patterns (the code in issue #1086) disappear, which seems to be another existing problem.
Both
```rust
match value {
_ /* */ => {
fn2();
}
}
```
and
```rust
match value {
_ /**/ => {
fn2();
}
}
```
are formatted as
```rust
match_ value {
_ => {
fn2();
}
}
```

Fix formatting empty block comments (`/**/`)

---

README.md
appveyor.yml

After mentioning it in #1097, I've added an `appveyor.yml` (based on the one in [rust-everywhere](https://github.com/japaric/rust-everywhere), which builds all variants of {stable, beta, nightly}, {MSVC x64, MSVC x86, gcc x64, gcc x86}) and a link to an Appveyor badge in `README.md`.
To complete the job, the rustfmt repo will have to be added as a new project in Appveyor. I've added my fork under my Appveyor account and it's running on Appveyor as expected.

Add Appveyor CI support

---

README.md
src/bin/rustfmt.rs

Now is possible to have a *hidden* file with name `.rustfmt.toml`. Also due to the parent directory searching it is possible to keep a global `.rustfmt.toml` file in the *home* directory if preferred.
With this **rustfmt** will look for files named either `rustfmt.toml` or `.rustfmt.toml`; But new file names can be easily added if needed.

Multiple config file names feature

---

src/items.rs
tests/source/issue-1049.rs
tests/target/issue-1049.rs

Fix off-by-one error in rewrite_fn_base.  #1049 
Also remove a line break.

Fix overlong function signature

---

README.md

Multirust is deprecated so I thought it might be a good idea to have the rustup.rs instructions instead.

Update README with Rustup.rs instead of multirust

---

src/config.rs
src/items.rs
src/types.rs
tests/source/space-before-bound.rs
tests/source/space-before-type-annotation.rs
tests/target/space-before-bound.rs
tests/target/space-before-type-annotation.rs

* An option to leave a space before the colon in a type annotation
* An option to leave a space before the colon in a trait or lifetime bound

Add two new whitespace options (#1109)

---

src/imports.rs

Fixes underflow described in #1116.

Fix underflow in format_imports

---

src/imports.rs
tests/source/issue-1120.rs
tests/target/issue-1120.rs

This fixes #1120, by ensuring that the start of the prefix before a list of `use` declarations cannot be before the last character processed by the formatter.
The prefix is also trimmed when we can detect that it ends with the indent whitespace of a `use` declaration within a block.

Fix #1120 - rework how the use list prefix is determined.

---

src/filemap.rs
tests/system.rs

Addresses #807 - the added test doesn't actually test the changed code, but since its a minor detail and this is not an issue about correctness then I thought it'd be ok.

Don't emit filename in diff mode, add filename to diff metadata

---

src/imports.rs
src/missed_spans.rs
src/visitor.rs
tests/config/issue-1124.toml
tests/source/issue-1124.rs
tests/target/issue-1124.rs

Fix issue 1124 by detecting start of output rather than start of an input file to introduce a newline before a `use`. Also add in code to detect insertion of a span that either
1. contains whitespace directly before a `use`, or
2. contains whitespace running on from the last insertion before a `use` (as a newline will be inserted before the `use` is rendered, so the whitespace will become trailing whitespace on a line).

Fix issue 1124 - detect start of output rather than start of input file when writing output source file

---

README.md

This adds very simplistic instructions on how to run rustfmt on CI.
I also wrote a blog post for more details: http://johannh.me/blog/rustfmt-ci.html

Add instructions on how to run rustfmt on Travis

---

src/rustfmt_diff.rs

For a terminal like DUMB, we were still attempting to print colourful
diffs, which failed with a `NotSupported` error.
Fixes #1140

Check term supports colour before printing fancy diffs

---

src/items.rs
tests/source/impls.rs
tests/target/impls.rs

Split impl at 'for' if a line break is needed

---

src/comment.rs
src/config.rs
src/expr.rs
src/items.rs
src/types.rs
tests/source/comment4.rs
tests/source/space-not-after-type-annotation-colon.rs
tests/source/space-not-before-bound-colon.rs
tests/source/spaces-around-ranges.rs
tests/target/comment4.rs
tests/target/space-not-after-type-annotation-colon.rs
tests/target/space-not-before-bound-colon.rs
tests/target/spaces-around-ranges.rs

First commit: add new options for where to put spaces. I think its not necessary to differentiate between space before range operator and space after, as generally people will want either spaces before and after, or neither.
Second commit is a bugfix for #956

Two improvements

---

src/expr.rs
src/items.rs
tests/source/expr.rs
tests/target/expr.rs
tests/target/loop.rs

Fixes #1106
```rust
if let Some(entry) = WalkDir::new(path)
.into_iter()
.filter_entry(|entry| exclusions.filter_entry(entry))
.next() {
}
```

Prefer line break at `=`/`in`

---

src/expr.rs
tests/source/tuple.rs
tests/target/tuple.rs

Fixes #775.
The actual problem was in the tuple formatting code, `rewrite_tuple` referred to `config.max_width` where `width` passed from caller should be used.

Fix #775: Off-by-one overrun in deeply nested function call

---

src/comment.rs
tests/source/comment5.rs
tests/target/comment5.rs

This allows users to use custom comments such as
```
//@ this is a custom comment
//@ with multiple lines
```
without having them destroyed by rustfmt.

Add custom comments

---

README.md

Link directly to rust-mode.el, since rustfmt.el is marked obsolete.

Link to rust-mode.el instead of rustfmt.el

---

README.md

I know it's not much but the link in `rust.vim` has changed.

Update link towards vim documentation

---

src/macros.rs
src/visitor.rs
tests/source/macros.rs
tests/target/macros.rs

Preserve macro formatting if we can't rewrite it

---

src/config.rs
src/expr.rs
src/items.rs
src/patterns.rs
src/types.rs
tests/source/spaces-within-parens.rs
tests/target/spaces-within-parens.rs

Adds rule for enforcing spaces with parentheses.
I feel the implementation is a bit noisy - requiring config checks in several places thanks to the parentheses being written in several places.
Also if there's some test cases I missed, please mention those and I'll add 'em.
```
let x = (1 + 2)
// into
let x = ( 1 + 2 )
foo(1, 2, 3)
// into
foo( 1, 2, 3 )
let (a, b, c) = (d, e, f)
// into
let ( a, b, c ) = ( d, e, f )
```
but
```rust
foo()
()
```

Add support for spaces_within_parens config

---

src/chains.rs
src/config.rs
src/items.rs
src/types.rs
tests/source/spaces-within-angle-brackets.rs
tests/target/spaces-within-angle-brackets.rs

Enabling the config adds spaces within type arguments: <>
At least the `format!("for< {} > {}: {}", lifetime_str, type_str, bounds_str)` case is missing a test. Haven't played with traits enough to figure out an usage for the syntax.

Add support for spaces_within_angle_brackets

---

src/missed_spans.rs
tests/source/issue-1177.rs
tests/target/issue-1177.rs

This PR closes #1177. Essentially rustfmt was reformatting the whole string of `// comment \n    /* block comment */`, but was only checking the beginning of that string to determine whether it was a line comment or not, and thus adding the extra newline.

Stop extra newlines from being added after block comments

---

src/bin/cargo-fmt.rs

This pull request attempts to address #1126 .
The functionality is limited to top level files, similar to how the current version only touches top-level library and main binary files.

#1126 cargo-fmt processes bench, test, example files

---

src/comment.rs
src/imports.rs
src/visitor.rs
tests/source/imports-reorder-lines-and-items.rs
tests/system.rs
tests/target/imports-reorder-lines-and-items.rs

Where the first `use` statement in a file is prefixed with an attribute or doc comment, this is not accounted for when calculating the start position for reordering imports for that file.
This PR uses the lowest position out of all the attributes for the first item, or the item's own lowest position if it has no attributes.
Without the fix, the amended test fails with the message:
```
thread 'system_tests' panicked at 'Request to format inverted span: Loc { file: FileMap(tests/source/imports-reorder-lines-and-items.rs), line: 5, col: CharPos(0) } to Loc { file: FileMap(tests/source/imports-reorder-lines-and-items.rs), line: 4, col: CharPos(0) }', src/missed_spans.rs:60
```

Fixes #1184 where reordering import items could cause a panic.

---

src/config.rs

- Fix typo
- Switch comments verbs to the the 3rd person to offer a better coherence among options

Improve config::WriteMode comments

---

src/lists.rs
tests/source/issue-1216.rs
tests/target/issue-1216.rs

The problem is that the comment is interpreted as a block commend and it panics because there is no ending.
This fixes it, but I'm not sure if this is a good solution.
Please feel free to decline the request and suggest a better solution.
There does not seem to be a second place where a similar `find("/*")` appears.
Thx

fix #1216: panic on comment starting with //*

---

src/macros.rs
tests/source/macros.rs
tests/target/macros.rs

Fixes issues https://github.com/rust-lang-nursery/rustfmt/issues/878 and https://github.com/rust-lang-nursery/rustfmt/issues/1034

Stripping trailing commas and spaces from `vec!` elements

---

README.md

Old link was a 404, I think this new one is the most up to date,

Fixed broken link to style guidelines

---

src/lib.rs

(with current length and configured limit)

Better message for LineOverflow error

---

src/bin/cargo-fmt.rs

Hello,
I’m wondering if there are any reasons against processing build scripts in addition to the other targets. Thanks!
Regards,
Ivan

Process build scripts

---

src/expr.rs
tests/source/issue-1239.rs
tests/target/issue-1239.rs

Inside multiline conditions in nested else statements, remove the alignment due to the let binding before the original if statement. Fixes #1239.

Handle multiline condition in let if else (fixes #1239)

---

src/bin/rustfmt.rs

Supress `Using rusftmt config file...` messages unless the --verbose flag is given.
If a user has a config file, then every time rusftfmt runs it will print the `Using rustfmt config file...`
I think it is a good practice that if nothing has gone wrong, by default, nothing is printed. This will mean that users with config files will be more likely to notice actual error/warning messages.

Don't print config file by default

---

src/config.rs
src/lib.rs
tests/source/comment4.rs
tests/source/enum.rs
tests/source/file-lines-3.rs
tests/source/hard-tabs.rs
tests/source/imports.rs
tests/source/issue-913.rs
tests/source/string-lit.rs
tests/source/string_punctuation.rs
tests/source/struct_lits.rs
tests/source/struct_lits_visual.rs
tests/source/struct_lits_visual_multiline.rs
tests/source/structs.rs
tests/system.rs
tests/target/comment4.rs
tests/target/enum.rs
tests/target/file-lines-3.rs
tests/target/hard-tabs.rs
tests/target/imports.rs
tests/target/issue-913.rs
tests/target/string-lit.rs
tests/target/string_punctuation.rs
tests/target/struct_lits.rs
tests/target/struct_lits_visual.rs
tests/target/struct_lits_visual_multiline.rs
tests/target/structs.rs

Makes it configurable whether to error if unable to get all lines within
the max_width.
Testing this option turned out to be impossible, because the tests currently do not take into account any encountered FormattingErrors, so I also changed that to make tests fail if a FormattingError is encountered, as well as modifying all tests so that they do not produce FormattingErrors (in almost all of the tests this is accomplished by setting error_on_line_overflow = false).

Add error_on_line_overflow option

---

src/types.rs

I think there are still a few places that unconditionally use <tt>&nbsp;=&nbsp;</tt> as a separator.

honor type_punctuation_density for assoc. types

---

README.md

This does not change the semantics of what is run in travis, but rather fixes the example so that the output in travis makes more sense.
In particular:
- This will no longer run `cargo install rustfmt` when rustfmt is already installed (and that command would error anyways)
- Because of this, `|| true` is no longer needed, and is removed so that actual install errors for rustfmt are shown correctly
- This separates the combined script before into three separate commands, so that travis will output a "success" or "fail" for each individual command, rather than a combined "success" or "fail" for the entire thing (which is less helpful).

Update example in travis section of README

---

src/items.rs
src/visitor.rs
tests/target/issue-1255.rs

This is a fix for issue #1255, and it's pretty much my first PR of any consequence, in Rust or any language, so I think I'd like to explain myself and what I've done.
Taking a look over the code (and taking a read of the Rust `ast`), I realised that `rustfmt` was treating `TraitItems` and `ImplItems` in the same way - passing them both over to `rewrite_associated_type`, which ignores the additional `defaultness` field on the impl item (hence the bug).
So I wrote a new function, `rewrite_associated_impl_type` (is this name right?), which can take the `defaultness` as an additional argument. This doesn't do anything more that prepend the result of the original function with `default` when appropriate.
I've covered this with an idempotence test - named with the issue number.
I'm sure this is …

Fix #1255 - incorrect removal of `default` on associated types

---

src/expr.rs
tests/source/issue-1127.rs
tests/target/issue-1127.rs

This fixes issue #1127. This is my first dive into rustfmt, so I'll explain my changes to make sure they're agreeable. 
In terms of diagnosing the issue, I focused on the only 3 occurrences of `context.config.wrap_match_arms` (all are in `expr.rs`). 
The first was on [line 1256](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/expr.rs#L1256). Removing the config condition had no effect on the output, so I stopped focusing on this section. 
The next occurrence was on [line 1284](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/expr.rs#L1284), inside a block which starts at [line 1271](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/expr.rs#L1271). This whole block would only effect match arms which could be formatted into a single line; so none of that …

Fix wrap_match_arms resulting in a missing comma

---

Cargo.toml

ref : #1340
> ASL 2.0 requires text license to be present along with source. MIT doesn't require, but it's required by Fedora policies and it would not hurt as well.

include license files into archive on crates.io (#1340)

---

Design.md
src/config.rs
src/items.rs
src/missed_spans.rs
src/visitor.rs
tests/config/small_tabs.toml

Since the config option only affects comment widths, and the previous
name has led to some confusion (see #1321, #1152).

config: Rename ideal_width -> comment_width

---

src/modules.rs

`rustfmt` is recommended to be used in a CI server, but it is non-deterministic.
Closes #1141.

Make list_files deterministic (Closes #1141)

---

src/config.rs

This will make it clear if a user has misspelled a config option, or if
an option has been changed/removed.
I took the conservative path and made it warn on unused options, but it may make more sense to panic on unused options instead.

Warn on unused config options

---

src/patterns.rs
tests/target/issue-1397.rs

We previously double-added a trailing comma for single-member struct patterns that were arranged vertically. One was added by `write_list` (since such structs return true for `needs_trailing_separator`), and another is added by the if in `rewrite_struct_path`. This patch corrects this by checking for vertical layout before deciding whether to add a comma before `..`. This fixes #1397.

Avoid extra comma in vertical single-field struct patterns

---

src/imports.rs
tests/target/import-fencepost-length.rs

This fixes how line lengths for use statements with multiple
items don't extend beyond the maximum line length.
Fixes #1400

Break `use` statements into multiple lines

---

src/config.rs
src/expr.rs
tests/source/indent_match_arms.rs
tests/target/indent_match_arms.rs

Makes it optional whether to indent arms in match expressions. Setting
this to false may be desirable for people wishing to avoid
double-indents, in that if the match arm is a block, the block will
cause an extra indentation level, and if it isn't a block but just a
single line, it's still easy to see the logic at a glance.
This style is preferred in certain other languages with switch
statements, e.g. Linux style C and the most common Java style.

Add indent_match_arms option

---

src/lists.rs
tests/source/space-not-before-newline.rs
tests/target/space-not-before-newline.rs

Consider the following code, which produced a `left behind trailing whitespace (sorry)` warning before.
```rust
enum Foo {
Bar,
// commented out: Baz
}
```
This commit prevents rustfmt from producing a trailing space after `Bar,`.

Omit space before '\n' + comment (fixes #457)

---

src/expr.rs
src/lists.rs
src/types.rs
src/utils.rs

This PR removes duplicated definitions of `type_annotation_separator` and `type_bound_colon`.
Also fixes a typo in the document of `src/lists.rs`.

Remove duplicates

---

src/file_lines.rs
src/visitor.rs

The `--file-lines` flag currently restricts formating only to statements that are entirely within the specified ranges. This means that if the user passes a single line but the statement on that line extends to the next, then the formatting operation will have no effect. The reverse, of formatting statements that overlap the line ranges seems more intuitive. In fact this is the technique used by clang-format for its `--lines` command line argument.

Format any statement whose span intersects file_lines

---

src/items.rs
tests/source/structs.rs
tests/target/structs.rs

Split long fields in structs

---

src/bin/cargo-fmt.rs

see rust-lang-nursery/rustfmt#1244
cc @nrc

Implemented support for workspaces

---

src/bin/rustfmt.rs
src/file_lines.rs

This pull request adds the ability to restrict which lines get formatted when the input is provided on stdin.
The change also tweaks the behavior of the `--file_lines` argument in a different way. Previously, any files mentioned in `--file_lines` were added to the list of files to be formatted, and the mere presence of the flag meant that stdin would not be used as an input source. Now the determination of whether to use stdin is done solely on whether any files are passed on the command line, and extraneous files are ignored in `--file_lines`. 
This approach provides consistent behavior in the case that `--file_lines` contains both stdin and actual files, but it may be somewhat unintuitive to silently ignore files listed in `--file_lines`.

The --file_lines argument now supports "stdin"

---

src/lib.rs

Resolves #1335. Does not attempt to handle a `\r` not followed by a `\n` nor
attempt to handle Unicode intricacies (#6) including zero-width or multi-byte
characters.

Do not count `\r` as part of line width.

---

src/chains.rs
src/expr.rs
src/macros.rs
tests/source/expr-block.rs
tests/target/expr-block.rs

I'm aware some people don't like boolean arguments, but this has [precedence in this code base](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/lists.rs#L594) and since there were only a few call sites it seemed like the cleanest way to fix the bug.
Relevant issues:
#1419 
#1425
#1418

fix for #1419 and #1425

---

src/bin/rustfmt.rs
src/config.rs
tests/system.rs

This commit changes the behavior of rustfmt to use default config when it failed to parse a config file.
Presumably closes #1426, but I am not sure if this is the preferable way to solve the issue.
I would appreciate feedback. Thank you!

Print error and usage when decoding config file failed

---

src/bin/cargo-fmt.rs
src/chains.rs
tests/source/chains-visual.rs
tests/target/chains-visual.rs

This commit closes #1389. `subexpr_list` is constructed in a FILO manner, so if
we want to know whether the first connector is `?` or not, we must look at the
tail of the `subexpr_list`.

Lookup the last element of 'subexpr_list' instead of the first one

---

src/bin/rustfmt.rs

To be noted that `PathBuf::from("relative/path/to/test") != PathBuf::from("/absolute/path/to/test")`, so the check in https://github.com/rust-lang-nursery/rustfmt/blob/master/src/bin/rustfmt.rs#L239 may fail even all args are correct.

fix path check

---

src/expr.rs
src/imports.rs
src/patterns.rs
src/types.rs
tests/target/closure.rs

This PR closes #1327.
Input:
```rust
fn foo() {
let hash: &Fn(&&Block) -> u64 = &|block| -> u64 {
let mut h = SpanlessHash::new(cx);
h.hash_block(block);
h.finish()
};
}
```
Output:
```rust
fn foo() {
let hash: &Fn(&&Block) -> u64 = &|block| -> u64 {
let mut h = SpanlessHash::new(cx);
h.hash_block(block);
h.finish()
};
}
```

Add heuristic choosing block or visual indent for unary op based on span 

---

src/lib.rs

In format_lines line length counted as bytes but config.max_width as characters count.
for line like (84 chars):
`// У типажей может существовать стандартная реализация для их функций, поэтому`
produced error:
`Rustfmt failed at /home/diabolo/src/rust/chat/src/main.rs:7: line exceeded maximum length (maximum: 100, found: 147) (sorry)`
this fix just replace line length for count chars in line (not bytes).

format_lines: fix line_len for config.max_width

---

Cargo.lock
src/bin/rustfmt.rs
src/summary.rs

Show exit codes' meanings with the rustfmt help message

---

src/bin/rustfmt.rs

Currently rustfmt panics when non-existent files or directories are given. This PR prevents it from happening by explicitly checking that the given files exist and they are not directories.

Prevent panicking against directories or non-existent files

---

src/chains.rs
src/items.rs
src/lib.rs
tests/source/struct_tuple_visual.rs
tests/target/struct_tuple_visual.rs

This PR
* removes TODOs,
* removes duplicated expressions,
* and uses appropriate functions inside `Shape`'s methods.
If it is preferable to create separate PRs, please tell me.

Refactor source codes

---

src/chains.rs
src/expr.rs
src/file_lines.rs
src/items.rs
src/macros.rs
src/types.rs
tests/source/match.rs
tests/target/match.rs

This PR closes #1371.
Input:
```rust
fn main() {
Some(match type_ {
sfEvtClosed => Closed,
sfEvtResized => {
let e = unsafe { *event.size.as_ref() };
Resized {
width: e.width,
height: e.height,
}
}
sfEvtLostFocus => LostFocus,
sfEvtGainedFocus => GainedFocus,
sfEvtTextEntered => {
TextEntered {
unicode: unsafe {
::std::char::from_u32((*event.text.as_ref()).unicode)
.expect("Invalid unicode encountered on TextEntered event")
},
}
}
sfEvtKeyPressed => {
let e = unsafe { event.key.as_ref() };
KeyPressed {
code: unsafe { ::std::mem::transmute(e.code) },
alt: e.alt.to_bool(),
ctrl: e.control.to_bool(),
shift: e.shift.to_bool(),
system: e.system.to_bool(),
}
}
sfEvtKeyReleased => {
let e = unsafe { event.key.as_ref() };
KeyReleased {
code: unsafe { ::std::mem::transmute(e.code) },
alt: …
```

Format nested mathces properly.

---

src/items.rs
src/types.rs
tests/source/type-punctuation.rs
tests/target/type-punctuation.rs

In its current form only occurrences of `+` in `Box<Copy+Sync>` were affected by `type_punctuation_density`.
This PR extends this behavior to all other occurrences, such as `struct Foo<T: Copy + Sync> { … }` as from a user's perspective they all look like a single thing: an intersection of traits.

Made `type_punctuation_density` apply too all `+` in types

---

tests/system.rs

The current error message for missing files does not include the actual file path.
As such one currently has to guess it from the last logged test case.

Improve error message for missing source/target test file

---

Configurations.md
README.md

Having struggled with figuring out the right options for rustfmt before, I spent the last two days writing up a visual guide for rustfmt's `config.rs`.
While doing so I stumbled upon these:
1. [`fn_args_density = "CompressedIfEmpty"` appears to be broken in rustfmt](https://github.com/rust-lang-nursery/rustfmt/issues/1483)
2. [`where_indent` appears to be ignored completely by rustfmt](https://github.com/rust-lang-nursery/rustfmt/issues/1484)
3. [`where_density = "Vertical"` behaves like `where_density = "Tall"`](https://github.com/rust-lang-nursery/rustfmt/issues/1485)
Could you clear me up on these three issues?
---
And please let me know of any changes you'd like to get done to the guide before you'd consider it ready to merge!

Added visual configurations guide.

---

src/items.rs
tests/source/structs.rs
tests/target/structs.rs

Handle empty tuple struct def with comment properly

---

src/chains.rs
src/expr.rs
src/file_lines.rs
src/items.rs
src/string.rs
src/types.rs
src/visitor.rs
tests/source/chains.rs
tests/source/closure.rs
tests/source/configs-chain_indent-block.rs
tests/source/configs-chain_indent-visual.rs
tests/target/chains.rs
tests/target/closure.rs
tests/target/configs-chain_indent-block.rs
tests/target/configs-chain_indent-visual.rs

This PR closes #1405 and #1466.
When formatting a block closure, rustfmt should first try visual indent and then try block indent if the first attempt failed. However, currently rustfmt just returns `None` before trying block indent via `try_opt!`. This PR fixes that.
Also, this PR fixes 2 small bugs related to chains:
1. rustfmt fails to format a long chain with a single child.
e.g.
```rust
// length = 105
let f = fooooooooooooooooooooooooooooooooooooooooooooooooo.baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaar;
```
2. rustfmt splits a chain whose length is equal to `chain_one_line_max`.
e.g.
```rust
// length = 60, default value of `chain_one_line_max`
self.single_line_fn(&result, block).or_else(|| Some(result))
```
will be
```rust
// length = 60, default value of `chain_one_line_max` …
```

Fix weird indentation inside closures

---

src/bin/rustfmt.rs
src/config.rs

This PR allow `config-path` to point to a file. Closes #1429.
e.g.
```
rustfmt --config-path rfc-rustfmt.toml src/lib.rs
```
Also, this PR
1. prevents rustfmt from using default config when `config-path` is specified.
2. adds newline between an error messge and an usage message to improve readability.
3. prevents panicking when reading invalid config file (closes #1082).

Allow config-path to point to a file

---

src/expr.rs
src/items.rs
src/lib.rs
src/visitor.rs

While reading the code, I found following two patterns to be pervasive.
```rust
// 1
let max_width = context.config.max_width - indent.width();
let shape = Shape::legacy(max_width, indent);
```
```rust
// 2
let new_shape = Shape {
width: context.config.max_width - shape.indent.width(),
**shape
}
```
This PR adds above two methods and does minor refactorings.

Add methods to Shape

---

src/expr.rs
tests/source/closure.rs
tests/target/closure.rs

This PR closes #1509.
Now we have a fixpoint:
```rust
impl Foo {
pub fn bar(&self) {
Some(SomeType {
push_closure_out_to_100_chars: iter(otherwise_it_works_ok.into_iter().map(|f| {
Ok(f)
})),
})
}
}
```

Add fallback path inside rewrite_closure

---

src/expr.rs
src/items.rs
tests/source/configs-fn_call_style-block.rs
tests/target/configs-fn_call_style-block.rs
tests/target/expr-block.rs
tests/target/fn-custom-7.rs

This PR removes comma from function definition if it only has a single argument and the argument fits into a single line. Partially solves #1441?
Also this PR changes the output of test in `fn-custom-7.rs`, assuming that those commas are unnecessary. If it is preferable to preserve them, I will change this PR accordingly.

Remove comma from function definition with a single argument

---

src/bin/cargo-fmt.rs
src/bin/rustfmt.rs
src/checkstyle.rs
src/file_lines.rs
src/filemap.rs
src/lib.rs
src/utils.rs

Closes #1515.
Running rustfmt with `use_try_shorthand = true` worked for most part, except [these two](https://github.com/topecongiro/rustfmt/blob/2776615dc95715d197c2e757ae18b3285f06d80e/src/file_lines.rs#L176-L179) in file_lines.rs. It required type annotation.

Replace 'try!' with '?'

---

src/expr.rs
tests/source/configs-fn_call_style-block-trailing-comma.rs
tests/source/configs-fn_call_style-visual-trailing-comma.rs
tests/target/configs-fn_call_style-block-trailing-comma.rs
tests/target/configs-fn_call_style-visual-trailing-comma.rs

Closes #1528 (which I introduced, sorry).

Use newline only when fn_call_style is Block

---

src/expr.rs
tests/source/configs-fn_call_width-zero.rs
tests/target/configs-fn_call_style-block.rs
tests/target/configs-fn_call_width-zero.rs

Closes #1508.
A test in `configs-fn_call_style-block.rs` is changed because `Client::with_connector(HttpsConnector::new(TlsClient::new()))` has 61 chars, which is larger than the default `fn_call_width`.

Use vertical layout when args len is larger than fn_call_width

---

src/expr.rs
tests/source/struct-field-attributes.rs
tests/target/struct-field-attributes.rs

Support struct_field_attributes

---

README.md

This PR changes the link of Visual Studio Code extension in README.md, from [RustyCode](https://github.com/saviorisdead/RustyCode) to [vscode-rust](https://github.com/editor-rs/vscode-rust).
Although the README introduced RustyCode as the extension of rustfmt in Visual Studio Code, RustyCode is no longer maintained according to vscode-rust's README.

Change the link of Visual Studio Code extension

---

src/chains.rs
src/expr.rs
src/macros.rs
src/rewrite.rs
src/visitor.rs
tests/target/closure-block-inside-macro.rs

Closes #1547, although I am not sure whether `RewriteContext` is a good place to add additional information.

Prevent rewriting closure block to expr inside macro

---

src/file_lines.rs
src/lib.rs
src/missed_spans.rs
tests/source/file-lines-4.rs
tests/source/file-lines-5.rs
tests/source/file-lines-6.rs
tests/target/file-lines-4.rs
tests/target/file-lines-5.rs
tests/target/file-lines-6.rs

This patch makes rustfmt respect the file_lines argument in more places.
For example, trying to format the first three lines of example.rs:
```rust
struct A {
t: i64,     
}
mod foo {
fn bar() {
// test
let i = 12;
// test
}
// aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
fn baz() {
let j = 15;     
}
}
```
with this command:
```
rustfmt  --write-mode=diff --file-lines '[{"file": "example.rs", "range": [0, 2]}]' example.rs
```
used to produce this output:
```diff
Diff in example.rs at line 1:
struct A {⏎
-t: i64,     ⏎
+    t: i64,⏎
}⏎
⏎
mod foo {⏎
Diff in example.rs at line 6:
fn bar() {⏎
-                         // test⏎
+        // test⏎
let i = 12;⏎
-                                 // test⏎
+        // …
```

Better file_lines

---

src/expr.rs
src/issues.rs
src/items.rs
src/macros.rs
src/missed_spans.rs
src/patterns.rs
src/types.rs
src/visitor.rs
tests/source/macros.rs
tests/target/macros.rs

Closes #1555.
Looks good for most part (e.g. using block indent for `return`).
However, I am not sure whether the code like the following is fine:
```rust
!self.
.file_lines
.intersects_range(file_name, cur_line, cur_line + subslice_num_lines) {
```
Currently, the above code gets formatted as
```rust
!self.
.file_lines
.intersects_range(file_name, cur_line, cur_line + subslice_num_lines) {
```
Basically, since chain is block-indented, after the PR the width of `!` is not taken into account.

Only add offset for unary op

---

tests/source/issue-1366.rs
tests/target/issue-1366.rs

As the comments in the issue state: it appears to work now, so this test
should just stop any regressions.
The second example in the issue description will format to the first,
which is then a fixed-point.

Add test for issue #1366.

---

Configurations.md
src/config.rs
src/patterns.rs
tests/source/configs-condense_wildcard_suffices-false.rs
tests/source/configs-condense_wildcard_suffices-true.rs
tests/source/pattern-condense-wildcards.rs
tests/target/configs-condense_wildcard_suffices-false.rs
tests/target/configs-condense_wildcard_suffices-true.rs
tests/target/pattern-condense-wildcards.rs

Fixes #1477.
---
Is backwards compat for the old name wanted to bridge over updates?

config: fix `suffices` -> `suffixes` typo

---

src/expr.rs
src/types.rs
src/utils.rs
tests/source/configs-fn_call_style-block-trailing-comma.rs
tests/source/configs-fn_call_style-block.rs
tests/source/expr-block.rs
tests/target/closure-block-inside-macro.rs
tests/target/configs-fn_call_style-block-trailing-comma.rs
tests/target/configs-fn_call_style-block.rs
tests/target/expr-block.rs

Closes #1422, closes #1449, and closes #1494.

Nesting of block indented expressions

---

src/chains.rs
src/comment.rs
src/expr.rs
src/file_lines.rs
src/items.rs
src/lists.rs
src/macros.rs
src/modules.rs
src/string.rs
src/types.rs
src/utils.rs
tests/system.rs
tests/target/chains.rs
tests/target/configs-fn_call_style-block.rs
tests/target/file-lines-1.rs
tests/target/file-lines-3.rs

Please see https://github.com/rust-lang-nursery/fmt-rfcs/issues/66.

 Allow first child to stay on the same line with block parent when rewriting chain

---

src/macros.rs
tests/source/macros.rs
tests/target/macros.rs

Closes #1577.
I recently added a commit that allows rewriting of macro to fail on the rhs of assignment,
so that rustfmt can try to put the macro on the next line.
This seems to  work reasonable, although when macro contains invalid syntax, the whole trial is meaningless since it will eventually fail.
This PR avoids it by returning the original code snippet from `rewrite_macro` when parsing failed.

Use original code snippet for macro which contains invalid syntax

---

src/expr.rs
tests/source/configs-fn_call_style-block.rs
tests/target/configs-fn_call_style-block.rs

Currnely, when `fn_call_style = Block`, rustfmt puts the first argument when it shouldn't:
```rust
bootstrap.checks.register("PERSISTED_LOCATIONS",
move || if locations2.0.inner_mut.lock().poisoned {
Check::new(
State::Error,
"Persisted location storage is poisoned due to a write failure",
)
} else {
Check::new(State::Healthy, "Persisted location storage is healthy")
},);
```
This PR fixes the above bug.

Decide whether args fit in a single line inside rewrite_call_args

---

src/items.rs
tests/target/issue-1587.rs

This PR closes #1587.
TBH I am not sure whether the position of closing paren is ideal.

Put closing paren on the next line when the last arg contains comment

---

src/chains.rs
src/expr.rs
src/items.rs
tests/source/configs-fn_call_style-block.rs
tests/target/closure-block-inside-macro.rs
tests/target/configs-fn_call_style-block.rs

This PR allows macro to be nested like function call:
```rust
foo(try!(
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
))
```
Also, currently rustfmt forgets to add a trailing comma for multiline args when the function call is inside macro:
```rust
try!(foo(
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
));
```
This PR fixed this.

Allow macro to be nested like function call

---

src/items.rs
tests/target/fn-args-with-last-line-comment.rs
tests/target/issue-1587.rs

Closes #1595.
This PR adds a trailing comma to the last arg in order to avoid reformatting.

Add a trailing comma if the last arg ends with comment

---

src/items.rs
tests/source/structs.rs
tests/target/structs.rs

Allow comments after attributes of struct fields

---

src/expr.rs

`rewrite_call` uses binary search to decide the appropriate width for callee.
However, this is unnecessary when we are passing string as callee to `rewrite_call`,
since the width of string does not change after calling `rewrite` against it.
This PR avoids using binary search when callee is string.
We get roughly 0~20% speed up against a large code base with this PR.

Avoid unnecessary binary search in rewrite_call

---

src/expr.rs
tests/source/macros.rs
tests/source/skip.rs
tests/target/macros.rs
tests/target/skip.rs

Closes #1178 and closes #1346.
If rustfmt should not support attributes on expressions, I am fine closing this without merging.

Allow attributes on expressions

---

src/comment.rs
tests/source/closure.rs
tests/source/issue-1278.rs
tests/source/macros.rs
tests/target/closure.rs
tests/target/configs-fn_call_style-block-tab_spaces-2.rs
tests/target/issue-1214.rs
tests/target/issue-1278.rs
tests/target/issue-691.rs
tests/target/macros.rs

This PR closes #691.
However, TBH I am not sure whether how I deal with this issue is ideal.
Introducing `enum CommentStyle` seems overkill after looking back this PR.
I really appreciate any feedbacks.
Thank you in advance!

Format comments with different opening in different manner

---

src/bin/rustfmt.rs
src/config.rs

* Make method for searching parents for toml file public
* Make method for loading config from path directly public, tweak the
API since it was never returning None
Would allow RLS to reuse the rustfmt.toml searching/loading code (https://github.com/rust-lang-nursery/rls/pull/331)

Expose methods to locate and load config

---

src/expr.rs
tests/target/configs-control_style-rfc.rs

This PR closes #1618, although it only fixes the issue related to exceeding the max width.
I am not confident that output is correctly indented.
```rust
fn main() {
loop {
if foo {
if ((right_paddle_speed < 0.) &&
(right_paddle.position().y - paddle_size.y / 2. > 5.)) ||
((right_paddle_speed > 0.) &&
(right_paddle.position().y + paddle_size.y / 2. < game_height as f32 - 5.))
{
foo
}
if ai_timer.elapsed_time().as_microseconds() > ai_time.as_microseconds() {
if ball.position().y + ball_radius >
right_paddle.position().y + paddle_size.y / 2.
{
foo
}
}
}
}
}
```

Use correct line budget when using Rfc control style

---

src/items.rs
tests/source/configs-fn_args_layout-block.rs
tests/target/configs-fn_args_layout-block.rs

Forbid trailing comma at the end of args of variadic functions

---

src/items.rs
tests/target/fn-custom-2.rs
tests/target/fn-custom-3.rs
tests/target/issue-1624.rs

This PR
* removes an extra blank line from function definition when `fn_args_layout = "Block"` and `fn_args_paren_newline = false` are used (Please take a look at #1624 and https://github.com/rust-lang-nursery/fmt-rfcs/issues/39).
* allows the opening `(` of args to stay after the closing `>` of multi line generic.

Refactor vertical layout of function definition with options

---

src/expr.rs
src/rewrite.rs
src/visitor.rs
tests/target/unindent_if_else_cond_comment.rs

Closes #1575.
The option only supports comment starting with `//` and is set to `false` by default.

Add format_if_else_cond_comment config option

---

Configurations.md
rfc-rustfmt.toml
src/chains.rs
src/config.rs
src/expr.rs
src/filemap.rs
src/items.rs
src/lib.rs
src/macros.rs
src/missed_spans.rs
src/rewrite.rs
src/types.rs
src/visitor.rs
tests/system.rs
tests/target/chains.rs
tests/target/combining.rs
tests/target/configs-combine_control_expr-false.rs
tests/target/configs-combine_control_expr-true.rs
tests/target/configs-fn_call_style-block.rs
tests/target/hard-tabs.rs
tests/target/nested-visual-block.rs

This PR allows more expressions to be combined with function calls, but not with match arms because I am not sure how combining interacts with `wrap_match_arms` option.
If it is prefered to wait before implementing, I am happy to close this without merging.

Combine more expressions

---

Configurations.md
src/config.rs
src/expr.rs
src/items.rs
tests/source/configs-space_after_struct_lit_field_colon-false.rs
tests/source/configs-space_after_struct_lit_field_colon-true.rs
tests/source/configs-space_before_struct_lit_field_colon-false.rs
tests/source/configs-space_before_struct_lit_field_colon-true.rs
tests/target/configs-space_after_struct_lit_field_colon-false.rs
tests/target/configs-space_after_struct_lit_field_colon-true.rs
tests/target/configs-space_before_struct_lit_field_colon-false.rs
tests/target/configs-space_before_struct_lit_field_colon-true.rs
tests/target/space-before-type-annotation.rs
tests/target/space-not-after-type-annotation-colon.rs

In Rust, colons are used for three purposes:
* Type annotations, including type ascription
* Trait bounds
* Struct literal fields
This commit adds options for the last missing of the three purposes,
struct literal fields.

Add config options for spaces around the colon in struct literal fields

---

src/visitor.rs
tests/source/attrib.rs
tests/source/enum.rs
tests/source/struct-field-attributes.rs
tests/target/attrib.rs
tests/target/enum.rs
tests/target/nestedmod/mod.rs
tests/target/nestedmod/mod2b.rs
tests/target/struct-field-attributes.rs

This PR implements basic formatting against `syntax::ast::Attribute`.
Possible TODOs:
* Add an option to change indent style or list layout when list (e.g. `[derive(..)]`) goes multi line
* Implement https://github.com/rust-lang-nursery/fmt-rfcs/issues/72
Closes #984, closes #1261, and closes #1462.

Implement Rewrite trait for syntax::ast::Attribute 

---

rfc-rustfmt.toml

Following https://github.com/rust-lang-nursery/fmt-rfcs/issues/39.
```rust
fn extract_one(
&mut self,
m: FxHashMap<PathBuf, PathKind>,
flavor: CrateFlavor,
slot: &mut Option<(Svh, MetadataBlob)>,
) -> Option<(PathBuf, PathKind)> {
// ...
}
```

Add 'fn_args_paren_newline = false' to rfc-rustfmt.toml

---

src/items.rs
tests/target/comments-fn.rs

Fixes the second issue of #1643.

Force brace on new line if the signature ends with comment

---

src/expr.rs
tests/source/configs-fn_call_style-block.rs
tests/target/configs-fn_call_style-block-trailing-comma.rs
tests/target/configs-fn_call_style-block.rs

Previously when arguments of macro contained no newlines rustfmt put it in a single line without respecting max width. This PR fixed this.
Closes #1651.

Use block indent for args of macro if single line args exceeds max width

---

src/expr.rs
src/items.rs
src/types.rs
tests/source/big-impl-rfc.rs
tests/source/big-impl.rs
tests/source/impls.rs
tests/target/big-impl-rfc.rs
tests/target/big-impl.rs
tests/target/configs-generics_indent-block.rs
tests/target/fn-custom-2.rs
tests/target/fn-custom-3.rs
tests/target/impls.rs

This PR updates formatting against long impls.
Passes all stress tests from #1357 and #1369. ~~when using `rfc-rustfmt.toml`, but fails on some tests when using the current default configutation.~~
~~I am creating this PR anyway since we will be switching the default to Rfc style and this PR does cause no regression.~~

Refactor impl format

---

src/items.rs
src/types.rs
tests/source/where-clause-rfc.rs
tests/target/where-clause-rfc.rs

Currently we get
```rust
pub trait SomeTrait<T>
where
T: Something
+ Sync
+ Send
+ Display
+ Debug
+ Copy
+ Hash
+ Debug
+ Display
+ Write
+ Read
+ FromStr
{
}
```
This PR fixed this by following https://github.com/rust-lang-nursery/fmt-rfcs/issues/75#issuecomment-307950340.

Fix excessive indentation in trait where clause when using Rfc style

---

src/expr.rs
src/items.rs
src/lib.rs
src/visitor.rs
tests/source/attrib.rs
tests/target/attrib.rs

This PR
1. add changes to prevent rustfmf to overflow arithmetic when running tests.
2. try to use correct spans when rewriting attributes. The span of `ast::Expr` does not cover its attributes, and the span of `ast::MetaItem` is missing closing parens.

Use correct spans when rewrting attributes

---

Cargo.toml
tests/system.rs

When there are no `[[bin]]` sections, all the binaries in `src/bin` are
automatically picked up. When a section is added, that is no longer the
case, so all the binaries need to be specified explicitly.
(Should fix #1670)

Add back cargo-fmt binary

---

src/expr.rs
src/types.rs
tests/target/configs-fn_args_layout-block.rs
tests/target/fn_args_layout-block.rs
tests/target/multiple.rs
tests/target/type.rs
tests/target/type_alias.rs

This PR closes #1662.
In order to reuse the code for rewriting tupe literals and tupe types, we need a way to distinguish `ast::Expr` and `ast::Ty`. This PR adds `ExprTypeIdentifier` trait to solve this, although I am not convinced that this is an ideal way, especially it requires reconstructing a vector of args.
```rust
let args = args.iter().map(|e| e.to_expr()).collect::<Vec<_>>(); 
```

Block indent tuple type when fn_call_style is Block

---

README.md

RustFmt is much faster than BeautifyRust and preserves scroll position

suggested a better Sublime Text plugin

---

src/expr.rs
src/imports.rs
tests/target/issue-1681.rs

This PR wraps closure with multi line condition in block if it is being 'overflowed' at the last arg position of function call (I hope the sentence makes sense).
Closes #1681.

Wrap closure in block with a single control flow expr with multi line condition

---

src/bin/rustfmt.rs

Remove -nightly suffix in version printing

---

src/chains.rs
src/comment.rs
src/expr.rs
src/items.rs
src/lists.rs
src/types.rs
src/visitor.rs
tests/source/closure.rs
tests/target/closure.rs
tests/target/match.rs

Closes #1697. cc #1681, this PR adds another rule that if the closure's parameters list goes multi line, we avoid overflowing.
Also, this PR fixes a bug when calculating the budget for function call arguments.

Forbid overflowing closure if its header goes multi lines

---

src/chains.rs
src/comment.rs
src/expr.rs
src/items.rs
src/lists.rs
src/macros.rs
src/missed_spans.rs
src/types.rs
src/utils.rs
src/visitor.rs
tests/target/chains-visual.rs
tests/target/configs-fn_call_style-block.rs
tests/target/configs-force_format_strings-true.rs
tests/target/configs-format_strings-true.rs
tests/target/long_field_access.rs

This PR disallows the overflowing of the last element of the chain if the last element will fit in a single line when the chain itself is split into multi lines (.
For example, with respect to the following snippet,
```rust
let almost_total = rewrites[..last_non_try_index].iter().fold(
0,
|a, b| a + first_line_width(b),
);
```
this PR formats it like the following:
```rust
let almost_total = rewrites[..last_non_try_index]
.iter()
.fold(0, |a, b| a + first_line_width(b)); 
```
because the last element will fit in a single line.
However, with respect to the next example,
```rust
foo().bar().use_multilines(|x| {
let y = x + 1;
y
})
```
the chain will not get broken into multiline because the last element will not fit into a single line even if the chain got split.

Allow overflowing the last element of chain if it is originally multi-lined

---

src/items.rs
src/lists.rs
src/types.rs
tests/source/big-impl-rfc.rs
tests/source/type_alias.rs
tests/target/big-impl-rfc.rs
tests/target/extern_not_explicit.rs
tests/target/fn-simple.rs
tests/target/fn.rs
tests/target/hard-tabs.rs
tests/target/type.rs
tests/target/type_alias.rs

Refactor format against types and generics

---

src/expr.rs
tests/source/macros.rs
tests/target/macros.rs

Closes #1712.
rustfmt had heuristic to allow rewriting of macro to fail on the rhs of assignment, so that rustfmt can try to put the macro on the next line.
This worked reasonable when the default was visual indent style. Now that we use block indent style as a default and we have more horizontal budget, this heuristic seems unnecessary.
This PR removes this heuristic all together.

Avoid line break when rhs of assignment is an invalid macro

---

src/chains.rs
src/expr.rs
src/items.rs
src/patterns.rs
src/utils.rs
src/visitor.rs

If the condition of control flow expressions ends with closing parens and alike,
put the opening bracket of the body on the same line with closing parens.

Combine control flow condition and body

---

src/expr.rs
tests/source/configs-control_brace_style-always_next_line.rs
tests/source/configs-control_brace_style-always_same_line.rs
tests/source/configs-control_brace_style-closing_next_line.rs
tests/target/configs-control_brace_style-always_next_line.rs
tests/target/configs-control_brace_style-always_same_line.rs
tests/target/configs-control_brace_style-closing_next_line.rs

This small PR fixes #1377 and keeps braces on the same line as `match` when using `AlwaysSameLine` and `ClosingNextLine` for `control_brace_style`. Using `AlwaysNextLine` works as expected.

Keep brace on same line as `match` when using `ClosingNextLine`.

---

src/expr.rs
tests/target/configs-fn_call_style-block.rs
tests/target/macros.rs

A follow up of #1743.
Currently, rustfmt casually adds a trailing comma to arguments of macro invocation if they look like function call or alike. However, depending on the macro's definition, adding a trailing comma can break the code.
This PR fixes this by disallowing adding a trailing comma unless the original source code has one.

Do not add trailing comma inside macro invocation unless there alreay is

---

Configurations.md
src/config.rs
src/expr.rs
src/items.rs
src/lib.rs
src/lists.rs
src/patterns.rs
src/vertical.rs
tests/source/configs-struct_field_align_threshold-20.rs
tests/target/attrib.rs
tests/target/configs-struct_field_align_threshold-20.rs
tests/target/issue-1397.rs
tests/target/issue-855.rs
tests/target/struct_lits.rs

This PR adds vertical alignment option for struct fields. cc #1103.
Also, this PR fixes rustfmt to use `struct_lit_width` whenever necessary.
configs-struct_field_align_threshold-20.rs includes tests from structs.rs and structs_lit.rs in order to prevent regression.

Add vertical alignment option for struct fields

---

src/expr.rs
src/file_lines.rs
src/items.rs
src/lists.rs
src/rewrite.rs
src/utils.rs
tests/target/configs-struct_field_align_threshold-20.rs
tests/target/enum.rs
tests/target/macros.rs
tests/target/multiple.rs
tests/target/paths.rs
tests/target/struct_tuple_visual.rs
tests/target/structs.rs
tests/target/trailing_commas.rs

RFC: Use block indent style for struct tuple

---

src/bin/cargo-fmt.rs
src/expr.rs
src/items.rs
src/lists.rs
tests/source/structs.rs
tests/target/configs-struct_field_align_threshold-20.rs
tests/target/enum.rs
tests/target/fn-args-with-last-line-comment.rs
tests/target/fn-simple.rs
tests/target/macros.rs
tests/target/multiple.rs
tests/target/structs.rs

This PR implements vertical alignment for comments after elements in list-like structures which use `write_list` (struct, enum, function call, generics, etc.).

Comment vertical alignment

---

src/chains.rs

See https://github.com/rust-lang/rust/pull/42492#issuecomment-310897984 and below.
I'm still not sure how changes to AST breaking rustfmt need to be sequenced to pass all the CIs.

Update rustfmt for ast::ExprKind::MethodCall changes

---

src/bin/cargo-fmt.rs
src/chains.rs
src/comment.rs
src/config.rs
src/expr.rs
src/items.rs
src/lib.rs
src/patterns.rs
src/types.rs
src/utils.rs
src/visitor.rs
tests/target/expr.rs
tests/target/match.rs

This PR implements part of RFC style for match arm and condition pattern (cc https://github.com/rust-lang-nursery/fmt-rfcs/issues/34#issue-185204114).
> ## large patterns
>
>If using a compound pattern (pat1 | pat2), prefer to put the whole pattern on one line. If it does not fit, put each sub-pattern on a new line, with the line terminated by |:

RFC: patterns in condition and match arm

---

src/items.rs
src/lib.rs
tests/target/comments-fn.rs
tests/target/impl.rs

This PR covers missing comments before and after `where` by creating `span` manually.
We could also recover missing comments by using `recover_comment_removed` and this is much simpler.
However, using `recover_comment_removed` means we give up formatting the item with `where` entirely.
Closes #458 and closes #1758.

Recover removed comment before and after `where`

---

src/expr.rs
src/types.rs
tests/source/long-match-arms-brace-newline.rs
tests/target/configs-control_style-rfc.rs
tests/target/long-match-arms-brace-newline.rs
tests/target/match.rs

This PR implements part of RFC style for match arm.
1. Put `{` on a newline if we break before `if`
2. Do not add visual offset (`if `) when the condition goes multi line (like we do in normal `if` expression)

Rfc: fix up match arm pattern

---

Configurations.md
src/config.rs
src/expr.rs
src/items.rs
src/utils.rs
src/visitor.rs
tests/target/configs-trailing_semicolon-false.rs
tests/target/configs-trailing_semicolon-true.rs

trailing_semicolon controls whether to add a trailing semicolon after break, continue and return.
Closes #993.

Add trailing_semicolon config option

---

src/visitor.rs
tests/source/skip.rs
tests/target/skip.rs

Support rustfmt_skip on statements

---

src/expr.rs
src/items.rs
src/visitor.rs
tests/target/chains-visual.rs
tests/target/chains.rs
tests/target/issue-831.rs

This PR adds a heuristic to `rewrite_pair` that if the right hand side expression looks like block (more specifically, ends with `{`), then allow the rhs to stay on the same line with lhs even if it gets multi-lined.
Closes #831.

Allow block-like rhs expression to stay on the same line with lhs

---

src/expr.rs
src/items.rs
src/lib.rs
src/visitor.rs
tests/source/attrib.rs
tests/source/issue-1800.rs
tests/target/attrib.rs
tests/target/comment4.rs
tests/target/issue-1800.rs

Closes #1800.
This PR has some flaws:
1. It does not work well with comments after attributes (see diffs in `comment4.rs`).
2. When run from `cargo fmt`, it cannot format inner attributes outside of `lib.rs`.

Format inner attributes

---

src/items.rs
tests/target/configs-struct_variant_width-0.rs

Currently rustfmt does not force vertical layout. Closes #1809.

Force vertical layout when struct_variant_width is 0

---

tests/source/file-lines-1.rs
tests/source/file-lines-2.rs
tests/source/file-lines-3.rs
tests/source/file-lines-4.rs
tests/target/file-lines-1.rs
tests/target/file-lines-2.rs
tests/target/file-lines-3.rs
tests/target/file-lines-4.rs

Looks like the issue in #1159 was fixed at some point, so this PR adds deleted comments to the file-lines tests.
Closes #1159.

Restore comments in file-lines tests

---

src/comment.rs
src/expr.rs
src/imports.rs
src/items.rs
src/patterns.rs
src/types.rs
src/visitor.rs
tests/target/chains-visual.rs
tests/target/configs-control_style-rfc.rs
tests/target/expr.rs
tests/target/loop.rs

This PR
1. fixes impatient line breaks of condition ([examples](https://github.com/rust-lang-nursery/rustfmt/pull/1821/commits/e523f053a3cd06453733f5543492d80e10bf8964)).
2. simplify `rewrite_pair`.

Avoid unnecessary line breaks

---

src/expr.rs
src/items.rs
src/utils.rs
src/visitor.rs
tests/source/file-lines-item.rs
tests/target/file-lines-item.rs

Currently rustfmt ignores file lines check for items.
Closes #1835.

More fine-grained file-lines

---

src/visitor.rs
tests/source/extern.rs
tests/target/extern.rs

These changes aim to fix #1815
This is my first PR here and although the added test cases pass I'm pretty sure my implementation is extremely naive and doesn't use the available tools in `rustfmt`. Also it allocates (probably) unnecessarily.
Any suggestions?

Remove whitespace between words in extern declarations

---

Cargo.toml
src/bin/rustfmt-format-diff.rs
src/bin/test/bindgen.diff

This patch introduces a super-simple format-diff tool, that allows you to do:
```
git diff | rustfmt-format-diff -p 1
```
To format your current changes.
For now it doesn't accept too much customisation, and it basically calls rustfmt
with the default configuration, but more customisation can be added in the
future if needed.

bin: Add a very simple rustfmt-format-diff.

---

src/config.rs
src/items.rs
src/utils.rs
tests/target/configs-where_density-compressed.rs
tests/target/configs-where_density-compressed_if_empty.rs
tests/target/fn-custom-4.rs
tests/target/fn_args_layout-block.rs
tests/target/long-fn-1.rs
tests/target/multiple.rs

This PR implements https://github.com/rust-lang-nursery/fmt-rfcs/issues/74, with some refactoring and bug fixes.
Closes #1843. Closes #1844.

Implement single-line where

---

src/imports.rs
src/visitor.rs
tests/source/imports.rs
tests/target/imports.rs

This prevents code like
```rust
#[cfg(unix)]
pub use self::unix::{};
```
from becoming
```rust
#[cfg(unix)]
```
which would cause the attribute to be attached to the next item.

Fix #1858 - "Don't erase a use with attributes attached"

---

src/lists.rs
tests/source/expr-block.rs
tests/target/expr-block.rs

Currently rustfmt forces the pre-comment of the item to be placed on the different line.
This PR changes this behaviour and let the comment keep the original layout as long as it does not exceed the max width.
Closes #1862.

Keep the pre-comment on the same line with item if it fits max width

---

src/bin/rustfmt.rs
src/config.rs
src/imports.rs
src/lib.rs
src/visitor.rs
tests/source/extern.rs
tests/system.rs
tests/target/attrib-extern-crate.rs
tests/target/extern.rs

This PR adds `reorder_extern_crates` and `reorder_extern_crates_in_group` config options.
Closes #1857.

Reorder extern crates

---

src/config.rs
src/lib.rs
tests/target/configs-error_on_line_overflow_comment-false.rs

This PR adds an option `error_on_line_overflow_comments` which when set to `false` prevents rustfmt from emitting errors about comments that overflowed the max width (cc #1770).
This option is not perfect in that it only works against single-lined comments (e.g. `//`, `///` and alike).
Dealing with block comments (`/* .. */`) is left for future work.

Add error_on_line_overflow_comments config option

---

src/bin/cargo-fmt.rs
src/bin/rustfmt.rs
src/config.rs
src/expr.rs
src/filemap.rs
src/types.rs
src/visitor.rs
tests/source/fn-simple.rs
tests/source/indent_match_arms.rs
tests/source/issue-510.rs
tests/source/remove_blank_lines.rs
tests/source/spaces-within-angle-brackets.rs
tests/source/spaces-within-parens.rs
tests/source/spaces-within-square-brackets.rs
tests/source/struct_tuple_visual.rs
tests/target/fn-simple.rs
tests/target/indent_match_arms.rs
tests/target/issue-510.rs
tests/target/remove_blank_lines.rs
tests/target/spaces-within-angle-brackets.rs
tests/target/spaces-within-parens.rs
tests/target/spaces-within-square-brackets.rs
tests/target/struct_tuple_visual.rs

Remove blank lines at start or end of block 

---

src/lib.rs
src/rustfmt_diff.rs
src/utils.rs

The current rustfmt only emits very dry error messages.
This PR attempts to improve it with more verbose error messages resembling those of rustc.

Enhance error messages

---

src/items.rs
tests/source/associated-types-bounds-wrapping.rs
tests/target/associated-types-bounds-wrapping.rs

Bounds were wrapped to the full width of the line rather then the width available after the "type ...: ", resulting in rustfmt unnecessarily producing lines that were longer than the maximum width.
With a max line width of 100, rustfmt would force the following formatting:
```rust
pub trait HttpService {
type WsService: 'static + Service<Request = WsCommand, Response = WsResponse, Error = ServerError>;
// ^ error: line width 103
}
```
whereas the correct formatting is:
```rust
pub trait HttpService {
type WsService: 'static
+ Service<Request = WsCommand, Response = WsResponse, Error = ServerError>;
}
```

Fix wrapping of bounds in associated types

---

Configurations.md
src/config.rs
src/expr.rs
src/imports.rs
src/items.rs
src/lists.rs
src/types.rs
src/vertical.rs
src/visitor.rs
tests/source/configs-match_pattern_separator_break_point-Front.rs
tests/source/match.rs
tests/target/configs-match_pattern_separator_break_point-Front.rs
tests/target/control-brace-style-always-next-line.rs
tests/target/control-brace-style-always-same-line.rs
tests/target/match.rs

This PR implements `match_pattern_separator_break_point` config option, which controls where to break match sub-patterns (before or after `|`).
```rust
match m {
Variant::Tag
| Variant::Tag2
| Variant::Tag3
| Variant::Tag4
| Variant::Tag5
| Variant::Tag6 => {}
}
```
```rust
match m {
Variant::Tag |
Variant::Tag2 |
Variant::Tag3 |
Variant::Tag4 |
Variant::Tag5 |
Variant::Tag6 => {}
}
```
Related issue: https://github.com/rust-lang-nursery/fmt-rfcs/issues/34

Add mach_pattern_separator_break_point config option 

---

src/visitor.rs

The span of `ast::NestedMetaItem` used to be missing closing parens (cc #1668).
This is now fixed via https://github.com/rust-lang/rust/pull/43933 and hence we need not use `count_missing_closing_parens()` anymore.

Remove count_missing_closing_parens()

---

Configurations.md
src/config.rs
src/items.rs
tests/source/configs-attributes_on_same_line_as_field-false.rs
tests/source/configs-attributes_on_same_line_as_field-true.rs
tests/source/configs-attributes_on_same_line_as_variant-false.rs
tests/source/configs-attributes_on_same_line_as_variant-true.rs
tests/target/configs-attributes_on_same_line_as_field-false.rs
tests/target/configs-attributes_on_same_line_as_field-true.rs
tests/target/configs-attributes_on_same_line_as_variant-false.rs
tests/target/configs-attributes_on_same_line_as_variant-true.rs

Try to put attributes on the same line as fields
- **Default value**: `true`
- **Possible values**: `true`, `false`
```rust
struct Lorem {
#[serde(rename = "Ipsum")] ipsum: usize,
#[serde(rename = "Dolor")] dolor: usize,
#[serde(rename = "Amet")] amet: usize,
}
```
```rust
struct Lorem {
#[serde(rename = "Ipsum")]
ipsum: usize,
#[serde(rename = "Dolor")]
dolor: usize,
#[serde(rename = "Amet")]
amet: usize,
}
```
Try to put attributes on the same line as variants
- **Default value**: `true`
- **Possible values**: `true`, `false`
```rust
enum Lorem {
#[serde(skip_serializing)] Ipsum,
#[serde(skip_serializing)] Dolor,
#[serde(skip_serializing)] Amet,
}
```
```rust
enum Lorem {
#[serde(skip_serializing)]
Ipsum,
#[serde(skip_serializing)]
Dolor,
#[serde(skip_serializing)]
Amet,
}
```

Add attributes_on_same_line_as_{field,variant} configs

---

Configurations.md
src/config.rs
src/expr.rs
tests/source/configs-multiline_closure_forces_block-false.rs
tests/source/configs-multiline_closure_forces_block-true.rs
tests/source/configs-multiline_match_arm_forces_block-false.rs
tests/source/configs-multiline_match_arm_forces_block-true.rs
tests/target/configs-multiline_closure_forces_block-false.rs
tests/target/configs-multiline_closure_forces_block-true.rs
tests/target/configs-multiline_match_arm_forces_block-false.rs
tests/target/configs-multiline_match_arm_forces_block-true.rs

cc https://github.com/rust-lang-nursery/rustfmt/issues/1791
Allow overflow on closures
- **Default value**: `true`
- **Possible values**: `true`, `false`
```rust
result.and_then(|maybe_value| match maybe_value {
None => ...,
Some(value) => ...,
})
```
```rust
result.and_then(|maybe_value| {
match maybe_value {
None => ...,
Some(value) => ...,
}
})
```
Allow overflow on match arms
- **Default value**: `true`
- **Possible values**: `true`, `false`
```rust
match lorem {
None => if ipsum {
println!("Hello World");
},
Some(dolor) => ...,
}
```
```rust
match lorem {
None => {
if ipsum {
println!("Hello World");
}
}
Some(dolor) => ...,
}
```

Add overflow_closures and overflow_match_arms opts

---

Configurations.md
src/config.rs
src/lists.rs
src/visitor.rs
tests/source/configs-merge_derives-true.rs
tests/target/configs-merge_derives-true.rs

cc https://github.com/rust-lang-nursery/fmt-rfcs/issues/72.
Note that when there are other attributes other than `#[derive(...)]` or doc comments, the merged derives will be put after all other attributes. See the diffs in lists.rs for example.

Add merge_derives config option

---

src/items.rs
src/lib.rs
src/visitor.rs
tests/source/issue-1914.rs
tests/target/issue-1914.rs

When formatting `ast::ForeignItem`, rustfmt used to ignore attributes and did not take max width into account.
Closes #1914. Closes #1915.

Implement Rewrite trait for ast::ForeignItem

---

src/lib.rs
src/macros.rs
tests/source/macros.rs
tests/target/macros.rs

Ignore empty lines inside arguments of macro with brace

---

Cargo.toml
src/comment.rs
src/expr.rs
src/items.rs
src/visitor.rs
tests/source/attrib.rs
tests/source/trait.rs
tests/target/attrib.rs
tests/target/comment.rs
tests/target/comment4.rs
tests/target/impl.rs
tests/target/trait.rs

This PR 
1. implements `recover_missing_comments_in_span()`, which is generalized function for recovering missing comments in the given span.
2. use it to recover missing comments.
3. preserve blank line between doc comment and attribute
4. apply some refactoring (e.g. use `String::with_capacity()` instead of `String::new()`)
Closes #1887.
Closes #1911.

Enhance comment formatting

---

Cargo.lock
src/bin/rustfmt-format-diff.rs
src/bin/rustfmt.rs
tests/system.rs

With `rustc 1.21.0-nightly (e26688824 2017-08-27)` I suddenly got errors and warnings on running `cargo build`, complaining about unused extern crate. This PR fixes it (with `cargo update`).

Remove unused extern crate

---

src/expr.rs
src/imports.rs
src/items.rs
src/lib.rs
src/visitor.rs
tests/source/attrib.rs
tests/target/attrib.rs

Format and preserve attributes on `ast::Stmt`

---

src/items.rs
tests/source/configs-item_brace_style-always_next_line.rs
tests/target/configs-item_brace_style-always_next_line.rs

This PR
1. adds `struct_remove_empty_body` config option which removes the empty braces from struct when set to `true`. 
2. puts the opening and the closing braces of empty struct and enum on the same line, even when `item_brace_style = AlwaysNextLine`.
~~Closes #1892.~~
Remove braces of empty struct definition.
- **Default value**: `false`
- **Possible values**: `false`, `true`.
*Note*: Braces with comments will not be removed.
```rust
struct Foo {}
Struct Bar()
struct FooBar { /* comment */ }
```
```rust
struct Foo;
struct Bar;
struct FooBar { /* comment */ }
```

Add struct_remove_empty_body config option

---

src/expr.rs
src/lib.rs
src/macros.rs
tests/source/macros.rs
tests/target/macros.rs

This PR enhances macro rewrite in two folds:
1. Closes #1742.
2. Allow `ast::Ty` and `ast::Pat` to appear in macro arguments (currently rustfmt is only capable of `ast::Expr`). Closes #1919.

Enhance macro rewrite

---

src/expr.rs
src/visitor.rs
tests/source/attrib.rs
tests/target/attrib.rs
tests/target/chains-visual.rs
tests/target/chains.rs
tests/target/hard-tabs.rs

This PR
1. adds small refactoring (https://github.com/topecongiro/rustfmt/commit/737186b8901a4c843f5b7eed2f3a9a8a3e41e397).
2. disables single-lined closure with block body w.r.t. Rfc style (https://github.com/topecongiro/rustfmt/commit/f8bdcd62e8f4087f602018c97063733590367ffe).
3. formats long derive (https://github.com/topecongiro/rustfmt/commit/47062c8f0a3a197a8e2f83e070c4be1e866514fa).
Closes #1941.

Some Fixes

---

src/items.rs
src/lib.rs
src/lists.rs
src/types.rs
tests/source/structs.rs
tests/target/structs.rs

This PR 
1. closes #1095.
2. avoids cloning string by creating a wrapper type in `rewrite_generics_inner()`.

Exclude prefix colon from span when rewriting comment

---

src/missed_spans.rs
src/visitor.rs
tests/source/comment.rs
tests/source/comment4.rs
tests/target/comment.rs
tests/target/comment4.rs

Use the last line's width for indent width in rewriting missed span to fix unindented comments

---

src/imports.rs
src/visitor.rs
tests/target/configs-reorder_imports_in_group-false.rs
tests/target/issue-1124.rs

Closes #1137 (with some refactorings).

Use write_list() to format imports

---

src/bin/cargo-fmt.rs

Closes #1963.
Due to a typo from #1931 😞

Avoid panicking when calling 'cargo fmt --all'

---

Configurations.md
src/chains.rs
src/comment.rs
src/config.rs
src/expr.rs
src/file_lines.rs
src/imports.rs
src/items.rs
src/lib.rs
src/lists.rs
src/macros.rs
src/missed_spans.rs
src/patterns.rs
src/string.rs
src/summary.rs
src/types.rs
src/utils.rs
src/vertical.rs
src/visitor.rs
tests/target/closure.rs
tests/target/configs-control_style-rfc.rs
tests/target/expr-block.rs
tests/target/expr.rs
tests/target/hard-tabs.rs
tests/target/issue-1239.rs
tests/target/match.rs
tests/target/type-ascription.rs

This PR implements a config option for controlling the placement of binary operators, and change the default to put binary operators in front so that it follows the style specified in RFC.
cc https://github.com/rust-lang-nursery/fmt-rfcs/issues/18.
cc https://github.com/rust-lang-nursery/fmt-rfcs/pull/91.

RFC: binop

---

Cargo.lock
src/expr.rs
src/items.rs
src/lib.rs
src/lists.rs
src/macros.rs
src/missed_spans.rs
src/utils.rs
src/visitor.rs

This PR changes the return type of some functions from `String` to `Cow<'static, str>` to avoid unnecessary allocation.

Refactoring: use Cow and etc.

---

src/expr.rs
src/imports.rs
src/types.rs
src/utils.rs
src/visitor.rs
tests/source/configs-reorder_imports-true.rs
tests/target/configs-reorder_imports-true.rs

Reorder use items inside blocks 

---

src/expr.rs
src/utils.rs

This PR removes `rewrite_call_with_binary_search()`. We can remove it because the default indent style for function call is now `"Block"`.

Remove rewrite_call_with_binary_search()

---

src/lib.rs
tests/config/disable_all_formatting.toml
tests/system.rs
tests/target/disable_all_formatting.rs

Echo back input from stdin when disable_all_formatting is true

---

src/comment.rs
src/expr.rs
src/items.rs

One of the most time consuming function in rustfmt is `recover_comment_removed()`. E.g. it takes up roughly 20% of the execution time when running rustfmt against librustc.
This PR attempts to avoid expensive recover procedure whenever possible by comparing the equality of original text and formatted text.
cc #338

Run recover_comment_removed() only if the text changed after format

---

src/patterns.rs

Hi! I'm currently adding support for `..=` syntax as a synonym for `...`: https://github.com/rust-lang/rust/pull/44709
I made a small change in ~HIR~ the AST which prevents rustfmt from compiling, however with this workaround it will compile without errors, in both old and new versions of rustc. Once the PR gets merged, I will fix this. Basically the change in ~HIR~ the AST is the new RangeSyntax enum:
enum RangeEnd {
// Included,
Included(RangeSyntax),
Excluded,
}
enum RangeSyntax {
DotDotDot, // ...
DotDotEq,  // ..=
}

Temporarily replace `RangeEnd::Included` with `_`

---

src/expr.rs
src/items.rs
src/macros.rs
src/patterns.rs

Since we entirely removed binary search from `rewrite_call()`, there is no need to return `Result<String, Ordering>` any more.

Change return type of rewrite_call_inner() to Option<String>

---

src/comment.rs
src/visitor.rs
tests/source/macros.rs
tests/target/macros.rs

Remove trailing white spaces from macro def unless spaces are inside raw strings.
Closes #878.

Remove trailing whitespaces in macro def

---

src/items.rs
src/lists.rs
src/utils.rs

Fixes #617 ... for now.
The problem was that some codes are assuming the newline in the input code is always '\n'. Especially, str.starts_with('\n') was breaking danger because it always fail in CRLF environment.
I'm still feeling uncomfortable that so many codes seems to not consider CRLF env, but fortunately str.ends_with('\n') and str.contains('\n') both work properly under CRLF env. At least, no tests are broken in Windows anymore.
Need to push #2028 beforehand to check if the tests are really fixed under Windows.

Fix broken tests under CRLF environment.

---

Contributing.md
src/chains.rs
src/comment.rs
src/expr.rs
src/imports.rs
src/items.rs
src/lists.rs
src/macros.rs
src/patterns.rs
src/shape.rs
src/string.rs
src/types.rs
src/utils.rs
src/vertical.rs
src/visitor.rs

For fun and profit, closes #2034.

Replace `try_opt!` macro with a `?` operator

---

tests/system.rs

Fixes #1318 .
This just fixes the framework error: Many tests are still failing under Windows machine because of CRLF newline. Maybe I follow up with another pull requests.
Note: I cannot use str::lines() method to compare because that method does not respects the last empty line in the file.
https://doc.rust-lang.org/std/string/struct.String.html#method.lines

Fix the test framework is failing in CRLF env.

---

tests/source/issue-1211.rs
tests/target/issue-1211.rs

Since rustfmt has moved away from syntex the overflow seen in https://github.com/rust-lang-nursery/rustfmt/issues/1211 is no longer a problem. This commit adds a test to verify that.
Closes #1211.

Add a test for issue 1211, showing it's no longer an issue.

---

src/chains.rs
src/expr.rs
src/shape.rs
src/types.rs
src/utils.rs

This PR consists of small refactorings.
The last commit is suspicious, rustfmt removes trailing comma from function call.

Refactorings

---

src/bin/rustfmt.rs

output --dump-default-config to stdout if no path is given

---

README.md

Would make it easier to see what the version is and to get to https://crates.io/crates/rustfmt-nightly from https://github.com/rust-lang-nursery/rustfmt

Add crates.io version shield

---

README.md
src/bin/rustfmt.rs

Fixes #317.
Resubmission of #1982.
r? @nrc

Document `--dump-default-config` in README.md

---

src/expr.rs
tests/source/closure.rs
tests/target/closure.rs

Take width of return type into account for body shape of closure

---

src/bin/rustfmt.rs
src/config.rs

This option specifies the rustfmt version that *must* be used to format the code. Trying to use a
different version raises an error.
closes #1505

add `required-version` option to rustfmt.toml

---

src/rustfmt_diff.rs

While working on #1173, I found that calling `make_diff` with `context_size` of `0` didn't work properly (or at least not as I expected!): it sometimes includes a `Context` line (I think in the first `Mismatch`) and splits a contiguous chunk of changed lines into separate `Mismatch`es.
I'm not completely convinced about what it does with `context_size>0` and two changes closer than that together; it splits it into two `Mismatch` items after the context lines between them.  The Unix diff command merges them together.  In any case, I don't think I've changed how that behaves.

Fix make_diff with zero context requested

---

src/bin/cargo-fmt.rs
src/bin/rustfmt.rs
src/visitor.rs

Adjusts several error and warning report cases to output using eprintln! instead of println! so that messages are sent to stderr. Attempts to address https://github.com/rust-lang-nursery/rustfmt/issues/1979

Use stderr for various errors and warnings.

---

src/lib.rs

Expands the error message returned if the after_file function fails to also include path_str. This allows users to better identify files that are not being formatted. Attempts help address https://github.com/rust-lang-nursery/rustfmt/issues/1880, though doesn't provide the stats on how many files were and were not formatted.
Wasn't sure how to test or if a test is sane here, but please advise if anyone looking at this has any ideas how to do so.

Return a more verbose error when formatting a file fails

---

Configurations.md
src/config.rs
src/expr.rs
tests/source/configs-match_arm_forces_newline-true.rs
tests/target/configs-match_arm_forces_newline-true.rs

This is an attempt at implementing #2039. I don't quite understand `rewrite_match_body` function yet, I just played around with some parameters until it indented as I wanted.

[not ready] Implement match_arm_forces_newline option (#2039)

---

src/expr.rs
tests/source/closure.rs
tests/target/closure.rs

An example taken from [rls/src/build/cargo.rs](https://github.com/rust-lang-nursery/rls/blob/75f97194ff7a265184fd0212086ad9e94b44096a/src/build/cargo.rs#L385-L393):
```rust
let modified = args.iter()
.map(|a| {
// Emitting only dep-info is possible only for final crate type, as
// as others may emit required metadata for dependent crate types
if a.starts_with("--emit") && is_final_crate_type && !self.workspace_mode {
"--emit=dep-info"
} else { a }
})
.collect::<Vec<_>>();
```
rustfmt fails to format the above snippet. This PR fixes it.

Fix rustfmt failing to format closure block body with comment

---

src/expr.rs
tests/source/macros.rs
tests/target/macros.rs

Only read the trailing comma of outermost fn call 

---

src/bin/cargo-fmt.rs

Closes #2056.
I apologize for messed up commits 😭

Add local dependencies to targets

---

src/lib.rs

Needed for [this PR](https://github.com/rust-lang/rust/pull/44636#issuecomment-336191781).
However, this'll break until the mentionned PR gets merged, and the mentionned PR requires this one to be merged otherwise tests won't pass. So much fun. :)

Update to last Emitter update

---

src/bin/cargo-fmt.rs

With rustfmt-nightly 0.2.10, `cargo fmt` fails when it fails to resolve the path to local dependencies. This PR fixes it by not propagating the io error when local dependencies cannot be found.

Do not propagate io error when dependencies are not found

---

src/bin/rustfmt.rs
src/config.rs

Hello,
This is my first contribution to any open source project, so any advice would be awesome and thank you for being nice :) 
I am checking CFG_RELEASE_CHANNEL environment option to see if we are running on nightly version, I am not confident about this solution. There's must be a better way that I've missed.
All the tests are passing, I've added 2 tests to verify if my changes are working, which are also passing.
Thank you

Implemented 'unstable options' command line option

---

Configurations.md
Design.md
README.md
src/chains.rs
src/comment.rs
src/config.rs
src/expr.rs
src/issues.rs
src/lists.rs
src/macros.rs
src/patterns.rs
src/vertical.rs
src/visitor.rs
tests/source/configs-struct_field_align_threshold-20.rs
tests/source/fn-simple.rs
tests/source/fn_args_density-vertical.rs
tests/source/issue-1049.rs
tests/source/issue-1468.rs
tests/source/match.rs
tests/source/structs.rs
tests/source/unions.rs
tests/target/configs-struct_field_align_threshold-20.rs
tests/target/fn-simple.rs
tests/target/fn_args_density-vertical.rs
tests/target/issue-1049.rs
tests/target/issue-1468.rs
tests/target/match.rs
tests/target/structs.rs
tests/target/unions.rs

This is the result of me testing out a WIP source code spell-checker
and your project was the random target this time.

fix some typos

---

src/comment.rs
src/expr.rs
src/string.rs
tests/source/soft-wrapping.rs
tests/target/soft-wrapping.rs

This PR is a first step to implementing soft wrapping for comments (cc #535).
Note that this PR does **NOT** implement soft wrapping for doc comments (`///` or `//!`). Currently each line of doc comments are rewritten on its own due to how it's implemented in AST (a vector of `ast::Attribute`). Fixing this will be in a different PR, hopefully.

Soft wrapping for comments

---

Contributing.md

_This is a little speculative._
The [current "good starting issues" link](https://github.com/rust-lang-nursery/rustfmt/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy) in [Contributing.md](https://github.com/rust-lang-nursery/rustfmt/blob/master/Contributing.md) searches for issues labeled with "easy". There are currently no issues -- opened or closed -- with this label.
I arrived here via https://www.rustaceans.org/findwork/starters/rustfmt, which is looking for issues labeled with "good-first-issue". Here's the speculation: I'm guessing that at some point in the past the "easy" label in this repository was updated to "good-first-issue". This PR was created, in case that's correct.
The PR changes the link to [this](https://github.com/rust-lang-nursery/rustfmt/issues?q=is%3Aopen+is%3Aissue+labe …

Updating good starting issues link

---

src/bin/cargo-fmt.rs
src/chains.rs
src/comment.rs
src/expr.rs
src/types.rs
src/vertical.rs
src/visitor.rs
tests/source/closure-block-inside-macro.rs
tests/system.rs
tests/target/chains-visual.rs
tests/target/chains.rs
tests/target/hard-tabs.rs

This PR forces rustfmt to use block when rewriting the body of closure with a single control flow expression.
CC #1791, https://github.com/rust-lang-nursery/fmt-rfcs/issues/35.

Force to use block for closure body with a single control flow expression

---

src/items.rs
tests/target/issue-2103.rs

Handle case where there is a where clause but no generic parameters.

---

src/chains.rs
src/items.rs
tests/source/chains.rs
tests/target/chains.rs

Closes #2126.
I was wondering if we should allow first child on the next line if there is an offset:
```rust
// Don't do this
self
.span_from(sub_span.expect("No span found for struct arant variant"));
// But this is fine?
let x = self
.span_from(sub_span.expect("No span found for struct arant variant")); 
```

Handle chain with a single long child with a small parent 

---

src/bin/git-fmt.rs
src/visitor.rs
tests/source/soft-wrapping.rs
tests/target/enum.rs
tests/target/soft-wrapping.rs

Soft wrapping doc comments

---

src/items.rs
tests/source/trait.rs
tests/target/trait.rs

Comments around trait bounds

---

Configurations.md

The example for `where_density = "Vertical"` in Configurations.md does not match the current output from rustfmt. This corrects that.
You can view the live change [here](https://github.com/davidalber/rustfmt/blob/fix-where-density-examples/Configurations.md#vertical-default-1) and compare with the current format [here](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#vertical-default-1). The `where_density = "Tall"` example, which this change makes "Vertical" identical to, is [here](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#tall).
Fixes #2133.

Updating `where_density = "Vertical"` example

---

Configurations.md

A live version of the new example is [here](https://github.com/davidalber/rustfmt/blob/add-combine-control-expr-example/Configurations.md#false-2). The existing `combine_control_expr = true` example is [here](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#true-default-2), in case that's useful for comparison in any way.
Fixes #2132.

Adding an example for `combine_control_expr = false`

---

src/items.rs
tests/source/structs.rs
tests/target/structs.rs

This PR is a follow up of #2145, fixes an issue that where clause on unit struct gets removed.

Format where clause on unit struct

---

Cargo.lock
src/checkstyle.rs
src/rustfmt_diff.rs

This was a bug in the `diff` crate which has been fixed in 0.1.11. This PR
simply bumps `diff` to that version.
Fixes #1753.
$ xxd main.rs
00000000: 666e 206d 6169 6e28 2920 7b7d            fn main() {}
$ cargo run --bin rustfmt -- main.rs --write-mode=diff
$ echo $?
0
$ git checkout issue-1753
Switched to branch 'issue-1753'
$ cargo run --bin rustfmt -- main.rs --write-mode=diff
Diff in /Users/utkarsh/dev/git/rustfmt/main.rs at line 1:
fn main() {}⏎
+⏎
$ echo $?
4
cc @afshinm @octaltree

Fix missing trailing newline in --write-mode=diff.

---

src/items.rs
tests/source/enum.rs
tests/target/enum.rs

Recover from failing to format variants even where there is no comment 

---

Cargo.lock
Cargo.toml
src/bin/cargo-fmt.rs
src/config.rs

This PR replaces the direct calls of `cargo metadata` with `cargo_metadata` crate. Also, this PR fixes some bugs related to `cargo fmt`.
Closes #1201.
Closes #2182.
Closes #2189.

Use cargo_metadata

---

src/bin/rustfmt.rs
src/chains.rs
src/comment.rs
src/expr.rs
src/items.rs
src/visitor.rs
tests/source/chains.rs
tests/target/chains-visual.rs
tests/target/chains.rs
tests/target/configs-fn_call_indent-block.rs
tests/target/issue-913.rs
tests/target/match.rs
tests/target/pattern.rs

Fix budget-related bugs when rewriting chain

---

src/closures.rs
src/expr.rs
src/visitor.rs
tests/source/closure.rs
tests/target/closure.rs

Use an explicit flag to decide on whether to add brace compensation for block expression

---

src/bin/cargo-fmt.rs
src/config.rs
src/expr.rs
src/issues.rs
src/items.rs
src/macros.rs
src/patterns.rs
src/types.rs
src/visitor.rs
tests/target/configs-force_multiline_block-false.rs

cc https://github.com/rust-lang-nursery/fmt-rfcs/issues/61, #1791. 
Please feel free to keep this open and umerged if necessary.

Do not put if on the same line as match arm

---

src/imports.rs
src/visitor.rs

Rustfmt will be broken after rust-lang/rust#45846 (support for the `use_nested_groups` feature) lands on nightly. That PR completly changes the AST for `use` declarations, so imports formatting will break.
This PR fixes rustfmt to keep the old behavior with the new AST, and adds _partial_ support for the new features introduced in the rustc PR: some of them will work, some will behave unexpectedly and some will just panic with `unimplemented!`.

Fix broken build after use_nested_groups lands on nightly

---

Configurations.md

I combined the examples into single examples with comments announcing each code example.
Closes #2220

Combine 3 repeated sections into a single section

---

src/bin/cargo-fmt.rs

Do not pass files as arguments to rustfmt when dumping the default config

---

src/types.rs
tests/source/macros.rs
tests/target/macros.rs

Format a macro in the type position

---

src/chains.rs
tests/source/chains.rs
tests/target/chains.rs

Fix double indented chained closure

---

Configurations.md

A duplicate codeblock end marker broke the formatting of this example.

Fix format for `spaces_around_ranges` example

---

src/config.rs

Warnings on stdout can really hurt Rls as it's a stdin-stdout server, see https://github.com/rust-lang-nursery/rls/issues/616. This PR routes the config warnings to stderr instead. Feel free to fix another way and close this PR.

Fix config warnings leaking into stdout

---

.travis.yml

Builds on macOS are failing, e.g. https://travis-ci.org/rust-lang-nursery/rustfmt/jobs/310698549, due to `pip` not working.
This PR
- ensures that python is installed on macOS (travis-ci/travis-ci#2312)
- does `pip install --user` on linux but without `--user` on macOS, which has python in virtualenv
- sets up PATH in a os-agnostic manner (huonw/travis-cargo#71)

[Travis] Fix python/travis-cargo on macOS

---

src/bin/rustfmt-format-diff.rs
src/comment.rs
src/expr.rs
src/imports.rs
src/items.rs
src/lib.rs
src/macros.rs
src/patterns.rs
src/rewrite.rs
src/rustfmt_diff.rs
src/visitor.rs

rustfmt makes heavy use of `snippet()` to fetch a piece of snippet from the original file. It returns `String`, even though we do not modify the returned value. It is preferable to return `&str` to avoid allocations on heap.
We get about 15% speed up against a large code base. The following is a quick experiment result that runs `cargo fmt --all` against rustc:
- OS: Linux 4.13.16
- rustc: `rustc 1.24.0-nightly (1956d5535 2017-12-03)`
- CPU: `Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz`
- RAM: 8GB
| version | time [s] (an average of 10 attempts) |
| ----------|-------|
| master (0432d4db35cee640ca96460f4ebc4baad3891d6d) | 9.77 |
| PR (a5b5ef078bd835f68a1e2b8eb5f63d0797e4e0e8) | 8.47 |
This PR introduces `unsafe` code in rustfmt (specifically in `impl SnippetProducer`):
- transmute …

Optimize snippet()

---

src/config.rs

Per discussion in #2228
https://github.com/rust-lang-nursery/rustfmt/pull/2228#issuecomment-348893294
https://github.com/rust-lang-nursery/rustfmt/pull/2228#issuecomment-349799548
Inline comment should explain the reasoning.
Open to bikeshed.

unstable_features without CFG_RELEASE_CHANNEL

---

src/imports.rs
src/items.rs
src/lib.rs
src/missed_spans.rs
src/spanned.rs
src/visitor.rs

Closes #1298.
Closes #2006.
Closes #2037.
cc #1978.
Note that this PR still warns on nested expressions with `[rustfmt_skip]`:
```rust
fn foo() {
// Does not report an error.
#[rustfmt_skip]
let a = foo(
vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
);
// Reports an error.
let a = bar(
#[rustfmt_skip] vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
);
}
```
Handling nested expressions is hard because we do not use visitor for them. Assuming that most of the usage of `#[rustfmt_skip]` is on items or statements, I will send this PR anyway.

Do not report errors on skipped items or statements 

---

src/chains.rs
src/closures.rs
src/expr.rs
tests/source/chains-visual.rs
tests/target/chains-visual.rs

Closes #2264.
`.block()` and `block_only()` were used as safe guards when switching the default indent style from visual to block. Now that the indent style is consistent throughout expressions, we can remove them safely.

Remove block() and block_only() wherever possible

---

src/expr.rs
src/items.rs
tests/source/expr.rs
tests/target/expr.rs

rustfmt fails to format assignment if it uses exactly 100 (or `max_width`) chars up to `=`:
```rust
// From src/items.rs
fn bar() {
if let ast::ItemKind::Trait(_, unsafety, ref generics, ref type_param_bounds, ref trait_items) = item {
//                                                                                             ^ 100 chars
abcdefg;
}
}
```
This PR fixes it.

Assignment whose lhs has 100 chars

---

src/bin/rustfmt.rs
src/config.rs

This PR
1. prevents printing usage when rustfmt failed due to IO errors. Also adds summary "Format Rust code".
2. warns when there are unknown configuration options. Currently rustfmt does not emit any warning. Since we have removed and combined many config options, we should explicitly warn these changes to the user. This is not a hard error: rustfmt still formats files even when unknown config options is in rustfmt.toml.

Attempt to improve error meassage from rustfmt

---

src/bin/cargo-fmt.rs
src/comment.rs
src/expr.rs
src/filemap.rs
src/imports.rs
src/items.rs
src/macros.rs
src/missed_spans.rs
src/summary.rs
src/visitor.rs

This PR
1. applies refactorings from `cargo clippy`.
2. refactors `write_snippet_inner()`. First split it into `process_comment()` and `process_missing_code()`, then simplify each functions.

Refactorings from cargo clippy etc.

---

Configurations.md
README.md

Closes #2227
Stability extracted manually from [config.rs](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/config.rs#L584-L689). If I read #1998 correctly, the third argument to each line in the `create_config!` is a boolean indicating un/stable, which is what is now represented here as well.
The `unstable_features` option is not separately documented, only at the top as how to enable unstable configuration options.

Add configuration stability information

---

src/expr.rs
src/items.rs
tests/target/type_alias.rs

Use `rewrite_assign_rhs()` when rewriting type alias.
cc #2294, where macro in type position is indented excessively.

Fix wrong indentation on type alias

---

src/missed_spans.rs
tests/source/hard-tabs.rs
tests/target/hard-tabs.rs

Using last_line_width() ignores the width of tab character ('\t').
Closes #2296.

Fix indent width bug when recovering comments

---

src/bin/cargo-fmt.rs

- Running `rustfmt` to get version.
- Did some refactoring to share code with the format files code path.
Before:
```sh
$ cargo run --bin cargo-fmt -- --version
.
.
.
Unrecognized option: 'version'
```
After:
```sh
$ cargo run --bin cargo-fmt -- --version
.
.
.
0.3.2-nightly ( )
```
Fixes #2269.

Adding --version to cargo-fmt

---

tests/system.rs

_This addresses the test infrastructure changes for #1492._
Test counts before:
- coverage: 1
- system: 227
- idempotent: 276
- self: 7
Test counts after:
- coverage: 1
- system: 235
- idempotent: 284
- self: 7
The difference of eight in the system and idempotency tests is due to already-existing files in subdirectories of tests/source and tests/target. They all pass, but from the associated PRs and commits, it's not clear to me they are supposed to be formatted.
```
$ tree tests/source/nested_skipped/ tests/source/nestedmod/
tests/source/nested_skipped/
└── mod.rs
tests/source/nestedmod/
├── mod.rs
├── mod2a.rs
├── mod2b.rs
├── mod2c.rs
├── mymod1
│   └── mod3a.rs
└── submod2
├── a.rs
└── mod.rs
```

Adding ability to recursively find test files

---

README.md

This complements https://github.com/rust-lang-nursery/rustfmt/commit/7a4daf0d415cf5760c8133d6d643b235de7583f1.

Fix version replacement notes for CI in README.md

---

README.md

This is a minor README-formatting change that aligns text with the bullet it is part of. Look starting at "On Linux" in the screenshots below.
**[Current](https://github.com/rust-lang-nursery/rustfmt#tips):**
**[Updated](https://github.com/davidalber/rustfmt/tree/indent-bullet-text#tips):**

Aligning text with its bullet

---

src/codemap.rs
src/expr.rs
src/lists.rs
tests/source/macros.rs
tests/system.rs
tests/target/macros.rs

Continuing with the implementation of rust-lang-nursery/fmt-rfcs#86, allows for this form of `assert_eq!` macros:
```rust
assert_eq!(
left.id, right.id,
"IDs are not equal: {:?} {:?}",
left, right
);
```
As a side-effect of how I implemented this it also allows for `assert!` macros to have the format arguments split across multiple lines even if the assert condition is not simple:
```rust
assert!(
result >= 42,
"The result must be at least 42: {:?}",
result, result.code, context
);
```
I think that's reasonable behaviour, although not explicitly specified in the RFC pull request (rust-lang-nursery/fmt-rfcs#110)

Add assert_eq! to special-cased macros

---

src/config.rs
src/lib.rs
src/macros.rs
src/visitor.rs
tests/source/macros.rs
tests/target/macros.rs

Formats some macros 2.0 macro defs (only the most sugary kind, see the tests, and it only tries - in many cases it will fail).
The basic strategy is to parse the macro into parts, roughly format the tokens in the arguments, then replace any arguments in the macro body (e.g., `$x` with `zx`), then attempt to format the macro body as if it were regular code. If that succeeds, then we undo the substitutions and put all the parts together.
r? @topecongiro

Some macros 2.0 macro defs

---

Configurations.md

Closes #2312 
I am really not sure if I did everything correctly here. For example: I put the two options at the end of `Configurations.md`, because I didn't know where to put them otherwise. The order of `rustfmt --config-help` doesn't match the order in `Configurations.md`.
Just tell me what I could improve. Happy holidays, of course :)

Add options `blank_lines_{lower|upper}_bound` to `Configurations.md`

---

src/items.rs
src/utils.rs
tests/target/issue-2329.rs

The panic was caused by `+1` inside `trim_newlines()`. It turns out that this function is unnecessary, because we call this against `trim()`med buffer 😛 
Closes #2329.

Issue 2329

---

Cargo.lock
Cargo.toml
Configurations.md
src/rustfmt_diff.rs
tests/system.rs

This PR adds a test that extracts Rust code blocks from [Configurations.md](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md) and attempts to format them. This is the automation part of #1845. If we get through this, the next step will be fixing the formatting failures.
Some details on how this works:
- Rust code blocks are identifed by lines beginning with "```rust".
- One explicit configuration setting is supported per code block.
- Rust code blocks with no configuration setting are illegal and cause an assertion failure.
- Configuration names in Configurations.md must be in the form of "## \`NAME`".
- Configuration values in Configurations.md must be in the form of "#### \`VALUE`".
- Each extracted block is formatted.
- Mismatches are prepended by a message …
```

Configurations checking

---

src/expr.rs

`ExactSizeIterator` is seemingly unused in expr.rs. This removes it from the block of `use` statements.

Removing unused name

---

tests/system.rs

While looking at the list of examples to update in Configurations.md, I realized the failure messages added in #2292 aren't consistent with the format used in the mismatch failure message. This commit modifies them to be more consistent and more concise.

Modifying failure messages to be consistent with mismatch message

---

src/rustfmt_diff.rs
tests/system.rs

This is my followup to [this comment from #2292](https://github.com/rust-lang-nursery/rustfmt/pull/2292#discussion_r159597526):
> After this PR, I'm going to spin up a new one to merge `print_diff_fancy` and `print_diff_basic` by adding more implementation to the enum. I think the enum is too abstract like this.
I actually eliminated the PrintType enum and created a struct -- OutputWriter -- that contains the logic for determining whether to write output using `println!` or a Terminal instance from the term crate. This allowed `print_diff_fancy` and `print_diff_basic` to be consolidated into `print_diff`.

Consolidating the logic for printing output

---

src/expr.rs
src/items.rs
tests/system.rs
tests/target/issue-2324.rs

Issue 2324

---

Configurations.md

As the next phase of #1845 I am fixing the formatting failures uncovered by #2292. Most of them are straightforward and will arrive as one big PR. I am submitting this one separately because it potentially exposes a bug.
In terms of getting the test to pass, here's the line failure count for `cargo test -- --ignored` before the change:
```
Ran 104 configurations tests.
left: `55`,
right: `0`: 55 configurations tests failed', tests/system.rs:790:5
```
Here's the line failure count for `cargo test -- --ignored` after the change:
```
Ran 104 configurations tests.
thread 'configuration_snippet_tests' panicked at …
```

Getting `binop_separator="Back"` snippet in Configurations.md to pass

---

Configurations.md

#2361 accidentally changed `let or =` into `r =`. This change corrects that.

Restoring accidentally-removed characters

---

Configurations.md
src/expr.rs

Hard coded SeparatorPlace::Front in call to rewrite_pair for range
caused binop_separator="Back" to be handled incorrectly
Fixed call to rewrite_pair and the example in Configuration.md showing
the faulty behavior

Fixing binop_separator="Back" for ranges (Issue #2364)

---

src/expr.rs
tests/source/macros.rs
tests/target/macros.rs

Do not panic when special macros have less args than expected

---

src/lib.rs
tests/system.rs

Tabs are currently measured as `1` character when detecting `ErrorKind::LineOverflow`. Instead, they should use `config.tab_spaces()` to ensure `hard_tabs = true` correctly identifies failing lines.
The following configuring should produce:
```
error: line exceeded maximum width (maximum: 20, found: 21)
```
```toml
hard_tabs = true
max_width = 20
```
```rs
fn method() {
aaaaaaaaaaaaaaaaa
}
```
No error occurs. The tab is counted as a single character (`found: 18`).

LineOverflow: Count tabs as tab_spaces when measuring line length for overflow

---

Configurations.md
src/patterns.rs
tests/source/configs/spaces_around_ranges/false.rs
tests/source/configs/spaces_around_ranges/true.rs
tests/target/configs/spaces_around_ranges/false.rs
tests/target/configs/spaces_around_ranges/true.rs

Currently, the `spaces_around_ranges` configuration option only affects ranges in statements. For example, `let lorem = 0..10;` becomes `let lorem = 0 .. 10;`, if `spaces_around_ranges=true`. However, if `spaces_around_ranges=true` the following is not formatted as one might expect:
```rust
match lorem {
1..5 => foo(),
_ => bar,
}
```
This PR extends the effect of `spaces_around_ranges` to match arm patterns.
Fixes #2372 and will supersede #2373, if accepted.

Extending `spaces_around_ranges` to ranges in match arm patterns

---

Configurations.md

This is the first batch of straightforward configuration snippet fixes for #1845. The second batch will follow, but I wanted to get this out since it has been accumulating for a while.
The fixes use a few approaches. The most common changes are to wrap the snippet in a function and to make the line longer to reach the default max width, which often triggers formatting.
This batch corrects thirty configuration snippets, as can be seen with `cargo test -- --ignored`. Here is the output on master:
```
Ran 104 configurations tests.
left: `54`,
right: `0`: 54 configurations tests failed', tests/system.rs:790:5
```
Here is the output on the PR branch:
```
---- …
```

Fixing straightforward configuration snippets (Part 1)

---

src/bin/rustfmt.rs

This is a tiny PR that lets the rustfmt binary build without a CARGO_PKG_VERSION environment variable, using "unknown" in its place if necessary.
I happen to compile this library without Cargo, and thus don't have this variable present. It is possible for me to spoof the value if there are objections making the value optional.

Make rustfmt-bin's CARGO_PKG_VERSION envvar optional

---

src/comment.rs
src/items.rs
tests/source/enum.rs
tests/target/enum.rs

Closes #2389.
We still put attributes and fields on the same line inside variant (I hope I am using the right terminologies). For example,
```rust
// Attributes on the same line
pub enum Entry<'a, K: 'a, V: 'a> {
Vacant(#[stable(feature = "rust1", since = "1.0.0")] VacantEntry<'a, K, V>),
Occupied(#[stable(feature = "rust1", since = "1.0.0")] OccupiedEntry<'a, K, V>),
}
// Attributes on the different line
pub enum Entry<'a, K: 'a, V: 'a> {
#[stable(feature = "rust1", since = "1.0.0")]
Vacant(VacantEntry<'a, K, V>),
#[stable(feature = "rust1", since = "1.0.0")]
Occupied(OccupiedEntry<'a, K, V>),
}
```

Put attributes and enum variants on different lines

---

Configurations.md

This is the second -- and final -- batch of straightforward configuration snippet fixes for #1845. See #2369 for the first batch.
As in the previous PR, the fixes use a few approaches. Most commonly, snippets are wrapped in a function and lines are made longer to reach the default max width, which often triggers formatting.
This batch corrects sixteen configuration snippets, as can be seen with `cargo test -- --ignored`. Here is the output on master:
```
Ran 104 configurations tests.
left: `22`,
right: `0`: 22 configurations tests failed', tests/system.rs:800:5
```
Here is the output on the PR branch:
```
Ran 104 …
```

Fixing straightforward configuration snippets (Part 2)

---

Cargo.lock
Cargo.toml
src/closures.rs
src/expr.rs
tests/source/immovable_generators.rs
tests/target/immovable_generators.rs

Support immovable generators

---

Cargo.lock
Cargo.toml
src/codemap.rs
src/visitor.rs

Fixes #2403 (I think)
r? @topecongiro 
`is_mod_decl` was introduced for the re-ordering modules PR. I think the removed clause is bogus if we are formatting a program passed as a string rather than a file since in that case we have the 0s for `mod foo;`. Simply removing the clause seemed to pass tests, but I'm not sure if you had some use case in mind?

Make `is_mod_decl` more accommodating

---

src/macros.rs
tests/source/macros.rs
tests/target/macros.rs

Formatting macro def with repeat is a bit rough, so just skip it for now. This PR at least avoids panicking reported in #2388.

Skip rewriting macro def with repeat

---

README.md

Remove reference to the syntex version as it is outdated, and use rustup over cargo for installing rustfmt. cc #2402.

Update a minimal travis example

---

src/lib.rs
tests/target/issue-2401.rs

When using hard tabs, we should only remove `\t`.
Closes #2401.

Use correct offset when unindenting code block

---

src/visitor.rs
tests/source/configs/reorder_extern_crates/false.rs
tests/source/configs/reorder_extern_crates/true.rs
tests/target/configs/reorder_extern_crates/false.rs
tests/target/configs/reorder_extern_crates/true.rs

Closes #2399.
Currently rustfmt reorders items without attributes. This PR relaxes this rule, and items without `#[macro_use]` will be reordered. AFAIK the only attribute that makes items order-dependent is `#[macro_use]`, so I think this change is safe, but I could easily be wrong.
r? @nrc

Do not reorder items with '#[macro_use]'

---

src/bin/cargo-fmt.rs
src/config.rs
src/macros.rs
src/spanned.rs
src/utils.rs
src/visitor.rs
tests/source/macro_rules.rs
tests/target/macro_not_expr.rs
tests/target/macro_rules.rs
tests/target/macros.rs

I took an existing logic for Macros 2.0 and adapted for "legacy" (stable) `macro_rules` syntax. At this point it seems to produce quite consistent and expected results.
Admittedly the code is quite hacky, but I guess that's what one should expect when attempting to format macros. If not, I'm open to suggestions :)
Issue: #8

Format stable macro_rules

---

Configurations.md

This PR fixes the two [control flow snippets for in Configurations.md](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#control-flow) per the outcome of #2427.
Here is the current output of `cargo test -- --ignored` on master:
```
Ran 106 configurations tests.
left: `6`,
right: `0`: 6 configurations tests failed', tests/system.rs:800:5
```
Here is the output of `cargo test -- --ignored` on the PR branch:
```
Ran 106 configurations tests.
left: `4`,
right: `0`: 4 configurations tests failed', …
```

Fixing `indent_style` control flow examples

---

rustfmt-core/tests/lib.rs

Issue #2419 changed the directory in which `configuration_snippet_tests` runs, which broke the test. Since the test is currently annotated with `#[ignore]`, the break wasn't caught before merge.
Currently, running `cargo test -- --ignored` on master currently yields the following.
```
thread 'configuration_snippet_tests' panicked at 'Couldn't read file Configurations.md: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
```
Running `cargo test -- --ignored` on the PR branch yields the following.
```
.
.
.
Ran 106 configurations tests.
left: `4`,
right: `0`: 4 …
```

Fixing path to Configurations.md

---

rustfmt-core/tests/lib.rs

The build is warning about an unused import ([see Line 603 of this build](https://travis-ci.org/rust-lang-nursery/rustfmt/jobs/340285804#L603), for example).
```
Compiling rustfmt-core v0.4.0 (file:///home/travis/build/rust-lang-nursery/rustfmt/rustfmt-core)
warning: unused import: `config::file_lines::FileLines`
--> rustfmt-core/tests/lib.rs:30:5
|
30 | use config::file_lines::FileLines;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: #[warn(unused_imports)] on by default
```
This PR remove the unused import.

Removing unused import

---

Configurations.md
rustfmt-core/tests/lib.rs

[Configurations.md](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md) contains two snippets ([here](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#example) and [here](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#example-1)) whose format is not meant to verified. The current code in master tries and fails to format those snippets. This PR introduces a mechanism to opt configuration code snippets out of verification.
To opt a snippet out of verification, add `// rustfmt: skip` to the top of the snippet. This is visible when viewing the file through the web UI.
Here is the output of `cargo test -- --ignored` on master:
```
Ran 106 configurations tests.
thread …
```

Skipping formatting of some configuration snippets

---

Configurations.md

The command-line option `--unstable-options` does not exist, but `--unstable-features` does. From `rustfmt --help`:
```
--unstable-features
Enables unstable features. Only available on nightly
channel
```

Fixing command-line option name

---

rustfmt-core/src/macros.rs
rustfmt-core/tests/source/macro_rules.rs
rustfmt-core/tests/target/macro_rules.rs

Disable formatting macro-def if args do not fit on one line

---

rustfmt-core/src/lib.rs
rustfmt-core/tests/source/macro_rules.rs
rustfmt-core/tests/target/macro_rules.rs

`MacroBranch::rewrite()` assumes that when `format_code_block()` returns `Some(s)`, then `s` is a correctly formatted code block. Currently this is not the case, `format_code_block()` may return `Some(s)` even if if has failed to format the code. This PR tries to fix it by checking the width of each line and if it is not exceeding the max width. 
Closes  #2438.

Return `None` when format_code_block may have failed

---

README.md

I set up a [project](https://github.com/davidalber/rustfmt-travis) that verifies [the minimal Travis CI config from the README](https://github.com/rust-lang-nursery/rustfmt#checking-style-on-a-ci-server). That project's build will fail if the Travis config stops working. It also has a test to verify that its .travis.yml matches the example in the rustfmt README.
This PR adds a badge of the other repository's build so that there will be a visual indicator whether the configuration still works. You can see the live change [here](https://github.com/davidalber/rustfmt/tree/travis-config-badge#checking-style-on-a-ci-server).
It seems like a good idea to me, and I'd like to read comments on it. If you like the idea, but don't want it in a repository outside the organization, I'm happy to help …

Proposal: add badge for Travis CI example status

---

Contributing.md

Also specifically mention the IRC network (irc.mozilla.org) that the channel is on.

IRC channel is now #rust-dev-tools

---

rustfmt-core/src/comment.rs
rustfmt-core/src/visitor.rs
rustfmt-core/tests/source/markdown-comment.rs
rustfmt-core/tests/target/markdown-comment.rs

Preserve trailing two whitespace in comments

---

rustfmt-core/src/lib.rs
rustfmt-core/tests/source/configs/skip_children/true.rs
rustfmt-core/tests/target/configs/skip_children/true.rs

Do not try to parse external modules when skipping children

---

rustfmt-core/src/comment.rs
rustfmt-core/tests/source/markdown-comment-with-options.rs
rustfmt-core/tests/target/markdown-comment-with-options.rs

Preserve trailing spaces in doc comments even when options are set

---

rustfmt-config/src/lib.rs

It was rendering the phrase as "Whether to use different formatting for items andexpressions if they satisfy a heuristic notion of 'small'.". It should be: "Whether to use different formatting for items and expressions if they satisfy a heuristic notion of 'small'.". Note the space between "and" and "expressions".

Fixed small typo in configuration help

---

rustfmt-core/src/expr.rs
rustfmt-core/src/spanned.rs
rustfmt-core/tests/source/match.rs
rustfmt-core/tests/target/match.rs

Format a match arm with the beginning vertical bar

---

rustfmt-core/src/imports.rs
rustfmt-core/src/items.rs
rustfmt-core/src/lib.rs
rustfmt-core/src/reorder.rs
rustfmt-core/src/visitor.rs

This PR moves stuffs related to reordering items into a `reorder` module.

Refactoring: add `reorder` modules

---

rustfmt-core/src/comment.rs
rustfmt-core/tests/target/issue-2346.rs

Fixes #2346
not entirely sure whether that's the right fix, but i guessed so because `result` seems to contain multiple lines of a comment, which makes the equality check come to nothing.

Fix #2346: empty comments should not have any trailing space added

---

rustfmt-core/src/macros.rs
rustfmt-core/tests/source/macro_rules.rs
rustfmt-core/tests/target/macro_rules.rs

A body of `macro_rules!` can be surrounded by `{}`, `();` or `[];`. rustfmt can handle the first one, but cannot the others. IMO the latter two are rarely used, so this PR just skip formatting those to avoid panicking.
Closes #2466.

Skip formatting macro_rules! that are not using {} 

---

rustfmt-config/src/file_lines.rs
rustfmt-core/src/chains.rs
rustfmt-core/src/closures.rs
rustfmt-core/src/codemap.rs
rustfmt-core/src/comment.rs
rustfmt-core/src/expr.rs
rustfmt-core/src/imports.rs
rustfmt-core/src/issues.rs
rustfmt-core/src/items.rs
rustfmt-core/src/lib.rs
rustfmt-core/src/lists.rs
rustfmt-core/src/macros.rs
rustfmt-core/src/patterns.rs
rustfmt-core/src/reorder.rs
rustfmt-core/src/shape.rs
rustfmt-core/src/string.rs
rustfmt-core/src/types.rs
rustfmt-core/src/utils.rs
rustfmt-core/src/vertical.rs
rustfmt-core/src/visitor.rs

This PR applies some optimizations suggested by `perf` that does not require (I think) fancy modification. 
In total, depending on the code base, this gives 10~30 % speed up compared to the latest master.
rustfmt is already fast enough, so if any of the changes seem to disrupt readability of the code, I am willing to revert them from this PR.

Apply optimization suggested by perf

---

Configurations.md

This PR modifies the `struct_lit_single_line` option configuration snippet examples to be shorter. The current example is not formatted as claimed by Configurations.md, but as discussed in #2458, shorter examples are. This change eliminates one failure in the configuration_snippet_tests test.
Here is the current output of cargo test -- --ignored on master:
```
Ran 106 configurations tests.
left: `2`,
right: `0`: 2 configurations tests failed', rustfmt-core/tests/lib.rs:851:5
```
Here is the output of cargo test -- --ignored on the PR branch:
```
Ran 106 configurations tests.
thread 'configuration_snippet_tests' …
```

Using shorter example for `struct_lit_single_line` option

---

Configurations.md

This PR updates the Configurations.md documentation for the `reorder_extern_crates` and `reorder_extern_crates_in_group` options.
- For `reorder_extern_crates = false` the snippet is updated to demonstrate that `extern crate` groups are not collapsed.
- For `reorder_extern_crates_in_group` the references to `reorder_imports` needing to be `true` is removed because it is not true.
- For `reorder_extern_crates_in_group = true` the need for `reorder_extern_crates` to also be `true` is documented.
- The snippet for `reorder_extern_crates_in_group = false` has been removed and replaced with text explaining that the `false` value for that option has no effect beyond whatever the `reorder_extern_crates` option is set to.
You can see the live version of these changes …

Update `reorder_extern_crates*` Configuration.md snippets

---

rustfmt-core/src/visitor.rs
rustfmt-core/tests/source/macro_rules.rs
rustfmt-core/tests/target/macro_rules.rs

This allows us to keep formatting the macro def with attributes that become
invalid syntax when the `$` is replaced with `z`, e.g. `#[doc = $expr]`.
Closes #2470.

Return the original snippet if the attribute contains invalid syntax

---

rustfmt-core/tests/lib.rs

With #2472 closed, all configuration snippet tests are passing. This PR removes the `#[ignore]` attribute from the test to turn it on for everyone and closes #1845. :shipit:

Removing ignore attribute

---

rustfmt-bin/build.rs
rustfmt-bin/src/main.rs

should resolve #2451
before:
```
0.4.0-nightly (383e7e99 2018-02-19)
```
after this commit, `channel(nightly|beta|stable)` will not be hard-coded into version info anymore.
```
rustfmt 0.4.0-nightly (e87c2cae 2018-02-21)
```

Explict version info

---

rustfmt-bin/build.rs
rustfmt-core/src/expr.rs
rustfmt-core/src/macros.rs
rustfmt-core/src/types.rs
rustfmt-core/tests/source/macro_rules.rs
rustfmt-core/tests/target/configs/indent_style/block_call.rs
rustfmt-core/tests/target/macro_rules.rs

Avoid drifting macro body which is unformattable

---

Configurations.md
rustfmt-config/src/config_type.rs
rustfmt-core/tests/lib.rs

This PR updates configuration_snippet_tests to catch outdated Configurations.md.
1. Error if there is an unknown configuration option in Configuration.md.
2. Error if there are multiple guides for the same configuration option in Configuration.md.
3. Error if an user-facing configuration option does not have its guide in Configuration.md.
Should prevent issues like #2459.
cc @davidalber, thank you for creating an infrastructure for testing Configurations.md in the first place!

Error on outdated Configurations.md

---

rustfmt-core/src/macros.rs
rustfmt-core/tests/source/macros.rs
rustfmt-core/tests/target/macros.rs

Preserve trailing comma on macro in item position 

---

rustfmt-core/tests/lib.rs

`cargo test` currently fails with:
```
---- self_tests stdout ----
thread 'self_tests' panicked at 'Couldn't read file ../cargo-bin/src/main.rs: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
and
```
---- self_tests stdout ----
thread 'self_tests' panicked at 'Couldn't read file ../rustfmt-bin/src/main.rs: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
I suppose in light of 9d2229f2fdf59b1cc80aea8851e14db81c55c82f, `self_tests()` should be updated?

Remove cargo-fmt and rustfmt-bin from self_tests()

---

CODE_OF_CONDUCT.md
Contributing.md
README.md

It seems like a good idea to add the Rust Code of Conduct here. What do you think? It's in the core Rust repository ([here](https://github.com/rust-lang/rust/blob/master/CODE_OF_CONDUCT.md)). This PR adds it to rustfmt. I kind of think, for history's sake, that it would make sense for the repository owners' to add it, so if you want to do that, that's fine by me!
I followed the lead in the Rust repository to add the full Code of Conduct, rather than just linking to the page from rust-www. I think that's a nicer solution, but it does come with a risk of the Code of Conduct in satellite repositories becoming out of sync with the main version. To help with that, I've set up a repository that verifies everything is in sync ([here](https://github.com/davidalber/rust-conduct-conformulator)). …

Adding the Rust Code of Conduct

---

.travis.yml

The macOS Travis build is broken. I believe the cause is [Homebrew changed the `python` formula to be Python 3](https://brew.sh/2018/01/19/homebrew-1.5.0/). Thus, when we try to `brew install python3` we are really trying install the `python` target, which is already (currently) Python 2 in the Travis image.
I first tried fixing this by upgrading the `python` formula. This added a lot of time to the build, and wasn't quite working before I realized that `travis-cargo` does not care whether it's executing in a Python 2 or Python 3 interpreter. Thus, I just dropped the whole "try to get a Python 3 virtual environment" angle. Currently, this is running using Python 2, but I suspect that Travis will update the image sometime and it will then by Python 3.

Fixing macOS Travis setup

---

src/types.rs
tests/source/issue-2506.rs
tests/target/issue-2506.rs

For #2506, added `dyn ` check when rewriting TraitObject.
I added 2 tests, but I'm not sure they're enough comprehensive.

Issue 2506

---

src/items.rs
tests/source/impls.rs
tests/target/big-impl-block.rs
tests/target/impls.rs

Disallow combining parens and brackets in impl 

---

src/attr.rs
src/comment.rs
src/shape.rs
tests/source/issue-2520.rs
tests/target/enum.rs
tests/target/issue-2520.rs

There was a bug in `take_while_with_pred`, and rustfmt formatted doc comments separately:
```rust
//! ```rust
//! println!( "hello, world" );
```
and
```rust
//! ``` 
```
, this PR fixes the above bug and make sure that the code block that are not enclosed properly will not get removed.
Also in some occasion rustfmt did not take `comment_width` into account when rewriting doc comments. This PR fixes it as well.
Closes #2520.

Fix bugs when rewriting doc comments with code block

---

Cargo.toml
src/chains.rs
src/macros.rs

Doctests were disabled globally because up until #2456, they were just
formatting examples which were not supposed to compile. Now that there
is one runnable doctest, I disabled the other ones individually (by
adding the ignore directive).
I also added some empty lines around the code blocks to avoid the
following warning and instead ignore the code blocks cleanly:
```
WARNING: ... Code block is not currently run as a test, but will in future versions of rustdoc. Please ensure this code block is a runnable test, or use the `ignore` directive.
```
See rust-lang/rust#28712 for further details.

Enable doctests

---

src/chains.rs
src/expr.rs
src/items.rs
src/lib.rs
src/macros.rs
src/overflow.rs
src/patterns.rs
src/rewrite.rs
src/shape.rs
src/types.rs
src/visitor.rs
tests/lib.rs
tests/source/type.rs
tests/target/big-impl-block.rs
tests/target/big-impl-visual.rs
tests/target/comment.rs
tests/target/trailing_commas.rs
tests/target/type.rs

This PR modifies `rewrite_call_inner` to  handle a list of items which is surrounded by `<>`, like genercis or types.
Since keep calling it `rewrite_call_inner` is counterintuitive, I created a new module `overflow` and put related funtions there. I am open to bikesheding on better name. I kind of gave up to come up with a better one.
Closes #2510.

Make rewrite_call_inner more generic

---

src/expr.rs
src/lib.rs
src/macros.rs
src/spanned.rs
tests/source/issue-2523.rs
tests/target/issue-2523.rs

`format_code_block` formats the given `code_snippet` by enclosing it inside
`fn main` block. Previously we did not add indentation to the `code_snippet`
before formatting it. This works fine as long as we can format the given
`code_snippet`, but when the code block has unformattable macro, they gets
unindented. This PR fixes it by adding proper indentation before formatting
the `code_snippet`.
For example, when formatting the following code block,
```rust
some_macro!(pub fn foo() {
println!("Don't unindent me!");
});
```
previously we enclosed it like this:
```rust
fn main() {
some_macro!(pub fn foo() {
println!("Don't unindent me!");
});
}
```
with this PR, we will enclose it like this:
```rust
fn main() {
some_macro!(pub fn foo() {
println!("Don't unindent me!");
});
}
```
Closes #2523.

Do not unindent code block in comments with unformattable macro

---

Cargo.lock
Cargo.toml
src/comment.rs
src/lib.rs
tests/target/issue-2526.rs

Check whether '\\'' is char literal or lifetime 

---

Cargo.toml
src/cargo-fmt/main.rs

Previously, cargo fmt  invoked without parameters would
only format the crate in the current directory, even if
the crate was part of a workspace. This patch restores
that behavior.

Restore cargo fmt behavior in workspaces

---

src/expr.rs
src/items.rs
src/types.rs
tests/source/issue-2506.rs
tests/source/where-clause-rfc.rs
tests/target/impls.rs
tests/target/issue-2506.rs
tests/target/trait.rs
tests/target/where-clause-rfc.rs
tests/target/where-clause.rs

This PR implements a corner case of RFC style for trait:
```diff
-pub trait Number
-    : Copy
+pub trait Number:
+    Copy
+ Eq
+ Not<Output = Self>
+ Shl<u8, Output = Self>
+ Shr<u8, Output = Self>
+ BitAnd<Self, Output = Self>
+ BitOr<Self, Output = Self>
+ BitAndAssign
-    + BitOrAssign {
+    + BitOrAssign
+{

Implement RFC style for trait

---

Configurations.md
src/bin/main.rs
src/config/config_type.rs
src/config/mod.rs
src/config/options.rs
src/lib.rs
tests/lib.rs

This PR adds `ignore` config option, which lets users to tell rustfmt to skip formatting the specified files and directories. The current implementation is not as smart as `.gitignore`, but should get the job done.
For example, with the following config file, rustfmt will ignore `src/types.rs`,
`src/foo/bar.rs` and every file under `examples/` directory.
```toml
[ignore]
files = [
"src/types.rs",
"src/foo/bar.rs",
]
directories = [
"examples",
]
```
Closes #705.
Closes #2444.

Add ignore config option

---

src/expr.rs
tests/source/expr.rs
tests/target/expr.rs

**EDIT**: this is no longer true.
---
This PR allows the **last** rhs of a binary expression to be overflowed if it is a **chain**. 
We do not want to overflow the rhs of a binary expression that is inside the other binary expression. For example, we do not want to do these:
```diff
-        self.inner_as_ref().contains('\n')
-            || self.pre_comment
-                .as_ref()
-                .map_or(false, |s| s.contains('\n'))
-            || self.post_comment
-                .as_ref()
-                .map_or(false, |s| s.contains('\n'))
+        self.inner_as_ref().contains('\n') || self.pre_comment
+            .as_ref()
+            .map_or(false, |s| s.contains('\n')) || self.post_comment
+            .as_ref()
+            .map_or(false, |s| s.contains('\n'))
```
```diff …
```

Overflow the last rhs of a binary expression

---

build.rs
src/bin/main.rs

On the current master `rustfmt --version` emits `rustfmt 0.4.1- (87180d90 2018-03-16)`. Looks like the change from #2478 to build.rs got removed. This PR fixes it.
With this PR `rustfmt --version` emits `rustfmt 0.4.1-nightly (ca6fc67e 2018-03-17)`.

Fix print_version

---

src/macros.rs
tests/source/macro_rules.rs
tests/target/macro_rules.rs

Skip name replacement in comments and strings 

---

src/attr.rs
src/comment.rs
src/issues.rs
src/items.rs
src/lib.rs
src/utils.rs

and micro-optimizations I found while grepping with `.chars()`.

Don't index a string with chars().count()/position()

---

Cargo.lock
Cargo.toml
src/imports.rs
src/macros.rs
src/reorder.rs
tests/target/imports.rs

This PR updates `rustc-ap-syntax` to 73.0.0, and fixes some breaking changes.
1. Underscore is now one of keywords.
2. `ast::UseTreeKind::Simple` now takes `Option<ast::Ident>` instead of `ast::Ident`.
3. Currently we use `UseSegment::Ident` for all of the segments except the last.
E.g. `use super::foo::bar::self;` will be
`[Ident("super"), Ident("foo"), Ident("bar"), Self(None)]`.
in the current implementation. I think that this should be
`[Super(None), Ident("foo"), Ident("bar"), Self(None)]`.
instead.
I noticed this because some tests failed after updating
`rustc-ap-syntax` to 73.0.0.

Update rustc-ap-syntax to 73.0.0

---

src/cargo-fmt/main.rs
src/macros.rs
src/spanned.rs
src/utils.rs
tests/target/macro_not_expr.rs
tests/target/macro_rules.rs
tests/target/macros.rs

This PR adds two config options `space_after_colon_macro_def` and `space_before_colon_macro_def` which control spaces around a colon of metavariable definitions in macro def.
Also this PR changes the default format to **not** to put a space after a colon. I think that the formatting without a space is more popular in the wild, and incurs less conflicts with users.
Alternatively we could decide whether we should add a space or not based on what kind of separator is used in the definition: if arguments are separated by `,`, then we add a space after each colon, but if weird separators, like `=>`, `:` or even just a space, are used, then we do not add a space. However this seems too complex and error-prone, so I would rather keep the rule simple and consistent.
@nrc Do you have any thoughts …

Add config option to control spaces around colon in macro def

---

src/matches.rs
tests/target/issue-2554.rs

Pass the span after the match's condition expression.
Closes #2554.

Do not add the beginning vert to the match arm

---

src/attr.rs
tests/source/attrib.rs
tests/target/attrib.rs
tests/target/enum.rs

Currently rustfmt forces mixed layout when formatting attributes. This is suboptimal when the attribute has complex inner items. This PR fixes it by disallowing mixed layout when every item in the attribute is either list or assignment.

Use vertical layout for complex attributes

---

src/macros.rs
src/spanned.rs
tests/source/macros.rs
tests/target/macros.rs

`parse_item` from libsyntax may return `None`, so we need to discard
the result in that case.
Closes #2569.

Avoid panicking on macro call with a single comma

---

Cargo.lock
Cargo.toml
src/macros.rs

Update `rustc-ap-syntax` to 82.0.0.

Cargo update

---

Configurations.md
src/config/mod.rs

Amends #2030 (adding option)
Amends #2215 (adding documentation)
Remember that `where` is not just a keyword but an English word, making both the option name and the documentation extremely hard to read without emphasis. I added the emphasis in the markdown, and reworded a little.

Improve `where_single_line` help

---

build.rs

Cargo rebuilds the project (even if source codes are unchanged) when any file in the project directry is changed and `build.rs` is run, which takes 5 seconds on my machine. This PR prevents unnecessary runs of it.

Rerun build.rs only when .git/HEAD or CFG_RELEASE_CHANNEL is changed

---

src/comment.rs
src/lib.rs
src/macros.rs
tests/source/macros.rs
tests/target/macros.rs

We manually indent/unindent code block when formatting macros or doc comments, but these modifications should not applied to string literals (except when the line of string literal ends with `\`).
Closes #2588.

Do not indent or unindent inside string literal 

---

src/attr.rs
src/comment.rs
src/config/lists.rs
src/imports.rs
src/lib.rs
src/lists.rs
src/reorder.rs
tests/source/issue-2256.rs
tests/target/imports.rs
tests/target/issue-2256.rs

This PR uses normalized form of `ast::UseTree` to format them.
My apologies for a big commit which makes this hard to review, I tried to separate them in logical way, but failed to do so...
Closes #2531.

Use normalized form to format use items

---

src/imports.rs
src/lists.rs
tests/source/imports_block_indent.rs
tests/target/imports_block_indent.rs

Use multiple lines for imports list which exceeds max width

---

src/bin/main.rs

Currently, `error_on_unformatted` and `skip_children` options
specified in the config file are discarded.
This happens because CLI options have a higher priority,
but we coerce an absence of a `bool` option to `false`.
In this scenario, an absence of a `bool` option is indistinguishable
from explicitly set as `false`. We should coerce it to `None` instead,
so it does not override the one in the config file.
Issue: https://github.com/rust-lang-nursery/rustfmt/issues/2565

Fix error_on_unformatted and skip_children override

---

README.md

when using stable cargo install fails due to #![feature] usage:
error[E0554]: #![feature] may not be used on the stable release channel
--> /Users/dnw/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-serialize-67.0.0/lib.rs:24:1
|
24 | #![feature(rustc_private, box_syntax)]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0554]: #![feature] may not be used on the stable release channel
--> /Users/dnw/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-serialize-67.0.0/lib.rs:25:1
|
25 | #![feature(core_intrinsics)]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0554]: #![feature] may not be used on the stable release channel
--> /Users/dnw/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-serialize-67.0.0/lib.rs:26:1
|
26 | #![feature(i128_type)]
| ^^^^^^^^^^^^^^^^^^^^^^ …

specify nightly required to install from source

---

src/bin/main.rs
src/config/config_type.rs
src/config/mod.rs

This PR suppresses the output of unstable config options by default.
Users can specify the `--unstable-features` option to show the config options
that are unstable.
Fixes #2611.

Suppress unstable config options by default.

---

Configurations.md
src/config/mod.rs
src/imports.rs
src/lists.rs
src/reorder.rs
tests/source/merge_imports.rs
tests/target/merge_imports.rs

This PR adds a `merge_imports` config option, which merges multiple imports with the same prefix into a single nested import.
Thoughts:
1. We should not merge imports with different visibility or attributes.
2. In the previous review, @nrc [suggested to use different levels of merging over a simple boolean](https://github.com/rust-lang-nursery/rustfmt/pull/2475#issuecomment-367891258). I tried to use `usize` (0 means no merging, 1 means merging the top level segment, and so on), but it turned out to be kind of counter-intuitive IMO, so came back to true/false. 
Closes #1383. Closes #2452. Closes #2544.

Merge imports

---

Contributing.md

Since https://github.com/rust-lang/rust-central-station/pull/40 has been
merged, we have a stable location for the nightly docs.

Link to official nightly documentation

---

build.rs

Dependent crates (most notably RLS) don't have .git metadata along with fetched published crate, so they might possibly be considered dirty and rebuilt, even when the file has not changed.
This happened when building RLS manually with `cargo build --release` and then spawning rls using `cargo run --release`. Appropriate error from cargo: `stale: /home/xanewok/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.6.0/.git/HEAD -- missing`.
With the change Cargo does not unnecessarily rebuild rustfmt-nightly everytime local RLS is spawned by the extension.

Ignore checking inexistent .git/HEAD in build.rs

---

src/items.rs
src/utils.rs
tests/source/enum.rs
tests/target/configs/struct_field_align_threshold/20.rs
tests/target/enum.rs
tests/target/issue-977.rs
tests/target/structs.rs
tests/target/unions.rs

Use consistent formatting for empty enum and struct

---

src/comment.rs
src/config/options.rs
src/imports.rs
src/items.rs
src/test/mod.rs
tests/source/reorder-impl-items.rs
tests/target/reorder-impl-items.rs

Closes #2634.
(The actual relevant commit that fixes the issue is the second one, I am sorry for constructing a poor commit log.)

Avoid flip-flopping impl items when reordering them

---

src/imports.rs
tests/source/configs/imports_layout/merge_mixed.rs
tests/target/configs/imports_layout/merge_mixed.rs
tests/target/imports.rs

Make imports_layout = "Mixed" addressed

---

src/config/config_type.rs
src/config/options.rs
tests/source/issue-2644.rs
tests/source/width-heuristics.rs
tests/target/issue-2644.rs
tests/target/width-heuristics.rs

Do not scale WidthHeuristics when max_width less than 100

---

Configurations.md
src/config/mod.rs
src/expr.rs
tests/source/configs/remove_nested_parens/remove_nested_parens.rs
tests/source/expr.rs
tests/source/paren.rs
tests/target/configs/remove_nested_parens/remove_nested_parens.rs
tests/target/expr.rs
tests/target/paren.rs

Address https://github.com/rust-lang-nursery/rustfmt/pull/2519#issuecomment-371691543

Add remove nested parens option

---

src/overflow.rs
tests/source/expr.rs
tests/target/expr.rs

Take the first line's width of a single item into account when
trying to overflow something.
Closes #2676.

Do not overflow a long item

---

README.md

Some of the change made in #2539 were not reflected in README.md.
I thinks that https://github.com/davidalber/rustfmt-travis should also be updated.

Update README.md to reflect change in #2539

---

Configurations.md
src/bin/main.rs
src/chains.rs
src/closures.rs
src/comment.rs
src/config/summary.rs
src/expr.rs
src/imports.rs
src/items.rs
src/lib.rs
src/lists.rs
src/macros.rs
src/matches.rs
src/overflow.rs
src/types.rs
tests/source/binary-expr.rs
tests/target/binary-expr.rs
tests/target/expr-block.rs
tests/target/expr.rs
tests/target/issue-1239.rs

Currently rustfmt puts as many operands as possible in a single line, then after exceeding max width, it puts other operands on its own line. e.g.
```rust
if self.items.len() == 1 && self.one_line_width != 0 && !list_items[0].has_comment()
&& !list_items[0].inner_as_ref().contains('\n')
&& ::lists::total_item_width(&list_items[0]) <= self.one_line_width
```
Instead, we should put each operand on its own line when it fits in a single line:
```rust
if self.items.len() == 1
&& self.one_line_width != 0
&& !list_items[0].has_comment()
&& !list_items[0].inner_as_ref().contains('\n')
&& ::lists::total_item_width(&list_items[0]) <= self.one_line_width
```
Closes #2530.

Put operands on its own line when each fits in a single line

---

src/test/mod.rs

Two tests were executing `cargo run` but `cargo` is not ambiently available to
execute. Instead it's best to execute the rustfmt binary directly, which is
always assembled as part of `cargo test`.

Fix rustfmt tests in the Rust repo

---

.travis.yml
ci/integration.sh

This commit adds integration tests against some crates in the
nursery.
Each integration test is added as a separate build-bot, where
the rust-lang-nursery/${CRATE} is first downloaded and its tests run.
Afterwards, `cargo fmt --all` is applied to the crate, and the tests
are re-run. If the tests fail after formatting, the integration test
fails.
The crates that currently fail are added as allowed-to-fail, but the
intent is that either these crates or rustfmt should be fixed such
that the tests pass.
Closes #2692 .

Add integration tests against crates in the rust-lang-nursery

---

src/types.rs

I don't really get why the box was used but the code works without it so I removed it to avoid allocating on the heap.

Remove unnecessary use of Box in `format_function_type`

---

ci/integration.sh

The current ci exits on error without outputting the result of running `cargo fmt` which makes issues harder to debug than necessary.
This PR changes that to always output the result of `cargo fmt`.

output the result of rustfmt on ci

---

ci/integration.sh

This should make cloning a bit faster for all the integration tests.

Shallow clone in integration tests

---

ci/integration.sh

cc @nrc this might print all the output, maybe `cargo fmt --all ...` is interacting with `set -ex` and the function was erroring before the `cat rustfmt_output` was executed.

try harder to print output

---

README.md

"write-mode" parameter is now deleted and mentioning it in doc was misleading

Remove "write-mode" from doc

---

src/items.rs
tests/source/trait.rs
tests/target/trait.rs

`rustfmt 0.7.0-nightly (b0eb8993 2018-05-18)` changes the following code
```rust
#![feature(optin_builtin_traits)]
pub auto trait Auto {}
```
which compiles cleanly, to
```rust
#![feature(optin_builtin_traits)]
auto pub trait Auto {}
```
which does not compile. This PR fixes the issue and adds tests for it.

Fix position of auto in auto trait declaration

---

README.md

The current stable rustfmt (rustfmt 0.4.1-stable) does not contain the `--check` flag, which is used in the Travis config snippet. Once a new stable version is released, the snippet can be switched
back to stable Rust.
Fixes #2688.

Use nightly Rust in Travis CI config snippet

---

.travis.yml
ci/integration.sh

And emit rustfmt output so they can be debugged

Fix and tweak integration tests

---

src/expr.rs
tests/source/label_break.rs
tests/target/label_break.rs

Format label break

---

src/expr.rs
src/items.rs
src/overflow.rs
tests/source/expr.rs
tests/target/expr.rs

Disallow combining a method call with prefix or suffix 

---

src/comment.rs
tests/source/doc-comment-with-example.rs
tests/target/doc-comment-with-example.rs

Format code block with sharp prefix

---

src/string.rs

We've already checked if `cur_end >= graphemes.len()` before entering the outer while loop and only need to check if `cur_end == graphemes.len()` as `cur_end` only increments by one.
I believe separating the checks into functions makes the code clearer. 
The change to `whitespace_at` makes the code easier to understand for anyone reading the code, and I believe more efficient (why would you need to trim both sides of a grapheme and then check if it is empty when you can just check the characters one by one and stop when you find a non-whitespace).
The change to `punctuation_at` makes it clear that we only need to look at a single codepoint to know if a grapheme is a punctuation.

Some changes to rewrite_string

---

src/missed_spans.rs
tests/source/macros.rs
tests/target/macros.rs

Trim unnecessary whitespaces between a macro call and a semicolon

---

src/config/file_lines.rs
src/missed_spans.rs

fix https://github.com/rust-lang-nursery/rustfmt/issues/2737.
Don't add extra lines if the next lines should be skipped.
I have no idea why this bug seems to appear only on windows with crlf files ¯\_(ツ)_/¯

Fix test failing on windows due to crlf

---

Cargo.lock
Cargo.toml
src/expr.rs
src/test/mod.rs

* Fixes latest nightly compile, resolves #2744
* Resolves #2743 as match arm is itself obsolete
* Add a more merciful test failure message for devs that run `cargo test` on this project before `cargo build`, resolves #2738

Update rustc-ap-* -> 148.0.0

---

src/items.rs
tests/source/configs/where_single_line/true.rs
tests/target/configs/where_single_line/true.rs
tests/target/impl.rs
tests/target/impls.rs

Remove newline in empty impl

---

src/cargo-fmt/main.rs

1. replace dump-default-config with print-config, should be related to https://github.com/rust-lang-nursery/rustfmt/commit/eca7796fb1cd8866189e273f7e5d1df5585b269e
2. update rustfmt flags that should work without targets
this doesn't work as expected at this moment:
```
cd /tmp && cargo fmt -- -h
`cargo manifest` failed.
```
this PR will enable commands like these without requiring users operating under a certain cargo project path:
```
cargo fmt -- --print-config default
cargo fmt -- -h
cargo fmt -- -V
```

update rustfmt flags that should work without targets

---

src/comment.rs
tests/target/issue-2759.rs

This PR is a followup of #2732, where I first added the support for formatting code block in doc comments with `#`. I have forgot to handle errors in the original PR:
1. When we have failed to format the code block.
2. When the code block does not have the trailing ` ``` `.
3. When the `#` is indented.
This PR fixes #2732 and handle the above cases.
Closes #2759.

Fix breaking code block with `#` in doc comments

---

src/config/lists.rs
src/imports.rs
src/lists.rs
tests/source/imports.rs
tests/target/configs/imports_layout/merge_mixed.rs
tests/target/imports.rs

Put each nested import on its own line

---

src/items.rs
tests/source/impls.rs
tests/target/big-impl-block.rs
tests/target/impls.rs

This PR fixes two minor formatting bugs w.r. impls:
1. Currently rustfmt does not respect `empty_item_single_line` config option when formatting empty impls.
2. Putting the `where` on the same line with the indented closing bracket, which makes the following where clauses hard to read (#2746).
Closes #2746.

Fix poor formatting of impls

---

src/closures.rs
src/expr.rs
tests/target/label_break.rs

Fix break_label formatting

---

src/config/summary.rs
src/lib.rs
src/macros.rs
src/rewrite.rs
src/visitor.rs
tests/source/macro_rules.rs
tests/target/issue-2523.rs
tests/target/macro_rules.rs

rustfmt manually adds/removes indentation when trying to format macro def's body. This does not work when the macro body contains a macro call that rustfmt cannot format, and causes an issue like #2607 or #2770. This PR fixes it by changing the `format_snippet` to return `None` when it has failed to format the macro call in the snippet.
Closes #2607.
Closes #2770.

Change format_snippet to return None when it has failed to format macro call

---

src/lib.rs

* Clean up code as it took me a while to understand what variable `b` was to finally realize it wasn't used.
* Simplify how trailing whitespace are reported ( it was using an intermediate buffer, in the current state it doesn't make sense anymore)

Clean Up code where last whitspace tracking isn't used

---

src/filemap.rs
src/lib.rs
src/test/mod.rs

* End Lines are handled by the format process instead of the write mode, because :
- Conceptually it sounds right
- Absolutely all write modes where doing it anyway
- It was done several times in some in case
- It greatly simplify the code
* Parse Error doesn't return successful anymore
* Use new Rust Apis to [read ](https://doc.rust-lang.org/std/fs/fn.read_to_string.html)and [write](https://doc.rust-lang.org/std/fs/fn.write.html) files in write mode

Improve end lines handling

---

.travis.yml
ci/integration.sh

Adds test for the failure in #2787 , doesn't fix anything.

test cargo fmt --all -- --check returns success after formatting

---

src/lib.rs
tests/source/issue-2728.rs
tests/target/issue-2728.rs

Do you mind if I clone() the whole config object?

Fix #2728.

---

src/attr.rs
src/closures.rs
src/config/lists.rs
src/expr.rs
src/imports.rs
src/items.rs
src/lists.rs
src/macros.rs
src/matches.rs
src/overflow.rs
src/reorder.rs
src/types.rs
src/vertical.rs
tests/config/issue-2794.toml
tests/source/issue-2794.rs
tests/target/issue-2794.rs

Adds a test for the regression in the `Vertical` imports layout reported in #2794.

Add test and fix for #2794

---

Configurations.md

`blank_lines_upper_bound` has default value `1`, not `2`.

Remove wrong "(default)" from `Configurations.md`

---

Cargo.lock
Cargo.toml
src/chains.rs
src/expr.rs
src/imports.rs
src/items.rs
src/spanned.rs
src/types.rs
src/visitor.rs
tests/source/assignment.rs
tests/target/assignment.rs

This PR
1. updates `rustc-ap-*` to 174.0.0, which includes a fix for #2791
2. fixes compile errors from breaking changes in libsyntax (cc https://github.com/rust-lang/rust/pull/48149)

Update rustc-ap-* to 174.0.0

---

src/matches.rs
tests/source/match.rs
tests/target/match.rs

This addresses issue #2621
This commit turns out to be a partial revert of
ea3c01e3374143912f048b22fda106ee8d5a1cd8
The rationale is that a `|` character preceding a match pattern is not
semantically relevant and therefore should be considered a
style/formatting choice.
A discussion concluded that the best way to emit consistent formatting
here was to strip the leading `|`
This removes the match_with_beginning_vert test because it was asserting
the old behaviour which has been changed, it adds a new test
(issue_2621) which should be a more comprehensive check of the behavior
of `|` in match arms.
Discussion at https://github.com/rust-lang-nursery/fmt-rfcs/issues/119

Strip leading `|` in match arm patterns

---

src/attr.rs
src/lists.rs
src/matches.rs
src/shape.rs
tests/source/attrib.rs
tests/source/match.rs
tests/target/attrib.rs
tests/target/enum.rs
tests/target/match.rs
tests/target/struct-field-attributes.rs

r? @topecongiro 
The second commit is a bit big, sorry. The basic outline of the refactoring is to layout attributes iteratively rather than recursively, then get derive and non-derive code to share as much code as possible (unfortunately that is a lot less than I hoped).
The results are still not ideal - when we do full vertical formatting for a derive it is kind of silly looking (see one of the test fixups), but you need a lot of derives until you hit that. I'm not sure what would be better either - it is pretty consistent with functions, at least. It would be nice to combine attributes like we do for function attributes and to handle attributes with formatting strings like `println!`.
Long term, attributes will be allowed to be just tokens, so we'll have the same problems as macros.

Some formatting fixes

---

src/macros.rs
tests/source/macro_rules.rs
tests/target/macro_rules.rs

Return the trimmed original snippet when formatting macro def failed

---

src/bin/main.rs

Due to the way getopts works, it requires the equals sign.

Fix help for --help=file-lines

---

Cargo.lock
Cargo.toml
Configurations.md
src/closures.rs
src/config/mod.rs
src/config/options.rs
src/expr.rs
src/lib.rs
tests/target/async_closure.rs

This PR
1. adds `edition` config option to specify which edition to use.
2. handles async closure by using `syntax_pos::hygiene::set_default_edition` (cc https://github.com/rust-lang/rust/issues/51888).
Close #2813.

Format async closure

---

src/comment.rs
src/expr.rs
src/string.rs
src/utils.rs
tests/source/issue-1210/a.rs
tests/source/issue-1210/b.rs
tests/source/issue-1210/c.rs
tests/source/issue-1210/d.rs
tests/source/issue-1210/e.rs
tests/target/issue-1210/a.rs
tests/target/issue-1210/b.rs
tests/target/issue-1210/c.rs
tests/target/issue-1210/d.rs
tests/target/issue-1210/e.rs

Close #1210 
The proposed implementation of `rewrite_string` relies less on manual handling of ranges within the string, which I find (subjectively!) easier to reason about. If you prefer the previous logic, I will modify this PR accordingly.
In addition, this rewrite keeps the `max_width` argument although it is unused ATM, for reasons described in a comment of the issue. I will change this PR as per the comment's response.

fix rewrite_string when a line feed is present in a sequence of whitespaces, resulting in strange formatting

---

Configurations.md
src/config/mod.rs
src/lib.rs
src/test/mod.rs

I tried to fix the tests for AppVeyor, but didn't actually test on Windows before opening this PR. Also, I'm not sure if this is really the best way to do this, but it seemed to be the easiest.
Fixes #2626.

Change default newline style to "Native"

---

Configurations.md
src/config/config_type.rs
src/config/options.rs
tests/source/configs/use_small_heuristics/max.rs
tests/target/configs/use_small_heuristics/max.rs

This is useful when working with very small max_widths like 79 chars. I agree with this [comment](https://github.com/rust-lang-nursery/rustfmt/issues/2636#issuecomment-382844133) but rustfmt's heuristics generate a lot of vertical space in https://github.com/xiph/rav1e project, which uses  a max_width of 79 chars.

Add max_width option for all heuristics.

---

Cargo.lock
Cargo.toml
src/items.rs
src/visitor.rs
tests/source/existential_type.rs
tests/target/existential_type.rs

This PR updates `rustc-ap-*` to "206.0.0" and adds a support for existential type (cc https://github.com/rust-lang/rust/pull/52024).

Format existetenial type

---

src/macros.rs
tests/source/macros.rs
tests/target/macros.rs

Keep the context that we are inside macro in nested macro

---

src/items.rs
src/types.rs
src/visitor.rs
tests/source/type.rs
tests/target/type.rs

Closes #2859.
This PR only deals with generic bounds that are 'in order', where lifetimes come after traits, as otherwise the ruling becomes quite complicated.

Put lifetimes after trait when they gets orphaned

---

Configurations.md
src/config/mod.rs
src/config/options.rs
src/formatting.rs

This changes the default newline style from `Native` to `Auto`. When set to `Auto` the original source input is examined and checked for `CRLF`. 
This prevents situations on windows where the entire project would be are re-formatted when they are using rustfmt defaults (i.e. when there is no `rustfmt.toml`).

Auto-detect newline style by default

---

src/bin/main.rs

These features are registered only on Nightly and so matches.opt_present panics when it's called without the is_nightly guard.

Fix check for unstable features

---

.travis.yml

Now that `packed_simd` has been from `stdsimd` it is probably worth it to keep it around as an integration test since it uses a lot of macros which has caught rustfmt issues in the past.

add integration test rust-lang-nursery/packed_simd

---

src/attr.rs
src/closures.rs
src/expr.rs
src/imports.rs
src/items.rs
src/lists.rs
src/macros.rs
src/matches.rs
src/overflow.rs
src/patterns.rs
src/reorder.rs
src/types.rs
src/vertical.rs

This PR introduces builder pattern for constructing `ListFormatting`. This greatly simplifies the code, but more importantly, I think that this makes the further updates and refactoring much easier.
r? @nrc

Use builder pattern for ListFormatting

---

src/visitor.rs
tests/source/expr.rs
tests/target/expr.rs

Implicitly handling it in the next `push_stmt` makes `format_missing` unhappy.
Closes #2884.

Explicitly handle semicolon after the item in statement position

---

src/chains.rs
src/codemap.rs
src/lists.rs
tests/source/chains_with_comment.rs
tests/target/chains_with_comment.rs

This PR lets rustfmt handle chains with comment.
r? @nrc
- This PR cannot handle comment within `.` and a chain item (e.g. `foo. /* comment */ bar()`).
- When `use_try_shorthand` is on, comment within chain items are not formatted as we get faulty span when converting `try!(expr)` to `expr?`.
Closes #2177.

Format chains with comment

---

src/macros.rs
tests/source/macro_rules.rs
tests/target/macro_rules.rs

Use correct max width when formatting macro body

---

src/config/file_lines.rs

Blocks https://github.com/rust-lang-nursery/rls/pull/990.
r? @nrc

Expose FileLines JSON representation
